const OWN=Object.prototype.hasOwnProperty;const SAFE_ENV=new Set(['SCAFFOLD','LAB','PREPROD']);
function req(v,l){if(typeof v!=='string'||!v.trim())throw new Error(`${l} required`);return v.trim();}
function ctxOf(i){const c=i?.context;if(!c||typeof c!=='object'||Array.isArray(c))throw new Error('context required');const d=Object.getOwnPropertyDescriptors(c);for(const k of ['company_id','engine_id','environment','version']){if(!OWN.call(d,k)||d[k].get||d[k].set)throw new Error(`context.${k} must be own data`);}const s=Object.freeze({company_id:req(d.company_id.value,'company_id'),engine_id:req(d.engine_id.value,'engine_id'),environment:req(d.environment.value,'environment'),version:req(d.version.value,'version')});if(s.engine_id!=='CAP-001')throw new Error('engine_id must be CAP-001');if(!SAFE_ENV.has(s.environment))throw new Error('unsafe environment');return s;}
function ownBool(i,k,def=false){if(!OWN.call(i,k))return def;if(typeof i[k]!=='boolean')throw new Error(`${k} must be boolean`);return i[k];}
function ownCost(i,k){if(!OWN.call(i,k))return 0;const v=i[k];if(typeof v!=='number'||!Number.isFinite(v)||v<0)throw new Error(`${k} must be finite nonnegative number`);return v;}
function unique(a,l){if(!Array.isArray(a)||a.length===0)throw new Error(`${l} required`);return Object.freeze([...new Set(a.map(v=>req(v,l)))]);}
function human(reason,ctx){return Object.freeze({status:'HUMAN_REQUIRED',reason,context:ctx,executed:false});}
export function planAcquisition(i={}){const context=ctxOf(i),authorized=ownBool(i,'authorized',false),prodWrite=ownBool(i,'requires_prod_write',false),cost=ownCost(i,'estimated_additional_cost_eur');if(prodWrite)return human('HIGH_RISK',context);if(cost>0)return human('MONEY_LIMIT',context);if(!authorized)return human('POLICY_CONFLICT',context);const channels=unique(i.channels,'channels'),evidence=unique(i.evidence_refs,'evidence_refs');const objective=req(i.objective,'objective');return Object.freeze({status:'ACQUISITION_PLAN_READY',engine_id:'CAP-001',context,mode:'PLAN_ONLY',executed:false,prod_writes:false,trading_access:false,additional_cost_target_eur:0,objective,channels,evidence_refs:evidence,decision_policy:'ZERO_COST_FIRST',paid_budget_eur:0,paid_activation:false,outputs:Object.freeze(['channel_ranking','landing_hypotheses','creative_hypotheses','experiment_plan','stop_scale_rules']),requires_policy_before_external_action:true});}
export function rankChannel({expected_leads,quality_score,effort_score,cost_eur=0,confidence}){for(const [k,v] of Object.entries({expected_leads,quality_score,effort_score,cost_eur,confidence}))if(typeof v!=='number'||!Number.isFinite(v))throw new Error(`${k} must be finite`);if(expected_leads<0||quality_score<0||quality_score>1||effort_score<=0||cost_eur<0||confidence<0||confidence>1)throw new Error('invalid channel metrics');if(cost_eur>0)return Object.freeze({status:'HUMAN_REQUIRED',reason:'MONEY_LIMIT',score:null});if(confidence<0.6)return Object.freeze({status:'HUMAN_REQUIRED',reason:'LOW_CONFIDENCE',score:null});return Object.freeze({status:'RANKED',score:Number(((expected_leads*quality_score*confidence)/effort_score).toFixed(6)),deterministic:true,cost_eur:0});}
