const REQUIRED_CONTEXT=['company_id','engine_id','environment','version'];
const HUMAN_REQUIRED=new Set(['LEGAL_REQUIRED','SIGNATURE_REQUIRED','LOW_CONFIDENCE','HIGH_RISK','POLICY_CONFLICT','SECURITY_INCIDENT','MONEY_LIMIT','CUSTOMER_HUMAN_REQUEST']);
const SAFE_ENV=new Set(['SCAFFOLD','LAB','PREPROD']);
const OWN=Object.prototype.hasOwnProperty;
function req(v,l){if(typeof v!=='string'||!v.trim())throw new Error(`${l} required`);return v.trim();}
function snapshotContext(input){const raw=input?.context;if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('context required');const d=Object.getOwnPropertyDescriptors(raw);for(const k of REQUIRED_CONTEXT){if(!OWN.call(d,k)||d[k].get||d[k].set)throw new Error(`context.${k} must be own data`);}const c={company_id:req(d.company_id.value,'context.company_id'),engine_id:req(d.engine_id.value,'context.engine_id'),environment:req(d.environment.value,'context.environment'),version:req(d.version.value,'context.version')};if(c.engine_id!=='MKT-001')throw new Error('engine_id must be MKT-001');if(!SAFE_ENV.has(c.environment))throw new Error('unsafe environment');return Object.freeze(c);}
function human(reason,ctx){if(!HUMAN_REQUIRED.has(reason))throw new Error('invalid HUMAN_REQUIRED');return Object.freeze({status:'HUMAN_REQUIRED',reason,context:ctx,executed:false});}
function boolOwn(input,key,defaultValue=false){if(!OWN.call(input,key))return defaultValue;if(typeof input[key]!=='boolean')throw new Error(`${key} must be boolean`);return input[key];}
function costOwn(input,key){if(!OWN.call(input,key))return 0;const v=input[key];if(typeof v!=='number'||!Number.isFinite(v)||v<0)throw new Error(`${key} must be finite nonnegative number`);return v;}
function uniqueStrings(v,label){if(v==null)return Object.freeze([]);if(!Array.isArray(v))throw new Error(`${label} must be array`);return Object.freeze([...new Set(v.map(x=>req(x,label)))]);}
function chooseReason({prodWrite,cost,authorized}){if(prodWrite)return 'HIGH_RISK';if(cost>0)return 'MONEY_LIMIT';if(!authorized)return 'POLICY_CONFLICT';return null;}
export function planMarketing(input={}){const ctx=snapshotContext(input);const authorized=boolOwn(input,'authorized',false);const prodWrite=boolOwn(input,'requires_prod_write',false);const cost=costOwn(input,'estimated_additional_cost_eur');const reason=chooseReason({prodWrite,cost,authorized});if(reason)return human(reason,ctx);const evidenceRefs=uniqueStrings(input.evidence_refs,'evidence_ref');const channels=uniqueStrings(input.channels,'channel');const objectives=uniqueStrings(input.objectives,'objective');if(evidenceRefs.length===0||objectives.length===0)return human('LOW_CONFIDENCE',ctx);return Object.freeze({status:'MARKETING_PLAN_READY',engine_id:'MKT-001',context:ctx,mode:'PLAN_ONLY',executed:false,prod_writes:false,trading_access:false,additional_cost_target_eur:0,evidence_refs:evidenceRefs,channels,objectives,outputs:Object.freeze(['positioning','audience_segments','channel_plan','content_backlog','experiment_backlog','measurement_plan']),budget_policy:'ZERO_COST_FIRST',paid_activation:false,requires_policy_before_external_action:true});}
export function scoreExperiment(input={}){const confidence=Number(input.confidence);const impact=Number(input.impact);const effort=Number(input.effort);const cost=Number(input.cost_eur??0);for(const [k,v] of [['confidence',confidence],['impact',impact],['effort',effort],['cost_eur',cost]])if(!Number.isFinite(v))throw new Error(`${k} must be finite`);if(confidence<0||confidence>1||impact<0||impact>10||effort<=0||cost<0)throw new Error('invalid experiment metrics');if(cost>0)return Object.freeze({status:'HUMAN_REQUIRED',reason:'MONEY_LIMIT',score:null});if(confidence<0.6)return Object.freeze({status:'HUMAN_REQUIRED',reason:'LOW_CONFIDENCE',score:null});const score=Number(((impact*confidence)/effort).toFixed(6));return Object.freeze({status:'SCORED',score,cost_eur:0,deterministic:true});}
