import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")??"";
const A=Deno.env.get("SUPABASE_ANON_KEY")??"";
const S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const OPENAI=Deno.env.get("OPENAI_API_KEY")??"";
const BUCKET="fenix-prod-documents";
const APPLY="fenix-document-intelligence";
const ALLOWED=new Set(["https://app.fenixcapital.es"]);
const SUPPORTED=new Set(["application/pdf","image/png","image/jpeg","image/webp"]);
const MAX=12*1024*1024;

function headers(req:Request){const o=req.headers.get("origin")||"";return{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-fenix-env":"PROD","Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://app.fenixcapital.es","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
function out(req:Request,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:headers(req)})}
function b64(bytes:Uint8Array){let s="";const step=0x8000;for(let i=0;i<bytes.length;i+=step)s+=String.fromCharCode(...bytes.subarray(i,i+step));return btoa(s)}
function cleanString(v:unknown,max=1000){return typeof v==="string"?v.trim().slice(0,max):""}
function cleanFields(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))return{};const src=v as Record<string,unknown>,o:Record<string,string|number|boolean>={};for(const[k,val]of Object.entries(src)){if(val===null||val===undefined||val==="")continue;if(typeof val==="string")o[k]=val.trim().slice(0,1000);else if(typeof val==="number"&&Number.isFinite(val))o[k]=val;else if(typeof val==="boolean")o[k]=val}return o}
function outputText(r:any){if(typeof r?.output_text==="string"&&r.output_text.trim())return r.output_text;for(const item of r?.output??[])for(const c of item?.content??[])if(c?.type==="output_text"&&typeof c.text==="string")return c.text;return""}

const schema={type:"object",additionalProperties:false,properties:{document_type:{type:"string"},person:{type:"string"},confidence:{type:"number",minimum:0,maximum:1},summary:{type:"string"},fields:{type:"object",additionalProperties:false,properties:{nombre:{type:["string","null"]},apellidos:{type:["string","null"]},documento_identidad:{type:["string","null"]},fecha_nacimiento:{type:["string","null"]},telefono:{type:["string","null"]},email:{type:["string","null"]},domicilio:{type:["string","null"]},codigo_postal:{type:["string","null"]},localidad:{type:["string","null"]},provincia:{type:["string","null"]},nacionalidad:{type:["string","null"]},estado_civil:{type:["string","null"]},profesion:{type:["string","null"]},empresa:{type:["string","null"]},tipo_contrato:{type:["string","null"]},antiguedad_laboral:{type:["string","null"]},ingresos_netos_mensuales:{type:["number","null"]},otros_ingresos_mensuales:{type:["number","null"]},cuotas_deuda_mensuales:{type:["number","null"]},ahorros:{type:["number","null"]},precio_vivienda:{type:["number","null"]},importe_solicitado:{type:["number","null"]}},required:["nombre","apellidos","documento_identidad","fecha_nacimiento","telefono","email","domicilio","codigo_postal","localidad","provincia","nacionalidad","estado_civil","profesion","empresa","tipo_contrato","antiguedad_laboral","ingresos_netos_mensuales","otros_ingresos_mensuales","cuotas_deuda_mensuales","ahorros","precio_vivienda","importe_solicitado"]}},required:["document_type","person","confidence","summary","fields"]};

type Ctx={actor_code:string;role:string};
type Resolved={upload:any;origin_type:string;origin_code:string;document_id:string|null;legacy:boolean};

async function resolveUpload(svc:any,ctx:Ctx,uploadId:string):Promise<{ok:boolean,status:number,error?:string,data?:Resolved}>{
 const q=await svc.schema("fenix_prod").from("document_upload_sessions").select("id,actor_code,origin_type,origin_code,storage_path,mime_type,filename,status").eq("id",uploadId).maybeSingle();
 if(q.error||!q.data)return{ok:false,status:404,error:"upload_not_found"};const us:any=q.data;
 if(us.status!=="completed")return{ok:false,status:409,error:"upload_not_completed"};
 if(us.origin_type&&us.origin_code){if(ctx.role!=="Direccion"&&us.actor_code!==ctx.actor_code)return{ok:false,status:403,error:"forbidden"};return{ok:true,status:200,data:{upload:us,origin_type:String(us.origin_type),origin_code:String(us.origin_code),document_id:null,legacy:false}}}
 if(ctx.role!=="Direccion")return{ok:false,status:403,error:"legacy_backfill_direction_only"};
 const v=await svc.schema("fenix_prod").from("document_versions").select("document_id").eq("storage_path",us.storage_path).maybeSingle();if(v.error||!v.data)return{ok:false,status:404,error:"legacy_document_version_not_found"};
 const d=await svc.schema("fenix_prod").from("documentos").select("id,expediente_id").eq("id",v.data.document_id).maybeSingle();if(d.error||!d.data?.expediente_id)return{ok:false,status:409,error:"legacy_document_without_expediente"};
 const e=await svc.schema("fenix_prod").from("expedientes").select("expediente_code").eq("id",d.data.expediente_id).eq("synthetic",false).maybeSingle();if(e.error||!e.data?.expediente_code)return{ok:false,status:404,error:"legacy_expediente_not_found"};
 return{ok:true,status:200,data:{upload:us,origin_type:"expediente",origin_code:String(e.data.expediente_code),document_id:String(d.data.id),legacy:true}};
}

async function extractOne(req:Request,svc:any,ctx:Ctx,auth:string,uploadId:string,body:any){
 const resolved=await resolveUpload(svc,ctx,uploadId);if(!resolved.ok||!resolved.data)return{status:resolved.status,body:{ok:false,error:resolved.error}};const r=resolved.data,us=r.upload;
 const mime=String(us.mime_type||"").toLowerCase();if(!SUPPORTED.has(mime))return{status:415,body:{ok:false,error:"unsupported_document",mime_type:mime}};
 const dl=await svc.storage.from(BUCKET).download(us.storage_path);if(dl.error||!dl.data)return{status:404,body:{ok:false,error:"document_missing"}};if(dl.data.size>MAX)return{status:413,body:{ok:false,error:"document_too_large"}};
 if(r.legacy)await svc.schema("fenix_prod").from("document_intelligence_runs").upsert({upload_id:uploadId,document_id:r.document_id,expediente_code:r.origin_code,actor_code:ctx.actor_code,status:"processing",error:null,updated_at:new Date().toISOString()});
 const bytes=new Uint8Array(await dl.data.arrayBuffer()),dataUrl=`data:${mime};base64,${b64(bytes)}`;
 const fileContent=mime==="application/pdf"?{type:"input_file",filename:String(us.filename||"documento.pdf"),file_data:dataUrl}:{type:"input_image",image_url:dataUrl,detail:"high"};
 const ai=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${OPENAI}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-4.1-mini",store:false,temperature:0,instructions:"Eres un extractor documental para Fénix Capital. El archivo puede ser un PDF cuyo contenido sea únicamente una imagen escaneada o exportada desde Canva. Lee visualmente todas las páginas. Extrae solo datos realmente visibles y atribuibles a la persona/operación del documento. No inventes ni completes por contexto. Usa null si no aparece o no es legible. Fechas YYYY-MM-DD. Conserva DNI/NIE/pasaporte tal como aparece. Importes como números. Si un documento no prueba un campo, déjalo null.",input:[{role:"user",content:[{type:"input_text",text:"Lee visualmente este PDF o imagen y devuelve los datos estructurados de la persona/operación."},fileContent]}],text:{format:{type:"json_schema",name:"fenix_profile_extract",strict:true,schema}}})});
 const raw=await ai.text();let parsed:any=null;try{const x=JSON.parse(raw),t=outputText(x);parsed=t?JSON.parse(t):null}catch{}
 if(!ai.ok||!parsed){if(r.legacy)await svc.schema("fenix_prod").from("document_intelligence_runs").update({status:"failed",error:"document_extract_failed",updated_at:new Date().toISOString()}).eq("upload_id",uploadId);return{status:502,body:{ok:false,error:"document_extract_failed",provider_status:ai.status}}}
 const extracted=cleanFields(parsed.fields);if(!Object.keys(extracted).length){if(r.legacy)await svc.schema("fenix_prod").from("document_intelligence_runs").update({status:"failed",extraction:parsed,error:"no_fields_detected",updated_at:new Date().toISOString()}).eq("upload_id",uploadId);return{status:422,body:{ok:false,error:"no_fields_detected"}}}
 const declaredType=cleanString(body?.declared_document_type,120)||cleanString(parsed.document_type,120)||"Documento";
 const declaredPerson=cleanString(body?.declared_person,220)||cleanString(parsed.person,220)||"Persona no identificada";
 const applyPayload={origin_type:r.origin_type,origin_code:r.origin_code,declared_document_type:declaredType,declared_person:declaredPerson,document_type:cleanString(parsed.document_type,120)||declaredType,confidence:Number(parsed.confidence)||0,summary:cleanString(parsed.summary,1900),fields:extracted,document_page_id:r.legacy?"":cleanString(body?.document_page_id,100),confirm_overwrite:Boolean(body?.confirm_overwrite)};
 const applied=await fetch(`${U}/functions/v1/${APPLY}/apply`,{method:"POST",headers:{Authorization:auth,apikey:A,"content-type":"application/json"},body:JSON.stringify(applyPayload)});const appliedText=await applied.text();let appliedBody:any=null;try{appliedBody=JSON.parse(appliedText)}catch{appliedBody={raw:appliedText.slice(0,400)}};
 let fieldApply:any=null;if(r.origin_type==="expediente"){const f=await svc.rpc("fenix_prod_document_intelligence_fields_server",{p_actor_code:ctx.actor_code,p_exp_code:r.origin_code,p_fields:extracted});fieldApply=f.error?{ok:false,error:"field_apply_failed"}:f.data;}
 const review=applied.status===409;const ok=(applied.ok||review)&&(!fieldApply||fieldApply.ok!==false);if(r.legacy)await svc.schema("fenix_prod").from("document_intelligence_runs").update({status:review?"needs_review":ok?"applied":"failed",extraction:{document_type:applyPayload.document_type,person:declaredPerson,confidence:applyPayload.confidence,summary:applyPayload.summary,fields:extracted,canonical_fields:fieldApply},error:ok?null:(appliedBody?.error||fieldApply?.error||"apply_failed"),updated_at:new Date().toISOString()}).eq("upload_id",uploadId);
 return{status:review?409:ok?200:(applied.status>=400?applied.status:500),body:{ok:ok&&!review,status:review?409:ok?200:500,review_required:review,legacy:r.legacy,upload_id:uploadId,origin_type:r.origin_type,origin_code:r.origin_code,extraction:{document_type:applyPayload.document_type,person:declaredPerson,confidence:applyPayload.confidence,summary:applyPayload.summary,fields:extracted},applied:appliedBody,canonical_fields:fieldApply}};
}

Deno.serve(async(req:Request)=>{try{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:headers(req)});if(req.method!=="POST")return out(req,{ok:false,error:"method_not_allowed"},405);
 const auth=req.headers.get("authorization")??"";if(!auth.toLowerCase().startsWith("bearer "))return out(req,{ok:false,error:"unauthorized"},401);if(!U||!A||!S||!OPENAI)return out(req,{ok:false,error:"server_config_missing",openai_configured:Boolean(OPENAI)},503);
 const user=createClient(U,A,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}}),svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});const c=await user.rpc("fenix_prod_session_context");if(c.error||!c.data?.actor_code)return out(req,{ok:false,error:"identity_not_linked"},403);const ctx:Ctx={actor_code:String(c.data.actor_code),role:String(c.data.role||"")};
 const body=await req.json().catch(()=>null);if(!body)return out(req,{ok:false,error:"invalid_json"},400);
 if(body.mode==="legacy_status"){if(ctx.role!=="Direccion")return out(req,{ok:false,error:"forbidden"},403);const all=await svc.schema("fenix_prod").from("document_upload_sessions").select("id",{count:"exact",head:true}).eq("status","completed").eq("mime_type","application/pdf").is("origin_type",null);const runs=await svc.schema("fenix_prod").from("document_intelligence_runs").select("status");const counts:Record<string,number>={};for(const x of runs.data??[])counts[x.status]=(counts[x.status]??0)+1;return out(req,{ok:true,total_legacy_pdfs:all.count??0,processed:Object.values(counts).reduce((a,b)=>a+b,0),by_status:counts});}
 if(body.mode==="legacy_batch"){if(ctx.role!=="Direccion")return out(req,{ok:false,error:"forbidden"},403);const limit=Math.max(1,Math.min(2,Number(body.limit)||2));const done=await svc.schema("fenix_prod").from("document_intelligence_runs").select("upload_id");const doneIds=new Set((done.data??[]).map((x:any)=>String(x.upload_id)));const q=await svc.schema("fenix_prod").from("document_upload_sessions").select("id").eq("status","completed").eq("mime_type","application/pdf").is("origin_type",null).order("created_at",{ascending:true}).limit(250);const ids=(q.data??[]).map((x:any)=>String(x.id)).filter((id:string)=>!doneIds.has(id)).slice(0,limit);const results=[] as any[];for(const id of ids){const z=await extractOne(req,svc,ctx,auth,id,body);results.push({upload_id:id,status:z.status,ok:z.body?.ok,review_required:z.body?.review_required,error:z.body?.error,origin_code:z.body?.origin_code,extraction:z.body?.extraction,applied:z.body?.applied,canonical_fields:z.body?.canonical_fields});}return out(req,{ok:true,attempted:ids.length,results});}
 const uploadId=cleanString(body.upload_id,80);if(!uploadId)return out(req,{ok:false,error:"upload_id_required"},400);const z=await extractOne(req,svc,ctx,auth,uploadId,body);return out(req,z.body,z.status);
 }catch(e){console.error("fenix-document-extract-prod",e);return out(req,{ok:false,error:"document_extract_exception"},500)}});
