-- PROD contract: expediente intervinientes -> canonical clientes -> contact lists.
-- Applied to cluhljgonannaafpmblx on 2026-09-07 before merge; idempotent replay.

alter table fenix_prod.clientes add column if not exists dni_nie text;
alter table fenix_prod.clientes add column if not exists profile jsonb not null default '{}'::jsonb;

create table if not exists fenix_prod.expediente_personas (
 id uuid primary key default gen_random_uuid(), expediente_code text not null references fenix_prod.expedientes(expediente_code) on delete cascade,
 cliente_code text not null references fenix_prod.clientes(cliente_code) on delete cascade, rol_operacion text not null default 'Titular comprador',
 orden_expediente integer, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(expediente_code,cliente_code)
);
alter table fenix_prod.expediente_personas enable row level security;
revoke all on fenix_prod.expediente_personas from anon,authenticated;

create table if not exists fenix_prod.contact_lists (
 id uuid primary key default gen_random_uuid(), list_code text not null unique, nombre text not null unique, active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table fenix_prod.contact_lists enable row level security;
revoke all on fenix_prod.contact_lists from anon,authenticated;

create table if not exists fenix_prod.contact_list_members (
 list_code text not null references fenix_prod.contact_lists(list_code) on delete cascade,
 cliente_code text not null references fenix_prod.clientes(cliente_code) on delete cascade, created_at timestamptz not null default now(), primary key(list_code,cliente_code)
);
alter table fenix_prod.contact_list_members enable row level security;
revoke all on fenix_prod.contact_list_members from anon,authenticated;

create or replace function public.fenix_prod_exp_people_server(p_actor_code text,p_exp_code text) returns jsonb language plpgsql security definer set search_path=public,fenix_prod as $$
declare v_role text;v_items jsonb;v_count int;v_tit int;v_ava int;
begin
 select role into v_role from fenix_prod.actors where actor_code=p_actor_code and active;
 if not exists(select 1 from fenix_prod.expedientes where expediente_code=p_exp_code) then return jsonb_build_object('ok',false,'status',404,'error','expediente_not_found');end if;
 if coalesce(v_role,'') not in('Direccion','Financiero') then return jsonb_build_object('ok',false,'status',403,'error','forbidden');end if;
 select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('id',c.cliente_code,'contact_code',c.cliente_code,'comprador',trim(concat_ws(' ',c.nombre,c.apellidos)),'nombre',c.nombre,'apellidos',c.apellidos,'dni_nie',c.dni_nie,'telefono',c.telefono,'email',c.email,'rol_operacion',ep.rol_operacion,'orden_expediente',ep.orden_expediente,'fecha_nacimiento',c.profile->>'fecha_nacimiento','nacionalidad',c.profile->>'nacionalidad','residencia',c.profile->>'residencia','estado_civil',c.profile->>'estado_civil','regimen_matrimonial',c.profile->>'regimen_matrimonial','situacion_laboral',c.profile->>'situacion_laboral','empresa_organismo',coalesce(c.profile->>'empresa_organismo',c.profile->>'empresa'),'antiguedad_laboral',c.profile->>'antiguedad_laboral','sueldo_neto_mensual',nullif(c.profile->>'sueldo_neto_mensual','')::numeric,'deudas_mensuales',nullif(c.profile->>'deudas_mensuales','')::numeric,'ahorro_disponible',nullif(c.profile->>'ahorro_disponible','')::numeric,'listas',(select coalesce(jsonb_agg(l.nombre order by l.nombre),'[]'::jsonb) from fenix_prod.contact_list_members m join fenix_prod.contact_lists l on l.list_code=m.list_code where m.cliente_code=c.cliente_code and l.active))) order by coalesce(ep.orden_expediente,999),ep.created_at),'[]'::jsonb),count(*),count(*) filter(where lower(ep.rol_operacion) like '%titular%' or lower(ep.rol_operacion) like '%comprador%'),count(*) filter(where lower(ep.rol_operacion) like '%avalista%') into v_items,v_count,v_tit,v_ava from fenix_prod.expediente_personas ep join fenix_prod.clientes c on c.cliente_code=ep.cliente_code where ep.expediente_code=p_exp_code and ep.active and c.active;
 return jsonb_build_object('ok',true,'status',200,'count',v_count,'titulares',v_tit,'avalistas',v_ava,'items',v_items);
exception when others then return jsonb_build_object('ok',false,'status',500,'error',sqlerrm);end$$;

create or replace function public.fenix_prod_exp_person_create_server(p_actor_code text,p_exp_code text,p_payload jsonb) returns jsonb language plpgsql security definer set search_path=public,fenix_prod as $$
declare v_role text;v_client text;v_existing text;v_dni text;v_name text;v_last text;v_rel uuid;
begin
 select role into v_role from fenix_prod.actors where actor_code=p_actor_code and active;if coalesce(v_role,'') not in('Direccion','Financiero') then return jsonb_build_object('ok',false,'status',403,'error','forbidden');end if;
 if not exists(select 1 from fenix_prod.expedientes where expediente_code=p_exp_code) then return jsonb_build_object('ok',false,'status',404,'error','expediente_not_found');end if;
 v_name=nullif(trim(coalesce(p_payload->>'nombre','')),'');if v_name is null then return jsonb_build_object('ok',false,'status',400,'error','nombre_required');end if;v_last=nullif(trim(coalesce(p_payload->>'apellidos','')),'');v_dni=upper(regexp_replace(coalesce(p_payload->>'dni_nie',''),'[^A-Za-z0-9]','','g'));
 if v_dni<>'' then select cliente_code into v_client from fenix_prod.clientes where upper(regexp_replace(coalesce(dni_nie,''),'[^A-Za-z0-9]','','g'))=v_dni and active order by created_at limit 1;end if;
 if v_client is null then v_client='CLI-'||upper(substr(md5(gen_random_uuid()::text),1,12));insert into fenix_prod.clientes(cliente_code,nombre,apellidos,estado,cliente_fenix,consentimiento_comercial,source_payload,synthetic,active,dni_nie,profile) values(v_client,v_name,v_last,'Activo',true,false,jsonb_build_object('source','expediente_interviniente','expediente_code',p_exp_code),false,true,nullif(v_dni,''),p_payload-'nombre'-'apellidos'-'dni_nie'-'rol_operacion'-'orden_expediente');else select ep.cliente_code into v_existing from fenix_prod.expediente_personas ep where ep.expediente_code=p_exp_code and ep.cliente_code=v_client and ep.active;if v_existing is not null then return jsonb_build_object('ok',false,'status',409,'error','already_linked','existing_id',v_existing);end if;end if;
 insert into fenix_prod.expediente_personas(expediente_code,cliente_code,rol_operacion,orden_expediente) values(p_exp_code,v_client,coalesce(nullif(p_payload->>'rol_operacion',''),'Titular comprador'),nullif(p_payload->>'orden_expediente','')::int) returning id into v_rel;return jsonb_build_object('ok',true,'status',201,'id',v_client,'relation_id',v_rel);
exception when unique_violation then return jsonb_build_object('ok',false,'status',409,'error','already_linked','existing_id',v_client);when others then return jsonb_build_object('ok',false,'status',500,'error',sqlerrm);end$$;

create or replace function public.fenix_prod_exp_person_update_server(p_actor_code text,p_client_code text,p_changes jsonb) returns jsonb language plpgsql security definer set search_path=public,fenix_prod as $$
declare v_role text;v_profile jsonb;v_dni text;
begin select role into v_role from fenix_prod.actors where actor_code=p_actor_code and active;if coalesce(v_role,'') not in('Direccion','Financiero') then return jsonb_build_object('ok',false,'status',403,'error','forbidden');end if;if not exists(select 1 from fenix_prod.clientes where cliente_code=p_client_code and active) then return jsonb_build_object('ok',false,'status',404,'error','contact_not_found');end if;
 v_dni=case when p_changes?'dni_nie' then nullif(upper(regexp_replace(coalesce(p_changes->>'dni_nie',''),'[^A-Za-z0-9]','','g')),'') else null end;if v_dni is not null and exists(select 1 from fenix_prod.clientes where cliente_code<>p_client_code and active and upper(regexp_replace(coalesce(dni_nie,''),'[^A-Za-z0-9]','','g'))=v_dni) then return jsonb_build_object('ok',false,'status',409,'error','dni_already_exists');end if;select profile into v_profile from fenix_prod.clientes where cliente_code=p_client_code;
 update fenix_prod.clientes set nombre=case when p_changes?'nombre' then coalesce(nullif(trim(p_changes->>'nombre'),''),nombre) else nombre end,apellidos=case when p_changes?'apellidos' then nullif(trim(p_changes->>'apellidos'),'') else apellidos end,dni_nie=case when p_changes?'dni_nie' then v_dni else dni_nie end,telefono=case when p_changes?'telefono' then nullif(trim(p_changes->>'telefono'),'') else telefono end,email=case when p_changes?'email' then nullif(trim(p_changes->>'email'),'') else email end,profile=coalesce(v_profile,'{}'::jsonb)||(p_changes-'nombre'-'apellidos'-'dni_nie'-'telefono'-'email'-'rol_operacion'-'orden_expediente'),updated_at=now() where cliente_code=p_client_code;
 if p_changes?'rol_operacion' or p_changes?'orden_expediente' then update fenix_prod.expediente_personas set rol_operacion=case when p_changes?'rol_operacion' then coalesce(nullif(p_changes->>'rol_operacion',''),rol_operacion) else rol_operacion end,orden_expediente=case when p_changes?'orden_expediente' then nullif(p_changes->>'orden_expediente','')::int else orden_expediente end,updated_at=now() where cliente_code=p_client_code and active;end if;return jsonb_build_object('ok',true,'status',200,'id',p_client_code);
exception when others then return jsonb_build_object('ok',false,'status',500,'error',sqlerrm);end$$;

create or replace function public.fenix_prod_contact_lists_server(p_actor_code text,p_client_code text default null) returns jsonb language plpgsql security definer set search_path=public,fenix_prod as $$declare v_role text;v_items jsonb;begin select role into v_role from fenix_prod.actors where actor_code=p_actor_code and active;if coalesce(v_role,'') not in('Direccion','Financiero') then return jsonb_build_object('ok',false,'status',403,'error','forbidden');end if;select coalesce(jsonb_agg(jsonb_build_object('list_code',l.list_code,'nombre',l.nombre,'selected',case when p_client_code is null then false else exists(select 1 from fenix_prod.contact_list_members m where m.list_code=l.list_code and m.cliente_code=p_client_code)end) order by l.nombre),'[]'::jsonb) into v_items from fenix_prod.contact_lists l where l.active;return jsonb_build_object('ok',true,'status',200,'items',v_items);end$$;

create or replace function public.fenix_prod_contact_list_assign_server(p_actor_code text,p_client_code text,p_list_name text,p_selected boolean) returns jsonb language plpgsql security definer set search_path=public,fenix_prod as $$declare v_role text;v_code text;begin select role into v_role from fenix_prod.actors where actor_code=p_actor_code and active;if coalesce(v_role,'') not in('Direccion','Financiero') then return jsonb_build_object('ok',false,'status',403,'error','forbidden');end if;if not exists(select 1 from fenix_prod.clientes where cliente_code=p_client_code and active) then return jsonb_build_object('ok',false,'status',404,'error','contact_not_found');end if;v_code='LIST-'||upper(substr(md5(lower(trim(p_list_name))),1,12));if p_selected then insert into fenix_prod.contact_lists(list_code,nombre) values(v_code,trim(p_list_name)) on conflict(nombre) do update set active=true,updated_at=now() returning list_code into v_code;insert into fenix_prod.contact_list_members(list_code,cliente_code) values(v_code,p_client_code) on conflict do nothing;else select list_code into v_code from fenix_prod.contact_lists where lower(nombre)=lower(trim(p_list_name));if v_code is not null then delete from fenix_prod.contact_list_members where list_code=v_code and cliente_code=p_client_code;end if;end if;return jsonb_build_object('ok',true,'status',200,'list_code',v_code,'selected',p_selected);end$$;

-- Existing expedientes are backfilled exactly once into a stable CLI-EXP-* contact.
insert into fenix_prod.clientes(cliente_code,nombre,apellidos,estado,cliente_fenix,consentimiento_comercial,source_payload,synthetic,active,dni_nie,profile)
select 'CLI-EXP-'||upper(substr(md5(e.expediente_code),1,12)),coalesce(nullif(trim(e.payload_operacion->>'nombre'),''),coalesce(nullif(trim(e.cliente_alias),''),'Cliente')),nullif(trim(e.payload_operacion->>'apellidos'),''),'Activo',true,false,jsonb_build_object('source','expediente_backfill','expediente_code',e.expediente_code),false,true,nullif(upper(regexp_replace(coalesce(e.payload_operacion->>'documento_identidad',''),'[^A-Za-z0-9]','','g')),''),coalesce(e.payload_operacion,'{}'::jsonb) from fenix_prod.expedientes e where(coalesce(e.payload_operacion->>'nombre','')<>'' or coalesce(e.payload_operacion->>'documento_identidad','')<>'') and not exists(select 1 from fenix_prod.expediente_personas ep where ep.expediente_code=e.expediente_code) on conflict(cliente_code) do nothing;
insert into fenix_prod.expediente_personas(expediente_code,cliente_code,rol_operacion,orden_expediente) select e.expediente_code,'CLI-EXP-'||upper(substr(md5(e.expediente_code),1,12)),'Titular comprador',1 from fenix_prod.expedientes e join fenix_prod.clientes c on c.cliente_code='CLI-EXP-'||upper(substr(md5(e.expediente_code),1,12)) where not exists(select 1 from fenix_prod.expediente_personas ep where ep.expediente_code=e.expediente_code) on conflict do nothing;
