import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const ALLOWED=new Set(['https://app.fenixcapital.es']);
function key(raw:string){try{const x=JSON.parse(raw||'{}');return String((x as any)?.default??Object.values(x??{})[0]??'')}catch{return ''}}
function config(){const URL=Deno.env.get('SUPABASE_URL')??'',ANON=Deno.env.get('SUPABASE_ANON_KEY')||key(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')??''),SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||key(Deno.env.get('SUPABASE_SECRET_KEYS')??'');return{URL,ANON,SERVICE}}
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ALLOWED.has(o)?o:'https://app.fenixcapital.es','Access-Control-Allow-Headers':'authorization,apikey,content-type,idempotency-key','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Vary':'Origin','x-fenix-env':'PROD'}}
function out(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function json(req:Request){try{return await req.json()}catch{return {}}}
async function identity(req:Request){const c=config(),h=req.headers.get('authorization')||'';if(!c.URL||!c.ANON||!c.SERVICE||!h.startsWith('Bearer '))return null;const auth=createClient(c.URL,c.ANON,{auth:{persistSession:false,autoRefreshToken:false}}),svc=createClient(c.URL,c.SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});const {data:u,error}=await auth.auth.getUser(h.slice(7));if(error||!u.user)return null;const {data:ctx,error:ce}=await svc.rpc('fenix_prod_actor_context_by_auth_server',{p_auth_user_id:u.user.id});if(ce||!ctx?.ok)return null;return{svc,actor:ctx.actor_code}}
function route(req:Request){return new URL(req.url).pathname.replace(/^\/(?:functions\/v1\/)?fenix-task-api/,'')||'/'}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const me=await identity(req);if(!me)return out(req,{ok:false,status:401,error:'unauthorized'},401);const p=route(req),raw=p==='/'?'':decodeURIComponent(p.slice(1));try{if(req.method==='POST'&&!raw){const b:any=await json(req),due=b.fecha_limite?new Date(String(b.fecha_limite)).toISOString():null;const {data:r,error}=await me.svc.rpc('fenix_prod_task_create_server',{p_actor_code:me.actor,p_tarea:String(b.tarea||''),p_target_actor_code:String(b.id_trabajador_operativo||me.actor||''),p_criticidad:b.criticidad||null,p_fecha_limite:due,p_idempotency_key:req.headers.get('idempotency-key')||b.idempotency_key||null});if(error)throw error;return out(req,r,Number(r?.status)||200)}if(req.method==='GET'&&raw){const {data:r,error}=await me.svc.rpc('fenix_prod_task_get_server',{p_actor_code:me.actor,p_task_code:raw});if(error)throw error;return out(req,r,Number(r?.status)||200)}if(req.method==='PATCH'&&raw){const b:any=await json(req);let version=Number(b.expected_version??0)||null;if(b.id_trabajador_operativo){const {data:rr,error:re}=await me.svc.rpc('fenix_prod_reassign_task_server',{p_actor_code:me.actor,p_task_code:raw,p_new_actor_code:String(b.id_trabajador_operativo),p_expected_version:version});if(re)throw re;if(Number(rr?.status)!==200)return out(req,rr,Number(rr?.status)||400);version=Number(rr?.version??(version?version+1:0))||null}const hasUpdate=['estado','criticidad','fecha_limite','completada'].some(k=>Object.prototype.hasOwnProperty.call(b,k));if(!hasUpdate)return out(req,{ok:true,status:200,version,task_code:raw},200);const due=Object.prototype.hasOwnProperty.call(b,'fecha_limite')&&b.fecha_limite?new Date(String(b.fecha_limite)).toISOString():null;const {data:r,error}=await me.svc.rpc('fenix_prod_task_update_server',{p_actor_code:me.actor,p_task_code:raw,p_expected_version:version,p_estado:b.estado??null,p_criticidad:b.criticidad??null,p_fecha_limite:due,p_completada:Object.prototype.hasOwnProperty.call(b,'completada')?Boolean(b.completada):null});if(error)throw error;return out(req,r,Number(r?.status)||200)}return out(req,{ok:false,status:405,error:'method_not_allowed'},405)}catch(e){console.error(e);return out(req,{ok:false,status:500,error:'task_backend_error'},500)}});
