import {test,expect} from '@playwright/test';
import fs from 'node:fs';

test('CEREBRO is served by the authenticated SPA route, not a shadow static page',async()=>{
  expect(fs.existsSync('public/cerebro/index.html')).toBe(false);
  const shell=fs.readFileSync('src/CerebroConsoleShell.tsx','utf8');
  expect(shell).toContain("location.pathname.replace(/\\/+$/,'')==='/cerebro'");
  expect(shell).toContain("data?.actor_code==='CARLOS-ADMIN'");
  const guard=fs.readFileSync('src/RouteAccessGuard.tsx','utf8');
  expect(guard).toContain("'/cerebro'");
  expect(guard).toContain('<CerebroConsoleShell/>');
  const gateway=fs.readFileSync('supabase/functions/cerebro-console-gateway-v0/index.ts','utf8');
  expect(gateway).toContain('actor==="CARLOS-ADMIN"');
  expect(gateway).toContain('reason:"OWNER_ONLY"');
  const knowledge=fs.readFileSync('supabase/functions/cerebro-console-gateway-v0/knowledge.ts','utf8');
  expect(knowledge).toContain('actorCode!=="CARLOS-ADMIN"');
  expect(knowledge).toContain('SOCIAL_SCHEDULE_DATA_SOURCE_ID');
  expect(knowledge).toContain('Programación Editorial');
  expect(knowledge).toContain('cerebro-social-schedule-read-preprod');
  expect(knowledge).toContain('CEREBRO_SOCIAL_QUEUE');
  expect(knowledge).toContain('texto|copy|contenido|caption|que pone');
  expect(knowledge).toContain('message:result.item.caption');
  expect(knowledge).toContain('content_key?:string');
  expect(knowledge).toContain('(^|[^a-z0-9])x([^a-z0-9]|$)');
  expect(knowledge).toContain('socialPublicationByContext');
  expect(knowledge).toContain('caption:String(item?.caption??"")');
  expect(knowledge).toContain('DOMAIN_CANONICAL');
  expect(knowledge).toContain('Conocimiento financiero canónico · Fénix Uno');
  expect(knowledge).toContain('Company Registry · CEREBRO · Fénix Capital');
  expect(knowledge).toContain('read_context');
  const api=fs.readFileSync('src/cerebroConsoleApi.ts','utf8');
  expect(api).toContain('read_context');
  expect(shell).toContain('readContext');
  const socialReader=fs.readFileSync('supabase/functions/cerebro-social-schedule-read-preprod/index.ts','utf8');
  expect(socialReader).toContain('cerebro_social_queue_preprod');
  expect(socialReader).toContain('SOCIAL_READ');
  const app=fs.readFileSync('src/App.tsx','utf8');
  expect(app).toContain("supabase.auth.getSession()");
  expect(app).toContain("fenix-session-active");
  expect(app).toContain("{label:'CEREBRO',route:'/cerebro',resource:'CEREBRO'}");
  const appGateway=fs.readFileSync('supabase/functions/fenix-app-gateway/index.ts','utf8');
  expect(appGateway).toContain("a==='CARLOS-ADMIN'");
  expect(appGateway).toContain("label:'CEREBRO',route:'/cerebro',resource:'CEREBRO'");
  const profile=fs.readFileSync('src/ProfileShell.tsx','utf8');
  expect(profile).toContain("label:'CEREBRO',route:'/cerebro'");
});
