import {test,expect} from '@playwright/test';

const session={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJub25lIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJleHAiOjE5OTk5OTk5OTl9.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-comm-confirm-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'direccion@fenix.test',app_metadata:{},user_metadata:{actor_code:'DIR-TEST'},created_at:'2026-08-23T00:00:00.000Z'}};

async function boot(page:any,item:any,counters:{authorize:number;send:number}){
 await page.addInitScript((s:any)=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(s));localStorage.setItem('fenix-remember-device','true')},session);
 await page.route('**/functions/v1/fenix-app-gateway-test/**',async(r:any)=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-TEST',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Comunicaciones',route:'/comunicaciones'}]})});return r.fulfill({status:404,body:'{}'});});
 await page.route('**/functions/v1/fenix-communications-gateway-test/**',async(r:any)=>{const u=r.request().url();if(r.request().method()==='GET'&&u.endsWith('/comunicaciones'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[item]})});if(u.endsWith('/authorize')){counters.authorize++;return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true})});}if(u.endsWith('/send')){counters.send++;return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true})});}return r.fulfill({status:404,body:'{}'});});
}

test.describe('Fénix PRE-PROD · confirmación de transiciones de comunicación',()=>{
 test('autorizar requiere revisar y confirmar antes del POST',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();const counters={authorize:0,send:0};await boot(page,{communication_code:'COM-QA-1',canal:'Email',scope_type:'expediente',scope_code:'EXP-QA',recipient_alias:'cliente@example.test',estado:'Preparada',version:3,payload_hash:'hash-qa'},counters);await page.goto('/comunicaciones');await page.getByRole('button',{name:'Revisar autorización'}).click();expect(counters.authorize).toBe(0);const preview=page.getByTestId('communication-transition-preview');await expect(preview).toContainText('Email');await expect(preview).toContainText('EXP-QA');await page.getByRole('button',{name:'Confirmar autorización'}).click();await expect.poll(()=>counters.authorize).toBe(1);expect(counters.send).toBe(0);
 });

 test('simulación requiere revisar y confirmar y nunca usa envío real',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();const counters={authorize:0,send:0};let sendBody:any=null;await boot(page,{communication_code:'COM-QA-2',canal:'WhatsApp',scope_type:'expediente',scope_code:'EXP-QA-2',recipient_alias:'600000000',estado:'Autorizada',version:4,payload_hash:'hash-qa-2'},counters);await page.unroute('**/functions/v1/fenix-communications-gateway-test/**');await page.route('**/functions/v1/fenix-communications-gateway-test/**',async(r:any)=>{const u=r.request().url();if(r.request().method()==='GET'&&u.endsWith('/comunicaciones'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{communication_code:'COM-QA-2',canal:'WhatsApp',scope_type:'expediente',scope_code:'EXP-QA-2',recipient_alias:'600000000',estado:'Autorizada',version:4,payload_hash:'hash-qa-2'}]})});if(u.endsWith('/send')){counters.send++;sendBody=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true})});}return r.fulfill({status:404,body:'{}'});});await page.goto('/comunicaciones');await page.getByRole('button',{name:'Revisar simulación'}).click();expect(counters.send).toBe(0);await expect(page.getByTestId('communication-transition-preview')).toContainText('WhatsApp');await page.getByRole('button',{name:'Confirmar simulación'}).click();await expect.poll(()=>counters.send).toBe(1);expect(sendBody.mode).toBe('SIMULATED');
 });
});
