import {test,expect} from '@playwright/test';

const session={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6InFhQGZlbml4LnRlc3QiLCJleHAiOjE5OTk5OTk5OTl9.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-communications-states-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'qa@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-23T00:00:00.000Z'}};

async function seed(page:any){await page.addInitScript((s:any)=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(s));localStorage.setItem('fenix-remember-device','true')},session)}
async function gateway(page:any,role='Direccion',navStatus=200){await page.route('**/functions/v1/fenix-app-gateway-test/**',async(r:any)=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-QA',role})});if(u.endsWith('/navigation'))return r.fulfill({status:navStatus,contentType:'application/json',body:navStatus===200?JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Comunicaciones',route:'/comunicaciones'}]}):'{}'});return r.fulfill({status:404,body:'{}'})})}

test.describe('Fénix PRE-PROD · estados de Comunicaciones',()=>{
 test('carga explícita y vacío autorizado',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await gateway(page);await page.route('**/functions/v1/fenix-communications-gateway-test/comunicaciones',async r=>{await new Promise(res=>setTimeout(res,300));return r.fulfill({status:200,contentType:'application/json',body:'{"items":[]}'})});await page.goto('/comunicaciones');const root=page.locator('.comm-root');await expect(root.getByTestId('communications-loading')).toBeVisible();await expect(root.locator('form.comm-form')).toBeVisible();await expect(root.locator('.ops-table-card tbody tr')).toHaveCount(0);});
 test('403 y navegación caída quedan fail-closed solo Inicio',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await gateway(page,'Direccion',500);await page.route('**/functions/v1/fenix-communications-gateway-test/comunicaciones',r=>r.fulfill({status:403,body:'{}'}));await page.goto('/comunicaciones');const root=page.locator('.comm-root');await expect(root.getByTestId('communications-forbidden')).toHaveText('Tu perfil no tiene acceso al módulo de Comunicaciones.');const menu=root.locator('.ops-side nav');await expect(menu.getByRole('button',{name:'Inicio',exact:true})).toBeVisible();await expect(menu.getByRole('button',{name:'Comunicaciones',exact:true})).toHaveCount(0);await expect(root.locator('form.comm-form')).toHaveCount(0);await expect(root.locator('.ops-table-card')).toHaveCount(0);});
 test('500 técnico no se presenta como 403',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await gateway(page);await page.route('**/functions/v1/fenix-communications-gateway-test/comunicaciones',r=>r.fulfill({status:500,body:'{}'}));await page.goto('/comunicaciones');const root=page.locator('.comm-root');await expect(root.getByTestId('communications-error')).toHaveText('No se pudieron cargar las comunicaciones.');await expect(root.getByText('Tu perfil no tiene acceso al módulo de Comunicaciones.',{exact:true})).toHaveCount(0);await expect(root.locator('form.comm-form')).toHaveCount(0);});
 test('fallo de red termina loading, limpia datos y no habilita acciones',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await gateway(page);await page.route('**/functions/v1/fenix-communications-gateway-test/**',r=>r.abort());await page.goto('/comunicaciones');const root=page.locator('.comm-root');await expect(root.getByTestId('communications-error')).toHaveText('No se pudo conectar con el servicio de comunicaciones.');await expect(root.getByTestId('communications-loading')).toHaveCount(0);await expect(root.locator('form.comm-form')).toHaveCount(0);await expect(root.locator('.ops-table-card')).toHaveCount(0);});
});
