import {expect,test} from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const viewer=fs.readFileSync(path.join(process.cwd(),'src/DocumentViewerShell.tsx'),'utf8');
const gate=fs.readFileSync(path.join(process.cwd(),'src/OperationalRecordDetailGate.tsx'),'utf8');
const library=fs.readFileSync(path.join(process.cwd(),'src/DocumentacionShell.tsx'),'utf8');
test('smart quick viewer stays modal, contextual, financial and non-destructive',async()=>{
 expect(viewer).toContain('VISTA PREVIA FINANCIERA');
 expect(viewer).toContain('role="dialog"');
 expect(viewer).toContain('aria-modal="true"');
 expect(viewer).toContain('position:fixed;inset:0');
 expect(viewer).toContain('height:min(90vh,1000px)');
 expect(viewer).toContain('Datos que necesita el financiero');
 expect(viewer).toContain('No consta en este documento');
 expect(viewer).toContain('Control de calidad');
 expect(viewer).toContain('Acciones seguras');
 expect(viewer).toContain('Abrir original');
 expect(viewer).toContain('^\\/documentacion\\/([^/]+)$');
 expect(viewer).toContain("params.get('preview')==='1'");
 expect(library).toContain('?preview=1&returnTo=');
 expect(gate).toContain("match?.[1]==='documentacion'&&new URLSearchParams(search).get('preview')==='1'");
 expect(viewer).not.toContain('(?:documentos|documentacion)');
 expect(viewer).toContain("u.protocol==='https:'||u.protocol==='http:'");
 expect(viewer).toContain("event.key==='Escape'");
 expect(viewer).not.toMatch(/authenticatedEdgeFetch\([^)]*['\"]fenix-[^'\"]*(?<!-test)['\"]/);
});
