import {expect,test} from '@playwright/test';
import {getDocumentOperationalFields} from '../src/documentOperationalFieldProfile';
function map(row:Record<string,unknown>){return Object.fromEntries(getDocumentOperationalFields(row).map(x=>[x.label,x.value]));}
test('Vida laboral convierte evidencia exacta en métricas laborales útiles',()=>{const x=map({tipo:'Vida laboral',total_dias:7025,fecha_alta_actual:'2022-05-01',fecha_informe:'2026-06-10',periodos_trabajados:'GENERAL SAS 01/05/2022 --- | GENERAL EMPRESA B 01/01/2020 30/04/2022'});expect(x['Años totales cotizados']).toBe('19,2 años');expect(x['Antigüedad empleo actual']).toBe('4,1 años');expect(x['Últimos trabajos / periodos']).toContain('SAS');});
test('Nómina muestra relación neto bruto y alertas explícitas',()=>{const x=map({tipo:'Nómina',bruto:3066.56,neto:2100.53,deducciones:966.03,embargos:'EMBARGO 120,00'});expect(x['Neto sobre bruto']).toBe('68,5 %');expect(x['Deducciones totales']).toContain('966,03');expect(x['Alerta embargos / anticipos']).toContain('EMBARGO');});
test('Renta deriva medias mensuales sin sustituir importes anuales',()=>{const x=map({tipo:'Declaración de la Renta / IRPF',rendimientos_trabajo:59468.81,rendimientos_inmobiliarios:50.72,inmuebles:'1 inmueble'});expect(x['Media mensual trabajo (anual / 12)']).toContain('4.955,73');expect(x['Patrimonio / inmuebles declarados']).toBe('1 inmueble');});
test('Movimientos resume nóminas y financiación detectadas',()=>{const x=map({tipo:'Movimientos bancarios',nominas:'27/05/2026 +2.249,85 NOMINA | 28/04/2026 +2.688,17 NOMINA',cuotas_prestamos:'01/05 FINANCIACION 325,40'});expect(x['Nóminas detectadas en el periodo']).toBe(2);expect(x['Media de abonos de nómina detectados']).toContain('2.469,01');expect(x['Cuotas / financiación detectada']).toContain('325,40');});
test('Nota simple pone cargas en primer plano',()=>{const x=map({tipo:'Nota simple',titulares:'Persona A 100%',hipotecas:'Hipoteca Banco X',embargos:'Embargo AEAT',cargas:'Hipoteca y embargo'});expect(x['Alertas registrales']).toContain('Hipotecas');expect(x['Alertas registrales']).toContain('Embargos');expect(x['Cargas relevantes']).toBe('Hipoteca y embargo');});
test('FEIN calcula total nominal solo desde cuota y número de cuotas explícitos',()=>{const x=map({tipo:'FEIN',importe_prestamo:180000,cuota:711.22,numero_cuotas:360,vinculaciones:'Nómina + hogar'});expect(x['Total nominal de cuotas']).toContain('256.039,20');expect(x['Diferencia cuotas - capital']).toContain('76.039,20');expect(x['Vinculaciones que revisar']).toContain('Nómina');});
test('Tasación eleva valor y salvedades operativas',()=>{const x=map({tipo:'Tasación',valor_tasacion:195000,condicionantes:'Comprobar ampliación',salvedades:'Terraza no inscrita'});expect(x['Valor operativo de referencia']).toContain('195.000,00');expect(x['Bloqueos / salvedades a revisar']).toContain('Terraza');});
test('DNI y Pasaporte exponen edad y vigencia sin alterar identidad',()=>{const x=map({tipo:'DNI / NIE',fecha_nacimiento:'1981-04-10',fecha_caducidad:'2034-11-13'});expect(String(x['Edad'])).toMatch(/\d+ años/);expect(x['Estado de vigencia']).toBe('Vigente');});
test('Préstamo expone deuda y carga mensual',()=>{const x=map({tipo:'Préstamo / deuda',capital_pendiente:8450.25,cuota:325.4,vencimiento:'2028-06-15'});expect(x['Deuda pendiente']).toContain('8.450,25');expect(x['Carga mensual']).toContain('325,40');});
