import {test,expect} from '@playwright/test';

const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6InFhYUBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-exp-create-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'qa@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-22T00:00:00.000Z'}};
async function boot(page:any,role:'Direccion'|'Financiero'|'Visitador'='Direccion'){
 await page.addInitScript((session:any)=>{window.localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));window.localStorage.setItem('fenix-remember-device','true');},fakeSession);
 await page.route('**/functions/v1/fenix-app-gateway-test/**',async(r:any)=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:role==='Direccion'?'DIR-TEST':role==='Financiero'?'FIN-A':'VIS-A',role})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Expedientes',route:'/expedientes'}]})});if(u.endsWith('/personal'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{actor_code:'FIN-A',name:'Financiero A',role:'Financiero'}]})});return r.fulfill({status:404,body:'{}'});});
 await page.route('**/functions/v1/fenix-comprador-action-test/expedientes/*/compradores',async r=>r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:crypto.randomUUID(),cliente_id:crypto.randomUUID(),cliente_reutilizado:true})}));
}

test.describe('Fénix PRE-PROD · alta canónica de expediente',()=>{
 test('Dirección abre expediente y reutiliza contacto coincidente',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Direccion');let posted:any=null;
  await page.route('**/functions/v1/fenix-notion-actions-test/expedientes/create',async r=>{posted=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',destino:'/expedientes/aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',cliente_id:'bbbbbbbb-1111-4111-8111-bbbbbbbbbbbb',cliente_destino:'/contactos/bbbbbbbb-1111-4111-8111-bbbbbbbbbbbb',cliente_reutilizado:true})});});
  await page.goto('/expedientes/nuevo');await expect(page.getByRole('heading',{name:'Nuevo expediente'})).toBeVisible();await page.getByLabel('Nombre').fill('Cliente');await page.getByLabel('Apellidos').fill('Existente');await page.getByLabel('Email').fill('cliente@fenix.test');await page.getByLabel('Responsable financiero').selectOption('FIN-A');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await expect(page.getByText(/reutilizarán automáticamente/i)).toBeVisible();await page.getByRole('button',{name:'Confirmar y crear'}).click();await expect(page.getByText('Expediente creado y enlazado al contacto existente. No se ha duplicado el cliente.')).toBeVisible();expect(posted.nombre).toBe('Cliente');expect(posted.id_financiero_operativo).toBe('FIN-A');await expect(page.getByRole('button',{name:'Abrir contacto'})).toBeVisible();await expect(page.getByRole('button',{name:'Abrir expediente'})).toBeVisible();
 });
 test('Financiero se autoasigna sin poder cambiar responsable',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Financiero');let posted:any=null;
  await page.route('**/functions/v1/fenix-notion-actions-test/expedientes/create',async r=>{posted=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'cccccccc-1111-4111-8111-cccccccccccc',destino:'/expedientes/cccccccc-1111-4111-8111-cccccccccccc',cliente_id:'dddddddd-1111-4111-8111-dddddddddddd',cliente_destino:'/contactos/dddddddd-1111-4111-8111-dddddddddddd',cliente_reutilizado:false})});});
  await page.goto('/expedientes/nuevo');await page.getByLabel('Nombre').fill('Nuevo');await expect(page.getByLabel('Responsable financiero')).toHaveValue('FIN-A');await expect(page.getByLabel('Responsable financiero')).toHaveAttribute('readonly','');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await page.getByRole('button',{name:'Confirmar y crear'}).click();expect(posted.id_financiero_operativo).toBe('FIN-A');await expect(page.getByText('Expediente y contacto de cliente creados y enlazados en las fuentes canónicas.')).toBeVisible();
 });
 test('permite cinco titulares y conserva los datos financieros de cada persona',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Direccion');const buyers:any[]=[];
  await page.route('**/functions/v1/fenix-notion-actions-test/expedientes/create',async r=>r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'eeeeeeee-1111-4111-8111-eeeeeeeeeeee',destino:'/expedientes/eeeeeeee-1111-4111-8111-eeeeeeeeeeee',cliente_reutilizado:false})}));
  await page.route('**/functions/v1/fenix-comprador-action-test/expedientes/*/compradores',async r=>{buyers.push(JSON.parse(r.request().postData()||'{}'));return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:`00000000-0000-4000-8000-${String(buyers.length).padStart(12,'0')}`})});});
  await page.goto('/expedientes/nuevo');for(let i=0;i<4;i++)await page.getByRole('button',{name:'Añadir otra persona'}).click();await expect(page.getByTestId('exp-create-person')).toHaveCount(5);
  await page.getByLabel('Nombre').fill('Hermano 1');await page.getByLabel('Nombre persona 2').fill('Hermano 2');await page.getByLabel('Nombre persona 3').fill('Hermano 3');await page.getByLabel('Nombre persona 4').fill('Hermano 4');await page.getByLabel('Nombre persona 5').fill('Hermano 5');
  const first=page.getByTestId('exp-create-person').first();await first.getByLabel('DNI / NIE').fill('11111111A');await first.getByLabel('Situación laboral').selectOption('Asalariado indefinido');await first.getByLabel('Sueldo neto mensual €').fill('2200');await first.getByLabel('Deudas mensuales €').fill('275');await first.getByLabel('Ahorro disponible €').fill('18000');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await expect(page.getByText(/5 intervinientes/)).toBeVisible();await page.getByRole('button',{name:'Confirmar y crear'}).click();await expect.poll(()=>buyers.length).toBe(5);expect(buyers[0].dni_nie).toBe('11111111A');expect(buyers[0].situacion_laboral).toBe('Asalariado indefinido');expect(buyers[0].sueldo_neto_mensual).toBe(2200);expect(buyers[0].deudas_mensuales).toBe(275);expect(buyers[0].ahorro_disponible).toBe(18000);expect(buyers.map(x=>x.orden_expediente)).toEqual([1,2,3,4,5]);
 });
 test('Visitador no obtiene formulario de alta hipotecaria',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Visitador');await page.goto('/expedientes/nuevo');await expect(page.getByText('Tu perfil no puede crear expedientes.')).toBeVisible();await expect(page.getByRole('button',{name:'Revisar antes de crear'})).toHaveCount(0);
 });
});
