import {test,expect} from '@playwright/test';

const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6InFhYUBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-exp-create-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'qa@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-22T00:00:00.000Z'}};
async function boot(page:any,role:'Direccion'|'Financiero'|'Visitador'='Direccion'){
 await page.addInitScript((session:any)=>{window.localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));window.localStorage.setItem('fenix-remember-device','true');},fakeSession);
 await page.route('**/functions/v1/fenix-app-gateway-test/**',async(r:any)=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:role==='Direccion'?'DIR-TEST':role==='Financiero'?'FIN-A':'VIS-A',role})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Expedientes',route:'/expedientes'}]})});if(u.endsWith('/personal'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{actor_code:'FIN-A',name:'Financiero A',role:'Financiero'}]})});return r.fulfill({status:404,body:'{}'});});
}

test.describe('Fénix PRE-PROD · alta canónica de expediente',()=>{
 test('Dirección abre expediente y reutiliza contacto coincidente',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Direccion');let posted:any=null;
  await page.route('**/functions/v1/fenix-notion-actions-test/expedientes/create',async r=>{posted=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',destino:'/expedientes/aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',cliente_id:'bbbbbbbb-1111-4111-8111-bbbbbbbbbbbb',cliente_destino:'/contactos/bbbbbbbb-1111-4111-8111-bbbbbbbbbbbb',cliente_reutilizado:true})});});
  await page.goto('/expedientes/nuevo');await expect(page.getByRole('heading',{name:'Nuevo expediente'})).toBeVisible();await page.getByLabel('Nombre').fill('Cliente');await page.getByLabel('Apellidos').fill('Existente');await page.getByLabel('Email').fill('cliente@fenix.test');await page.getByLabel('Responsable financiero').selectOption('FIN-A');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await expect(page.getByText(/reutilizará un contacto coincidente/i)).toBeVisible();await page.getByRole('button',{name:'Confirmar y crear'}).click();await expect(page.getByText('Expediente creado y enlazado al contacto existente. No se ha duplicado el cliente.')).toBeVisible();expect(posted.nombre).toBe('Cliente');expect(posted.id_financiero_operativo).toBe('FIN-A');await expect(page.getByRole('button',{name:'Abrir contacto'})).toBeVisible();await expect(page.getByRole('button',{name:'Abrir expediente'})).toBeVisible();
 });
 test('Financiero se autoasigna sin poder cambiar responsable',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Financiero');let posted:any=null;
  await page.route('**/functions/v1/fenix-notion-actions-test/expedientes/create',async r=>{posted=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'cccccccc-1111-4111-8111-cccccccccccc',destino:'/expedientes/cccccccc-1111-4111-8111-cccccccccccc',cliente_id:'dddddddd-1111-4111-8111-dddddddddddd',cliente_destino:'/contactos/dddddddd-1111-4111-8111-dddddddddddd',cliente_reutilizado:false})});});
  await page.goto('/expedientes/nuevo');await page.getByLabel('Nombre').fill('Nuevo');await expect(page.getByLabel('Responsable financiero')).toHaveValue('FIN-A');await expect(page.getByLabel('Responsable financiero')).toHaveAttribute('readonly','');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await page.getByRole('button',{name:'Confirmar y crear'}).click();expect(posted.id_financiero_operativo).toBe('FIN-A');await expect(page.getByText('Expediente y contacto de cliente creados y enlazados en las fuentes canónicas.')).toBeVisible();
 });
 test('Visitador no obtiene formulario de alta hipotecaria',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Visitador');await page.goto('/expedientes/nuevo');await expect(page.getByText('Tu perfil no puede crear expedientes.')).toBeVisible();await expect(page.getByRole('button',{name:'Revisar antes de crear'})).toHaveCount(0);
 });
});
