import {test,expect} from '@playwright/test';

const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6InFhYUBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-inmo-create-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'qa@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-22T00:00:00.000Z'}};
async function boot(page:any,role:'Direccion'|'Visitador'|'Financiero'='Direccion'){
 await page.addInitScript((session:any)=>{window.localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));window.localStorage.setItem('fenix-remember-device','true');},fakeSession);
 await page.route('**/functions/v1/fenix-app-gateway-test/**',async(r:any)=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:role==='Direccion'?'DIR-TEST':role==='Visitador'?'VIS-A':'FIN-A',role,zone_code:role==='Visitador'?'CORDOBA-A':null})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Inmobiliarias',route:'/inmobiliarias'}]})});if(u.endsWith('/visitadores'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{actor_code:'VIS-A',nombre:'Visitador A',rol:'Visitador'}]})});return r.fulfill({status:404,body:'{}'});});
}

test.describe('Fénix PRE-PROD · alta de inmobiliarias',()=>{
 test('Dirección puede crear sin inventar visitador y con preview',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Direccion');let posted:any=null;
  await page.route('**/functions/v1/fenix-notion-actions-test/inmobiliarias/create',async r=>{posted=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'aaaaaaaa-1111-4111-8111-eeeeeeeeeeee',destino:'/inmobiliarias/aaaaaaaa-1111-4111-8111-eeeeeeeeeeee'})});});
  await page.goto('/inmobiliarias/nueva');await expect(page.getByRole('heading',{name:'Nueva inmobiliaria'})).toBeVisible();await expect(page.getByText('Personal de la inmobiliaria')).toBeVisible();await page.getByLabel('Inmobiliaria').fill('Inmo QA');await page.getByLabel('Localidad').fill('Córdoba');await expect(page.getByLabel('Visitador responsable')).toHaveValue('');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await expect(page.getByText('Visitador: Sin asignar',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Confirmar y crear'}).click();await expect(page.getByText('Inmobiliaria creada correctamente.')).toBeVisible();expect(posted.id_visitador_operativo).toBe('');expect(posted.inmobiliaria).toBe('Inmo QA');
 });
 test('crea y vincula personal introducido en la misma alta',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Direccion');let contact:any=null;
  await page.route('**/functions/v1/fenix-notion-actions-test/inmobiliarias/create',r=>r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'aaaaaaaa-1111-4111-8111-eeeeeeeeeeee',destino:'/inmobiliarias/aaaaaaaa-1111-4111-8111-eeeeeeeeeeee'})}));
  await page.route('**/functions/v1/fenix-b2b-actions-test/contactos/create',async r=>{contact=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'bbbbbbbb-1111-4111-8111-eeeeeeeeeeee'})});});
  await page.goto('/inmobiliarias/nueva');await page.getByLabel('Inmobiliaria').fill('Inmo Personal');await page.locator('#staff-0-name').fill('Ana');await page.getByPlaceholder('Director, asesor, gerente...').fill('Directora');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await page.getByRole('button',{name:'Confirmar y crear'}).click();await expect(page.getByText(/Personal: 1 creado\/vinculado/)).toBeVisible();expect(contact.inmobiliaria_id).toBe('aaaaaaaa-1111-4111-8111-eeeeeeeeeeee');expect(contact.nombre).toBe('Ana');expect(contact.cargo).toBe('Directora');
 });
 test('Visitador crea para su propia identidad',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Visitador');let posted:any=null;
  await page.route('**/functions/v1/fenix-b2b-actions-test/inmobiliarias/create',async r=>{posted=JSON.parse(r.request().postData()||'{}');return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify({ok:true,id:'bbbbbbbb-1111-4111-8111-eeeeeeeeeeee',destino:'/inmobiliarias/bbbbbbbb-1111-4111-8111-eeeeeeeeeeee',zone:'CORDOBA-A'})});});await page.goto('/inmobiliarias/nueva');await page.getByLabel('Inmobiliaria').fill('Inmo Visitador');await expect(page.getByLabel('Visitador responsable')).toHaveValue('VIS-A');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await page.getByRole('button',{name:'Confirmar y crear'}).click();expect(posted.id_visitador_operativo).toBe('VIS-A');
 });
 test('duplicado se detiene y enlaza el registro existente',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Direccion');await page.route('**/functions/v1/fenix-notion-actions-test/inmobiliarias/create',r=>r.fulfill({status:409,contentType:'application/json',body:JSON.stringify({ok:false,error:'duplicate_inmobiliaria',existing_id:'cccccccc-1111-4111-8111-eeeeeeeeeeee',destino:'/inmobiliarias/cccccccc-1111-4111-8111-eeeeeeeeeeee'})}));await page.goto('/inmobiliarias/nueva');await page.getByLabel('Inmobiliaria').fill('Duplicada');await page.getByLabel('Localidad').fill('Lucena');await page.getByRole('button',{name:'Revisar antes de crear'}).click();await page.getByRole('button',{name:'Confirmar y crear'}).click();await expect(page.getByText('Ya existe una inmobiliaria coincidente. No se ha creado un duplicado.')).toBeVisible();await expect(page.getByRole('button',{name:'Abrir inmobiliaria existente'})).toBeVisible();
 });
 test('Financiero no obtiene formulario B2B de alta',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page,'Financiero');await page.goto('/inmobiliarias/nueva');await expect(page.getByText('Tu perfil no puede crear inmobiliarias.')).toBeVisible();await expect(page.getByRole('button',{name:'Revisar antes de crear'})).toHaveCount(0);
 });
});
