import {test,expect} from '@playwright/test';
import {classifyFilename} from '../src/documentClassification';
import {extractDocumentData} from '../src/operationalDocumentExtraction';

const session={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6ImRpcmVjY2lvbkBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-intelligent-doc-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'direccion@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-19T00:00:00.000Z'}};

test('nombre de archivo tipo + persona clasifica antes del OCR',()=>{expect(classifyFilename('DNI Emilia Garcia.pdf')).toEqual({type:'DNI',person:'Emilia Garcia',complete:true});expect(classifyFilename('scan001.pdf').complete).toBe(false);});
test('parser DNI extrae identidad y fecha sin inventar',()=>{const r=extractDocumentData(`DOCUMENTO NACIONAL DE IDENTIDAD\nAPELLIDOS: GARCIA LOPEZ\nNOMBRE: FRANCISCO\nNACIMIENTO: 12/05/1987\n12345678Z`,94);expect(r.documentType).toBe('DNI/NIE');expect(r.fields.documento_identidad).toBe('12345678Z');expect(r.fields.nombre).toBe('FRANCISCO');expect(r.fields.apellidos).toBe('GARCIA LOPEZ');expect(r.fields.fecha_nacimiento).toBe('1987-05-12');});
test('parser nómina extrae importes explícitos',()=>{const r=extractDocumentData('RECIBO DE SALARIOS NÓMINA\nEmpresa: FENIX SL\nTrabajador: Emilia Garcia\nTOTAL DEVENGADO 2.350,00 EUR\nLIQUIDO A PERCIBIR 1.850,25 EUR\nBASE COTIZACIÓN 2.350,00 EUR');expect(r.documentType).toBe('Nómina');expect(r.fields.neto).toBe(1850.25);expect(r.fields.bruto).toBe(2350);expect(r.fields.empresa_pagador).toContain('FENIX SL');});
test('parser oferta bancaria extrae condiciones sin inferir',()=>{const r=extractDocumentData('OFERTA HIPOTECA\nEntidad: BANCO EJEMPLO\nProducto: Hipoteca fija\nIMPORTE PRÉSTAMO 180.000,00 EUR\nPLAZO 30 AÑOS\nTIN 2,50 %\nTAE 2,91 %\nCUOTA 711,22 EUR\nVinculaciones: nómina y seguro hogar');expect(r.documentType).toBe('Oferta bancaria');expect(r.fields.importe_prestamo).toBe(180000);expect(r.fields.tin).toBe(2.5);expect(r.fields.tae).toBe(2.91);expect(r.fields.cuota).toBe(711.22);});
test('parser seguro bancario extrae prima y cobertura visible',()=>{const r=extractDocumentData('PÓLIZA SEGURO HOGAR\nEntidad aseguradora: Seguros Ejemplo\nTomador: Emilia Garcia\nPRIMA ANUAL 325,50 EUR\nCoberturas: continente, contenido y responsabilidad civil');expect(r.documentType).toBe('Seguro bancario');expect(r.fields.prima).toBe(325.5);expect(String(r.fields.coberturas)).toContain('continente');});
test('parser tasación extrae valor explícito',()=>{const r=extractDocumentData('INFORME DE TASACIÓN\nSociedad de tasación: Tasadora Ejemplo SA\nDirección: Calle Fenix 1, Córdoba\nVALOR DE TASACIÓN 245.000,00 EUR\nFecha del informe: 01/09/2026\nFinalidad: garantía hipotecaria');expect(r.documentType).toBe('Tasación');expect(r.fields.valor_tasacion).toBe(245000);expect(r.fields.fecha_tasacion).toBe('2026-09-01');});
test('parser préstamo extrae deuda explícita',()=>{const r=extractDocumentData('RECIBO PRÉSTAMO\nEntidad: BBVA\nTitular: Emilia Garcia\nCUOTA 243,10 EUR\nCAPITAL PENDIENTE 8.450,00 EUR\nTIN 5,10 %');expect(r.documentType).toBe('Préstamo / deuda');expect(r.fields.cuota).toBe(243.1);expect(r.fields.capital_pendiente).toBe(8450);});
test('documento ambiguo no fabrica datos',()=>{const r=extractDocumentData('FOTOCOPIA BORROSA SIN CAMPOS IDENTIFICABLES',40);expect(r.fields).toEqual({});expect(r.summary).toContain('no hay datos suficientemente claros');});

async function setup(page:any){await page.addInitScript((s:any)=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(s));localStorage.setItem('fenix-preprod-auth-v2',JSON.stringify(s));localStorage.setItem('fenix-remember-device','true');(window as any).Tesseract={recognize:async()=>({data:{text:'DOCUMENTO NACIONAL DE IDENTIDAD\nAPELLIDOS: GARCIA LOPEZ\nNOMBRE: FRANCISCO\nNACIMIENTO: 12/05/1987\n12345678Z',confidence:96}})};},session);await page.route('**/functions/v1/fenix-app-gateway-test/**',async(r:any)=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-TEST',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Contactos',route:'/contactos'}]})});if(u.endsWith('/contactos/c1'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,contacto:{id:'c1',nombre:'Paco'}})});return r.fulfill({status:404,body:'{}'});});await page.route('**/functions/v1/fenix-notion-runtime-test/clientes/c1',(r:any)=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({item:{id:'c1',cliente:'Paco',estado:'Seguimiento',tipo:'Titular',relacion:'Cliente'}})}));}
test('ficha contacto lee archivo bien nombrado, previsualiza y no escribe antes de confirmar',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await setup(page);let applyCalls=0,evidenceCalls=0;await page.route('**/functions/v1/fenix-evidence-universal-test/**',async r=>{evidenceCalls++;if(r.request().url().endsWith('/prepare'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,upload_id:'u1',storage_path:'DIR/evidence/c1/dni.jpg',token:'tok',max_bytes:12000000})});return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,document_page_id:'doc1'})});});await page.route('**/storage/v1/object/upload/sign/**',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));await page.route('**/functions/v1/fenix-document-intelligence-test/apply',async r=>{applyCalls++;const body=r.request().postDataJSON();expect(body.declared_document_type).toBe('DNI');expect(body.declared_person).toBe('Francisco Garcia Lopez');return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,status:200,updated:{nombre:'FRANCISCO',apellidos:'GARCIA LOPEZ'}})});});await page.goto('/contactos/c1');await page.getByTestId('intelligent-document-open').click();const input=page.getByRole('dialog',{name:'Lectura inteligente de documento'}).locator('input[type=file]');await input.setInputFiles({name:'DNI Francisco Garcia Lopez.jpg',mimeType:'image/jpeg',buffer:Buffer.from('fake-image')});await expect(page.getByText('12345678Z',{exact:true})).toBeVisible();expect(applyCalls).toBe(0);expect(evidenceCalls).toBe(0);await page.getByRole('button',{name:'Confirmar y aplicar datos'}).click();await expect.poll(()=>applyCalls).toBe(1);expect(evidenceCalls).toBeGreaterThanOrEqual(2);});
test('archivo ambiguo pregunta tipo y persona antes de OCR',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await setup(page);await page.goto('/contactos/c1');await page.getByTestId('intelligent-document-open').click();const dialog=page.getByRole('dialog',{name:'Lectura inteligente de documento'});await dialog.locator('input[type=file]').setInputFiles({name:'scan001.jpg',mimeType:'image/jpeg',buffer:Buffer.from('fake-image')});await expect(page.getByText('Antes de leerlo necesito saber qué documento es y a qué persona pertenece.',{exact:false})).toBeVisible();await expect(page.getByText('12345678Z',{exact:true})).toHaveCount(0);await page.getByLabel('Tipo de documento').fill('DNI');await page.getByLabel('Persona / referencia').fill('Francisco Garcia Lopez');await page.getByRole('button',{name:'Continuar con OCR'}).click();await expect(page.getByText('12345678Z',{exact:true})).toBeVisible();});
