import {test,expect} from '@playwright/test';
import {classifyFilename} from '../src/documentClassification';
import {extractDocumentData} from '../src/browserDocumentOcr';
import {evidenceContextFromPath} from '../src/evidenceContext';

const session={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6ImRpcmVjY2lvbkBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-intelligent-doc-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'direccion@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-19T00:00:00.000Z'}};

test('tipo + persona clasifica familias documentales antes del OCR',()=>{
 expect(classifyFilename('DNI Emilia Garcia.pdf')).toEqual({type:'DNI',person:'Emilia Garcia',complete:true});
 expect(classifyFilename('Nomina Emilia Garcia agosto.pdf').type).toBe('Nómina');
 expect(classifyFilename('Prestamo BBVA Emilia Garcia.pdf').type).toBe('Préstamo / deuda');
 expect(classifyFilename('Vida laboral Emilia Garcia.pdf').type).toBe('Vida laboral');
 expect(classifyFilename('Tarjeta de visita Ana Perez.jpg').type).toBe('Tarjeta de visita');
 expect(classifyFilename('scan001.pdf').complete).toBe(false);
});

test('contexto documental compartido cubre fichas operativas soportadas',()=>{
 expect(evidenceContextFromPath('/expedientes/EXP-1')?.type).toBe('expediente');
 expect(evidenceContextFromPath('/contactos/C-1')?.type).toBe('contacto');
 expect(evidenceContextFromPath('/contactos-b2b/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')?.type).toBe('contacto_b2b');
 expect(evidenceContextFromPath('/inmobiliarias/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')?.type).toBe('inmobiliaria');
 expect(evidenceContextFromPath('/tareas/T-1')?.type).toBe('tarea');
 expect(evidenceContextFromPath('/firmas/F-1')?.type).toBe('firma');
});

test('parser DNI extrae identidad y fecha sin inventar',()=>{const r=extractDocumentData(`DOCUMENTO NACIONAL DE IDENTIDAD\nAPELLIDOS / SURNAME\nGARCIA LOPEZ\nNOMBRE / NAME\nFRANCISCO\nNACIMIENTO / DATE OF BIRTH\n12/05/1987\n12345678Z`,94,'DNI');expect(r.documentType).toBe('DNI/NIE');expect(r.fields.documento_identidad).toBe('12345678Z');expect(r.fields.nombre).toBe('Francisco');expect(r.fields.apellidos).toBe('Garcia Lopez');expect(r.fields.fecha_nacimiento).toBe('1987-05-12');});

test('parser nómina extrae pagador, neto, bruto y periodo explícitos',()=>{const r=extractDocumentData(`RECIBO DE SALARIOS - NÓMINA\nTITULAR: EMILIA GARCIA LOPEZ\nEMPRESA: FENIX EJEMPLO SL\nPERIODO DE LIQUIDACIÓN: AGOSTO 2026\nTOTAL DEVENGADO: 2.250,00 EUR\nLÍQUIDO A PERCIBIR: 1.850,40 EUR`,92,'Nómina');expect(r.documentType).toBe('Nómina');expect(r.fields.empresa_pagador).toBe('FENIX EJEMPLO SL');expect(r.fields.neto_nomina).toBe(1850.4);expect(r.fields.bruto_nomina).toBe(2250);expect(r.fields.periodo_nomina).toBe('AGOSTO 2026');});

test('parser préstamo extrae únicamente deuda explícita',()=>{const r=extractDocumentData(`RECIBO PRÉSTAMO PERSONAL\nTITULAR: EMILIA GARCIA\nENTIDAD: BBVA\nCUOTA MENSUAL: 245,75 EUR\nCAPITAL PENDIENTE: 12.450,20 EUR\nNÚMERO DE PRÉSTAMO: 998877`,90,'Préstamo / deuda');expect(r.documentType).toBe('Préstamo / deuda');expect(r.fields.entidad_acreedora).toBe('BBVA');expect(r.fields.cuota).toBe(245.75);expect(r.fields.capital_pendiente).toBe(12450.2);});

test('parser contrato y vida laboral conserva datos expresos',()=>{const c=extractDocumentData(`CONTRATO DE TRABAJO\nTRABAJADOR: EMILIA GARCIA\nEMPRESA: FENIX EJEMPLO SL\nTIPO DE CONTRATO: INDEFINIDO\nFECHA DE INICIO: 01/02/2024\nPUESTO: ADMINISTRATIVA`,88,'Contrato');expect(c.documentType).toBe('Contrato laboral');expect(c.fields.tipo_contrato).toBe('INDEFINIDO');expect(c.fields.fecha_inicio).toBe('2024-02-01');const v=extractDocumentData(`INFORME DE VIDA LABORAL\nTITULAR: EMILIA GARCIA\nTOTAL DÍAS: 1460`,88,'Vida laboral');expect(v.documentType).toBe('Vida laboral');expect(v.fields.dias_alta).toBe(1460);});

test('parser IRPF, CIRBE y movimientos añade avisos y no inventa criterio financiero',()=>{const i=extractDocumentData(`IMPUESTO SOBRE LA RENTA IRPF\nCONTRIBUYENTE: EMILIA GARCIA\nEJERCICIO: 2025\nRENDIMIENTO NETO: 28.450,00`,90,'IRPF');expect(i.documentType).toBe('IRPF / autónomos');expect(i.fields.ejercicio).toBe('2025');expect(i.fields.importe_renta_explicito).toBe(28450);expect(i.warnings.join(' ')).toContain('no se emite interpretación fiscal');const c=extractDocumentData(`CIRBE CENTRAL DE INFORMACIÓN DE RIESGOS\nENTIDAD BBVA RIESGO DISPUESTO 12500,00`,90,'CIRBE');expect(c.documentType).toBe('CIRBE');expect(c.warnings.join(' ')).toContain('no se convierten automáticamente en deuda');const m=extractDocumentData(`EXTRACTO DE MOVIMIENTOS\nIBAN ES12 1234 5678 9012 3456 7890\n01/08/2026 TRANSFERENCIA 1200,00`,90,'Movimientos');expect(m.documentType).toBe('Movimientos bancarios');expect(m.fields.iban).toBe('ES1212345678901234567890');expect(m.warnings.length).toBeGreaterThan(0);});

test('parser nota simple y arras extrae hechos sin conclusión jurídica',()=>{const n=extractDocumentData(`REGISTRO DE LA PROPIEDAD - NOTA SIMPLE\nFINCA REGISTRAL: 12345\nTITULAR: EMILIA GARCIA\nCARGA: HIPOTECA A FAVOR DE BANCO EJEMPLO`,91,'Nota simple');expect(n.documentType).toBe('Nota simple');expect(n.fields.finca_registral).toBe('12345');expect(n.warnings.join(' ')).toContain('no se emite conclusión jurídica');const a=extractDocumentData(`CONTRATO DE ARRAS PENITENCIALES\nPRECIO DE COMPRAVENTA: 180.000,00 EUR\nARRAS: 18.000,00 EUR\nFECHA LÍMITE: 30/10/2026`,91,'Arras');expect(a.documentType).toBe('Arras');expect(a.fields.precio_compraventa).toBe(180000);expect(a.fields.importe_arras).toBe(18000);});

test('parser tarjeta de visita extrae contacto',()=>{const r=extractDocumentData(`ANA PEREZ GOMEZ\nDIRECTORA COMERCIAL\nINMOBILIARIA EJEMPLO\nana.perez@ejemplo.es\n+34 600 123 456\nwww.ejemplo.es`,95,'Tarjeta de visita');expect(r.documentType).toBe('Tarjeta de visita');expect(r.fields.nombre_contacto).toBe('Ana Perez Gomez');expect(r.fields.email).toBe('ana.perez@ejemplo.es');expect(r.fields.telefono).toBe('+34600123456');});

test('documento ambiguo no fabrica datos personales',()=>{const r=extractDocumentData('FOTOCOPIA BORROSA SIN CAMPOS IDENTIFICABLES',40);expect(r.fields).toEqual({});expect(r.summary).toContain('no hay datos suficientemente claros');});

async function setup(page:any){await page.addInitScript((s:any)=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(s));localStorage.setItem('fenix-preprod-auth-v2',JSON.stringify(s));localStorage.setItem('fenix-remember-device','true');(window as any).Tesseract={recognize:async()=>({data:{text:'DOCUMENTO NACIONAL DE IDENTIDAD\nAPELLIDOS\nGARCIA LOPEZ\nNOMBRE\nFRANCISCO\nNACIMIENTO\n12/05/1987\n12345678Z',confidence:96}})};},session);await page.route('**/functions/v1/fenix-app-gateway-test/**',async(r:any)=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-TEST',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Contactos',route:'/contactos'}]})});if(u.endsWith('/contactos/c1'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,contacto:{id:'c1',nombre:'Paco'}})});return r.fulfill({status:404,body:'{}'});});await page.route('**/functions/v1/fenix-notion-runtime-test/clientes/c1',(r:any)=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({item:{id:'c1',cliente:'Paco',estado:'Seguimiento',tipo:'Titular',relacion:'Cliente'}})}));}

test('franja inteligente queda inmediatamente debajo de la franja de subida',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await setup(page);await page.goto('/contactos/c1');await expect(page.getByTestId('context-evidence-open')).toBeVisible();await expect(page.getByTestId('intelligent-document-open')).toBeVisible();const order=await page.evaluate(()=>{const a=document.querySelector('.context-evidence-inline-host'),b=document.querySelector('.intelligent-ingestion-host');return Boolean(a&&b&&a.nextElementSibling===b)});expect(order).toBe(true);});

test('ficha contacto lee archivo bien nombrado, previsualiza y no escribe antes de confirmar',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await setup(page);let applyCalls=0,evidenceCalls=0;await page.route('**/functions/v1/fenix-evidence-universal-test/**',async r=>{evidenceCalls++;if(r.request().url().endsWith('/prepare'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,upload_id:'u1',storage_path:'DIR/evidence/c1/dni.jpg',token:'tok',max_bytes:12000000})});return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,document_page_id:'doc1'})});});await page.route('**/storage/v1/object/upload/sign/**',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));await page.route('**/functions/v1/fenix-document-intelligence-test/apply',async r=>{applyCalls++;const body=r.request().postDataJSON();expect(body.declared_document_type).toBe('DNI');expect(body.declared_person).toBe('Francisco Garcia Lopez');expect(body.fields.documento_identidad).toBe('12345678Z');return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,status:200,updated:{nombre:'Francisco',apellidos:'Garcia Lopez'}})});});await page.goto('/contactos/c1');await page.getByTestId('intelligent-document-open').click();const input=page.getByRole('dialog',{name:'Lectura inteligente de documento'}).locator('input[type=file]');await input.setInputFiles({name:'DNI Francisco Garcia Lopez.jpg',mimeType:'image/jpeg',buffer:Buffer.from('fake-image')});await expect(page.getByText('12345678Z',{exact:true})).toBeVisible();expect(applyCalls).toBe(0);expect(evidenceCalls).toBe(0);await page.getByRole('button',{name:'Confirmar y guardar lectura'}).click();await expect.poll(()=>applyCalls).toBe(1);expect(evidenceCalls).toBeGreaterThanOrEqual(2);});

test('archivo ambiguo pregunta tipo y persona antes de OCR',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await setup(page);await page.goto('/contactos/c1');await page.getByTestId('intelligent-document-open').click();const dialog=page.getByRole('dialog',{name:'Lectura inteligente de documento'});await dialog.locator('input[type=file]').setInputFiles({name:'scan001.jpg',mimeType:'image/jpeg',buffer:Buffer.from('fake-image')});await expect(page.getByText('Antes de leerlo necesito saber qué documento es y a qué persona o referencia pertenece.')).toBeVisible();await expect(page.getByText('12345678Z',{exact:true})).toHaveCount(0);await page.getByLabel('Tipo de documento').fill('DNI');await page.getByLabel('Persona / referencia').fill('Francisco Garcia Lopez');await page.getByRole('button',{name:'Continuar con lectura'}).click();await expect(page.getByText('12345678Z',{exact:true})).toBeVisible();});
