import {test,expect,Page} from '@playwright/test';

const session={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6Im5vdGlmQGZlbml4LnRlc3QiLCJleHAiOjE5OTk5OTk5OTl9.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-notifications-states-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'notif@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-19T00:00:00.000Z'}};
async function seed(page:Page){await page.addInitScript(s=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(s));localStorage.setItem('fenix-remember-device','true');},session);}
async function gateway(page:Page,navigationStatus=200){await page.route('**/functions/v1/fenix-app-gateway-test/**',async r=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-TEST',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:navigationStatus,contentType:'application/json',body:navigationStatus===200?JSON.stringify({items:['/inicio','/notificaciones']}):'{}'});return r.fulfill({status:404,body:'{}'});});}

test('Notificaciones distingue loading y vacío autorizado',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await gateway(page);await page.route('**/functions/v1/fenix-notion-runtime-test/tareas',async r=>{await new Promise(res=>setTimeout(res,350));return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})});});await page.goto('/notificaciones');await expect(page.getByTestId('notifications-loading')).toBeVisible();await expect(page.getByTestId('notifications-empty')).toBeVisible();});

test('Notificaciones falla cerrado con 403 y navegación caída',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await gateway(page,500);await page.route('**/functions/v1/fenix-notion-runtime-test/tareas',r=>r.fulfill({status:403,body:'{}'}));await page.goto('/notificaciones');await expect(page.getByTestId('notifications-forbidden')).toContainText('no tiene acceso');await expect(page.locator('.notif-kpis')).toHaveCount(0);await expect(page.locator('.notif-list>button')).toHaveCount(0);const menu=page.locator('.notif-root .ops-side nav');await expect(menu.getByRole('button')).toHaveCount(1);await expect(menu.getByRole('button',{name:'Inicio',exact:true})).toBeVisible();});

test('Notificaciones distingue 5xx de fallo de red y no deja datos stale',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await gateway(page);await page.route('**/functions/v1/fenix-notion-runtime-test/tareas',r=>r.fulfill({status:503,body:'{}'}));await page.goto('/notificaciones');await expect(page.getByTestId('notifications-error')).toHaveText('No se pudo cargar la fuente canónica de tareas.');await expect(page.locator('.notif-kpis')).toHaveCount(0);await page.unroute('**/functions/v1/fenix-notion-runtime-test/tareas');await page.route('**/functions/v1/fenix-notion-runtime-test/tareas',r=>r.abort('failed'));await page.reload();await expect(page.getByTestId('notifications-error')).toHaveText('No se pudo conectar con la fuente canónica de tareas.');await expect(page.locator('.notif-list>button')).toHaveCount(0);});
