import {test,expect} from '@playwright/test';

const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJjY2NjY2NjYy1jY2NjLTRjY2MtOGNjYy1jY2NjY2NjY2NjY2MiLCJleHAiOjE5OTk5OTk5OTl9.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-demo-special-not-real',user:{id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',aud:'authenticated',role:'authenticated',email:'qa-demo@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-29T00:00:00.000Z'}};
const items=[{label:'Inicio',route:'/inicio'},{label:'Expedientes',route:'/expedientes'},{label:'Obras Nuevas',route:'/obras-nuevas'},{label:'Herencias',route:'/herencias'},{label:'Agenda',route:'/agenda'}];
async function boot(page:any){await page.addInitScript(session=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));localStorage.setItem('fenix-remember-device','true')},fakeSession);await page.route('**/functions/v1/fenix-app-gateway-test/**',async r=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-QA',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items})});if(u.endsWith('/personal'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})});return r.fulfill({status:404,body:'{}'})});await page.route('**/functions/v1/fenix-ana-test/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({capabilities:{can_correct_ana:true}})}));await page.route('**/functions/v1/fenix-special-cases-runtime-test/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})}))}

test('PRE-PROD muestra herencias DEMO en fases diferentes y abre su línea temporal',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page);await page.goto('/herencias');await expect(page.getByText('DEMO · Herencia Familia Romero',{exact:true})).toBeVisible();await expect(page.getByText('DEMO · Herencia Hermanos Molina',{exact:true})).toBeVisible();await page.getByText('DEMO · Herencia Familia Romero',{exact:true}).click();await expect(page).toHaveURL(/\/herencias\/demo-herencia-documentacion$/);await expect(page.getByText(/RECORRIDO DE LA HERENCIA · ACTUAL: Documentación/)).toBeVisible();await expect(page.getByText('Certificado de últimas voluntades',{exact:true})).toBeVisible();await page.goto('/herencias/demo-herencia-notaria');await expect(page.getByText(/RECORRIDO DE LA HERENCIA · ACTUAL: Preparación de firma/)).toBeVisible();await expect(page.getByText('Laura Molina Ruiz',{exact:true})).toBeVisible()});

test('PRE-PROD muestra obras nuevas DEMO en fases diferentes y abre su línea temporal',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page);await page.goto('/obras-nuevas');await expect(page.getByText('DEMO · Residencial Azahar · 18 viviendas',{exact:true})).toBeVisible();await expect(page.getByText('DEMO · Edificio Victoria · 9 viviendas',{exact:true})).toBeVisible();await page.getByText('DEMO · Residencial Azahar · 18 viviendas',{exact:true}).click();await expect(page).toHaveURL(/\/obras-nuevas\/demo-obra-control$/);await expect(page.getByText(/RECORRIDO DE LA OBRA NUEVA · ACTUAL: Control administrativo/)).toBeVisible();await expect(page.getByTestId('special-detail-summary').getByText('Pendiente un certificado técnico',{exact:true})).toBeVisible();await page.goto('/obras-nuevas/demo-obra-firma');await expect(page.getByText(/RECORRIDO DE LA OBRA NUEVA · ACTUAL: Preparación de firma/)).toBeVisible();await expect(page.getByText('Validado y enviado',{exact:true})).toBeVisible()});
