import {test,expect} from '@playwright/test';

const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJiYmJiYmJiYi1iYmJiLTRiYmItOGJiYi1iYmJiYmJiYmJiYmIiLCJleHAiOjE5OTk5OTk5OTl9.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-special-cases-not-real',user:{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',aud:'authenticated',role:'authenticated',email:'qa-special@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-28T00:00:00.000Z'}};
const items=[{label:'Inicio',route:'/inicio'},{label:'Expedientes',route:'/expedientes'},{label:'Bancos',route:'/bancos'},{label:'Contactos',route:'/contactos'},{label:'Inmobiliarias',route:'/inmobiliarias'},{label:'Tasaciones',route:'/tasaciones'},{label:'Firmas',route:'/firmas'},{label:'Documentación',route:'/documentacion'},{label:'Financieros',route:'/financieros'},{label:'Visitadores',route:'/visitadores'},{label:'Obras Nuevas',route:'/obras-nuevas'},{label:'Herencias',route:'/herencias'},{label:'Agenda',route:'/agenda'},{label:'Economía',route:'/economia'},{label:'Informes',route:'/informes'},{label:'Notarías',route:'/notarias'},{label:'Registros de la Propiedad',route:'/registros-propiedad'},{label:'Comunicaciones',route:'/comunicaciones'},{label:'Notificaciones',route:'/notificaciones'}];
const herId='aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',obnId='bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb';
const her={id:herId,nombre:'Herencia Familia QA',activo:true,estado:'En curso',fase:'Documentación',cliente:['client-1'],responsable:['team-1'],notaria:['notary-1'],registro:['registry-1'],siguiente_accion:'Solicitar certificado pendiente',faltantes:'Certificado de defunción',bloqueo:'',requiere_validacion:false,ultima_actividad:'2026-08-28',firma_prevista:'2026-09-10',firma_realizada:false,notas:'Caso de prueba'};
const obn={id:obnId,nombre:'Promoción Centro QA',activo:true,estado:'En curso',fase:'Preparación / envío a interlocutor',cliente_promotor:['client-2'],responsable:['team-1'],notaria:['notary-1'],registro:['registry-1'],interlocutor_actual:'Técnico municipal',siguiente_accion:'Autorizar envío documental',documentacion_faltante:'',bloqueo_incidencia:'Pendiente validación técnica',requiere_validacion:true,estado_envio:'Preparado',ultima_actividad:'2026-08-28',firma_prevista:'2026-10-01',firma_realizada:false,notas:'Obra nueva QA'};
const people=[{id:'person-1',persona:'Interviniente QA',rol:'Heredero/a',empresa_organismo:'',telefono:'600000000',email:'qa@example.test'}];

async function boot(page:any){await page.addInitScript(session=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));localStorage.setItem('fenix-remember-device','true')},fakeSession);await page.route('**/functions/v1/fenix-app-gateway-test/**',async r=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-QA',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items})});if(u.endsWith('/personal'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[],pending_profiles:0})});return r.fulfill({status:404,body:'{}'})});await page.route('**/functions/v1/fenix-ana-test/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({capabilities:{can_view_learning_inbox:false,can_correct_ana:true,can_decide_learning:false}})}));await page.route('**/functions/v1/fenix-notion-runtime-test/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})}));await page.route('**/functions/v1/fenix-special-cases-runtime-test/**',r=>{const u=r.request().url();let body:any={items:[]};if(u.includes(`/herencias/${herId}`))body={item:her,intervinientes:people};else if(u.endsWith('/herencias'))body={items:[her]};else if(u.includes(`/obras-nuevas/${obnId}`))body={item:obn,intervinientes:[]};else if(u.endsWith('/obras-nuevas'))body={items:[obn]};return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)})})}

test('Herencias usa patrón de Expedientes y ficha por fases',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page);await page.goto('/herencias');await expect(page.locator('.exp-filter-card')).toBeVisible();await expect(page.locator('[data-testid="herencias-live"]')).toBeVisible();await expect(page.locator('[data-testid="herencias-ana-hero"]')).toHaveCount(0);const row=page.locator('tbody tr').filter({hasText:'Herencia Familia QA'});await expect(row).toBeVisible();await row.click();await expect(page).toHaveURL(new RegExp(`/herencias/${herId}$`));await expect(page.getByRole('heading',{level:1,name:'Herencia Familia QA'})).toBeVisible();await expect(page.getByText('Solicitar certificado pendiente',{exact:true})).toBeVisible();await expect(page.getByText(/Certificado de defunción/)).toBeVisible();await expect(page.getByTestId('herencias-intervinientes')).toContainText('Interviniente QA')});

test('Obras Nuevas usa patrón de Expedientes y separa envío de validación',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await boot(page);await page.goto('/obras-nuevas');await expect(page.locator('.exp-filter-card')).toBeVisible();await expect(page.locator('[data-testid="obras-nuevas-live"]')).toBeVisible();await expect(page.locator('[data-testid="obras-nuevas-ana-hero"]')).toHaveCount(0);const row=page.locator('tbody tr').filter({hasText:'Promoción Centro QA'});await row.click();await expect(page).toHaveURL(new RegExp(`/obras-nuevas/${obnId}$`));await expect(page.getByRole('heading',{level:1,name:'Promoción Centro QA'})).toBeVisible();await expect(page.getByText(/Pendiente validación técnica/)).toBeVisible();await expect(page.locator('p').filter({hasText:'Estado de envío:'})).toContainText('Preparado')});
