import { test, expect } from '@playwright/test';

const fakeSessionA = {
  access_token: 'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6InFhYUBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',
  token_type: 'bearer', expires_in: 3600, expires_at: 1999999999, refresh_token: 'qa-refresh-a-not-real',
  user: {id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'qaa@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-19T00:00:00.000Z'}
};
const fakeSessionB = {...fakeSessionA,access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJiYmJiYmJiYi1iYmJiLTRiYmItOGJiYi1iYmJiYmJiYmJiYmIiLCJlbWFpbCI6InFhYkBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',refresh_token:'qa-refresh-b-not-real',user:{...fakeSessionA.user,id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',email:'qab@fenix.test'}};
const nav={items:[{label:'Inicio',route:'/inicio',resource:'Inicio App'},{label:'Expedientes',route:'/expedientes',resource:'Expedientes'},{label:'Bancos',route:'/bancos',resource:'Bancos'},{label:'Documentación',route:'/documentacion',resource:'Documentación'},{label:'Agenda/Tareas',route:'/tareas',resource:'Tareas'}]};

test.describe('Fénix app shell + calculadora',()=>{
 test.beforeEach(async({page})=>{
  await page.addInitScript(session=>{if(window.name!=='fenix-qa-session-seeded'){window.localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));window.localStorage.setItem('fenix-remember-device','true');window.name='fenix-qa-session-seeded';}},fakeSessionA);
  await page.route('**/functions/v1/fenix-app-gateway-test/**',async route=>{const url=route.request().url();if(url.endsWith('/session/context'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,context:{actor_code:'QA-BROWSER',role:'Financiero'}})});if(url.endsWith('/navigation'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(nav)});return route.fulfill({status:404,contentType:'application/json',body:'{}'});});
  await page.route('**/functions/v1/fenix-notion-runtime-test/expedientes',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})}));
  await page.route('**/auth/v1/logout**',route=>route.fulfill({status:204,body:''}));
  await page.goto('/');await expect(page.getByRole('region',{name:'Calculadora Hipotecaria'})).toBeVisible();await expect(page.getByText(/\bPRO\b/)).toHaveCount(0);await expect(page).toHaveURL(/\/inicio$/);await expect(page.locator('.role-home')).toBeVisible();
 });
 test('theme toggles and persists in session',async({page})=>{const root=page.locator('html');await expect(root).toHaveAttribute('data-theme','light');await page.locator('.role-home').getByRole('button',{name:'Cambiar tema'}).click();await expect(root).toHaveAttribute('data-theme','dark');await page.reload();await expect(root).toHaveAttribute('data-theme','dark');});
 test('calculator launcher stays orange while expanded surface follows theme',async({page})=>{await page.getByRole('button',{name:'Cerrar calculadora'}).click();const launcher=page.getByRole('button',{name:'Calculadora'});await expect(launcher).toBeVisible();expect(await launcher.evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(255, 95, 0)');await launcher.click();const panel=page.getByRole('region',{name:'Calculadora Hipotecaria'});expect(await panel.evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(255, 255, 255)');await page.locator('.role-home').getByRole('button',{name:'Cambiar tema'}).click();await page.getByRole('button',{name:'Cerrar calculadora'}).click();const darkLauncher=page.getByRole('button',{name:'Calculadora'});expect(await darkLauncher.evaluate(el=>getComputedStyle(el).backgroundColor)).toBe('rgb(255, 95, 0)');await darkLauncher.click();expect(await panel.evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe('rgb(255, 255, 255)');});
 test('calculator computes reference case locally',async({page})=>{await expect(page.getByText('421,60 €')).toBeVisible();await expect(page.getByText('Simulación orientativa. No implica aprobación bancaria.')).toBeVisible();});
 test('calculator keeps only close control and preserves inputs after reopen',async({page})=>{const amount=page.getByLabel('Importe €');await amount.fill('135000');await expect(page.getByRole('button',{name:'Minimizar calculadora'})).toHaveCount(0);await page.getByRole('button',{name:'Cerrar calculadora'}).click();await page.getByRole('button',{name:'Calculadora'}).click();await expect(page.getByLabel('Importe €')).toHaveValue('135000');});
 test('calculator close and launcher restore',async({page})=>{await page.getByRole('button',{name:'Cerrar calculadora'}).click();await expect(page.getByRole('region',{name:'Calculadora Hipotecaria'})).toHaveCount(0);await page.getByRole('button',{name:'Calculadora'}).click();await expect(page.getByRole('region',{name:'Calculadora Hipotecaria'})).toBeVisible();});
 test('navigation is sourced from authorized backend response without exposing actor codes',async({page})=>{const shell=page.locator('.role-home');const side=shell.locator('.ops-side nav');await expect(side.locator('button').filter({hasText:'Expedientes'})).toHaveCount(1);await expect(side.locator('button').filter({hasText:'Bancos'})).toHaveCount(1);await expect(shell.locator('.ops-profile strong')).toHaveText('Financiero');await expect(page.getByText('QA-BROWSER')).toHaveCount(0);await expect(page.getByText(/PRE-PROD|AUTH TEST|CAL-001|JWT \+ RBAC|RUTA INTERNA/)).toHaveCount(0);});
 test('router back-forward preserves calculator state',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();const amount=page.getByLabel('Importe €');await amount.fill('135000');await page.locator('.role-home .ops-side').getByRole('button',{name:'Expedientes'}).click();await expect(page).toHaveURL(/\/expedientes$/);await expect(page.getByRole('heading',{name:'Expedientes',exact:true})).toBeVisible();await page.getByRole('button',{name:'Bancos',exact:true}).first().click();await expect(page).toHaveURL(/\/bancos$/);await page.goBack();await expect(page).toHaveURL(/\/expedientes$/);await expect(amount).toHaveValue('135000');await page.goBack();await expect(page).toHaveURL(/\/inicio$/);await expect(amount).toHaveValue('135000');});
 test('logout clears user A calculator before user B session',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await page.getByLabel('Importe €').fill('135000');await expect.poll(()=>page.evaluate(()=>window.sessionStorage.getItem('fenix-calc:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'))).not.toBeNull();await page.locator('.role-home').getByRole('button',{name:'Cerrar sesión'}).click();await expect(page.getByRole('heading',{name:'Acceso seguro'})).toBeVisible();expect(await page.evaluate(()=>window.sessionStorage.getItem('fenix-calc:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'))).toBeNull();await page.evaluate(session=>{window.localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));window.localStorage.setItem('fenix-remember-device','true');},fakeSessionB);await page.reload();await expect(page.getByLabel('Importe €')).toHaveValue('100000');expect(await page.evaluate(()=>window.sessionStorage.getItem('fenix-calc:aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'))).toBeNull();});
 test('mobile keeps theme control and calculator usable',async({page},testInfo)=>{if(!testInfo.project.name.includes('mobile'))test.skip();const shell=page.locator('.role-home');await expect(shell.getByRole('button',{name:'Cambiar tema'})).toBeVisible();await expect(page.getByRole('region',{name:'Calculadora Hipotecaria'})).toBeVisible();await expect(shell.locator('.ops-side')).toBeHidden();});
 test('tablet collapses role sidebar without hiding app controls',async({page},testInfo)=>{if(!testInfo.project.name.includes('tablet'))test.skip();const shell=page.locator('.role-home');await expect(shell.getByRole('button',{name:'Cambiar tema'})).toBeVisible();await expect(page.getByRole('region',{name:'Calculadora Hipotecaria'})).toBeVisible();await expect(shell.locator('.ops-side')).toBeVisible();});
});