import {test,expect} from '@playwright/test';
const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6ImRpcmVjY2lvbkBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-doc-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'direccion@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-19T00:00:00.000Z'}};
const items=[{id:'aaaaaaaa-1111-4111-8111-bbbbbbbbbbbb',documento:'Contrato de servicios',categoria:'Interna',estado:'Vigente',fecha_proxima_revision:'2026-12-01',url:'https://example.com/contrato.pdf'},{id:'bbbbbbbb-1111-4111-8111-cccccccccccc',documento:'Guía de documentación cliente',categoria:'Guía general',estado:'Vigente',fecha_proxima_revision:'2026-06-15',url:'https://example.com/guia.pdf'},{id:'cccccccc-1111-4111-8111-dddddddddddd',documento:'Documento por clasificar',estado:'Pendiente',fecha_proxima_revision:'2026-01-10'}];

test.describe('Fénix PRE-PROD · contrato visual Documentación',()=>{
 test('usa biblioteca por tarjetas, filtros prefijados y apertura de archivos reales',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await page.setViewportSize({width:1600,height:900});await page.addInitScript(session=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));localStorage.setItem('fenix-remember-device','true');},fakeSession);
  await page.route('**/functions/v1/fenix-app-gateway-test/**',async r=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-TEST',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Documentación',route:'/documentacion'}]})});return r.fulfill({status:404,body:'{}'});});
  await page.route('**/functions/v1/fenix-notion-runtime-test/documentos',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({source:'notion_canonical',items})}));
  await page.goto('/documentacion');const root=page.locator('.doc-root');await expect(root).toBeVisible();await expect(root.getByRole('heading',{name:'Documentación',exact:true})).toBeVisible();await expect(root.getByText('ANA · DOCUMENTACIÓN')).toBeVisible();await expect(root.getByText('Datos actualizados')).toBeVisible();await expect(root.getByTestId('documentacion-preset-search')).toBeVisible();await expect(root.getByTestId('doc-card-grid')).toBeVisible();
  await expect(root.getByText('Contrato de servicios',{exact:true})).toBeVisible();await expect(root.getByText('Guía de documentación cliente',{exact:true})).toBeVisible();await expect(root.locator('.doc-library-card').filter({hasText:'Contrato de servicios'}).getByRole('link',{name:'Abrir documento'})).toHaveAttribute('target','_blank');await expect(root.locator('.doc-library-card').filter({hasText:'Documento por clasificar'}).getByRole('button',{name:'Archivo pendiente'})).toBeDisabled();
  await expect(root.locator('.ops-title').getByRole('button',{name:'+ Nuevo documento'})).toBeVisible();await expect(root.getByText(/\bPRO\b/)).toHaveCount(0);
 });
});
