import {test,expect} from '@playwright/test';
const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6ImRpcmVjY2lvbkBmZW5peC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-firmas-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'direccion@fenix.test',app_metadata:{},user_metadata:{},created_at:'2026-08-19T00:00:00.000Z'}};
const items=[
 {id:'aaaaaaaa-1111-4111-8111-bbbbbbbbbbbb',cliente:'JORGE Y ALEX',estado:'Programada',fecha_hora_firma:'2026-08-25 10:00',banco:'BBVA',notaria:'Notaría Centro',nota_simple_url:'https://example.com/nota.pdf',fein_url:'https://example.com/fein.pdf',forma_pago_url:'https://example.com/pago.pdf',dnis_participantes:[{url:'https://example.com/dni-jorge.pdf'},{url:'https://example.com/dni-alex.pdf'}],certificado_energetico_url:'https://example.com/cee.pdf'},
 {id:'bbbbbbbb-1111-4111-8111-cccccccccccc',cliente:'MARÍA',estado:'Firmada',fecha_hora_firma:'2026-08-20 12:00',banco:'Abanca',notaria:'Notaría Sur'}
];

test.describe('Fénix PRE-PROD · contrato visual Firmas',()=>{
 test('muestra tarjetas de firma con checklist documental y apertura en pestaña nueva',async({page},testInfo)=>{
  if(!testInfo.project.name.includes('desktop'))test.skip();await page.setViewportSize({width:1600,height:900});await page.addInitScript(session=>{localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));localStorage.setItem('fenix-remember-device','true');},fakeSession);
  await page.route('**/functions/v1/fenix-app-gateway-test/**',async r=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'DIR-TEST',role:'Direccion'})});if(u.endsWith('/navigation'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[{label:'Inicio',route:'/inicio'},{label:'Firmas',route:'/firmas'}]})});return r.fulfill({status:404,body:'{}'});});
  await page.route('**/functions/v1/fenix-notion-runtime-test/firmas',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({source:'notion_canonical',items})}));
  await page.goto('/firmas');const root=page.locator('.firmas-root');await expect(root).toBeVisible();await expect(root.getByRole('heading',{name:'Firmas',exact:true})).toBeVisible();await expect(root.getByText('ANA · FIRMAS')).toBeVisible();await expect(root.getByText('Datos actualizados')).toBeVisible();await expect(root.getByTestId('firmas-preset-search')).toBeVisible();await expect(root.getByTestId('firmas-card-grid')).toBeVisible();await expect(root.getByText('JORGE Y ALEX',{exact:true})).toBeVisible();await expect(root.getByText('Notaría Centro',{exact:true})).toBeVisible();
  const card=root.locator('.firma-card').filter({hasText:'JORGE Y ALEX'});await expect(card.getByText('Nota simple',{exact:true})).toBeVisible();await expect(card.getByText('FEIN',{exact:true})).toBeVisible();await expect(card.getByText('Forma de pago enviada al banco',{exact:true})).toBeVisible();await expect(card.getByText('Certificado energético',{exact:true})).toBeVisible();await expect(card.getByText('DNIs de participantes 1',{exact:true})).toBeVisible();await expect(card.getByText('DNIs de participantes 2',{exact:true})).toBeVisible();await expect(card.getByRole('link',{name:/Nota simple/})).toHaveAttribute('target','_blank');
  await expect(root.locator('.firmas-title').getByRole('button',{name:'+ Nueva firma'})).toBeVisible();await expect(root.getByText(/\bPRO\b/)).toHaveCount(0);
 });
});
