import {test,expect} from '@playwright/test';
const fakeSession={access_token:'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJzdWIiOiJhYWFhYWFhYS1hYWFhLTRhYWEtOGFhYS1hYWFhYWFhYWFhYWEiLCJlbWFpbCI6ImZpbmFuY2llcm9AZmVueC50ZXN0IiwiZXhwIjoxOTk5OTk5OTk5fQ.',token_type:'bearer',expires_in:3600,expires_at:1999999999,refresh_token:'qa-profile-not-real',user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',aud:'authenticated',role:'authenticated',email:'financiero@fenix.test',app_metadata:{},user_metadata:{full_name:'Perfil QA'},created_at:'2026-08-19T00:00:00.000Z'}};
async function seed(page:any){await page.addInitScript((session:any)=>{window.localStorage.setItem('fenix-preprod-auth',JSON.stringify(session));window.localStorage.setItem('fenix-remember-device','true')},fakeSession)}
async function routes(page:any,{goals=true,navigationStatus=200,delayProfileMs=0}:{goals?:boolean;navigationStatus?:number;delayProfileMs?:number}={}){
 await page.route('**/functions/v1/fenix-app-gateway-test/**',async r=>{const u=r.request().url();if(u.endsWith('/session/context'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actor_code:'FIN-A',role:'Financiero'})});if(u.endsWith('/navigation'))return r.fulfill({status:navigationStatus,contentType:'application/json',body:navigationStatus===200?JSON.stringify({items:['/inicio','/expedientes','/bancos','/buscar','/perfil']}):'{}'});return r.fulfill({status:404,body:'{}'})});
 await page.route('**/functions/v1/fenix-profile-api-test**',async r=>{if(delayProfileMs)await new Promise(resolve=>setTimeout(resolve,delayProfileMs));const u=r.request().url();if(u.endsWith('/goals'))return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,status:200,items:goals?[{metric_code:'EXPEDIENTES',target:10,actual:6,missing:4,pct:60,status:'EN_CURSO',guidance:'Faltan 4 expedientes para el objetivo mensual.'},{metric_code:'FIRMAS',target:4,actual:2,missing:2,pct:50,status:'EN_CURSO',guidance:'Faltan 2 firmas para el objetivo mensual.'}]:[]})});return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,status:200,item:{actor_code:'FIN-A',role:'Financiero',display_name:'Perfil QA',contact_email:'financiero@fenix.test',zone:'Córdoba',phone:'600000000',linkedin:'https://linkedin.test/perfil'}})})});
 await page.route('**/functions/v1/fenix-user-admin-test**',async r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({ok:false,error:'forbidden'})}));
}
test.describe('Fénix PRE-PROD · Mi perfil',()=>{
 test('muestra perfil editable, objetivos reales y navegación normalizada',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await page.setViewportSize({width:1600,height:900});await seed(page);await routes(page);await page.goto('/perfil');const root=page.locator('.profile-root');await expect(root).toBeVisible();await expect(root.getByRole('heading',{name:'Mi perfil',exact:true})).toBeVisible();await expect(root.getByRole('heading',{name:'Perfil QA',exact:true})).toBeVisible();await expect(root.getByText('financiero@fenix.test',{exact:true})).toBeVisible();await expect(root.getByText('60%',{exact:true})).toBeVisible();await expect(root.getByText('Faltan 4 expedientes para el objetivo mensual.',{exact:true})).toBeVisible();await expect(root.getByRole('button',{name:'Guardar perfil'})).toBeVisible();await expect(root.getByRole('button',{name:'Cambiar contraseña'})).toBeVisible();await expect(root.getByRole('button',{name:'Cambiar tema'})).toHaveCount(1);await expect(root.getByText('Crear usuario',{exact:true})).toHaveCount(0);const nav=root.locator('.ops-side nav');await expect(nav.getByRole('button',{name:'Expedientes',exact:true})).toBeVisible();await expect(nav.getByRole('button',{name:'Bancos',exact:true})).toBeVisible();await expect(nav.getByRole('button',{name:'Buscar',exact:true})).toHaveCount(0);await expect(nav.getByRole('button',{name:'Perfil',exact:true})).toHaveCount(0);const shot=await root.screenshot();await testInfo.attach('perfil-master-1600',{body:shot,contentType:'image/png'})});
 test('no presenta ausencia de objetivos mientras el perfil todavía está cargando',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await page.setViewportSize({width:1600,height:900});await seed(page);await routes(page,{delayProfileMs:800});await page.goto('/perfil');const root=page.locator('.profile-root');await expect(root.locator('[data-testid="profile-loading"]')).toBeVisible();await expect(root.getByText('Sin objetivos configurados.',{exact:true})).toHaveCount(0);await expect(root.getByRole('button',{name:'Cambiar tema'})).toHaveCount(1);await expect(root.locator('[data-testid="profile-loading"]')).toHaveCount(0,{timeout:5000});await expect(root.getByText('60%',{exact:true})).toBeVisible()});
 test('presenta objetivo, realizado, faltante y mejora sin inferir datos externos',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await routes(page);await page.goto('/perfil');const root=page.locator('.profile-root');const kpis=root.locator('.profile-kpis');await expect(kpis.getByText('6/10',{exact:true})).toBeVisible();await expect(kpis.getByText('2/4',{exact:true})).toBeVisible();await expect(root.getByText('Faltan 4 expedientes para el objetivo mensual.',{exact:true})).toBeVisible();await expect(root.getByText('Faltan 2 firmas para el objetivo mensual.',{exact:true})).toBeVisible();await expect(root.getByText('Córdoba',{exact:true})).toBeVisible()});
 test('si navigation falla conserva solo Inicio',async({page},testInfo)=>{if(!testInfo.project.name.includes('desktop'))test.skip();await seed(page);await routes(page,{navigationStatus:503});await page.goto('/perfil');const nav=page.locator('.profile-root .ops-side nav');await expect(nav.getByRole('button',{name:'Inicio',exact:true})).toHaveCount(1);await expect(nav.locator('button')).toHaveCount(1)});
});
