import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const BUCKET='fenix-prod-documents',ALLOWED=new Set(['https://app.fenixcapital.es']);let svc:any=null;
function keyFromJson(raw:string){try{const x=JSON.parse(raw||'{}');return String(x?.default??Object.values(x??{})[0]??'')}catch{return ''}}
function config(){const URL=Deno.env.get('SUPABASE_URL')??'',ANON=Deno.env.get('SUPABASE_ANON_KEY')||keyFromJson(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')??''),SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||keyFromJson(Deno.env.get('SUPABASE_SECRET_KEYS')??'');return{URL,ANON,SERVICE}}
function service(){const c=config();if(!c.URL||!c.SERVICE)return null;if(!svc)svc=createClient(c.URL,c.SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});return svc}
function cors(req:Request){const o=req.headers.get('origin')||'';return {'Access-Control-Allow-Origin':ALLOWED.has(o)?o:'https://app.fenixcapital.es','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, idempotency-key','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Vary':'Origin','x-fenix-env':'PROD'}}
function out(req:Request,body:any,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function body(req:Request){try{return await req.json()}catch{return {}}}
async function rpc(name:string,args:any={}){const s=service();if(!s)throw new Error('server_config_missing');const {data,error}=await s.rpc(name,args);if(error)throw new Error(`${name}: ${error.message}`);return data}
function result(req:Request,r:any){return out(req,r,Number(r?.status)||200)}
async function identity(req:Request){const c=config();if(!c.URL||!c.ANON||!service())return null;const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return null;const auth=createClient(c.URL,c.ANON,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await auth.auth.getUser(h.slice(7));if(error||!data.user)return null;const ctx=await rpc('fenix_prod_actor_context_by_auth_server',{p_auth_user_id:data.user.id});if(!ctx?.ok)return null;return{user:data.user,actor:ctx.actor_code,role:ctx.role}}
function seg(path:string){return path.split('/').filter(Boolean)}
function routePath(req:Request){const raw=new URL(req.url).pathname;return raw.replace(/^\/(?:functions\/v1\/)?fenix-app-gateway/,'')||'/'}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const u=new URL(req.url),p=routePath(req);if(p==='/health'){const c=config();return out(req,{ok:true,status:200,env:'PROD',service:'fenix-app-gateway',contract_version:3,config:{url:Boolean(c.URL),publishable:Boolean(c.ANON),secret:Boolean(c.SERVICE)}})}const c=config();if(!c.URL||!c.ANON||!c.SERVICE||!service())return out(req,{ok:false,status:503,error:'server_config_missing'},503);let me;try{me=await identity(req)}catch(e){console.error('identity',e);return out(req,{ok:false,status:500,error:'identity_resolution_failed'},500)}if(!me)return out(req,{ok:false,status:401,error:'identity_not_linked'},401);const a=me.actor,s=seg(p),b=req.method==='GET'?{}:await body(req),ss=service();try{
if(p==='/session/context'&&req.method==='GET')return result(req,await rpc('fenix_prod_session_context_server',{p_actor_code:a}));
if(p==='/navigation'&&req.method==='GET')return out(req,{ok:true,status:200,items:await rpc('fenix_prod_navigation_server',{p_actor_code:a})});
if(p==='/expedientes'&&req.method==='GET')return result(req,await rpc('fenix_prod_exp_list_server',{p_actor_code:a}));
if(s[0]==='expedientes'&&s[1]&&s[2]==='workspace'&&req.method==='GET')return result(req,await rpc('fenix_prod_expediente_workspace_server',{p_actor_code:a,p_exp_code:s[1]}));
if(s[0]==='expedientes'&&s[1]&&!s[2]&&req.method==='GET'){const x=await rpc('fenix_prod_get_expediente_server',{p_actor_code:a,p_code:s[1]});return x&&Object.keys(x).length?out(req,{ok:true,status:200,expediente:x}):out(req,{ok:false,status:404,error:'not_found'},404)}
if(p==='/tareas'&&req.method==='GET')return out(req,{ok:true,status:200,items:await rpc('fenix_prod_get_tareas_server',{p_actor_code:a})});
if(s[0]==='tareas'&&s[1]&&s[2]==='reassign'&&req.method==='POST')return result(req,await rpc('fenix_prod_reassign_task_server',{p_actor_code:a,p_task_code:s[1],p_new_actor_code:b.new_actor_code,p_expected_version:b.expected_version}));
if(p==='/search'&&req.method==='GET')return out(req,{ok:true,status:200,items:await rpc('fenix_prod_search_server',{p_actor_code:a,p_q:u.searchParams.get('q')||''})});
if(p==='/documentos'&&req.method==='GET')return out(req,{ok:true,status:200,items:await rpc('fenix_prod_document_list_server',{p_actor_code:a})});
if(s[0]==='documentos'&&s[1]&&s[2]==='versions'&&req.method==='GET')return result(req,await rpc('fenix_prod_document_versions_server',{p_actor_code:a,p_document_code:s[1]}));
if(s[0]==='documentos'&&s[1]&&s[2]==='view'&&req.method==='GET'){const r=await rpc('fenix_prod_document_view_path_server',{p_actor_code:a,p_document_code:s[1]});if(!r?.ok)return result(req,r);const {data,error}=await ss.storage.from(BUCKET).createSignedUrl(r.storage_path,300);if(error)return out(req,{ok:false,status:500,error:'signed_url_failed'},500);return out(req,{...r,signed_url:data.signedUrl,expires_in:300})}
if(s[0]==='documentos'&&s[1]&&!s[2]&&req.method==='GET')return result(req,await rpc('fenix_prod_document_access_server',{p_actor_code:a,p_document_code:s[1]}));
if(p==='/documentos/upload/prepare'&&req.method==='POST'){const id=crypto.randomUUID(),ext=String(b.filename||'file').replace(/[^A-Za-z0-9._-]/g,'_'),path=`${b.scope_type}/${b.scope_code}/${id}/${ext}`,exp=new Date(Date.now()+600000).toISOString();const r=await rpc('fenix_prod_doc_prepare',{p_actor_code:a,p_upload_id:id,p_scope_type:b.scope_type,p_scope_code:b.scope_code,p_storage_path:path,p_mime_type:b.mime_type,p_filename:b.filename,p_expires_at:exp});if(!r?.ok)return result(req,r);const {data,error}=await ss.storage.from(BUCKET).createSignedUploadUrl(path);if(error)return out(req,{ok:false,status:500,error:'upload_url_failed'},500);return out(req,{...r,upload_id:id,storage_path:path,signed_upload_url:data.signedUrl,token:data.token,expires_at:exp})}
if(p==='/documentos/upload/complete'&&req.method==='POST')return result(req,await rpc('fenix_prod_doc_finalize',{p_actor_code:a,p_upload_id:b.upload_id,p_sha256:b.sha256,p_mime_type:b.mime_type,p_bytes:b.bytes,p_title:b.title,p_tipo:b.tipo,p_sensibilidad:b.sensibilidad,p_replace_document_code:b.replace_document_code||null,p_document_code:b.document_code||null}));
if(p==='/bancos'&&req.method==='GET')return result(req,await rpc('fenix_prod_bank_list_server',{p_actor_code:a}));
if(s[0]==='bancos'&&s[1]&&req.method==='GET')return result(req,await rpc('fenix_prod_bank_detail_server',{p_actor_code:a,p_bank_code:s[1]}));
if(s[0]==='expedientes'&&s[1]&&s[2]==='bancos-candidatos'&&req.method==='GET')return result(req,await rpc('fenix_prod_bank_candidates_server',{p_actor_code:a,p_exp_code:s[1]}));
if(s[0]==='expedientes'&&s[1]&&s[2]==='envios-banco'&&s[3]==='prepare'&&req.method==='POST')return result(req,await rpc('fenix_prod_bank_prepare_server',{p_actor_code:a,p_exp_code:s[1],p_bank_code:b.bank_code,p_payload:b.payload,p_payload_hash:b.payload_hash,p_idempotency_key:req.headers.get('idempotency-key')||b.idempotency_key||''}));
if(s[0]==='expedientes'&&s[1]&&s[2]==='envios-banco'&&req.method==='GET')return result(req,await rpc('fenix_prod_bank_sends_server',{p_actor_code:a,p_exp_code:s[1]}));
if(s[0]==='envios-banco'&&s[1]&&s[2]==='authorize'&&req.method==='POST')return result(req,await rpc('fenix_prod_bank_authorize_server',{p_actor_code:a,p_send_code:s[1],p_expected_version:b.expected_version,p_payload_hash:b.payload_hash}));
if(s[0]==='envios-banco'&&s[1]&&s[2]==='send'&&req.method==='POST')return result(req,await rpc('fenix_prod_bank_send_server',{p_actor_code:a,p_send_code:s[1],p_expected_version:b.expected_version,p_payload_hash:b.payload_hash,p_idempotency_key:req.headers.get('idempotency-key')||b.idempotency_key||''}));
if(s[0]==='envios-banco'&&s[1]&&s[2]==='result'&&req.method==='POST')return result(req,await rpc('fenix_prod_bank_result_server',{p_actor_code:a,p_send_code:s[1],p_event_id:b.event_id,p_result:b.result||{}}));
if(s[0]==='envios-banco'&&s[1]&&!s[2]&&req.method==='GET')return result(req,await rpc('fenix_prod_bank_send_get_server',{p_actor_code:a,p_send_code:s[1]}));
if(s[0]==='expedientes'&&s[1]&&s[2]==='ofertas'&&req.method==='GET')return result(req,await rpc('fenix_prod_offer_list_server',{p_actor_code:a,p_exp_code:s[1]}));
if(s[0]==='ofertas'&&s[1]&&s[2]==='decision'&&req.method==='POST')return result(req,await rpc('fenix_prod_offer_decision_server',{p_actor_code:a,p_offer_code:s[1],p_expected_version:b.expected_version,p_decision:b.decision,p_reason:b.reason}));
if(s[0]==='ofertas'&&s[1]&&req.method==='GET')return result(req,await rpc('fenix_prod_offer_get_server',{p_actor_code:a,p_offer_code:s[1]}));
if(p==='/tasaciones'&&req.method==='GET')return result(req,await rpc('fenix_prod_appraisal_list_server',{p_actor_code:a}));
if(s[0]==='tasaciones'&&s[1]&&s[2]==='history'&&req.method==='GET')return result(req,await rpc('fenix_prod_appraisal_history_server',{p_actor_code:a,p_appraisal_code:s[1]}));
if(s[0]==='tasaciones'&&s[1]&&s[2]==='report'&&req.method==='GET')return result(req,await rpc('fenix_prod_appraisal_report_server',{p_actor_code:a,p_appraisal_code:s[1]}));
if(s[0]==='tasaciones'&&s[1]&&s[2]==='status'&&req.method==='POST')return result(req,await rpc('fenix_prod_appraisal_status_server',{p_actor_code:a,p_appraisal_code:s[1],p_expected_version:b.expected_version,p_new_status:b.status}));
if(s[0]==='tasaciones'&&s[1]&&s[2]==='validacion-belen'&&req.method==='POST')return result(req,await rpc('fenix_prod_appraisal_validate_server',{p_actor_code:a,p_appraisal_code:s[1],p_expected_version:b.expected_version,p_decision:b.decision,p_reason:b.reason}));
if(s[0]==='tasaciones'&&s[1]&&req.method==='GET')return result(req,await rpc('fenix_prod_appraisal_scope_server',{p_actor_code:a,p_appraisal_code:s[1]}));
if(p==='/firmas'&&req.method==='GET')return result(req,await rpc('fenix_prod_sign_list_server',{p_actor_code:a}));
if(s[0]==='firmas'&&s[1]&&s[2]==='history'&&req.method==='GET')return result(req,await rpc('fenix_prod_sign_history_server',{p_actor_code:a,p_firma_code:s[1]}));
if(s[0]==='firmas'&&s[1]&&s[2]==='schedule'&&req.method==='POST')return result(req,await rpc('fenix_prod_sign_schedule_server',{p_actor_code:a,p_firma_code:s[1],p_expected_version:b.expected_version,p_fecha_firma:b.fecha_firma,p_notaria:b.notaria,p_oficial:b.oficial}));
if(s[0]==='firmas'&&s[1]&&s[2]==='confirm'&&req.method==='POST')return result(req,await rpc('fenix_prod_sign_confirm_server',{p_actor_code:a,p_firma_code:s[1],p_expected_version:b.expected_version}));
if(s[0]==='firmas'&&s[1]&&s[2]==='close'&&req.method==='POST')return result(req,await rpc('fenix_prod_sign_close_server',{p_actor_code:a,p_firma_code:s[1],p_expected_version:b.expected_version}));
if(s[0]==='firmas'&&s[1]&&req.method==='GET')return result(req,await rpc('fenix_prod_sign_scope_server',{p_actor_code:a,p_firma_code:s[1]}));
if(s[0]==='expedientes'&&s[1]&&s[2]==='firma'&&req.method==='GET')return result(req,await rpc('fenix_prod_sign_by_exp_server',{p_actor_code:a,p_exp_code:s[1]}));
if(p==='/inmobiliarias'&&req.method==='GET')return result(req,await rpc('fenix_prod_inmo_list_server',{p_actor_code:a}));
if(p==='/inmobiliarias'&&req.method==='POST')return result(req,await rpc('fenix_prod_inmo_create_server',{p_actor_code:a,p_inmobiliaria_code:b.inmobiliaria_code,p_nombre_alias:b.nombre_alias,p_zone_code:b.zone_code}));
if(s[0]==='inmobiliarias'&&s[1]&&req.method==='PATCH')return result(req,await rpc('fenix_prod_inmo_update_server',{p_actor_code:a,p_inmobiliaria_code:s[1],p_expected_version:b.expected_version,p_nombre_alias:b.nombre_alias||null,p_zone_code:b.zone_code||null}));
if(s[0]==='inmobiliarias'&&s[1]&&req.method==='GET')return result(req,await rpc('fenix_prod_inmo_get_server',{p_actor_code:a,p_code:s[1]}));
if(p==='/contactos'&&req.method==='GET')return result(req,await rpc('fenix_prod_contacts_server',{p_actor_code:a}));
if(s[0]==='contactos'&&s[1]&&req.method==='GET')return result(req,await rpc('fenix_prod_contact_get_server',{p_actor_code:a,p_id:s[1]}));
if(p==='/visitadores'&&req.method==='GET')return result(req,await rpc('fenix_prod_visitadores_server',{p_actor_code:a}));
if(p==='/personal'&&req.method==='GET')return result(req,await rpc('fenix_prod_personal_server',{p_actor_code:a}));
if(p==='/ana/correcciones'&&req.method==='GET')return result(req,await rpc('fenix_prod_ana_corrections_list_server',{p_actor_code:a}));
if(p==='/ana/correcciones'&&req.method==='POST')return result(req,await rpc('fenix_prod_ana_correction_create_v2_server',{p_actor_code:a,p_scope_type:b.scope_type,p_scope_code:b.scope_code||null,p_ana_suggestion:b.ana_suggestion,p_user_reason:b.user_reason,p_proposed_rule:b.proposed_rule||null,p_idempotency_key:req.headers.get('idempotency-key')||b.idempotency_key||''}));
if(s[0]==='ana'&&s[1]==='correcciones'&&s[2]&&s[3]==='decision'&&req.method==='POST')return result(req,await rpc('fenix_prod_ana_correction_decide_v2_server',{p_actor_code:a,p_correction_code:s[2],p_expected_version:b.expected_version,p_decision_kind:b.decision_kind,p_review_reason:b.review_reason||null,p_approved_rule:b.approved_rule||null,p_idempotency_key:req.headers.get('idempotency-key')||b.idempotency_key||''}));
return out(req,{ok:false,status:404,error:'route_not_found',path:p},404)}catch(e){console.error('gateway',e);return out(req,{ok:false,status:500,error:'backend_error'},500)}});