import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const CONTRACT=require('./factory/catalogs/technology-scout.v0.json');
const REQUIRED_CONTEXT=new Set(CONTRACT.required_context);
const WEIGHTS=CONTRACT.score_weights;
const CANDIDATE_KEYS=new Set(['candidate_id','source_ref','observed_at','version_ref','license_ref','cost_eur_month','security_notes','integration_notes','fit','maintainability','security','interoperability','reversibility']);
function str(v,l){if(typeof v!=='string'||!v.trim())throw new Error(`${l} required`);return v;}
function num(v,l,min=0,max=100){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw new Error(`${l} invalid`);return v;}
function exact(o,keys,l){if(!o||typeof o!=='object'||Array.isArray(o))throw new Error(`${l} object required`);for(const k of Object.keys(o))if(!keys.has(k))throw new Error(`unexpected ${l} field ${k}`);}
function context(ctx){if(!ctx||typeof ctx!=='object'||Array.isArray(ctx))throw new Error('context required');if(Object.keys(ctx).length!==REQUIRED_CONTEXT.size)throw new Error('context fields mismatch');for(const k of REQUIRED_CONTEXT)str(ctx[k],`context.${k}`);if(ctx.environment!=='SCAFFOLD')throw new Error('Technology Scout V0 accepts SCAFFOLD only');}
function human(reason,candidate_id){return Object.freeze({status:'HUMAN_REQUIRED',reason,candidate_id,executed:false});}
export function scoreTechnologyCandidate(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('request required');context(input.context);if(input.prod_write===true)return human('HIGH_RISK',input.candidate?.candidate_id??null);if(input.trading_access===true)return human('POLICY_CONFLICT',input.candidate?.candidate_id??null);const c=input.candidate;exact(c,CANDIDATE_KEYS,'candidate');for(const k of ['candidate_id','source_ref','observed_at','version_ref','license_ref','security_notes','integration_notes'])str(c[k],`candidate.${k}`);num(c.cost_eur_month,'candidate.cost_eur_month',0,1e9);for(const k of ['fit','maintainability','security','interoperability','reversibility'])num(c[k],`candidate.${k}`);if(c.cost_eur_month>0)return human('MONEY_LIMIT',c.candidate_id);const zero_cost=100;const score=(c.fit*WEIGHTS.fit+zero_cost*WEIGHTS.zero_cost+c.maintainability*WEIGHTS.maintainability+c.security*WEIGHTS.security+c.interoperability*WEIGHTS.interoperability+c.reversibility*WEIGHTS.reversibility)/100;return Object.freeze({status:'SCORED',candidate_id:c.candidate_id,score:Number(score.toFixed(2)),recommendation:score>=80?'SHORTLIST':score>=60?'REVIEW':'REJECT',execution_mode:'PLAN_ONLY',executed:false,additional_cost_target_eur:0});}
export function rankTechnologyCandidates(requests){if(!Array.isArray(requests)||!requests.length)throw new Error('requests required');return Object.freeze(requests.map(scoreTechnologyCandidate).sort((a,b)=>(b.score??-1)-(a.score??-1)||String(a.candidate_id).localeCompare(String(b.candidate_id))));}
