import crypto from 'node:crypto';
const ENV=new Set(['LAB','PREPROD']);
const req=(v,l)=>{if(typeof v!=='string'||!v.trim())throw new TypeError(`${l} required`);return v.trim()};
const plain=(v,l)=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new TypeError(`${l} must be object`);return v};
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
function ctx(c){plain(c,'context');const o={company_id:req(c.company_id,'company_id'),engine_id:req(c.engine_id,'engine_id'),environment:req(c.environment,'environment'),version:req(c.version,'version')};if(o.engine_id!=='RSH-001')throw new Error('engine_id must be RSH-001');if(!ENV.has(o.environment))throw new Error('RSH-001 V0 is LAB/PREPROD only');return o;}
function source(s,i){plain(s,`sources[${i}]`);const confidence=Number(s.confidence);if(!Number.isFinite(confidence)||confidence<0||confidence>1)throw new TypeError(`sources[${i}].confidence must be 0..1`);return Object.freeze({source_id:req(s.source_id,`sources[${i}].source_id`),source_type:req(s.source_type,`sources[${i}].source_type`),source_uri:req(s.source_uri,`sources[${i}].source_uri`),retrieved_at:req(s.retrieved_at,`sources[${i}].retrieved_at`),confidence,excerpt_hash:req(s.excerpt_hash,`sources[${i}].excerpt_hash`)});}
function claim(c,i,sourceIds){plain(c,`claims[${i}]`);const refs=Array.isArray(c.source_ids)?c.source_ids:[];if(refs.length===0)throw new TypeError(`claims[${i}].source_ids required`);for(const id of refs){if(!sourceIds.has(id))throw new Error(`claims[${i}] references unknown source ${id}`);}const confidence=Number(c.confidence);if(!Number.isFinite(confidence)||confidence<0||confidence>1)throw new TypeError(`claims[${i}].confidence must be 0..1`);return Object.freeze({claim_id:req(c.claim_id,`claims[${i}].claim_id`),statement:req(c.statement,`claims[${i}].statement`),source_ids:Object.freeze([...refs]),confidence,contradicted:c.contradicted===true});}
export function buildResearchDossier(input={}){
 const i=plain(input,'input');const c=ctx(i.context);const query=req(i.query,'query');const sources=(Array.isArray(i.sources)?i.sources:[]).map(source);if(sources.length<2)return Object.freeze({status:'HUMAN_REQUIRED',reason:'LOW_CONFIDENCE',ready:false,detail:'minimum_two_sources_required',knowledge_promotion:false});
 const sourceIds=new Set(sources.map(s=>s.source_id));if(sourceIds.size!==sources.length)return Object.freeze({status:'HUMAN_REQUIRED',reason:'POLICY_CONFLICT',ready:false,detail:'duplicate_source_id',knowledge_promotion:false});
 const claims=(Array.isArray(i.claims)?i.claims:[]).map((x,n)=>claim(x,n,sourceIds));if(claims.length===0)return Object.freeze({status:'HUMAN_REQUIRED',reason:'LOW_CONFIDENCE',ready:false,detail:'no_claims',knowledge_promotion:false});
 const contradicted=claims.filter(x=>x.contradicted);const avg=claims.reduce((a,b)=>a+b.confidence,0)/claims.length;const distinctTypes=new Set(sources.map(s=>s.source_type)).size;
 if(contradicted.length>0)return Object.freeze({status:'HUMAN_REQUIRED',reason:'POLICY_CONFLICT',ready:false,detail:'contradicted_claims_present',contradicted_claim_ids:Object.freeze(contradicted.map(x=>x.claim_id)),knowledge_promotion:false});
 if(avg<0.7||distinctTypes<2)return Object.freeze({status:'HUMAN_REQUIRED',reason:'LOW_CONFIDENCE',ready:false,detail:avg<0.7?'claim_confidence_below_threshold':'source_diversity_below_threshold',knowledge_promotion:false});
 const body={research_id:req(i.research_id,'research_id'),company_id:c.company_id,engine_id:c.engine_id,environment:c.environment,version:c.version,query,sources,claims,summary:req(i.summary,'summary'),overall_confidence:Number(avg.toFixed(4)),source_count:sources.length,source_type_count:distinctTypes};
 return Object.freeze({status:'GREEN',reason:null,ready:true,dossier:Object.freeze({...body,evidence_hash:hash(body)}),knowledge_promotion:false,rule_promotion:false,requires_knw_review:true,audit_required:true,prod_write:false,trading_access:false,additional_cost_target_eur:0});
}
export const RSH001_CONTRACT=Object.freeze({engine_id:'RSH-001',purpose:'RESEARCH_AND_DOSSIER_ONLY',minimum_sources:2,minimum_source_types:2,minimum_claim_confidence:0.7,knowledge_promotion:false,rule_promotion:false,requires_knw_review:true,environments:['LAB','PREPROD'],prod_write:false,trading_access:false,additional_cost_target_eur:0,autonomous_prod:false});
