import test from 'node:test';
import assert from 'node:assert/strict';
import {expectedCoveragePairs,expectedTemplatesForDomain,validateGcpInventoryEnvelope} from '../runtime/gcp-live-inventory-validator-v0.mjs';

const ts='2026-09-10T21:00:00Z';
function commandResult(project_id,domain,template,overrides={}){return {command_run_ref:`run-${domain}-${Math.random()}`,command_template_id_or_ref:template,result_status:'EMPTY',captured_at:ts,principal_ref:'credential-ref://gcp-ro',evidence_ref:`evidence://gcp/${project_id}/${domain}`,resolved_parameters:{PROJECT_ID:project_id},discovered_values:[],...overrides};}
function coverageRecord(project_id,domain,index){const required=expectedTemplatesForDomain(domain); const results=required.map((t)=>commandResult(project_id,domain,t)); if(domain==='scheduler'){results[0].discovered_values=['europe-west1','us-central1']; results[1]=commandResult(project_id,domain,required[1],{resolved_parameters:{PROJECT_ID:project_id,LOCATION:'europe-west1'}}); results.push(commandResult(project_id,domain,required[1],{resolved_parameters:{PROJECT_ID:project_id,LOCATION:'us-central1'}}));} return {capture_id:`c-${index}`,record_kind:'COVERAGE',captured_at:ts,company_id:'fenix-capital',engine_id:'INT-001',environment:'SCAFFOLD',version:'1.0.0',project_id,domain,command_template_id_or_ref:`GCP-READONLY-CATALOG:${domain}`,principal_ref:'credential-ref://gcp-ro',result_status:'EMPTY',evidence_ref:`evidence://gcp/${project_id}/${domain}`,raw_payload_stored:false,secret_payload_present:false,resource_ref:'__DOMAIN__',classification_status:'UNCLASSIFIED',required_command_templates:required,command_results:results};}
function fullCoverage(){return expectedCoveragePairs().map(({project_id,domain},i)=>coverageRecord(project_id,domain,i));}
function envelope(c=fullCoverage(),r=[]){return JSON.stringify({coverage_records:c,resource_records:r});}

test('accepts complete catalog-bound 4x19 inventory envelope',()=>{const r=validateGcpInventoryEnvelope(envelope()); assert.equal(r.valid,true); assert.equal(r.coverage_pairs,76);});
test('rejects omitted canonical command template in multi-command domain',()=>{const c=fullCoverage(); const x=c.find((r)=>r.domain==='pubsub'); x.command_results.pop(); assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/missing required command template result/);});
test('rejects scheduler missing or duplicate discovered location expansion',()=>{const c=fullCoverage(); const s=c.find((r)=>r.domain==='scheduler'); s.command_results=s.command_results.filter((r)=>r.resolved_parameters.LOCATION!=='us-central1'); assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/exactly cover discovered locations/); const d=fullCoverage(); const sd=d.find((r)=>r.domain==='scheduler'); sd.command_results.push({...sd.command_results.at(-1),command_run_ref:'dup-location'}); assert.throws(()=>validateGcpInventoryEnvelope(envelope(d)),/duplicate LOCATION result/);});
test('rejects normalized impossible timestamps',()=>{for(const bad of ['2026-02-31T21:00:00Z','2026-01-01T24:00:00Z']){const c=fullCoverage(); c[0].captured_at=bad; assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/invalid calendar\/time component/);}});
test('rejects duplicate JSON members before parsing',()=>{const t='{"coverage_records":[],"coverage_records":[],"resource_records":[]}'; assert.throws(()=>validateGcpInventoryEnvelope(t),/duplicate JSON object key/);});
test('rejects non-reference provenance and edge-whitespace resource identities',()=>{const c=fullCoverage(); c[0].principal_ref='{"token":"x"}'; assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/canonical principal\/credential reference/); const r={capture_id:'r1',record_kind:'RESOURCE',captured_at:ts,company_id:'fenix-capital',engine_id:'INT-001',environment:'SCAFFOLD',version:'1.0.0',project_id:'fenix-trading-lab',domain:'compute',command_template_id_or_ref:'GCP-READONLY-CATALOG:compute',principal_ref:'credential-ref://gcp-ro',result_status:'SUCCESS',evidence_ref:'evidence://gcp/resource',raw_payload_stored:false,secret_payload_present:false,resource_ref:'projects/fenix-trading-lab/zones/x/instances/a ',classification_status:'TRAINING'}; assert.throws(()=>validateGcpInventoryEnvelope(envelope(fullCoverage(),[r])),/canonical without edge whitespace/);});
