import test from 'node:test';
import assert from 'node:assert/strict';
import {expectedCoveragePairs,expectedTemplatesForDomain,validateGcpInventoryEnvelope} from '../runtime/gcp-live-inventory-validator-v0.mjs';
const SHA='3437a1938643dd9bab03c3b8dff9f9047a07767d',ts='2026-09-11T00:20:00Z';let seq=0;
function cr(project_id,domain,template,overrides={}){return {command_run_ref:`run-${seq++}`,catalog_blob_sha:SHA,command_template_id_or_ref:template,result_status:'EMPTY',captured_at:ts,principal_ref:'credential-ref://gcp-ro',evidence_ref:`evidence://gcp/${project_id}/${domain}/${seq}`,resolved_parameters:{PROJECT_ID:project_id},returned_resource_refs:[],...overrides};}
function coverage(project_id,domain,index){const req=expectedTemplatesForDomain(domain);let results;if(domain==='scheduler')results=[cr(project_id,domain,req[0],{result_status:'EMPTY',discovered_values:[]})];else results=req.map(t=>cr(project_id,domain,t));return {capture_id:`c-${index}`,record_kind:'COVERAGE',captured_at:ts,company_id:'fenix-capital',engine_id:'INT-001',environment:'SCAFFOLD',version:'1.0.0',project_id,domain,catalog_blob_sha:SHA,command_template_id_or_ref:req[0],principal_ref:'credential-ref://gcp-ro',result_status:'EMPTY',evidence_ref:`evidence://coverage/${project_id}/${domain}`,raw_payload_stored:false,secret_payload_present:false,resource_ref:'__DOMAIN__',classification_status:'UNCLASSIFIED',required_command_templates:req,command_results:results};}
function full(){seq=0;return expectedCoveragePairs().map(({project_id,domain},i)=>coverage(project_id,domain,i));}
function env(c=full(),r=[]){return JSON.stringify({coverage_records:c,resource_records:r});}
function resourceFrom(cov,src,ref,classification='TRAINING',overrides={}){return {capture_id:`r-${seq++}`,record_kind:'RESOURCE',captured_at:ts,company_id:'fenix-capital',engine_id:'INT-001',environment:'SCAFFOLD',version:'1.0.0',project_id:cov.project_id,domain:cov.domain,catalog_blob_sha:SHA,command_template_id_or_ref:src.command_template_id_or_ref,principal_ref:src.principal_ref,result_status:'SUCCESS',evidence_ref:src.evidence_ref,raw_payload_stored:false,secret_payload_present:false,resource_ref:ref,classification_status:classification,command_run_ref:src.command_run_ref,...overrides};}
test('accepts complete 4x19 empty inventory envelope',()=>{const out=validateGcpInventoryEnvelope(env());assert.equal(out.valid,true);assert.equal(out.coverage_pairs,76);assert.equal(out.logical_resources,0);});
test('preserves permission gaps with empty resource lists',()=>{const c=full();c[0].command_results[0].result_status='PERMISSION_DENIED';c[0].result_status='PERMISSION_DENIED';assert.doesNotThrow(()=>validateGcpInventoryEnvelope(env(c)));});
test('rejects SUCCESS with empty returned_resource_refs',()=>{const c=full();c[0].command_results[0].result_status='SUCCESS';c[0].result_status='SUCCESS';assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/SUCCESS requires returned resources/);});
test('rejects incorrect COVERAGE aggregate status',()=>{const c=full();c[0].command_results[0].result_status='ERROR';c[0].result_status='EMPTY';assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/aggregate mismatch/);});
test('rejects COVERAGE top-level template ref not bound to its domain results',()=>{const c=full();c[0].command_template_id_or_ref='GCP-READONLY-CATALOG@deadbeef:projects:0';assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/coverage command template mismatch/);});
test('rejects resolved parameters not present in pinned command template',()=>{const c=full();c[0].command_results[0].resolved_parameters.API_KEY='actual-secret-value';assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/keys must match template placeholders/);});
test('scheduler job expansion requires exact PROJECT_ID and LOCATION placeholders',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='scheduler'),[discoverRef,jobsRef]=cov.required_command_templates;const location='europe-west1';cov.command_results=[cr(cov.project_id,'scheduler',discoverRef,{result_status:'SUCCESS',returned_resource_refs:['locations/europe-west1'],discovered_values:[location]}),cr(cov.project_id,'scheduler',jobsRef,{result_status:'EMPTY',resolved_parameters:{PROJECT_ID:cov.project_id,LOCATION:location}})];cov.result_status='SUCCESS';const src=cov.command_results[0];assert.doesNotThrow(()=>validateGcpInventoryEnvelope(env(c,[resourceFrom(cov,src,'locations/europe-west1','OTHER')])));delete cov.command_results[1].resolved_parameters.LOCATION;assert.throws(()=>validateGcpInventoryEnvelope(env(c,[resourceFrom(cov,src,'locations/europe-west1','OTHER')])),/keys must match template placeholders/);});
test('aggregates SUCCESS over EMPTY when there are no failures',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='pubsub'),[a,b]=cov.command_results,ref='projects/fenix-trading-lab/topics/a';a.result_status='SUCCESS';a.returned_resource_refs=[ref];b.result_status='EMPTY';cov.result_status='SUCCESS';assert.doesNotThrow(()=>validateGcpInventoryEnvelope(env(c,[resourceFrom(cov,a,ref)])));});
test('failure dominates SUCCESS in COVERAGE aggregate',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='pubsub'),[a,b]=cov.command_results,ref='projects/fenix-trading-lab/topics/a';a.result_status='SUCCESS';a.returned_resource_refs=[ref];b.result_status='PERMISSION_DENIED';cov.result_status='PERMISSION_DENIED';assert.doesNotThrow(()=>validateGcpInventoryEnvelope(env(c,[resourceFrom(cov,a,ref)])));});
test('accepts exact RESOURCE source and permits multiple provenance runs for same logical resource',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='pubsub'),[a,b]=cov.command_results;const ref='projects/fenix-trading-lab/topics/a';a.result_status='SUCCESS';a.returned_resource_refs=[ref];b.result_status='SUCCESS';b.returned_resource_refs=[ref];cov.result_status='SUCCESS';const r1=resourceFrom(cov,a,ref),r2=resourceFrom(cov,b,ref);const out=validateGcpInventoryEnvelope(env(c,[r1,r2]));assert.equal(out.resource_observations,2);assert.equal(out.logical_resources,1);});
test('uses tuple-safe observation keys when refs contain delimiter sequences',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='pubsub'),[a,b]=cov.command_results;a.command_run_ref='c';b.command_run_ref='b::c';a.result_status='SUCCESS';b.result_status='SUCCESS';a.returned_resource_refs=['a::b'];b.returned_resource_refs=['a'];cov.result_status='SUCCESS';const out=validateGcpInventoryEnvelope(env(c,[resourceFrom(cov,a,'a::b'),resourceFrom(cov,b,'a')]));assert.equal(out.resource_observations,2);assert.equal(out.logical_resources,2);});
test('handles large returned resource sets with exact indexed matching',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='resource_consumers'),src=cov.command_results[0],refs=Array.from({length:1500},(_,i)=>`//asset.googleapis.com/projects/fenix-trading-lab/resources/${i}`);src.result_status='SUCCESS';src.returned_resource_refs=refs;cov.result_status='SUCCESS';const resources=refs.map(ref=>resourceFrom(cov,src,ref,'OTHER'));const out=validateGcpInventoryEnvelope(env(c,resources));assert.equal(out.resource_observations,1500);});
test('rejects contradictory classifications across provenance runs',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='pubsub'),[a,b]=cov.command_results;const ref='projects/fenix-trading-lab/topics/a';a.result_status='SUCCESS';a.returned_resource_refs=[ref];b.result_status='SUCCESS';b.returned_resource_refs=[ref];cov.result_status='SUCCESS';assert.throws(()=>validateGcpInventoryEnvelope(env(c,[resourceFrom(cov,a,ref,'TRAINING'),resourceFrom(cov,b,ref,'TRADING')])),/contradictory resource classification/);});
test('rejects RESOURCE status contradicting SUCCESS source',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='pubsub'),src=cov.command_results[0],ref='projects/fenix-trading-lab/topics/a';src.result_status='SUCCESS';src.returned_resource_refs=[ref];cov.result_status='SUCCESS';assert.throws(()=>validateGcpInventoryEnvelope(env(c,[resourceFrom(cov,src,ref,'TRAINING',{result_status:'ERROR'})])),/RESOURCE must be real SUCCESS/);});
test('rejects omitted RESOURCE for returned ref',()=>{const c=full(),cov=c.find(x=>x.project_id==='fenix-trading-lab'&&x.domain==='pubsub'),src=cov.command_results[0];src.result_status='SUCCESS';src.returned_resource_refs=['projects/fenix-trading-lab/topics/a'];cov.result_status='SUCCESS';assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/exactly match returned_resource_refs/);});
test('rejects duplicate global command_run_ref across coverage records',()=>{const c=full();c[1].command_results[0].command_run_ref=c[0].command_results[0].command_run_ref;assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/duplicate global command_run_ref/);});
test('rejects cross-project resolved PROJECT_ID',()=>{const c=full();c[0].command_results[0].resolved_parameters.PROJECT_ID='fenix-inmobiliaria';assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/PROJECT_ID mismatch/);});
test('rejects duplicate JSON keys',()=>assert.throws(()=>validateGcpInventoryEnvelope('{"coverage_records":[],"coverage_records":[],"resource_records":[]}'),/duplicate JSON object key/));
test('rejects impossible timestamps and raw secret-like refs',()=>{const c=full();c[0].captured_at='2026-02-31T22:00:00Z';assert.throws(()=>validateGcpInventoryEnvelope(env(c)),/invalid calendar\/time component/);const d=full();d[0].principal_ref='raw-secret';assert.throws(()=>validateGcpInventoryEnvelope(env(d)),/principal reference/);});
test('Trading remains mutation-isolated by output contract',()=>{const out=validateGcpInventoryEnvelope(env());assert.equal(out.execution_mode,'READ_ONLY_CAPTURE_ONLY');assert.equal(out.trading_mutation_forbidden,true);});
