import test from 'node:test';
import assert from 'node:assert/strict';
import {expectedCoveragePairs,expectedTemplatesForDomain,validateGcpInventoryEnvelope} from '../runtime/gcp-live-inventory-validator-v0.mjs';

const ts='2026-09-10T22:00:00Z';
let seq=0;
function commandResult(project_id,domain,template,overrides={}){return {command_run_ref:`run-${domain}-${seq++}`,command_template_id_or_ref:template,result_status:'EMPTY',captured_at:ts,principal_ref:'credential-ref://gcp-ro',evidence_ref:`evidence://gcp/${project_id}/${domain}/${template.split(':').at(-1)}`,resolved_parameters:{PROJECT_ID:project_id},...overrides};}
function coverageRecord(project_id,domain,index){
  const required=expectedTemplatesForDomain(domain); let results;
  if(domain==='scheduler'){
    results=[commandResult(project_id,domain,required[0],{discovered_values:['europe-west1','us-central1']}),commandResult(project_id,domain,required[1],{resolved_parameters:{PROJECT_ID:project_id,LOCATION:'europe-west1'}}),commandResult(project_id,domain,required[1],{resolved_parameters:{PROJECT_ID:project_id,LOCATION:'us-central1'}})];
  }else results=required.map((t)=>commandResult(project_id,domain,t));
  return {capture_id:`c-${index}`,record_kind:'COVERAGE',captured_at:ts,company_id:'fenix-capital',engine_id:'INT-001',environment:'SCAFFOLD',version:'1.0.0',project_id,domain,command_template_id_or_ref:`GCP-READONLY-CATALOG:${domain}`,principal_ref:'credential-ref://gcp-ro',result_status:'EMPTY',evidence_ref:`evidence://gcp/${project_id}/${domain}`,raw_payload_stored:false,secret_payload_present:false,resource_ref:'__DOMAIN__',classification_status:'UNCLASSIFIED',required_command_templates:required,command_results:results};
}
function fullCoverage(){seq=0; return expectedCoveragePairs().map(({project_id,domain},i)=>coverageRecord(project_id,domain,i));}
function envelope(c=fullCoverage(),r=[]){return JSON.stringify({coverage_records:c,resource_records:r});}

test('accepts complete 4x19 catalog-bound inventory envelope',()=>{const r=validateGcpInventoryEnvelope(envelope()); assert.equal(r.valid,true); assert.equal(r.coverage_pairs,76);});
test('rejects omitted canonical command template in multi-command domain',()=>{const c=fullCoverage(); const x=c.find((r)=>r.domain==='pubsub'); x.command_results.pop(); assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/requires exactly one result/);});
test('accepts zero scheduler expansions after empty discovery',()=>{const c=fullCoverage(); const s=c.find((r)=>r.domain==='scheduler'); const t=s.required_command_templates; s.command_results=[commandResult(s.project_id,'scheduler',t[0],{result_status:'EMPTY',discovered_values:[]})]; assert.doesNotThrow(()=>validateGcpInventoryEnvelope(envelope(c)));});
test('accepts zero scheduler expansions after permission denied discovery',()=>{const c=fullCoverage(); const s=c.find((r)=>r.domain==='scheduler'); const t=s.required_command_templates; s.command_results=[commandResult(s.project_id,'scheduler',t[0],{result_status:'PERMISSION_DENIED',discovered_values:[]})]; assert.doesNotThrow(()=>validateGcpInventoryEnvelope(envelope(c)));});
test('rejects scheduler expansion when no locations discovered',()=>{const c=fullCoverage(); const s=c.find((r)=>r.domain==='scheduler'); const t=s.required_command_templates; s.command_results=[commandResult(s.project_id,'scheduler',t[0],{discovered_values:[]}),commandResult(s.project_id,'scheduler',t[1],{resolved_parameters:{PROJECT_ID:s.project_id,LOCATION:'europe-west1'}})]; assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/must be zero/);});
test('rejects scheduler missing or duplicate discovered location expansion',()=>{const c=fullCoverage(); const s=c.find((r)=>r.domain==='scheduler'); s.command_results=s.command_results.filter((r)=>r.resolved_parameters.LOCATION!=='us-central1'); assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/exactly cover discovered locations/); const d=fullCoverage(); const sd=d.find((r)=>r.domain==='scheduler'); sd.command_results.push({...sd.command_results.at(-1),command_run_ref:'dup-location'}); assert.throws(()=>validateGcpInventoryEnvelope(envelope(d)),/duplicate LOCATION result/);});
test('non-scheduler command results do not require discovery-only fields',()=>{const c=fullCoverage(); const p=c.find((r)=>r.domain==='pubsub'); assert.equal(Object.hasOwn(p.command_results[0],'discovered_values'),false); assert.doesNotThrow(()=>validateGcpInventoryEnvelope(envelope(c)));});
test('rejects normalized impossible timestamps',()=>{for(const bad of ['2026-02-31T21:00:00Z','2026-01-01T24:00:00Z']){const c=fullCoverage(); c[0].captured_at=bad; assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/invalid calendar\/time component/);}});
test('rejects duplicate JSON members before parsing',()=>{assert.throws(()=>validateGcpInventoryEnvelope('{"coverage_records":[],"coverage_records":[],"resource_records":[]}'),/duplicate JSON object key/);});
test('resource must bind to exact canonical successful source template and matching evidence',()=>{const c=fullCoverage(); const target=c.find((r)=>r.project_id==='fenix-trading-lab'&&r.domain==='pubsub'); const src=target.command_results[0]; src.result_status='SUCCESS'; const base={capture_id:'r1',record_kind:'RESOURCE',captured_at:ts,company_id:'fenix-capital',engine_id:'INT-001',environment:'SCAFFOLD',version:'1.0.0',project_id:'fenix-trading-lab',domain:'pubsub',command_template_id_or_ref:src.command_template_id_or_ref,principal_ref:'credential-ref://gcp-ro',result_status:'SUCCESS',evidence_ref:src.evidence_ref,raw_payload_stored:false,secret_payload_present:false,resource_ref:'projects/fenix-trading-lab/topics/a',classification_status:'TRAINING'}; assert.doesNotThrow(()=>validateGcpInventoryEnvelope(envelope(c,[base]))); assert.throws(()=>validateGcpInventoryEnvelope(envelope(c,[{...base,command_template_id_or_ref:'GCP-READONLY-CATALOG:pubsub'}])),/canonical command template/); assert.throws(()=>validateGcpInventoryEnvelope(envelope(c,[{...base,evidence_ref:'evidence://unrelated'}])),/SUCCESS source command result/);});
test('rejects resource sourced from unsuccessful command result',()=>{for(const status of ['EMPTY','PERMISSION_DENIED','API_UNAVAILABLE','ERROR']){const c=fullCoverage(); const target=c.find((r)=>r.project_id==='fenix-trading-lab'&&r.domain==='pubsub'); const src=target.command_results[0]; src.result_status=status; const resource={capture_id:`r-${status}`,record_kind:'RESOURCE',captured_at:ts,company_id:'fenix-capital',engine_id:'INT-001',environment:'SCAFFOLD',version:'1.0.0',project_id:'fenix-trading-lab',domain:'pubsub',command_template_id_or_ref:src.command_template_id_or_ref,principal_ref:'credential-ref://gcp-ro',result_status:'SUCCESS',evidence_ref:src.evidence_ref,raw_payload_stored:false,secret_payload_present:false,resource_ref:`projects/fenix-trading-lab/topics/${status.toLowerCase()}`,classification_status:'TRAINING'}; assert.throws(()=>validateGcpInventoryEnvelope(envelope(c,[resource])),/SUCCESS source command result/);}});
test('rejects cross-project resolved parameters',()=>{const c=fullCoverage(); c[0].command_results[0].resolved_parameters.PROJECT_ID='fenix-trading-lab'===c[0].project_id?'fenix-inmobiliaria':'fenix-trading-lab'; assert.throws(()=>validateGcpInventoryEnvelope(envelope(c)),/must equal record.project_id/);});
