import test from 'node:test';import assert from 'node:assert/strict';import {planMarketingBootstrap} from '../bootstrap/marketing-bootstrap.mjs';
const base={context:{company_id:'fenix',engine_id:'MKTBOOT-001',environment:'SCAFFOLD',version:'0.1.0'},authorized:true,estimated_additional_cost_eur:0,requires_prod_write:false};
test('MKTBOOT-001 returns zero-cost read-only plan aligned with canonical graph',()=>{const r=planMarketingBootstrap(base);assert.equal(r.status,'PLAN_READY');assert.equal(r.mode,'READ_ONLY_BOOTSTRAP_PLAN');assert.deepEqual(r.prerequisites,['KBOOT-001','SEOBOOT-001','SOCBOOT-001']);assert.deepEqual(r.optional_enrichment,['BMD-001']);});
test('MKTBOOT-001 blocks cost',()=>{assert.equal(planMarketingBootstrap({...base,estimated_additional_cost_eur:1}).reason,'MONEY_LIMIT');});
test('MKTBOOT-001 blocks prod write',()=>{assert.equal(planMarketingBootstrap({...base,requires_prod_write:true}).reason,'HIGH_RISK');});
test('MKTBOOT-001 requires authorization',()=>{assert.equal(planMarketingBootstrap({...base,authorized:false}).reason,'POLICY_CONFLICT');});
test('MKTBOOT-001 rejects accessor context and malformed security inputs',()=>{const context={company_id:'fenix',environment:'SCAFFOLD',version:'0.1.0'};Object.defineProperty(context,'engine_id',{enumerable:true,get(){return 'MKTBOOT-001';}});assert.throws(()=>planMarketingBootstrap({...base,context}),/own data property/);assert.throws(()=>planMarketingBootstrap({...base,requires_prod_write:'true'}),/must be boolean/);});
test('MKTBOOT-001 rejects coerced cost values',()=>{for(const v of [null,false,'','0',[]])assert.throws(()=>planMarketingBootstrap({...base,estimated_additional_cost_eur:v}),/invalid cost/);});
test('MKTBOOT-001 deep-freezes validated snapshot and uses canonical escalation priority',()=>{const r=planMarketingBootstrap(base);assert.equal(Object.isFrozen(r.context),true);assert.equal(Object.isFrozen(r.prerequisites),true);assert.throws(()=>{r.context.company_id='other';});assert.equal(planMarketingBootstrap({...base,authorized:false,requires_prod_write:true,estimated_additional_cost_eur:2}).reason,'HIGH_RISK');assert.equal(planMarketingBootstrap({...base,authorized:false,estimated_additional_cost_eur:2}).reason,'MONEY_LIMIT');});
