import test from 'node:test';
import assert from 'node:assert/strict';
import {createPromotionPlan} from '../runtime/promotion-pipeline.mjs';
import {loadDomainPolicyRegistry,resolveDomainAutonomyPolicy,evaluateRegisteredDomainAdoption,runRegisteredDomainPreprodLoop,domainPolicyCoverage,RSI_DOMAIN_POLICY_REGISTRY_CONTRACT} from '../runtime/rsi-domain-policy-registry.mjs';

function candidate(engine_id='LRN-001',overrides={}){return {candidate_id:`cand:${engine_id}:v2`,company_id:'fenix',engine_id,environment:'PREPROD',candidate_version:'0.6.0',risk_class:'LOW',confidence:0.95,prod_authorized:false,prod_write_authorized:false,trading_access:false,additional_cost_eur:0,...overrides};}
function promotion(engine_id='LRN-001',overrides={}){return {...createPromotionPlan({company_id:'fenix',engine_id,environment:'PREPROD',version:'0.6.0',baseline_version:'0.5.0',candidate_version:'0.6.0',judge_decision:'PASS',tribunal_decision:'GREEN',rollback_ref:`rollback:${engine_id}:0.5.0`,rebuild_ref:`rebuild:${engine_id}:0.6.0`,post_metrics:{quality_score:{min:80}},canary_percent:5}),...overrides};}

test('registry loads explicit Fenix policies and whole-domain autonomy count stays bounded',()=>{const r=loadDomainPolicyRegistry();assert.equal(r.policy_count,10);assert.equal(r.autonomous_count,2);assert.equal(r.assisted_count,8);assert.equal(r.prod_authorized,false);assert.equal(r.prod_write_authorized,false);assert.equal(r.trading_access,false);assert.equal(r.additional_cost_eur,0);assert.equal(r.multicompany_continuation,false);});

test('coverage keeps only LRN and AUTO as whole-domain PREPROD autonomous',()=>{const c=domainPolicyCoverage();assert.deepEqual(c.autonomous_domains,['cerebro.learning.continuous_evolution','fenix.automation']);assert.equal(c.assisted_domains.includes('fenix.knowledge.notion'),true);assert.equal(c.assisted_domains.includes('fenix.seo'),true);assert.equal(c.default_unregistered_domain_decision,'HOLD');});

test('unregistered domain fails closed',()=>{const r=resolveDomainAutonomyPolicy({company_id:'fenix',engine_id:'LEAD-001',domain_id:'fenix.leads'});assert.equal(r.decision,'HOLD');assert.equal(r.reasons[0],'EXPLICIT_DOMAIN_POLICY_REQUIRED');assert.equal(r.prod_authorized,false);});

test('SEO remains ASSISTED and cannot enter B4',()=>{const e='SEO-001';const r=runRegisteredDomainPreprodLoop({company_id:'fenix',engine_id:e,domain_id:'fenix.seo',candidate:candidate(e),promotion_plan:promotion(e),shadow_evidence:{pass:true,evidence_refs:['seo:shadow'],additional_cost_eur:0},canary_evidence:{pass:true,evidence_refs:['seo:canary'],additional_cost_eur:0},observed_metrics:{quality_score:90},observed_at:'2026-10-09T06:00:00Z'});assert.equal(r.decision,'HOLD');assert.equal(r.loop_started,false);});

test('LRN and AUTO retain whole-domain PREPROD autonomy',()=>{for(const [e,d] of [['LRN-001','cerebro.learning.continuous_evolution'],['AUTO-001','fenix.automation']]){const r=evaluateRegisteredDomainAdoption({company_id:'fenix',engine_id:e,domain_id:d,candidate:candidate(e),promotion_plan:promotion(e)});assert.equal(r.decision,'ALLOW_PREPROD_CANARY');assert.equal(r.autonomy_mode,'PREPROD_AUTONOMOUS');}});

test('KNW-001 permits only READONLY_REVIEW_PREPARATION while whole domain remains ASSISTED',()=>{
  const e='KNW-001',d='fenix.knowledge.notion';
  const missing=evaluateRegisteredDomainAdoption({company_id:'fenix',engine_id:e,domain_id:d,candidate:candidate(e,{confidence:0.85}),promotion_plan:promotion(e)});assert.equal(missing.decision,'HOLD');assert.equal(missing.reasons[0],'EXPLICIT_CAPABILITY_REQUIRED');
  const denied=evaluateRegisteredDomainAdoption({company_id:'fenix',engine_id:e,domain_id:d,candidate:candidate(e,{confidence:0.85,requested_capability:'KNOWLEDGE_CLASSIFY_APPROVE'}),promotion_plan:promotion(e)});assert.equal(denied.decision,'HOLD');assert.equal(denied.reasons[0],'CAPABILITY_NOT_AUTONOMOUS');
  const allowed=evaluateRegisteredDomainAdoption({company_id:'fenix',engine_id:e,domain_id:d,candidate:candidate(e,{confidence:0.85,requested_capability:'READONLY_REVIEW_PREPARATION'}),promotion_plan:promotion(e)});assert.equal(allowed.decision,'ALLOW_PREPROD_CANARY');assert.equal(allowed.autonomy_mode,'PREPROD_AUTONOMOUS_CAPABILITY_SCOPED');assert.equal(allowed.domain_autonomy_mode,'ASSISTED');assert.deepEqual(allowed.allowed_capabilities,['READONLY_REVIEW_PREPARATION']);
  const loop=runRegisteredDomainPreprodLoop({company_id:'fenix',engine_id:e,domain_id:d,candidate:candidate(e,{confidence:0.85,requested_capability:'READONLY_REVIEW_PREPARATION'}),promotion_plan:promotion(e),shadow_evidence:{pass:true,evidence_refs:['knw:readonly-shadow'],additional_cost_eur:0},canary_evidence:{pass:true,evidence_refs:['knw:readonly-canary'],additional_cost_eur:0},observed_metrics:{quality_score:90},observed_at:'2026-10-09T08:30:00Z'});assert.equal(loop.loop_started,true);assert.equal(loop.decision,'KEEP_NONPROD_AND_RELEARN');assert.equal(loop.prod_authorized,false);assert.equal(loop.prod_write_authorized,false);assert.equal(loop.trading_access,false);
});

test('risk confidence and money boundaries remain canonical',()=>{const high=evaluateRegisteredDomainAdoption({company_id:'fenix',engine_id:'AUTO-001',domain_id:'fenix.automation',candidate:candidate('AUTO-001',{risk_class:'HIGH'}),promotion_plan:promotion('AUTO-001')});assert.equal(high.human_required,'HIGH_RISK');const low=evaluateRegisteredDomainAdoption({company_id:'fenix',engine_id:'AUTO-001',domain_id:'fenix.automation',candidate:candidate('AUTO-001',{confidence:0.5}),promotion_plan:promotion('AUTO-001')});assert.equal(low.human_required,'LOW_CONFIDENCE');const money=evaluateRegisteredDomainAdoption({company_id:'fenix',engine_id:'AUTO-001',domain_id:'fenix.automation',candidate:candidate('AUTO-001'),promotion_plan:{...promotion('AUTO-001'),additional_cost_budget_eur:1}});assert.equal(money.human_required,'MONEY_LIMIT');});

test('exact whole-domain autonomous set remains LRN plus AUTO only',()=>{const r=loadDomainPolicyRegistry();const ids=r.policies.filter(x=>x.autonomy_mode==='PREPROD_AUTONOMOUS').map(x=>x.engine_id).sort();assert.deepEqual(ids,['AUTO-001','LRN-001']);assert.equal(r.policies.find(x=>x.engine_id==='KNW-001').autonomy_mode,'ASSISTED');assert.equal(r.policies.find(x=>x.engine_id==='KNW-001').capability_autonomy_mode,'PREPROD_AUTONOMOUS');});

test('registry contract never grants PROD Trading or MULTIEMPRESA authority',()=>{assert.equal(RSI_DOMAIN_POLICY_REGISTRY_CONTRACT.environment,'PREPROD');assert.equal(RSI_DOMAIN_POLICY_REGISTRY_CONTRACT.prod_authorized,false);assert.equal(RSI_DOMAIN_POLICY_REGISTRY_CONTRACT.prod_write_authorized,false);assert.equal(RSI_DOMAIN_POLICY_REGISTRY_CONTRACT.trading_access,false);assert.equal(RSI_DOMAIN_POLICY_REGISTRY_CONTRACT.multicompany_continuation,false);assert.equal(RSI_DOMAIN_POLICY_REGISTRY_CONTRACT.additional_cost_target_eur,0);});
