import test from 'node:test';import assert from 'node:assert/strict';import {planSeoBootstrap} from '../bootstrap/seo-bootstrap.mjs';
const base={context:{company_id:'fenix',engine_id:'SEOBOOT-001',environment:'SCAFFOLD',version:'0.1.0'},authorized:true,estimated_additional_cost_eur:0,requires_prod_write:false};
test('SEOBOOT-001 returns zero-cost read-only plan aligned with canonical graph',()=>{const r=planSeoBootstrap(base);assert.equal(r.status,'PLAN_READY');assert.equal(r.mode,'READ_ONLY_BOOTSTRAP_PLAN');assert.equal(r.additional_cost_target_eur,0);assert.deepEqual(r.prerequisites,['KW-001','WAUD-001']);assert.deepEqual(r.optional_enrichment,['LOCALP-001','KBOOT-001']);});
test('SEOBOOT-001 blocks cost',()=>{assert.equal(planSeoBootstrap({...base,estimated_additional_cost_eur:1}).reason,'MONEY_LIMIT');});
test('SEOBOOT-001 blocks prod write',()=>{assert.equal(planSeoBootstrap({...base,requires_prod_write:true}).reason,'HIGH_RISK');});
test('SEOBOOT-001 requires authorization',()=>{assert.equal(planSeoBootstrap({...base,authorized:false}).reason,'POLICY_CONFLICT');});
test('SEOBOOT-001 rejects inherited authorization and malformed security flags',()=>{const inherited=Object.create({authorized:true});inherited.context=base.context;assert.throws(()=>planSeoBootstrap(inherited),/authorized required/);assert.throws(()=>planSeoBootstrap({...base,requires_prod_write:'true'}),/must be boolean/);});
test('SEOBOOT-001 rejects coerced cost values',()=>{for(const v of [null,false,'','0'])assert.throws(()=>planSeoBootstrap({...base,estimated_additional_cost_eur:v}),/invalid cost/);});
test('SEOBOOT-001 uses canonical escalation priority',()=>{assert.equal(planSeoBootstrap({...base,authorized:false,requires_prod_write:true,estimated_additional_cost_eur:2}).reason,'HIGH_RISK');assert.equal(planSeoBootstrap({...base,authorized:false,estimated_additional_cost_eur:2}).reason,'MONEY_LIMIT');});
