import test from 'node:test';import assert from 'node:assert/strict';import {planSocialBootstrap} from '../bootstrap/social-bootstrap.mjs';
const base={context:{company_id:'fenix',engine_id:'SOCBOOT-001',environment:'SCAFFOLD',version:'0.1.0'},authorized:true,estimated_additional_cost_eur:0,requires_prod_write:false};
test('SOCBOOT-001 returns zero-cost read-only plan aligned with canonical graph',()=>{const r=planSocialBootstrap(base);assert.equal(r.status,'PLAN_READY');assert.equal(r.mode,'READ_ONLY_BOOTSTRAP_PLAN');assert.deepEqual(r.prerequisites,['SOCAUD-001']);assert.deepEqual(r.optional_enrichment,['SCAN-001','KBOOT-001']);});
test('SOCBOOT-001 blocks cost',()=>{assert.equal(planSocialBootstrap({...base,estimated_additional_cost_eur:1}).reason,'MONEY_LIMIT');});
test('SOCBOOT-001 blocks prod write',()=>{assert.equal(planSocialBootstrap({...base,requires_prod_write:true}).reason,'HIGH_RISK');});
test('SOCBOOT-001 requires authorization',()=>{assert.equal(planSocialBootstrap({...base,authorized:false}).reason,'POLICY_CONFLICT');});
test('SOCBOOT-001 deep-freezes tenant context and arrays',()=>{const r=planSocialBootstrap(base);assert.equal(Object.isFrozen(r),true);assert.equal(Object.isFrozen(r.context),true);assert.equal(Object.isFrozen(r.prerequisites),true);assert.equal(Object.isFrozen(r.outputs),true);assert.throws(()=>{r.context.company_id='other';});assert.throws(()=>{r.prerequisites.push('X');});});
test('SOCBOOT-001 rejects inherited authorization malformed prod flags and coerced cost',()=>{const inherited=Object.create({authorized:true});inherited.context=base.context;assert.throws(()=>planSocialBootstrap(inherited),/authorized required/);assert.throws(()=>planSocialBootstrap({...base,requires_prod_write:'true'}),/must be boolean/);for(const v of [null,false,'','0'])assert.throws(()=>planSocialBootstrap({...base,estimated_additional_cost_eur:v}),/invalid cost/);});
test('SOCBOOT-001 uses canonical escalation priority',()=>{assert.equal(planSocialBootstrap({...base,authorized:false,requires_prod_write:true,estimated_additional_cost_eur:2}).reason,'HIGH_RISK');assert.equal(planSocialBootstrap({...base,authorized:false,estimated_additional_cost_eur:2}).reason,'MONEY_LIMIT');});
