import test from 'node:test';
import assert from 'node:assert/strict';
import {assessDocumentation} from '../platform/system-documentation-engine.mjs';
const context={company_id:'fenix',engine_id:'DOCS-001',environment:'PREPROD',version:'0.1.0'};
const artifacts={registry:'engine-registry.md',contracts:'contracts.md',dependency_map:'deps.md',runbook:'runbook.md',changelog:'changelog.md',backup:'backup.md',rebuild:'rebuild.md',autonomy_state:'autonomy.md'};
test('marks complete documentation without writing',()=>{const r=assessDocumentation({context,authorized:true,confidence:.95,artifacts});assert.equal(r.status,'DOCUMENTATION_COMPLETE');assert.equal(r.missing.length,0);assert.equal(r.autowrite_execute,false);assert.equal(r.executed,false);assert.equal(r.msp_compatible,true)});
test('reports missing and stale gaps independently',()=>{const x={...artifacts,runbook:'',backup:{ref:'backup.md',stale:true},rebuild:{ref:'rebuild.md',stale:false}};const r=assessDocumentation({context,authorized:true,confidence:.95,artifacts:x});assert.equal(r.status,'DOCUMENTATION_GAPS');assert.deepEqual(r.missing,['runbook']);assert.deepEqual(r.stale,['backup']);assert.equal(r.artifacts.backup.ref,'backup.md')});
test('fails closed for prod, malformed booleans and low confidence',()=>{assert.throws(()=>assessDocumentation({context:{...context,environment:'PROD'},authorized:true,confidence:.95,artifacts}),/UNSAFE_CONTEXT/);assert.throws(()=>assessDocumentation({context,authorized:'true',confidence:.95,artifacts}),/AUTHORIZED_BOOLEAN_REQUIRED/);assert.equal(assessDocumentation({context,authorized:true,confidence:.3,artifacts}).reason,'LOW_CONFIDENCE')});
test('rejects accessor-backed artifact descriptors without executing getters',()=>{let touched=false;const bad={};Object.defineProperty(bad,'ref',{enumerable:true,get(){touched=true;return 'x'}});assert.throws(()=>assessDocumentation({context,authorized:true,confidence:.95,artifacts:{...artifacts,backup:bad}}),/ACCESSOR_FORBIDDEN/);assert.equal(touched,false)});
