import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")??"",A=Deno.env.get("SUPABASE_ANON_KEY")??"",N=Deno.env.get("NOTION_TOKEN")??"";
const NV="2025-09-03",BUYER="ddc88cd8-b8a3-43d4-b34c-7e4a17670ffc",EXP="993423d0-8d3e-411e-bd2c-dceae3cb893b";
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-fenix-env":"PREPROD_TEST"};
const J=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
function plain(p:any):any{if(!p)return null;switch(p.type){case"title":return(p.title??[]).map((x:any)=>x.plain_text??"").join("");case"rich_text":return(p.rich_text??[]).map((x:any)=>x.plain_text??"").join("");case"select":return p.select?.name??null;case"number":return p.number??null;case"checkbox":return Boolean(p.checkbox);case"date":return p.date?.start??null;case"relation":return(p.relation??[]).map((x:any)=>x.id);default:return null}}
async function page(id:string){const r=await fetch(`https://api.notion.com/v1/pages/${id}`,{headers:{Authorization:`Bearer ${N}`,"Notion-Version":NV}});const b=await r.json().catch(()=>null);if(r.status===404)return null;if(!r.ok)throw new Error(`notion_page_${r.status}`);return b}
async function query(expedienteId:string){const r=await fetch(`https://api.notion.com/v1/data_sources/${BUYER}/query`,{method:"POST",headers:{Authorization:`Bearer ${N}`,"Notion-Version":NV,"Content-Type":"application/json"},body:JSON.stringify({page_size:100,filter:{property:"Expedientes",relation:{contains:expedienteId}}})});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(`notion_query_${r.status}`);return b?.results??[]}
function buyer(p:any){const x=p.properties??{};return{id:p.id,comprador:plain(x["Comprador"]),nombre:plain(x["Nombre"]),apellidos:plain(x["Apellidos"]),dni_nie:plain(x["DNI/NIE"]),fecha_nacimiento:plain(x["Fecha nacimiento"]),edad:plain(x["Edad"]),nacionalidad:plain(x["Nacionalidad"]),residencia:plain(x["Residencia"]),estado_civil:plain(x["Estado civil"]),regimen_matrimonial:plain(x["Régimen matrimonial"]),hijos:plain(x["Hijos"]),situacion_laboral:plain(x["Situación laboral"]),empresa_organismo:plain(x["Empresa / organismo"]),antiguedad_laboral:plain(x["Antigüedad laboral"]),sueldo_neto_mensual:plain(x["Sueldo neto mensual"]),numero_pagas:plain(x["Número de pagas"]),otros_ingresos_mensuales:plain(x["Otros ingresos mensuales"]),deudas_mensuales:plain(x["Deudas mensuales"]),tarjetas_otras_cuotas:plain(x["Tarjetas / otras cuotas"]),pension_paga:plain(x["Pensión paga"]),pension_recibe:plain(x["Pensión recibe"]),ahorro_disponible:plain(x["Ahorro disponible"]),origen_fondos:plain(x["Origen fondos"]),aportado_operacion:plain(x["Aportado operación"]),fondos_donados:plain(x["Fondos donados"]),documentacion_completa:plain(x["Documentación completa"]),documentos:plain(x["Documentos"]),revision_belen:plain(x["Revisión Belén"]),rol_operacion:plain(x["Rol en operación"]),orden_expediente:plain(x["Orden en expediente"]),datos_revisados_financiero:plain(x["Datos revisados por financiero"]),pais_residencia:plain(x["País residencia"]),pagas_prorrateadas:plain(x["Pagas prorrateadas"]),actualizado:p.last_edited_time,fuente:"Notion · Compradores · Fénix Capital"}}
Deno.serve(async(req:Request)=>{try{if(req.method!=="GET")return J({ok:false,error:"method_not_allowed"},405);if(!U||!A||!N)return J({ok:false,error:"config_missing"},500);const auth=req.headers.get("authorization")??"";if(!auth.toLowerCase().startsWith("bearer "))return J({ok:false,error:"unauthorized"},401);const ac=createClient(U,A,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const c=await ac.rpc("preprod_test_session_context");if(c.error)return J({ok:false,error:"context_error"},500);const ctx:any=c.data;if(!ctx?.actor_code||!["Direccion","Financiero"].includes(ctx.role))return J({ok:false,error:"forbidden"},403);const path=new URL(req.url).pathname,m=path.match(/\/expedientes\/([0-9a-fA-F-]{32,36})\/compradores$/);if(!m)return J({ok:false,error:"not_found"},404);const id=m[1],ep=await page(id);if(!ep)return J({ok:false,error:"not_found"},404);if((ep.parent?.data_source_id??ep.parent?.database_id)!==EXP)return J({ok:false,error:"not_an_expediente"},400);if(ctx.role!=="Direccion"&&plain(ep.properties?.["ID financiero operativo"])!==ctx.actor_code)return J({ok:false,error:"forbidden"},403);const rows=(await query(id)).map(buyer).sort((x:any,y:any)=>(Number(x.orden_expediente??999)-Number(y.orden_expediente??999))||String(x.comprador??"").localeCompare(String(y.comprador??""),"es"));const titulares=rows.filter((x:any)=>x.rol_operacion==="Titular comprador"||x.rol_operacion==="Titular + avalista").length,avalistas=rows.filter((x:any)=>x.rol_operacion==="Avalista"||x.rol_operacion==="Titular + avalista").length;return J({ok:true,source:"notion_canonical",count:rows.length,titulares,avalistas,items:rows});}catch(e){console.error(e);return J({ok:false,error:"expediente_people_exception"},500)}});
