const OWN=Object.prototype.hasOwnProperty;const SAFE_ENV=new Set(['SCAFFOLD','LAB','PREPROD']);
function req(v,l){if(typeof v!=='string'||!v.trim())throw new Error(`${l} required`);return v.trim();}
function ctxOf(i){const c=i?.context;if(!c||typeof c!=='object'||Array.isArray(c))throw new Error('context required');const d=Object.getOwnPropertyDescriptors(c);for(const k of ['company_id','engine_id','environment','version']){if(!OWN.call(d,k)||d[k].get||d[k].set)throw new Error(`context.${k} must be own data`);}const s=Object.freeze({company_id:req(d.company_id.value,'company_id'),engine_id:req(d.engine_id.value,'engine_id'),environment:req(d.environment.value,'environment'),version:req(d.version.value,'version')});if(s.engine_id!=='SALE-001')throw new Error('engine_id must be SALE-001');if(!SAFE_ENV.has(s.environment))throw new Error('unsafe environment');return s;}
function ownBool(i,k,def=false){if(!OWN.call(i,k))return def;if(typeof i[k]!=='boolean')throw new Error(`${k} must be boolean`);return i[k];}
function ownCost(i,k){if(!OWN.call(i,k))return 0;const v=i[k];if(typeof v!=='number'||!Number.isFinite(v)||v<0)throw new Error(`${k} invalid`);return v;}
function n(v,l,min,max){if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)throw new Error(`${l} invalid`);return v;}
function unique(a,l){if(!Array.isArray(a)||a.length===0)throw new Error(`${l} required`);return Object.freeze([...new Set(a.map(v=>req(v,l)))]);}
function human(reason,ctx){return Object.freeze({status:'HUMAN_REQUIRED',reason,context:ctx,executed:false});}
export function planSale(i={}){const context=ctxOf(i),authorized=ownBool(i,'authorized',false),prodWrite=ownBool(i,'requires_prod_write',false),cost=ownCost(i,'estimated_additional_cost_eur');if(prodWrite)return human('HIGH_RISK',context);if(cost>0)return human('MONEY_LIMIT',context);if(!authorized)return human('POLICY_CONFLICT',context);const leadProbability=n(i.lead_probability,'lead_probability',0,1),confidence=n(i.confidence,'confidence',0,1);if(confidence<0.6)return human('LOW_CONFIDENCE',context);const evidence=unique(i.evidence_refs,'evidence_refs');const stage=req(i.stage,'stage').toUpperCase();const allowed=new Set(['NEW','CONTACTED','QUALIFIED','PROPOSAL','NEGOTIATION','WON','LOST']);if(!allowed.has(stage))throw new Error('invalid stage');let next_action='REVIEW';if(stage==='NEW')next_action=leadProbability>=0.75?'CONTACT_NOW':'CONTACT_TODAY';else if(stage==='CONTACTED')next_action='QUALIFY';else if(stage==='QUALIFIED')next_action='PREPARE_PROPOSAL';else if(stage==='PROPOSAL')next_action='FOLLOW_UP';else if(stage==='NEGOTIATION')next_action='HANDLE_OBJECTION';else if(stage==='WON')next_action='HANDOFF_OPERATION';else if(stage==='LOST')next_action='CAPTURE_LOSS_REASON';return Object.freeze({status:'SALES_PLAN_READY',engine_id:'SALE-001',context,opportunity_ref:req(i.opportunity_ref,'opportunity_ref'),stage,lead_probability:leadProbability,next_action,cadence:stage==='NEW'||stage==='CONTACTED'?Object.freeze(['T0','T+1D','T+3D']):Object.freeze(['T0','T+2D']),objection_playbook_required:stage==='NEGOTIATION',evidence_refs:evidence,mode:'PLAN_ONLY',executed:false,prod_writes:false,trading_access:false,additional_cost_target_eur:0,learning_event:'SALE_OUTCOME_RECORDED_ONLY_AFTER_RESULT'});}
