import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const ALLOWED=new Set(['https://app.fenixcapital.es']);
function key(raw:string){try{const x=JSON.parse(raw||'{}');return String((x as any)?.default??Object.values(x??{})[0]??'')}catch{return ''}}
function cfg(){return{url:Deno.env.get('SUPABASE_URL')??'',anon:Deno.env.get('SUPABASE_ANON_KEY')||key(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')??''),service:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||key(Deno.env.get('SUPABASE_SECRET_KEYS')??'')}}
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ALLOWED.has(o)?o:'https://app.fenixcapital.es','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Vary':'Origin','x-fenix-env':'PROD'}}
function out(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function me(req:Request){const c=cfg(),h=req.headers.get('authorization')||'';if(!c.url||!c.anon||!c.service||!h.startsWith('Bearer '))return null;const auth=createClient(c.url,c.anon,{auth:{persistSession:false,autoRefreshToken:false}}),svc=createClient(c.url,c.service,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await auth.auth.getUser(h.slice(7));if(error||!data.user)return null;const {data:ctx,error:ce}=await svc.rpc('fenix_prod_actor_context_by_auth_server',{p_auth_user_id:data.user.id});if(ce||!ctx?.ok)return null;return{svc,actor:ctx.actor_code,role:ctx.role}}
function path(req:Request){return new URL(req.url).pathname.replace(/^\/(?:functions\/v1\/)?fenix-special-cases-api/,'')||'/'}
function kind(s:string){return s==='herencias'?'herencia':s==='obras-nuevas'?'obra_nueva':null}
function status(r:any){return Number(r?.status)||200}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const id=await me(req);if(!id)return out(req,{ok:false,status:401,error:'unauthorized'},401);const p=path(req),parts=p.split('/').filter(Boolean),k=kind(parts[0]||'');if(!k)return out(req,{ok:false,status:404,error:'not_found'},404);try{if(req.method==='GET'&&parts.length===1){const {data,error}=await id.svc.rpc('fenix_prod_special_case_list_server',{p_actor_code:id.actor,p_case_type:k});if(error)throw error;return out(req,data,status(data))}if(req.method==='GET'&&parts.length===2){const {data,error}=await id.svc.rpc('fenix_prod_special_case_get_server',{p_actor_code:id.actor,p_case_code:decodeURIComponent(parts[1])});if(error)throw error;return out(req,data,status(data))}let b:any={};try{b=await req.json()}catch{}if(req.method==='POST'&&parts.length===1){const {data,error}=await id.svc.rpc('fenix_prod_special_case_create_with_people_server',{p_actor_code:id.actor,p_case_type:k,p_nombre:String(b.nombre||''),p_estado:b.estado||'Nueva',p_fase:b.fase||'Entrada',p_siguiente_accion:b.siguiente_accion||null,p_people:Array.isArray(b.intervinientes)?b.intervinientes:[]});if(error)throw error;return out(req,data,status(data))}if(req.method==='PATCH'&&parts.length===2){const {data,error}=await id.svc.rpc('fenix_prod_special_case_update_server',{p_actor_code:id.actor,p_case_code:decodeURIComponent(parts[1]),p_expected_version:b.expected_version??null,p_estado:b.estado??null,p_fase:b.fase??null,p_siguiente_accion:b.siguiente_accion??null,p_notas:b.notas??null,p_bloqueo:b.bloqueo??null,p_requiere_validacion:b.requiere_validacion??null});if(error)throw error;return out(req,data,status(data))}return out(req,{ok:false,status:405,error:'method_not_allowed'},405)}catch(e){console.error(e);return out(req,{ok:false,status:500,error:'special_case_backend_error'},500)}});
