const OWN=Object.prototype.hasOwnProperty;
const TARGETS=new Set(['DR-001','RBLD-001','BCP-001']);
const GATE_KEYS=Object.freeze(['backup_snapshot','restore_test','rollback_test','rebuild_test','dependency_map','current_contract','observability','audit']);
const req=(v,l)=>{if(typeof v!=='string'||!v.trim())throw new Error(`${l} required`);return v.trim()};
function plain(v,l){if(!v||Object.getPrototypeOf(v)!==Object.prototype)throw new Error(`${l} plain object required`);for(const [k,d] of Object.entries(Object.getOwnPropertyDescriptors(v)))if(d.get||d.set)throw new Error(`${l}.${k} accessors forbidden`);return v;}
function bool(v,l,def=false){if(v===undefined)return def;if(typeof v!=='boolean')throw new Error(`${l} boolean required`);return v;}
function human(reason,context){return Object.freeze({status:'HUMAN_REQUIRED',reason,ready:false,context,prod_promotion:false});}
function cost(i){if(!OWN.call(i,'additional_cost_eur'))return 0;const v=i.additional_cost_eur;if(typeof v!=='number'||!Number.isFinite(v)||v<0)throw new Error('additional_cost_eur invalid');return v;}
export function evaluateResilienceGate(i={}){plain(i,'input');const raw=plain(i.context??{},'context');for(const k of ['company_id','engine_id','environment','version'])if(!OWN.call(raw,k))throw new Error(`context.${k} required`);const c=Object.freeze({company_id:req(raw.company_id,'context.company_id'),engine_id:req(raw.engine_id,'context.engine_id'),environment:req(raw.environment,'context.environment'),version:req(raw.version,'context.version')});if(!TARGETS.has(c.engine_id))throw new Error('unsupported resilience engine');if(c.environment!=='PREPROD')return human('HIGH_RISK',c);if(bool(i.trading,'trading',false))return human('POLICY_CONFLICT',c);if(cost(i)>0)return human('MONEY_LIMIT',c);const gates={};for(const k of GATE_KEYS)gates[k]=bool(i[k],k,false);const missing=GATE_KEYS.filter(k=>gates[k]!==true);if(missing.length)return Object.freeze({status:'BLOCKED',reason:'POLICY_CONFLICT',ready:false,context:c,missing:Object.freeze(missing),prod_promotion:false});return Object.freeze({status:'RESILIENCE_READY',ready:true,company_id:c.company_id,engine_id:c.engine_id,environment:c.environment,coverage:Object.freeze(['DR-001','RBLD-001','BCP-001']),dr_ready:true,rebuild_ready:true,bcp_ready:true,prod_promotion:false,live_evidence:false,prod_autonomy:false,audit_required:true,gates:Object.freeze(gates),additional_cost_eur:0})}
