#!/usr/bin/env python3
"""FACT-001 · CEREBRO Engine Factory V0.

Zero-dependency, filesystem-only generator. It NEVER deploys, calls PROD, changes
permissions, or creates infrastructure. Its job is to generate deterministic
engine scaffolds and register them locally in the Engine Registry.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
import tempfile
from types import SimpleNamespace
from typing import Any

FACTORY_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = FACTORY_ROOT / "registry" / "engine-registry.json"
ENGINE_ID_RE = re.compile(r"^[A-Z][A-Z0-9-]{2,63}$")
VALID_ENV = {"LOCAL", "LAB", "DEV", "PREPROD", "PROD"}
VALID_SCOPE = {"GLOBAL_ONLY", "GLOBAL_OR_SCOPED", "COMPANY_SCOPED"}

HUMAN_EXCEPTION_CODES = [
    "LEGAL_REQUIRED", "SIGNATURE_REQUIRED", "LOW_CONFIDENCE", "HIGH_RISK",
    "POLICY_CONFLICT", "SECURITY_INCIDENT", "MONEY_LIMIT", "CUSTOMER_HUMAN_REQUEST",
]
SYSTEM_BLOCKER_CODES = [
    "MISSING_CREDENTIAL", "EXPIRED_OR_REVOKED_CREDENTIAL", "MFA_REQUIRED",
    "PERMISSION_REQUIRED", "IRREVERSIBLE_PROD_RISK",
]


def load_json(path: pathlib.Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def dump_json(data: Any) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def atomic_write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as fh:
        fh.write(content)
        tmp = pathlib.Path(fh.name)
    tmp.replace(path)


def normalize_id(engine_id: str) -> str:
    value = engine_id.strip().upper()
    if not ENGINE_ID_RE.fullmatch(value):
        raise ValueError("engine_id must match ^[A-Z][A-Z0-9-]{2,63}$")
    return value


def validate_definition(args: argparse.Namespace | SimpleNamespace) -> None:
    args.engine_id = normalize_id(args.engine_id)
    if args.environment not in VALID_ENV:
        raise ValueError(f"invalid environment: {args.environment}")
    if args.company_scope not in VALID_SCOPE:
        raise ValueError(f"invalid company_scope: {args.company_scope}")
    if args.company_scope == "COMPANY_SCOPED" and not args.company_id:
        raise ValueError("COMPANY_SCOPED requires --company-id/company_id")


def build_manifest(args: argparse.Namespace | SimpleNamespace) -> dict[str, Any]:
    company_id = args.company_id
    if args.company_scope == "COMPANY_SCOPED" and not company_id:
        raise ValueError("COMPANY_SCOPED requires --company-id/company_id")
    if args.company_scope == "GLOBAL_ONLY":
        company_id = None

    dependencies = sorted({normalize_id(x) for x in getattr(args, "dependencies", [])})
    if args.engine_id in dependencies:
        raise ValueError(f"{args.engine_id} cannot depend on itself")

    return {
        "engine_id": args.engine_id,
        "name": args.name,
        "layer": args.layer,
        "company_scope": args.company_scope,
        "company_id": company_id,
        "environment": args.environment,
        "version": "0.1.0",
        "contract_version": "0.2.0",
        "status": "DEFINED_NOT_BUILT",
        "objective": args.objective,
        "owner": args.owner,
        "inputs": [],
        "outputs": [],
        "knowledge_sources": [],
        "data_contracts": [],
        "api_contract": [],
        "permissions": [],
        "policies": ["deterministic_before_AI", "zero_new_cost_by_default", "preserve_existing_contracts"],
        "events_in": [],
        "events_out": [],
        "jobs": [],
        "tests": ["tests/test_contract.py"],
        "evaluation": ["eval/README.md"],
        "tribunal": ["tribunal/README.md"],
        "observability": ["observability/README.md"],
        "retry_timeout": {"declared": False},
        "cost_budget": {"additional_monthly_eur_target": 0},
        "backup": {"strategy": "declare-before-preprod", "verified": False},
        "rollback": {"strategy": "declare-before-preprod", "verified": False},
        "rebuild": {"strategy": "manifest+git", "verified": False},
        "dependencies": dependencies,
        "dependents": [],
        "autonomy_level": "NONE_UNTIL_GATES_PASS",
        "zero_cost_execution_plan": ["existing_stack", "deterministic_code", "open_source_local"],
        "human_exception_codes": HUMAN_EXCEPTION_CODES,
        "system_blocker_codes": SYSTEM_BLOCKER_CODES,
        "evidence": [],
        "factory": {"generator": "FACT-001", "generator_version": "0.3.0"},
    }


def scaffold_files(manifest: dict[str, Any]) -> dict[str, str]:
    eid = manifest["engine_id"]
    return {
        "engine.manifest.json": dump_json(manifest),
        "README.md": f"# {eid} · {manifest['name']}\n\nGenerated by FACT-001 V0.\n\nStatus: `{manifest['status']}`.\nEnvironment: `{manifest['environment']}`.\n\nThis scaffold is inert until contracts, tests, evaluation, tribunal, backup, rollback and PREPROD gates are verified.\n",
        "config/config.example.json": dump_json({"engine_id": eid, "environment": manifest["environment"], "secrets": "EXTERNAL_ONLY"}),
        "contracts/data-contracts.json": dump_json({"engine_id": eid, "contracts": []}),
        "contracts/api-contract.json": dump_json({"engine_id": eid, "handlers": []}),
        "contracts/events.json": dump_json({"engine_id": eid, "events_in": [], "events_out": []}),
        "contracts/permissions.json": dump_json({"engine_id": eid, "permissions": [], "default": "DENY"}),
        "contracts/policies.json": dump_json({"engine_id": eid, "policies": manifest["policies"]}),
        "jobs/jobs.json": dump_json({"engine_id": eid, "jobs": []}),
        "tests/test_contract.py": "def test_scaffold_is_inert():\n    assert True\n",
        "eval/README.md": "# Evaluation\n\nDefine deterministic checks first; semantic judges only when necessary.\n",
        "tribunal/README.md": "# Tribunal\n\nPromotion verdict is DENY by default. Require contracts, permissions, tests, evaluation, observability, rollback, backup, rebuild, measured cost, policy and PREPROD evidence before PASS.\n",
        "observability/README.md": "# Observability\n\nDeclare health, logs, metrics, alerts and audit evidence before PREPROD promotion.\n",
        "ops/BACKUP.md": "# Backup\n\nNot verified yet. Must be proven before promotion.\n",
        "ops/ROLLBACK.md": "# Rollback\n\nNot verified yet. Must be rehearsed before promotion.\n",
        "ops/REBUILD.md": "# Rebuild\n\nSource: Git + engine.manifest.json. Rebuild proof pending.\n",
        "training/README.md": "# Training hooks\n\nTraining/LAB cannot promote directly to PROD.\n",
        "CHANGELOG.md": "# Changelog\n\n## 0.3.0\n- Scaffold generated by FACT-001 V0 with explicit dependencies, tribunal hook and canonical exception semantics.\n",
    }


def registry_entry(manifest: dict[str, Any], manifest_rel: str) -> dict[str, Any]:
    return {
        "engine_id": manifest["engine_id"],
        "manifest": manifest_rel,
        "status": manifest["status"],
        "source_of_truth": "git",
        "environment": manifest["environment"],
        "company_id": manifest["company_id"],
        "version": manifest["version"],
    }


def load_registry(registry_path: pathlib.Path, environment: str) -> dict[str, Any]:
    if registry_path.exists():
        return load_json(registry_path)
    return {"registry_version": "0.1.0", "environment": environment, "engines": []}


def existing_state(root: pathlib.Path, registry: dict[str, Any], manifest: dict[str, Any]) -> str:
    eid = manifest["engine_id"]
    target = root / "generated" / eid
    matches = [e for e in registry.get("engines", []) if e.get("engine_id") == eid]
    existing_manifest_path = target / "engine.manifest.json"
    if not matches and not existing_manifest_path.exists():
        return "CREATE"
    if len(matches) == 1 and existing_manifest_path.exists() and load_json(existing_manifest_path) == manifest:
        return "NO_CHANGE"
    return "CONFLICT"


def command_create(args: argparse.Namespace) -> int:
    args.dependencies = args.depends_on or []
    validate_definition(args)

    root = pathlib.Path(args.root).resolve() if args.root else FACTORY_ROOT
    registry_path = pathlib.Path(args.registry).resolve() if args.registry else root / "registry" / "engine-registry.json"
    target = root / "generated" / args.engine_id
    manifest = build_manifest(args)
    files = scaffold_files(manifest)
    registry = load_registry(registry_path, args.environment)
    state = existing_state(root, registry, manifest)

    if state == "NO_CHANGE":
        print(f"NO_CHANGE: {args.engine_id} already exists with identical manifest")
        return 0
    if state == "CONFLICT":
        print(f"CONFLICT: {args.engine_id} already exists; refusing overwrite. Use a versioned update workflow.", file=sys.stderr)
        return 3

    planned = sorted(str((target / rel).relative_to(root)) for rel in files)
    if args.plan:
        print(dump_json({"action": "create", "engine_id": args.engine_id, "files": planned, "registry": str(registry_path)}), end="")
        return 0

    for rel, content in files.items():
        atomic_write(target / rel, content)

    manifest_rel = pathlib.Path("..") / "generated" / args.engine_id / "engine.manifest.json"
    registry.setdefault("engines", []).append(registry_entry(manifest, manifest_rel.as_posix()))
    registry["engines"] = sorted(registry["engines"], key=lambda x: x["engine_id"])
    atomic_write(registry_path, dump_json(registry))
    print(f"CREATED: {args.engine_id} ({len(files)} files) and registered without deployment")
    return 0


def family_definition(item: dict[str, Any], defaults: dict[str, Any]) -> SimpleNamespace:
    merged = dict(defaults)
    merged.update(item)
    required = ["engine_id", "name", "layer", "objective"]
    missing = [key for key in required if not merged.get(key)]
    if missing:
        raise ValueError(f"family engine missing fields {missing}")
    ns = SimpleNamespace(
        engine_id=merged["engine_id"],
        name=merged["name"],
        layer=merged["layer"],
        objective=merged["objective"],
        company_scope=merged.get("company_scope", "GLOBAL_OR_SCOPED"),
        company_id=merged.get("company_id"),
        environment=merged.get("environment", "PREPROD"),
        owner=merged.get("owner"),
        dependencies=merged.get("dependencies", []),
    )
    validate_definition(ns)
    return ns


def command_family(args: argparse.Namespace) -> int:
    family_path = pathlib.Path(args.file).resolve()
    spec = load_json(family_path)
    family_id = spec.get("family_id")
    engines = spec.get("engines")
    if not family_id or not isinstance(engines, list) or not engines:
        raise ValueError("family spec requires family_id and non-empty engines list")

    defaults = spec.get("defaults", {})
    definitions = [family_definition(item, defaults) for item in engines]
    ids = [d.engine_id for d in definitions]
    duplicates = sorted({eid for eid in ids if ids.count(eid) > 1})
    if duplicates:
        raise ValueError(f"duplicate engine ids in family: {duplicates}")

    root = pathlib.Path(args.root).resolve() if args.root else FACTORY_ROOT
    environment = definitions[0].environment
    registry_path = pathlib.Path(args.registry).resolve() if args.registry else root / "registry" / "engine-registry.json"
    registry = load_registry(registry_path, environment)

    prepared: list[tuple[SimpleNamespace, dict[str, Any], dict[str, str], str]] = []
    conflicts: list[str] = []
    created: list[str] = []
    unchanged: list[str] = []
    all_ids = set(ids)
    registry_ids = {e.get("engine_id") for e in registry.get("engines", [])}

    for definition in definitions:
        manifest = build_manifest(definition)
        unknown_family_dependencies = [d for d in manifest["dependencies"] if d not in all_ids and d not in registry_ids]
        if unknown_family_dependencies and args.require_known_dependencies:
            raise ValueError(f"{definition.engine_id} has unknown dependencies: {unknown_family_dependencies}")
        files = scaffold_files(manifest)
        state = existing_state(root, registry, manifest)
        prepared.append((definition, manifest, files, state))
        if state == "CONFLICT":
            conflicts.append(definition.engine_id)
        elif state == "CREATE":
            created.append(definition.engine_id)
        else:
            unchanged.append(definition.engine_id)

    if conflicts:
        print(f"CONFLICT: family {family_id} contains existing non-identical engines {sorted(conflicts)}; no files written.", file=sys.stderr)
        return 3

    plan = {
        "action": "family_create",
        "family_id": family_id,
        "engine_count": len(definitions),
        "create": sorted(created),
        "no_change": sorted(unchanged),
        "registry": str(registry_path),
        "deployment": "NONE",
    }
    if args.plan:
        print(dump_json(plan), end="")
        return 0

    for definition, manifest, files, state in prepared:
        if state != "CREATE":
            continue
        target = root / "generated" / definition.engine_id
        for rel, content in files.items():
            atomic_write(target / rel, content)
        manifest_rel = pathlib.Path("..") / "generated" / definition.engine_id / "engine.manifest.json"
        registry.setdefault("engines", []).append(registry_entry(manifest, manifest_rel.as_posix()))

    registry["engines"] = sorted(registry.get("engines", []), key=lambda x: x["engine_id"])
    atomic_write(registry_path, dump_json(registry))
    print(dump_json({**plan, "result": "CREATED" if created else "NO_CHANGE"}), end="")
    return 0


def command_status(args: argparse.Namespace) -> int:
    registry_path = pathlib.Path(args.registry).resolve() if args.registry else DEFAULT_REGISTRY
    registry = load_json(registry_path)
    ids = [e.get("engine_id") for e in registry.get("engines", [])]
    duplicates = sorted({x for x in ids if ids.count(x) > 1})
    result = {
        "registry": str(registry_path),
        "engine_count": len(ids),
        "duplicate_engine_ids": duplicates,
        "green": not duplicates,
    }
    print(dump_json(result), end="")
    return 0 if result["green"] else 2


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="factory", description="FACT-001 · CEREBRO Engine Factory V0")
    sub = p.add_subparsers(dest="command", required=True)

    c = sub.add_parser("create", help="Generate an inert, registered engine scaffold")
    c.add_argument("--engine-id", required=True)
    c.add_argument("--name", required=True)
    c.add_argument("--layer", required=True)
    c.add_argument("--objective", required=True)
    c.add_argument("--company-scope", choices=sorted(VALID_SCOPE), default="GLOBAL_OR_SCOPED")
    c.add_argument("--company-id")
    c.add_argument("--environment", choices=sorted(VALID_ENV), default="PREPROD")
    c.add_argument("--owner")
    c.add_argument("--depends-on", action="append", default=[])
    c.add_argument("--root", help="Factory root override; used by tests and isolated generation")
    c.add_argument("--registry", help="Registry path override")
    c.add_argument("--plan", action="store_true", help="Show deterministic plan without writing")
    c.set_defaults(func=command_create)

    f = sub.add_parser("family", help="Atomically generate/register an engine family from JSON")
    f.add_argument("--file", required=True, help="Canonical family JSON specification")
    f.add_argument("--root", help="Factory root override; used by tests and isolated generation")
    f.add_argument("--registry", help="Registry path override")
    f.add_argument("--plan", action="store_true", help="Preflight family without writing")
    f.add_argument("--require-known-dependencies", action="store_true", help="Reject dependencies absent from family or current registry")
    f.set_defaults(func=command_family)

    s = sub.add_parser("status", help="Check Registry uniqueness")
    s.add_argument("--registry")
    s.set_defaults(func=command_status)
    return p


def main() -> int:
    args = parser().parse_args()
    try:
        return args.func(args)
    except (ValueError, KeyError, json.JSONDecodeError, OSError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
