import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")??"",A=Deno.env.get("SUPABASE_ANON_KEY")??"",S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",N=Deno.env.get("NOTION_TOKEN")??"";
const DOC_DS="34037d5e-21e8-4221-b020-b0e6e1a5a14f",NV="2025-09-03";
const ALLOWED=new Set(["https://carlosjmunoz78.github.io","https://app.fenixcapital.es"]);
const ORIGINS=new Set(["contacto","expediente","firma","inmobiliaria","tasacion","tarea","documento","contacto_b2b","banco","notaria","registro","herencia","obra_nueva"]);
const EVIDENCE=new Set(["expediente","inmobiliaria","tarea","tasacion","firma"]);
function hdr(req:Request){const o=req.headers.get("origin")||"";return{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-fenix-env":"PREPROD_TEST","Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://carlosjmunoz78.github.io","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
const out=(req:Request,d:unknown,status=200)=>new Response(JSON.stringify(d),{status,headers:hdr(req)});
function route(req:Request){const raw=new URL(req.url).pathname,m=raw.match(/fenix-document-intelligence(?:-test)?/);return !m||m.index==null?raw:(raw.slice(m.index+m[0].length)||"/")}
function str(v:unknown,max=500){return typeof v==="string"?v.trim().slice(0,max):""}
function iso(v:unknown){const x=str(v,10);return /^\d{4}-\d{2}-\d{2}$/.test(x)?x:null}
function fields(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))return{};const o:Record<string,string|number|boolean>={};for(const[k,val]of Object.entries(v as Record<string,unknown>).slice(0,50)){const key=String(k).replace(/[^a-zA-Z0-9_áéíóúüñÁÉÍÓÚÜÑ-]/g,"_").slice(0,80);if(typeof val==="string"&&val.trim())o[key]=val.trim().slice(0,1000);else if(typeof val==="number"&&Number.isFinite(val))o[key]=val;else if(typeof val==="boolean")o[key]=val}return o}
function statusOf(r:any,fallback=403){const n=Number(r?.status);return Number.isInteger(n)&&n>=400&&n<=599?n:fallback}
async function store(pageId:string,payload:Record<string,unknown>){if(!N||!/^[0-9a-fA-F-]{32,36}$/.test(pageId))return{ok:false,error:"notion_unavailable"};const g=await fetch(`https://api.notion.com/v1/pages/${pageId}`,{headers:{Authorization:`Bearer ${N}`,"Notion-Version":NV}}),p:any=await g.json().catch(()=>null);if(!g.ok||!p)return{ok:false,error:"document_not_found"};if((p.parent?.data_source_id??p.parent?.database_id)!==DOC_DS)return{ok:false,error:"document_scope_mismatch"};const note=`[CEREBRO · LECTURA DOCUMENTAL]\n${JSON.stringify(payload)}`.slice(0,1950);const w=await fetch(`https://api.notion.com/v1/pages/${pageId}`,{method:"PATCH",headers:{Authorization:`Bearer ${N}`,"Notion-Version":NV,"Content-Type":"application/json"},body:JSON.stringify({properties:{Notas:{rich_text:[{type:"text",text:{content:note}}]}}})});return w.ok?{ok:true}:{ok:false,error:`notion_patch_${w.status}`}}
async function authorizeGeneric(svc:any,ctx:any,t:string,c:string){const role=String(ctx?.role??"");if(EVIDENCE.has(t)){const{data,error}=await svc.rpc("preprod_test_evidence_scope_server",{p_actor_code:ctx.actor_code,p_origin_type:t,p_origin_code:c});if(error)return{ok:false,status:500,error:"scope_check_failed"};return data?.ok?{ok:true}:{ok:false,status:statusOf(data),error:data?.error??"forbidden"}}if(t==="documento"){const{data,error}=await svc.rpc("preprod_test_document_access_server",{p_actor_code:ctx.actor_code,p_document_code:c});if(error)return{ok:false,status:500,error:"document_scope_check_failed"};if(!data?.exists)return{ok:false,status:404,error:"document_not_found"};return data?.allowed?{ok:true}:{ok:false,status:403,error:"forbidden"}}if(t==="contacto_b2b"){const{data,error}=await svc.rpc("preprod_test_contact_get_server",{p_actor_code:ctx.actor_code,p_id:c});if(error)return{ok:false,status:500,error:"contact_scope_check_failed"};return data?.ok?{ok:true}:{ok:false,status:statusOf(data),error:data?.error??"forbidden"}}if(t==="banco"){const{data,error}=await svc.rpc("preprod_test_bank_detail_server",{p_actor_code:ctx.actor_code,p_bank_code:c});if(error)return{ok:false,status:500,error:"bank_scope_check_failed"};return data?.ok?{ok:true}:{ok:false,status:statusOf(data),error:data?.error??"forbidden"}}if(t==="notaria"||t==="registro"){if(!["Direccion","Financiero"].includes(role))return{ok:false,status:403,error:"forbidden"};const rpc=t==="notaria"?"preprod_test_notarias_list_server":"preprod_test_registros_list_server",{data,error}=await svc.rpc(rpc,{p_actor_code:ctx.actor_code});if(error)return{ok:false,status:500,error:`${t}_scope_check_failed`};if(!data?.ok)return{ok:false,status:statusOf(data),error:data?.error??"forbidden"};const found=Array.isArray(data.items)&&data.items.some((x:any)=>String(x?.id??"")===c||String(x?.source_url??"").includes(c));return found?{ok:true}:{ok:false,status:404,error:`${t}_not_found`}}if(t==="herencia"||t==="obra_nueva")return role==="Direccion"?{ok:true}:{ok:false,status:403,error:"forbidden"};return{ok:false,status:400,error:"unsupported_origin_type"}}

Deno.serve(async(req:Request)=>{try{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:hdr(req)});if(!U||!A||!S)return out(req,{ok:false,error:"server_config_missing"},503);const ah=req.headers.get("authorization")??"";if(!ah.toLowerCase().startsWith("bearer "))return out(req,{ok:false,error:"unauthorized"},401);const user=createClient(U,A,{global:{headers:{Authorization:ah}},auth:{persistSession:false,autoRefreshToken:false}}),svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});const{data:ud,error:ue}=await user.auth.getUser(ah.slice(7));if(ue||!ud.user)return out(req,{ok:false,error:"unauthorized"},401);const{data:ctx,error:ce}=await svc.rpc("preprod_test_actor_context_by_auth_server",{p_auth_user_id:ud.user.id});if(ce)return out(req,{ok:false,error:"identity_resolution_failed"},500);if(!ctx?.ok||!ctx?.actor_code)return out(req,{ok:false,error:"identity_not_linked"},403);if(req.method!=="POST"||route(req)!=="/apply")return out(req,{ok:false,error:"not_found"},404);const b=await req.json().catch(()=>null);if(!b)return out(req,{ok:false,error:"invalid_json"},400);const ot=str(b.origin_type,40),oc=str(b.origin_code,180),all=fields(b.fields);if(!ORIGINS.has(ot)||!oc)return out(req,{ok:false,error:"invalid_scope"},400);const declaredType=str(b.declared_document_type,120),declaredPerson=str(b.declared_person,220);if(!declaredType||!declaredPerson)return out(req,{ok:false,error:"classification_required"},422);if(!Object.keys(all).length)return out(req,{ok:false,error:"no_applicable_fields"},422);const docPage=str(b.document_page_id,100),summary=str(b.summary,1900),detected=str(b.document_type,120)||"Documento",confidence=Number.isFinite(Number(b.confidence))?Number(b.confidence):null;const payload={version:3,environment:"PREPROD_TEST",origin_type:ot,origin_code:oc,declared_document_type:declaredType,declared_person:declaredPerson,detected_document_type:detected,summary,confidence,fields:all,actor_code:ctx.actor_code,processed_at:new Date().toISOString()};const identity={nombre:str((all as any).nombre,120)||null,apellidos:str((all as any).apellidos,180)||null,documento_identidad:str((all as any).documento_identidad,20).toUpperCase()||null,fecha_nacimiento:iso((all as any).fecha_nacimiento)};

if(ot==="contacto"&&Object.values(identity).some(Boolean)){if(!["Direccion","Financiero"].includes(String(ctx.role)))return out(req,{ok:false,error:"forbidden"},403);const{data:read,error:re}=await svc.rpc("preprod_test_contact_get_server",{p_actor_code:ctx.actor_code,p_id:oc});if(re)return out(req,{ok:false,error:"contact_read_failed"},500);if(!read?.ok)return out(req,{ok:false,error:read?.error??"contact_not_found"},statusOf(read,404));const row:any=read.contacto??{},src=row.source_payload&&typeof row.source_payload==="object"?row.source_payload:{};const conflicts:any[]=[];for(const[f,current,proposed]of [["nombre",row.nombre,identity.nombre],["apellidos",row.apellidos,identity.apellidos],["documento_identidad",src.documento_identidad,identity.documento_identidad],["fecha_nacimiento",src.fecha_nacimiento,identity.fecha_nacimiento]] as any[]){if(proposed&&current&&String(current).trim().toLocaleLowerCase("es")!==String(proposed).trim().toLocaleLowerCase("es"))conflicts.push({field:f,current:String(current),proposed:String(proposed)})}if(conflicts.length&&!Boolean(b.confirm_overwrite))return out(req,{ok:false,status:409,error:"conflicts_require_confirmation",conflicts},409);if(docPage){const s=await store(docPage,payload);if(!s.ok)return out(req,{ok:false,error:s.error},500)}const{data:updated,error:we}=await svc.rpc("preprod_test_document_intelligence_contact_update_server",{p_actor_code:ctx.actor_code,p_cliente_code:oc,p_nombre:identity.nombre,p_apellidos:identity.apellidos,p_documento_identidad:identity.documento_identidad,p_fecha_nacimiento:identity.fecha_nacimiento,p_intelligence:{...payload,document_page_id:docPage||null}});if(we)return out(req,{ok:false,error:"contact_update_failed"},500);if(!updated?.ok)return out(req,{ok:false,error:updated?.error??"contact_update_failed"},statusOf(updated,500));return out(req,{ok:true,status:200,updated,cerebro_stored:Boolean(docPage),classification:{document_type:declaredType,person:declaredPerson},conflicts_resolved:conflicts.length})}

if(ot==="expediente"&&(identity.nombre||identity.apellidos)){if(!["Direccion","Financiero"].includes(String(ctx.role)))return out(req,{ok:false,error:"forbidden"},403);const{data:exp,error:ee}=await svc.rpc("preprod_test_get_expediente_server",{p_actor_code:ctx.actor_code,p_code:oc});if(ee)return out(req,{ok:false,error:"expediente_read_failed"},500);if(!exp||Object.keys(exp).length===0)return out(req,{ok:false,error:"expediente_not_found"},404);const full=[identity.nombre,identity.apellidos].filter(Boolean).join(" ").trim(),current=String(exp.cliente_alias??"").trim();if(current&&current.toLocaleLowerCase("es")!==full.toLocaleLowerCase("es")&&!Boolean(b.confirm_overwrite))return out(req,{ok:false,status:409,error:"conflicts_require_confirmation",conflicts:[{field:"nombre",current,proposed:full}]},409);const version=Number(exp.version??b.expected_version);if(!Number.isInteger(version))return out(req,{ok:false,error:"missing_version"},409);if(docPage){const s=await store(docPage,payload);if(!s.ok)return out(req,{ok:false,error:s.error},500)}const{data:updated,error:we}=await svc.rpc("preprod_test_document_intelligence_exp_update_server",{p_actor_code:ctx.actor_code,p_exp_code:oc,p_expected_version:version,p_cliente_alias:full});if(we)return out(req,{ok:false,error:"expediente_update_failed"},500);if(!updated?.ok)return out(req,{ok:false,error:updated?.error??"expediente_update_failed"},statusOf(updated,500));return out(req,{ok:true,status:200,updated,cerebro_stored:Boolean(docPage),classification:{document_type:declaredType,person:declaredPerson}})}

const az:any=await authorizeGeneric(svc,ctx,ot,oc);if(!az.ok)return out(req,{ok:false,error:az.error},az.status);if(docPage){const s=await store(docPage,payload);if(!s.ok)return out(req,{ok:false,error:s.error},500)}return out(req,{ok:true,status:200,cerebro_stored:Boolean(docPage),canonical_updates:0,classification:{document_type:declaredType,person:declaredPerson},updated:all})}catch(e){console.error("fenix-document-intelligence-preprod",e);return out(req,{ok:false,error:"document_intelligence_exception"},500)}});
