import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const U=Deno.env.get("SUPABASE_URL")??"",A=Deno.env.get("SUPABASE_ANON_KEY")??"",S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",N=Deno.env.get("NOTION_TOKEN")??"";
const DOC_DS="34037d5e-21e8-4221-b020-b0e6e1a5a14f",BUYER_DS="ddc88cd8-b8a3-43d4-b34c-7e4a17670ffc",NV="2025-09-03";
const ALLOWED=new Set(["https://carlosjmunoz78.github.io","https://app.fenixcapital.es"]);
const ORIGINS=new Set(["contacto","expediente","comprador","firma","inmobiliaria","tasacion","tarea","documento","contacto_b2b","banco","notaria","registro","herencia","obra_nueva"]);
const EVIDENCE=new Set(["expediente","inmobiliaria","tarea","tasacion","firma"]);
function hdr(req:Request){const o=req.headers.get("origin")||"";return{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-fenix-env":"PREPROD_TEST","Access-Control-Allow-Origin":ALLOWED.has(o)?o:"https://carlosjmunoz78.github.io","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Vary":"Origin"}}
const out=(req:Request,d:unknown,status=200)=>new Response(JSON.stringify(d),{status,headers:hdr(req)});
function route(req:Request){const raw=new URL(req.url).pathname,m=raw.match(/fenix-document-intelligence(?:-test)?/);return !m||m.index==null?raw:(raw.slice(m.index+m[0].length)||"/")}
function str(v:unknown,max=500){return typeof v==="string"?v.trim().slice(0,max):""}
function iso(v:unknown){const x=str(v,10);return /^\d{4}-\d{2}-\d{2}$/.test(x)?x:null}
function fields(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))return{};const o:Record<string,string|number|boolean>={};for(const[k,val]of Object.entries(v as Record<string,unknown>).slice(0,50)){const key=String(k).replace(/[^a-zA-Z0-9_áéíóúüñÁÉÍÓÚÜÑ-]/g,"_").slice(0,80);if(typeof val==="string"&&val.trim())o[key]=val.trim().slice(0,1000);else if(typeof val==="number"&&Number.isFinite(val))o[key]=val;else if(typeof val==="boolean")o[key]=val}return o}
function statusOf(r:any,fallback=403){const n=Number(r?.status);return Number.isInteger(n)&&n>=400&&n<=599?n:fallback}
async function notionPage(id:string){const r=await fetch(`https://api.notion.com/v1/pages/${id}`,{headers:{Authorization:`Bearer ${N}`,"Notion-Version":NV}}),b:any=await r.json().catch(()=>null);if(r.status===404)return null;if(!r.ok)throw new Error(`notion_page_${r.status}`);return b}
function plain(p:any):any{if(!p)return null;if(p.type==="rich_text")return(p.rich_text??[]).map((x:any)=>x.plain_text??"").join("");if(p.type==="title")return(p.title??[]).map((x:any)=>x.plain_text??"").join("");if(p.type==="relation")return(p.relation??[]).map((x:any)=>x.id);if(p.type==="number")return p.number??null;if(p.type==="select")return p.select?.name??null;if(p.type==="date")return p.date?.start??null;return null}
async function store(pageId:string,payload:Record<string,unknown>){if(!N||!/^[0-9a-fA-F-]{32,36}$/.test(pageId))return{ok:false,error:"notion_unavailable"};const p=await notionPage(pageId);if(!p)return{ok:false,error:"document_not_found"};if((p.parent?.data_source_id??p.parent?.database_id)!==DOC_DS)return{ok:false,error:"document_scope_mismatch"};const note=`[CEREBRO · LECTURA DOCUMENTAL]\n${JSON.stringify(payload)}`.slice(0,1950);const w=await fetch(`https://api.notion.com/v1/pages/${pageId}`,{method:"PATCH",headers:{Authorization:`Bearer ${N}`,"Notion-Version":NV,"Content-Type":"application/json"},body:JSON.stringify({properties:{Notas:{rich_text:[{type:"text",text:{content:note}}]}}})});return w.ok?{ok:true}:{ok:false,error:`notion_patch_${w.status}`}}
async function authorizeGeneric(svc:any,ctx:any,t:string,c:string){const role=String(ctx?.role??"");if(EVIDENCE.has(t)){const{data,error}=await svc.rpc("preprod_test_evidence_scope_server",{p_actor_code:ctx.actor_code,p_origin_type:t,p_origin_code:c});if(error)return{ok:false,status:500,error:"scope_check_failed"};return data?.ok?{ok:true}:{ok:false,status:statusOf(data),error:data?.error??"forbidden"}}if(t==="documento"){const{data,error}=await svc.rpc("preprod_test_document_access_server",{p_actor_code:ctx.actor_code,p_document_code:c});if(error)return{ok:false,status:500,error:"document_scope_check_failed"};if(!data?.exists)return{ok:false,status:404,error:"document_not_found"};return data?.allowed?{ok:true}:{ok:false,status:403,error:"forbidden"}}if(t==="contacto_b2b"){const{data,error}=await svc.rpc("preprod_test_contact_get_server",{p_actor_code:ctx.actor_code,p_id:c});if(error)return{ok:false,status:500,error:"contact_scope_check_failed"};return data?.ok?{ok:true}:{ok:false,status:statusOf(data),error:data?.error??"forbidden"}}if(t==="banco"){const{data,error}=await svc.rpc("preprod_test_bank_detail_server",{p_actor_code:ctx.actor_code,p_bank_code:c});if(error)return{ok:false,status:500,error:"bank_scope_check_failed"};return data?.ok?{ok:true}:{ok:false,status:statusOf(data),error:data?.error??"forbidden"}}if(t==="notaria"||t==="registro"){if(!["Direccion","Financiero"].includes(role))return{ok:false,status:403,error:"forbidden"};const rpc=t==="notaria"?"preprod_test_notarias_list_server":"preprod_test_registros_list_server",{data,error}=await svc.rpc(rpc,{p_actor_code:ctx.actor_code});if(error)return{ok:false,status:500,error:`${t}_scope_check_failed`};if(!data?.ok)return{ok:false,status:statusOf(data),error:data?.error??"forbidden"};const found=Array.isArray(data.items)&&data.items.some((x:any)=>String(x?.id??"")===c||String(x?.source_url??"").includes(c));return found?{ok:true}:{ok:false,status:404,error:`${t}_not_found`}}if(t==="herencia"||t==="obra_nueva")return role==="Direccion"?{ok:true}:{ok:false,status:403,error:"forbidden"};return{ok:false,status:400,error:"unsupported_origin_type"}}
async function authorizeBuyer(ctx:any,id:string){if(!["Direccion","Financiero"].includes(String(ctx?.role)))return{ok:false,status:403,error:"forbidden",page:null};const p=await notionPage(id);if(!p)return{ok:false,status:404,error:"buyer_not_found",page:null};if((p.parent?.data_source_id??p.parent?.database_id)!==BUYER_DS)return{ok:false,status:400,error:"not_a_buyer",page:null};if(ctx.role==="Direccion")return{ok:true,status:200,page:p};const ids=plain(p.properties?.Expedientes);if(!Array.isArray(ids)||!ids.length)return{ok:false,status:403,error:"forbidden",page:null};for(const expId of ids){const ep=await notionPage(expId);if(ep&&plain(ep.properties?.["ID financiero operativo"])===ctx.actor_code)return{ok:true,status:200,page:p}}return{ok:false,status:403,error:"forbidden",page:null}}
function comparable(v:unknown){return String(v??"").trim().toLocaleLowerCase("es")}
function buyerChanges(all:Record<string,string|number|boolean>){const c:Record<string,unknown>={};const map:Record<string,string>={nombre:"nombre",apellidos:"apellidos",documento_identidad:"dni_nie",fecha_nacimiento:"fecha_nacimiento",nacionalidad:"nacionalidad",empresa:"empresa_organismo",antiguedad_laboral:"antiguedad_laboral",ingresos_netos_mensuales:"sueldo_neto_mensual",otros_ingresos_mensuales:"otros_ingresos_mensuales",cuotas_deuda_mensuales:"deudas_mensuales",ahorros:"ahorro_disponible"};for(const[from,to]of Object.entries(map))if(all[from]!==undefined&&all[from]!==null&&all[from]!=="")c[to]=all[from];const state=str(all.estado_civil,80);const norm=state.toLocaleLowerCase("es");const states:Record<string,string>={"soltero":"Soltero/a","soltera":"Soltero/a","soltero/a":"Soltero/a","casado":"Casado/a","casada":"Casado/a","casado/a":"Casado/a","divorciado":"Divorciado/a","divorciada":"Divorciado/a","divorciado/a":"Divorciado/a","separado":"Separado/a","separada":"Separado/a","separado/a":"Separado/a","viudo":"Viudo/a","viuda":"Viudo/a","viudo/a":"Viudo/a","pareja de hecho":"Pareja de hecho"};if(states[norm])c.estado_civil=states[norm];return c}
function currentBuyerField(p:any,key:string){const props=p?.properties??{},m:Record<string,string>={nombre:"Nombre",apellidos:"Apellidos",dni_nie:"DNI/NIE",fecha_nacimiento:"Fecha nacimiento",nacionalidad:"Nacionalidad",empresa_organismo:"Empresa / organismo",antiguedad_laboral:"Antigüedad laboral",sueldo_neto_mensual:"Sueldo neto mensual",otros_ingresos_mensuales:"Otros ingresos mensuales",deudas_mensuales:"Deudas mensuales",ahorro_disponible:"Ahorro disponible",estado_civil:"Estado civil"};return plain(props[m[key]])}

Deno.serve(async(req:Request)=>{try{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:hdr(req)});if(!U||!A||!S)return out(req,{ok:false,error:"server_config_missing"},503);const ah=req.headers.get("authorization")??"";if(!ah.toLowerCase().startsWith("bearer "))return out(req,{ok:false,error:"unauthorized"},401);const user=createClient(U,A,{global:{headers:{Authorization:ah}},auth:{persistSession:false,autoRefreshToken:false}}),svc=createClient(U,S,{auth:{persistSession:false,autoRefreshToken:false}});const{data:ud,error:ue}=await user.auth.getUser(ah.slice(7));if(ue||!ud.user)return out(req,{ok:false,error:"unauthorized"},401);const{data:ctx,error:ce}=await svc.rpc("preprod_test_actor_context_by_auth_server",{p_auth_user_id:ud.user.id});if(ce)return out(req,{ok:false,error:"identity_resolution_failed"},500);if(!ctx?.ok||!ctx?.actor_code)return out(req,{ok:false,error:"identity_not_linked"},403);if(req.method!=="POST"||route(req)!=="/apply")return out(req,{ok:false,error:"not_found"},404);const b=await req.json().catch(()=>null);if(!b)return out(req,{ok:false,error:"invalid_json"},400);const ot=str(b.origin_type,40),oc=str(b.origin_code,180),all=fields(b.fields);if(!ORIGINS.has(ot)||!oc)return out(req,{ok:false,error:"invalid_scope"},400);const declaredType=str(b.declared_document_type,120),declaredPerson=str(b.declared_person,220);if(!declaredType||!declaredPerson)return out(req,{ok:false,error:"classification_required"},422);if(!Object.keys(all).length)return out(req,{ok:false,error:"no_applicable_fields"},422);const docPage=str(b.document_page_id,100),summary=str(b.summary,1900),detected=str(b.document_type,120)||"Documento",confidence=Number.isFinite(Number(b.confidence))?Number(b.confidence):null;const payload={version:4,environment:"PREPROD_TEST",origin_type:ot,origin_code:oc,declared_document_type:declaredType,declared_person:declaredPerson,detected_document_type:detected,summary,confidence,fields:all,actor_code:ctx.actor_code,processed_at:new Date().toISOString()};const identity={nombre:str((all as any).nombre,120)||null,apellidos:str((all as any).apellidos,180)||null,documento_identidad:str((all as any).documento_identidad,20).toUpperCase()||null,fecha_nacimiento:iso((all as any).fecha_nacimiento)};

if(ot==="comprador"){const az=await authorizeBuyer(ctx,oc);if(!az.ok)return out(req,{ok:false,error:az.error},az.status);const changes=buyerChanges(all),conflicts:any[]=[];for(const[k,proposed]of Object.entries(changes)){const current=currentBuyerField(az.page,k);if(proposed!==null&&proposed!==undefined&&proposed!==""&&current!==null&&current!==undefined&&current!==""&&comparable(current)!==comparable(proposed))conflicts.push({field:k,current:String(current),proposed:String(proposed)})}if(conflicts.length&&!Boolean(b.confirm_overwrite))return out(req,{ok:false,status:409,error:"conflicts_require_confirmation",conflicts,extraction:{document_type:detected,person:declaredPerson,confidence,summary,fields:all}},409);if(docPage){const s=await store(docPage,payload);if(!s.ok)return out(req,{ok:false,error:s.error},500)}if(!Object.keys(changes).length)return out(req,{ok:true,status:200,cerebro_stored:Boolean(docPage),canonical_updates:0,classification:{document_type:declaredType,person:declaredPerson},updated:{}});const r=await fetch(`${U}/functions/v1/fenix-comprador-action-test/compradores/${encodeURIComponent(oc)}/action`,{method:"POST",headers:{Authorization:ah,apikey:A,"content-type":"application/json"},body:JSON.stringify({changes})});const updated:any=await r.json().catch(()=>null);if(!r.ok||updated?.ok===false)return out(req,{ok:false,error:updated?.error??"buyer_update_failed"},r.status||500);return out(req,{ok:true,status:200,updated,cerebro_stored:Boolean(docPage),canonical_updates:Object.keys(changes).length,classification:{document_type:declaredType,person:declaredPerson},conflicts_resolved:conflicts.length})}

if(ot==="contacto"&&Object.values(identity).some(Boolean)){if(!["Direccion","Financiero"].includes(String(ctx.role)))return out(req,{ok:false,error:"forbidden"},403);const{data:read,error:re}=await svc.rpc("preprod_test_contact_get_server",{p_actor_code:ctx.actor_code,p_id:oc});if(re)return out(req,{ok:false,error:"contact_read_failed"},500);if(!read?.ok)return out(req,{ok:false,error:read?.error??"contact_not_found"},statusOf(read,404));const row:any=read.contacto??{},src=row.source_payload&&typeof row.source_payload==="object"?row.source_payload:{};const conflicts:any[]=[];for(const[f,current,proposed]of [["nombre",row.nombre,identity.nombre],["apellidos",row.apellidos,identity.apellidos],["documento_identidad",src.documento_identidad,identity.documento_identidad],["fecha_nacimiento",src.fecha_nacimiento,identity.fecha_nacimiento]] as any[]){if(proposed&&current&&comparable(current)!==comparable(proposed))conflicts.push({field:f,current:String(current),proposed:String(proposed)})}if(conflicts.length&&!Boolean(b.confirm_overwrite))return out(req,{ok:false,status:409,error:"conflicts_require_confirmation",conflicts},409);if(docPage){const s=await store(docPage,payload);if(!s.ok)return out(req,{ok:false,error:s.error},500)}const{data:updated,error:we}=await svc.rpc("preprod_test_document_intelligence_contact_update_server",{p_actor_code:ctx.actor_code,p_cliente_code:oc,p_nombre:identity.nombre,p_apellidos:identity.apellidos,p_documento_identidad:identity.documento_identidad,p_fecha_nacimiento:identity.fecha_nacimiento,p_intelligence:{...payload,document_page_id:docPage||null}});if(we)return out(req,{ok:false,error:"contact_update_failed"},500);if(!updated?.ok)return out(req,{ok:false,error:updated?.error??"contact_update_failed"},statusOf(updated,500));return out(req,{ok:true,status:200,updated,cerebro_stored:Boolean(docPage),classification:{document_type:declaredType,person:declaredPerson},conflicts_resolved:conflicts.length})}

if(ot==="expediente"&&(identity.nombre||identity.apellidos)){const{data:exp,error:ee}=await svc.rpc("preprod_test_get_expediente_server",{p_actor_code:ctx.actor_code,p_code:oc});if(ee)return out(req,{ok:false,error:"expediente_read_failed"},500);if(!exp||Object.keys(exp).length===0)return out(req,{ok:false,error:"expediente_not_found"},404);if(docPage){const s=await store(docPage,payload);if(!s.ok)return out(req,{ok:false,error:s.error},500)}return out(req,{ok:true,status:200,cerebro_stored:Boolean(docPage),canonical_updates:0,classification:{document_type:declaredType,person:declaredPerson},note:"expediente_alias_not_overwritten_by_document_identity"})}

const az:any=await authorizeGeneric(svc,ctx,ot,oc);if(!az.ok)return out(req,{ok:false,error:az.error},az.status);if(docPage){const s=await store(docPage,payload);if(!s.ok)return out(req,{ok:false,error:s.error},500)}return out(req,{ok:true,status:200,cerebro_stored:Boolean(docPage),canonical_updates:0,classification:{document_type:declaredType,person:declaredPerson},updated:all})}catch(e){console.error("fenix-document-intelligence-preprod",e);return out(req,{ok:false,error:"document_intelligence_exception"},500)}});
