import {FormEvent,useEffect,useRef,useState} from 'react';
import {MessageCircle,RefreshCw,Send} from 'lucide-react';
import {createPortal} from 'react-dom';
import {useLocation} from 'react-router-dom';
import {gatewayRpc} from './appRpcCompat';
import {supabase} from './supabase';

type ChatMessage={message_code:string;sender_actor_code:string;sender_name:string;sender_role:string;body:string;created_at:string};
type ChatPayload={status?:number;items?:ChatMessage[];item?:ChatMessage};

export default function AnaChatBlock(){
 const location=useLocation();
 const active=location.pathname==='/ana';
 const[mount,setMount]=useState<HTMLElement|null>(null),[logged,setLogged]=useState(false),[messages,setMessages]=useState<ChatMessage[]>([]),[draft,setDraft]=useState(''),[loading,setLoading]=useState(false),[sending,setSending]=useState(false),[notice,setNotice]=useState('');
 const endRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(!active){setMount(null);return;}let alive=true;supabase.auth.getSession().then(({data})=>{if(alive)setLogged(Boolean(data.session))});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive)setLogged(Boolean(s))});const place=()=>{const root=[...document.querySelectorAll('.ops-root')].filter(n=>{const e=n as HTMLElement,r=e.getBoundingClientRect();return r.width>0&&r.height>0}).at(-1) as HTMLElement|undefined;const content=root?.querySelector('.ops-content') as HTMLElement|null;if(!content)return;let node=content.querySelector('.ana-chat-mount') as HTMLElement|null;if(!node){node=document.createElement('section');node.className='ana-chat-mount';content.appendChild(node)}setMount(node)};place();const obs=new MutationObserver(place);obs.observe(document.body,{childList:true,subtree:true});return()=>{alive=false;subscription.unsubscribe();obs.disconnect();document.querySelector('.ana-chat-mount')?.remove();setMount(null)}},[active]);
 async function load(silent=false){if(!active||!logged)return;if(!silent)setLoading(true);try{const{data,error}=await gatewayRpc<ChatPayload>('fenix_prod_chat_list_user',{p_limit:100});if(error){setNotice('No se pudo cargar la conversación.');return;}const p=data as ChatPayload|null;if(p?.status===403){setNotice('Tu perfil no tiene acceso al chat.');setMessages([]);return;}setMessages(Array.isArray(p?.items)?p!.items!.filter(x=>x&&typeof x.message_code==='string'&&typeof x.body==='string'):[]);setNotice('')}catch{setNotice('No se pudo conectar con el chat.')}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{if(active&&logged){void load();const t=window.setInterval(()=>void load(true),15000);return()=>window.clearInterval(t)}},[active,logged]);
 useEffect(()=>{if(messages.length)endRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length]);
 async function submit(e:FormEvent){e.preventDefault();const body=draft.trim();if(!body||sending)return;setSending(true);setNotice('');try{const{data,error}=await gatewayRpc<ChatPayload>('fenix_prod_chat_send_user',{p_body:body,p_idempotency_key:`ana-chat-${crypto.randomUUID()}`});const p=data as ChatPayload|null;if(error||p?.status!==200||!p?.item){setNotice(p?.status===403?'Tu perfil no puede escribir en este chat.':'No se pudo enviar el mensaje.');return;}setDraft('');await load(true)}catch{setNotice('No se pudo enviar el mensaje.')}finally{setSending(false)}}
 if(!active||!logged||!mount)return null;
 return createPortal(<article className="ana-knowledge-card" data-testid="ana-chat-block" aria-label="Conversación con Ana"><div className="ana-knowledge-head"><div className="ana-knowledge-title"><div className="ana-knowledge-icon"><MessageCircle size={18}/></div><div className="ana-knowledge-copy"><strong>CONVERSACIÓN CON ANA</strong><span>Canal persistente dentro de la pantalla de Ana.</span></div></div><button className="ana-knowledge-history" type="button" onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/><span>{loading?'Actualizando…':'Actualizar'}</span></button></div><div style={{maxHeight:320,overflow:'auto',display:'grid',gap:8,marginBottom:12}}>{messages.length===0&&!loading?<small>No hay mensajes todavía.</small>:messages.map(m=><div key={m.message_code} className="ops-message" style={{margin:0}}><strong>{m.sender_name||m.sender_actor_code}</strong><p style={{margin:'4px 0 0',whiteSpace:'pre-wrap'}}>{m.body}</p></div>)}<div ref={endRef}/></div>{notice&&<div className="ops-message" style={{margin:'0 0 10px'}}>{notice}</div>}<form onSubmit={submit} className="ana-knowledge-input-wrap"><textarea className="ana-knowledge-input" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={4000} placeholder="Escribe a Ana…"/><div className="ana-knowledge-footer" style={{padding:'0 12px 12px'}}><span className="ana-knowledge-status">{draft.length}/4000</span><button className="ana-knowledge-submit" type="submit" disabled={!draft.trim()||sending}><Send size={15}/>{sending?'Enviando…':'Enviar'}</button></div></form></article>,mount)
}
