import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Landmark,UserRound} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {anaVertical} from './assets/visualAssets';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './bancos-polish.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};type Focus='todos'|'100'|'doble'|'ambos';
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of ['items','bancos','results'])if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number')return String(v);}return'';}
function yes(row:Row,keys:string[]){return keys.some(k=>row[k]===true||/^(si|sí|yes|true)$/i.test(String(row[k]??'')));}
function has100(r:Row){return yes(r,['admite_100','financiacion_100','cien_por_cien'])}function hasDouble(r:Row){return yes(r,['doble_garantia','admite_doble_garantia'])}
function profileOf(r:Row){return first(r,['perfil','perfil_clientes','tipo','segmento'])||'Sin perfil'}

export default function BancosShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/bancos';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[focus,setFocus]=useState<Focus>('todos'),[profile,setProfile]=useState(''),[globalQuery,setGlobalQuery]=useState('');
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setRows([]);try{const[c,n,b]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchAppApi<unknown>('/bancos')]);if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);setStatus(b.status);setRows(b.status===200?rowsFrom(b.data):[]);if(b.status===403)setMessage('Tu perfil no tiene acceso a Bancos.');else if(b.status!==200)setMessage('No se pudo cargar la información actualizada de Bancos.');}catch{if(!alive)return;setCtx(null);setNav([]);setStatus(0);setRows([]);setMessage('No se pudo conectar con la fuente autorizada de Bancos.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,logged]);
 const profiles=useMemo(()=>Array.from(new Set(rows.map(profileOf).filter(x=>x!=='Sin perfil'))).sort((a,b)=>a.localeCompare(b,'es')),[rows]);
 const visible=useMemo(()=>rows.filter(r=>(!profile||profileOf(r)===profile)&&(focus==='todos'||(focus==='100'&&has100(r))||(focus==='doble'&&hasDouble(r))||(focus==='ambos'&&has100(r)&&hasDouble(r)))),[rows,profile,focus]);
 const kpis=useMemo(()=>({total:rows.length,cien:rows.filter(has100).length,doble:rows.filter(hasDouble).length,ambos:rows.filter(r=>has100(r)&&hasDouble(r)).length}),[rows]);
 const capabilityRank=useMemo(()=>[['100% informado',kpis.cien],['Doble garantía',kpis.doble],['Ambas capacidades',kpis.ambos]] as [string,number][],[kpis]);const maxCapability=Math.max(1,...capabilityRank.map(([,n])=>n));
 const effectiveNav=nav.length?nav:fallbackNav;
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}function globalSearch(){const q=globalQuery.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 const role=ctx?.role||'Usuario',anaSummary=loading?'Estoy revisando los criterios bancarios autorizados.':status!==200?'No tengo datos suficientes para recomendar un banco.':kpis.cien?`Hay ${kpis.cien} bancos con financiación al 100% informada y ${kpis.doble} con doble garantía informada. Compara siempre el caso concreto antes de mover un expediente.`:`Veo ${kpis.total} bancos, pero no hay capacidades especiales explícitas suficientes para priorizar sin revisar cada ficha.`;
 return <OperationalShellFrame className="inmo-root bancos-root" theme={theme} navigation={effectiveNav} activeRoute="/bancos" anaSubtitle="Compara criterios sin inventar condiciones." query={globalQuery} onQueryChange={setGlobalQuery} searchPlaceholder="Buscar en toda la app..." searchActionLabel="Buscar" onSearchAction={globalSearch} name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content bancos-content">
  <section className="inmo-ana-hero bancos-ana"><div className="inmo-ana-photo bancos-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · CRITERIOS BANCARIOS</span><h2>Busca el encaje antes de mover el expediente</h2><p>{anaSummary}</p><div className="inmo-next bancos-actions"><button onClick={()=>setFocus('100')}><b>1</b><strong>Ver bancos con 100%</strong><small>{kpis.cien} bancos →</small></button><button onClick={()=>setFocus('doble')}><b>2</b><strong>Ver doble garantía</strong><small>{kpis.doble} bancos →</small></button><button onClick={()=>navigate('/bancos/contactos')}><b>3</b><strong>Contactos bancarios</strong><small>Abrir contactos →</small></button></div></div><article className="inmo-correct"><span>CONTROL BANCARIO</span><h3>Qué puede encajar</h3><p>Ana solo compara capacidades declaradas en la ficha del banco.</p><textarea readOnly rows={3} value={`${kpis.cien} bancos con 100% informado`}/><input readOnly value={`${kpis.doble} con doble garantía informada`}/><button onClick={()=>navigate('/ana?mode=help&resource=bancos')}>Comparar con Ana</button></article></section>
  <div className="bancos-title inmo-title"><div><small>ENTIDADES Y CRITERIOS</small><h1>Bancos</h1><p>{status===200?`${rows.length} bancos visibles según tus permisos.`:'Información disponible según permisos.'}</p></div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos actualizados':'Sin conexión'}</span><button className="primary" onClick={()=>navigate('/bancos/nuevo')}>+ Nuevo banco</button></div></div>
  {!loading&&status===200&&<><section className="inmo-kpis bancos-kpis"><article><Landmark/><small>BANCOS VISIBLES</small><strong>{kpis.total}</strong><span>Dentro de tu ámbito</span></article><article><Landmark/><small>CON 100% INFORMADO</small><strong>{kpis.cien}</strong><span>Solo si la fuente lo declara</span></article><article><Landmark/><small>DOBLE GARANTÍA</small><strong>{kpis.doble}</strong><span>Solo si la fuente lo declara</span></article><article><Landmark/><small>AMBAS CAPACIDADES</small><strong>{kpis.ambos}</strong><span>100% y doble garantía</span></article></section><section className="inmo-insights inmo-live-charts"><article><span>CAPACIDADES DECLARADAS</span><h2>Qué ofrece la cartera bancaria</h2><div className="inmo-bars">{capabilityRank.map(([x,n])=><button key={x} className="inmo-bar-row inmo-bar-button" onClick={()=>setFocus(x==='100% informado'?'100':x==='Doble garantía'?'doble':'ambos')}><div className="inmo-bar-label"><strong>{x}</strong><span>{n}</span></div><div className="inmo-bar-track"><i style={{width:`${Math.max(8,n/maxCapability*100)}%`}}/></div></button>)}</div></article><article><span>LECTURA OPERATIVA</span><h2>Comparación rápida</h2><strong className="inmo-priority">{visible.length}</strong><p>Bancos visibles con los filtros prefijados seleccionados. Para condiciones concretas, abre siempre la ficha del banco.</p></article></section><section className="inmo-filter" data-testid="bancos-preset-search"><div className="inmo-filter-head"><div><small>BUSCADOR PREFIJADO</small><h2>Filtrar bancos sin escribir</h2></div><span>{visible.length} visibles</span></div><div className="inmo-filter-grid"><label>CAPACIDAD<select value={focus} onChange={e=>setFocus(e.target.value as Focus)}><option value="todos">Todos los bancos</option><option value="100">100% informado</option><option value="doble">Doble garantía informada</option><option value="ambos">100% + doble garantía</option></select></label><label>PERFIL<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="">Todos los perfiles</option>{profiles.map(v=><option key={v}>{v}</option>)}</select></label><button onClick={()=>{setFocus('todos');setProfile('')}}>Limpiar</button></div></section></>}
  {loading&&<div className="ops-empty" data-testid="bancos-loading"><strong>Cargando…</strong><span>Consultando la fuente autorizada de Bancos.</span></div>}{!loading&&message&&<div className="ops-message" data-testid={status===403?'bancos-forbidden':'bancos-error'}>{message}</div>}{!loading&&status===200&&visible.length===0&&<div className="ops-empty" data-testid="bancos-empty"><strong>Sin bancos visibles</strong><span>No hay registros disponibles con estos filtros.</span></div>}
  {!loading&&status===200&&visible.length>0&&<div className="bancos-grid">{visible.map((r,i)=>{const name=first(r,['nombre','name','banco','entidad'])||'Banco sin nombre';const profileText=first(r,['perfil','perfil_clientes','descripcion','criterio'])||'Perfil no informado';const id=first(r,['id','banco_code','code']);const cien=has100(r),doble=hasDouble(r);const open=()=>id&&navigate(`/bancos/${encodeURIComponent(id)}`);return <article key={id||`${name}-${i}`} className={id?'banco-openable':''} role={id?'link':undefined} tabIndex={id?0:undefined} onClick={e=>{if(!id||(e.target as HTMLElement).closest('button,a,input,select,textarea,label'))return;open()}} onKeyDown={e=>{if(id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();open()}}}><div className="banco-icon"><Landmark/></div><div><h2>{name}</h2><p>{profileText}</p></div><dl><div><dt>100%</dt><dd>{cien?'Sí':'No informado'}</dd></div><div><dt>Doble garantía</dt><dd>{doble?'Sí':'No informado'}</dd></div></dl>{id&&<button onClick={open}><Landmark size={15}/> Ver ficha</button>}<button onClick={()=>navigate('/bancos/contactos')}><UserRound size={15}/> Contactos</button></article>})}</div>}
 </OperationalShellFrame>;
}
