import {useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Mail,Moon,Phone,Sun,UserRound} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import type {NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './bank-contacts.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number')return String(v);}return'';}
function itemFrom(data:unknown):Row|null{if(!data||typeof data!=='object')return null;const d=data as Record<string,unknown>;if(d.item&&typeof d.item==='object')return d.item as Row;if(d.contacto&&typeof d.contacto==='object')return d.contacto as Row;return null;}
function navFrom(data:unknown):NavItem[]{if(!data||typeof data!=='object')return[];const xs=(data as{items?:unknown[]}).items;if(!Array.isArray(xs))return[];return xs.map(x=>x&&typeof x==='object'?x as Record<string,unknown>:null).filter(Boolean).map(x=>({label:typeof x!.label==='string'?x!.label:'',route:typeof x!.route==='string'?x!.route:''})).filter(x=>x.label&&x.route);}
export default function BankContactDetailShell(){
 const location=useLocation(),navigate=useNavigate();const m=location.pathname.match(/^\/bancos\/contactos\/([^/]+)$/);const id=m?decodeURIComponent(m[1]):'';const active=Boolean(id);const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[row,setRow]=useState<Row|null>(null),[status,setStatus]=useState<number|null>(null);
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchNotionRuntime<unknown>(`/contactos-bancarios/${encodeURIComponent(id)}`)]).then(([c,n,r])=>{if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?navFrom(n.data):[]);setStatus(r.status);setRow(r.status===200?itemFrom(r.data):null)});return()=>{alive=false};},[active,logged,id]);
 if(!active||!ready||!logged)return null;const name=row?first(row,['nombre','name','contacto']):'';const bank=row?first(row,['banco','entidad','bank']):'';const role=row?first(row,['cargo','role','puesto']):'';const phone=row?first(row,['telefono','phone','movil']):'';const email=row?first(row,['email','correo']):'';const branch=row?first(row,['sucursal','oficina','branch']):'';const schedule=row?first(row,['horario','schedule']):'';const zone=row?first(row,['zona','area','provincia']):'';
 const topbar=<header className="ops-top"><button className="bankc-back" onClick={()=>navigate('/bancos/contactos')}>← Volver a contactos</button><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{ctx?.role||'Usuario'}</strong></div></div></header>;
 return <OperationalShellFrame className="bankcd-root" theme={theme} navigation={nav} activeRoute="/bancos" anaSubtitle="Usa únicamente datos bancarios autorizados." anaRoute="/ana?mode=help&resource=bancos" query="" onQueryChange={()=>{}} searchPlaceholder="" name={ctx?.role||'Usuario'} role="" initials={(ctx?.role||'U').slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={async()=>{await supabase.auth.signOut();}} topbar={topbar} contentClassName="bankcd-content">
  {status===403&&<div className="ops-message">Tu perfil no tiene acceso a este contacto bancario.</div>}{status!==null&&status!==200&&status!==403&&<div className="ops-message">No se pudo cargar el contacto bancario.</div>}{status===200&&!row&&<div className="ops-empty"><strong>Contacto no disponible</strong><span>La fuente canónica no devolvió este registro.</span></div>}{status===200&&row&&<><div className="bankcd-title"><small>FICHA DE CONTACTO BANCARIO</small><h1>{name||'Contacto bancario'}</h1><p>{[role,bank].filter(Boolean).join(' · ')||'Cargo y banco no informados'}</p></div><section className="bankcd-card"><div className="bankc-avatar"><UserRound/></div><dl><div><dt>Banco</dt><dd>{bank||'No disponible'}</dd></div><div><dt>Cargo</dt><dd>{role||'No disponible'}</dd></div><div><dt>Sucursal</dt><dd>{branch||'No disponible'}</dd></div><div><dt>Zona</dt><dd>{zone||'No disponible'}</dd></div><div><dt><Phone size={13}/> Teléfono</dt><dd>{phone||'No disponible'}</dd></div><div><dt><Mail size={13}/> Email</dt><dd>{email||'No disponible'}</dd></div><div><dt>Horario</dt><dd>{schedule||'No disponible'}</dd></div><div><dt>Identificador</dt><dd>{id}</dd></div></dl></section><section className="bankcd-actions"><button onClick={()=>navigate('/bancos')}>Ver criterios del banco</button><button onClick={()=>navigate('/expedientes')}>Revisar expedientes</button><button onClick={()=>navigate('/ana?mode=help&resource=bancos')}>Preparar con Ana</button></section><div className="bankc-note">No se infieren datos de contacto, sucursal, horario o zona cuando la fuente canónica no los informa.</div></>}
 </OperationalShellFrame>;
}
