import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Mail,Phone,UserRound} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './bank-contacts.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of ['items','contactos','results'])if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number')return String(v);}return'';}
function idOf(r:Row){return first(r,['id','contacto_id','contact_id','code']);}
export default function BankContactsShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/bancos/contactos';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setRows([]);try{const[c,n,r]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchNotionRuntime<unknown>('/contactos-bancarios')]);if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);setStatus(r.status);if(r.status===200)setRows(rowsFrom(r.data));else if(r.status===403)setMessage('Tu perfil no tiene acceso a contactos bancarios.');else setMessage('No se pudo cargar la fuente canónica de contactos bancarios.');}catch{if(!alive)return;setCtx(null);setNav([]);setRows([]);setStatus(0);setMessage('No se pudo conectar con la fuente autorizada de contactos bancarios.');}finally{if(alive)setLoading(false)}})();return()=>{alive=false};},[active,logged]);
 const effectiveNav=nav.length?nav:fallbackNav;
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>Object.values(r).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase().includes(q));},[rows,query]);
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 const role=ctx?.role||'Usuario';
 return <OperationalShellFrame className="bankc-root" theme={theme} navigation={effectiveNav} activeRoute="/bancos" anaSubtitle="Localiza al contacto correcto sin inventar sucursales ni horarios." anaRoute="/ana?mode=help&resource=bancos" query={query} onQueryChange={setQuery} searchPlaceholder="Buscar contacto, banco o sucursal..." name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="bankc-content"><button className="bankc-back" onClick={()=>navigate('/bancos')}>← Volver a Bancos</button><div className="bankc-title"><div><small>CONTACTOS BANCARIOS · FUENTE CANÓNICA</small><h1>Contactos bancarios</h1><p>Personas de banco visibles para tu ámbito financiero.</p></div><div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando':status===200?'Datos vivos':'PRE-PROD'}</span><small className="bankc-source">Fuente canónica Notion</small></div></div>{loading&&<div className="ops-message" data-testid="bankc-loading">Cargando contactos bancarios autorizados…</div>}{!loading&&message&&<div className="ops-message" data-testid={status===403?'bankc-forbidden':'bankc-error'}>{message}</div>}{!loading&&status===200&&visible.length===0&&<div className="ops-empty" data-testid="bankc-empty"><strong>Sin contactos visibles</strong><span>No hay registros dentro de tu ámbito o filtro.</span></div>}{!loading&&status===200&&visible.length>0&&<div className="bankc-grid">{visible.map((r,i)=>{const id=idOf(r);const name=first(r,['nombre','name','contacto'])||'Contacto sin nombre';const bank=first(r,['banco','entidad','bank'])||'Banco no informado';const contactRole=first(r,['cargo','role','puesto'])||'Cargo no informado';const phone=first(r,['telefono','phone','movil']);const email=first(r,['email','correo']);const branch=first(r,['sucursal','oficina','branch']);return <article key={id||`${name}-${i}`} className={id?'bankc-openable':''} tabIndex={id?0:undefined} onClick={()=>id&&navigate(`/bancos/contactos/${encodeURIComponent(id)}`)} onKeyDown={e=>{if(id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();navigate(`/bancos/contactos/${encodeURIComponent(id)}`)}}}><div className="bankc-avatar"><UserRound/></div><div><h2>{name}</h2><p>{contactRole} · {bank}</p>{branch&&<small>{branch}</small>}</div><dl><div><dt><Phone size={13}/> Teléfono</dt><dd>{phone||'No disponible'}</dd></div><div><dt><Mail size={13}/> Email</dt><dd>{email||'No disponible'}</dd></div></dl>{id&&<span className="bankc-open">Abrir ficha →</span>}</article>})}</div>}<div className="bankc-note">No se completan horarios, sucursales, teléfonos ni correos que no existan en la fuente canónica.</div></OperationalShellFrame>;
}
