import {FormEvent,useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Mail,MessageCircle,ShieldCheck,Send,CheckCircle2,XCircle} from 'lucide-react';
import {SUPABASE_URL,supabase} from './supabase';
import {anaAvatar,fenixLogo} from './assets/visualAssets';
import './operational.css';

type AnyRow=Record<string,any>;
async function commApi(path:string,init?:RequestInit){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return {status:401,data:null as any};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-communications-gateway-test${path}`,{...init,headers:{'content-type':'application/json',...(init?.headers||{}),Authorization:`Bearer ${session.access_token}`}});let data:any=null;try{data=await r.json()}catch{}return {status:r.status,data};}

export default function CommunicationsShell(){
 const location=useLocation(),navigate=useNavigate();
 const active=location.pathname==='/comunicaciones'||location.pathname==='/comunicaciones/nueva';
 const params=new URLSearchParams(location.search);
 const [role,setRole]=useState('');const [items,setItems]=useState<AnyRow[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);
 const [scopeType,setScopeType]=useState(params.get('scope_type')||'expediente');const [scopeCode,setScopeCode]=useState(params.get('scope_code')||'');const [canal,setCanal]=useState('Email');const [recipient,setRecipient]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');
 async function load(){const ctx=await commApi('/comunicaciones');if(ctx.status===200)setItems(ctx.data?.comunicaciones||ctx.data?.items||[]);const {data:{session}}=await supabase.auth.getSession();if(session){const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-app-gateway-test/session/context`,{headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json().catch(()=>null);setRole(String(d?.context?.role??d?.role??''));}}
 useEffect(()=>{if(active)load()},[active]);
 if(!active)return null;
 async function prepare(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');const r=await commApi('/comunicaciones/prepare',{method:'POST',body:JSON.stringify({scope_type:scopeType,scope_code:scopeCode,canal,recipient_alias:recipient,asunto:subject,cuerpo:body,consentimiento_requerido:canal==='WhatsApp',consentimiento_valido:false,no_contactar:false,idempotency_key:`ui-${Date.now()}`})});setBusy(false);if(r.status===200||r.status===201){setMsg('Comunicación preparada. Queda pendiente de revisión y autorización antes de cualquier envío.');setRecipient('');setSubject('');setBody('');load()}else setMsg(`No se pudo preparar (${r.data?.error||r.status}).`)}
 async function authorize(x:AnyRow){setBusy(true);const r=await commApi(`/comunicaciones/${encodeURIComponent(x.communication_code)}/authorize`,{method:'POST',body:JSON.stringify({expectedVersion:x.version,payload_hash:x.payload_hash})});setBusy(false);setMsg(r.status===200?'Comunicación autorizada.':`No autorizada (${r.data?.error||r.status}).`);load()}
 async function simulate(x:AnyRow){setBusy(true);const r=await commApi(`/comunicaciones/${encodeURIComponent(x.communication_code)}/send`,{method:'POST',body:JSON.stringify({expectedVersion:x.version,payload_hash:x.payload_hash,idempotency_key:`sim-${x.communication_code}`,mode:'SIMULATED'})});setBusy(false);setMsg(r.status===200?'Simulación completada sin envío externo.':`Simulación bloqueada (${r.data?.error||r.status}).`);load()}
 return <div className="ops-root" data-theme={(sessionStorage.getItem('fenix-theme')||'light')}>
  <aside className="ops-side"><button className="ops-brand" onClick={()=>navigate('/inicio')}><img src={fenixLogo} alt=""/><strong>FÉNIX CAPITAL</strong></button><nav><button onClick={()=>navigate('/inicio')}>Inicio</button><button onClick={()=>navigate('/expedientes')}>Expedientes</button><button onClick={()=>navigate('/contactos')}>Contactos</button><button onClick={()=>navigate('/inmobiliarias')}>Inmobiliarias</button><button className="active">Comunicaciones</button></nav><button className="ops-ana" onClick={()=>navigate('/ana')}><img src={anaAvatar} alt="Ana"/><span><strong>Hablar con Ana</strong><small>Asistente de Fénix Capital</small></span></button></aside>
  <main className="ops-main"><header className="ops-top"><strong>Comunicaciones controladas</strong><div className="ops-top-actions"><div className="ops-profile"><strong>{role||'Usuario'}</strong></div></div></header><section className="ops-content">
   <div className="ops-title"><div><span className="ops-icon"><MessageCircle size={20}/></span><div><h1>Email y WhatsApp</h1><p>Preparar → revisar → autorizar → enviar → registrar resultado.</p></div></div><span className="ops-live ok">PRE-PROD seguro</span></div>
   <article className="ops-ana-card"><img src={anaAvatar} alt="Ana"/><div><strong>Ana</strong><p>El contenido puede generarse de forma viva. Ningún envío externo se ejecuta desde esta pantalla sin autorización previa.</p></div></article>
   {msg&&<div className="ops-message">{msg}</div>}
   <form className="ops-message" onSubmit={prepare} style={{display:'grid',gap:10}}><strong>Preparar nueva comunicación</strong><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10}}><label>Ámbito<select value={scopeType} onChange={e=>setScopeType(e.target.value)}><option value="expediente">Expediente</option><option value="inmobiliaria">Inmobiliaria</option></select></label><label>Código<input value={scopeCode} onChange={e=>setScopeCode(e.target.value)} required/></label><label>Canal<select value={canal} onChange={e=>setCanal(e.target.value)}><option>Email</option><option>WhatsApp</option></select></label><label>Destinatario<input value={recipient} onChange={e=>setRecipient(e.target.value)} required/></label></div>{canal==='Email'&&<label>Asunto<input value={subject} onChange={e=>setSubject(e.target.value)}/></label>}<label>Mensaje<textarea value={body} onChange={e=>setBody(e.target.value)} rows={5} required/></label><button className="primary" disabled={busy}><Mail size={16}/> Preparar para revisión</button></form>
   <div className="ops-table-card"><div className="ops-table-head"><strong>{items.length} comunicaciones visibles</strong><span>Sin datos inventados</span></div><div className="ops-table-wrap"><table><thead><tr><th>Canal</th><th>Ámbito</th><th>Destinatario</th><th>Estado</th><th>Versión</th><th>Acciones</th></tr></thead><tbody>{items.map(x=><tr key={x.communication_code}><td>{x.canal}</td><td>{x.scope_type} · {x.scope_code}</td><td>{x.recipient_alias}</td><td>{x.estado}</td><td>{x.version}</td><td style={{display:'flex',gap:6}}>{role==='Direccion'&&x.estado==='Preparada'&&<button onClick={()=>authorize(x)} disabled={busy}><ShieldCheck size={15}/> Autorizar</button>}{x.estado==='Autorizada'&&<button onClick={()=>simulate(x)} disabled={busy}><Send size={15}/> Simular</button>}{x.transport_test_status==='simulated_ok'?<CheckCircle2 size={17}/>:null}{x.last_error?<XCircle size={17}/>:null}</td></tr>)}</tbody></table></div></div>
  </section></main>
 </div>;
}
