import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Mail,MessageCircle,Phone,ShieldCheck,Send,CheckCircle2,XCircle} from 'lucide-react';
import {fetchAppApi,fetchEnvironmentApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import {applyAnaRelationalStyle} from './anaCommunicationStyle';
import './operational.css';
import './communications-shell.css';

type Theme='light'|'dark';
type AnyRow=Record<string,any>;
type Ctx={role?:string;context?:{role?:string}};
type Advice={action?:string|null;why?:string;client?:{name?:string|null;email?:string|null;phone?:string|null};channels?:{llamada?:{objetivo?:string;guion?:string;preguntas?:string[];resultado_esperado?:string}|null;whatsapp?:{texto?:string}|null;email?:{asunto?:string;cuerpo?:string}|null}};
type PendingAction={kind:'authorize'|'simulate'|'real';item:AnyRow}|null;
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
async function commApi(path:string,init?:RequestInit){return fetchEnvironmentApi<any>('fenix-communications-gateway',path,init,{productionAvailable:true});}
async function adviceApi(expedienteId:string){return fetchEnvironmentApi<Advice>('fenix-expediente-assistant',`/expedientes/${encodeURIComponent(expedienteId)}/advice`,undefined,{productionAvailable:false});}
function rowsFrom(data:unknown):AnyRow[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of ['items','contactos','results'])if(Array.isArray(d[k]))return d[k] as AnyRow[];return[];}
function first(r:AnyRow,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number')return String(v);}return'';}
function normalize(v:string){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9@.+ ]+/g,' ').replace(/\s+/g,' ').trim();}
const STOP=new Set(['manda','mandar','envia','enviar','email','correo','whatsapp','un','una','a','al','de','del','la','el','que','diciendo','dile','por','favor','te','le','les','para','con','y','documentacion','documento','documentos','docu']);
function meaningfulTokens(text:string){return normalize(text).split(' ').filter(x=>x.length>2&&!STOP.has(x));}
function cleanInstructionMessage(text:string){const m=text.match(/(?:diciendo(?:le)?\s+que|dile\s+que)\s+(.+)$/i);let x=(m?.[1]||text).trim();x=x.replace(/^(?:manda|envia|enviar|mandar)\s+(?:a\s+)?[^,]+,?\s*/i,'').trim();if(!x)return'';return x.charAt(0).toUpperCase()+x.slice(1).replace(/[.\s]+$/,'.');}
function draftBody(instruction:string,name:string,channel:string){const firstName=name.split(/\s+/)[0]||'';const message=cleanInstructionMessage(instruction)||'Te escribo en relación con la gestión que tenemos en curso.';if(channel==='WhatsApp')return `${firstName?`Hola ${firstName},`:'Hola,'}\n\n${message}\n\nQuedo pendiente. Gracias.`;return `${firstName?`Hola ${firstName},`:'Hola,'}\n\n${message}\n\nQuedo pendiente de cualquier comentario o de lo que necesites.\n\nUn saludo,\nFénix Capital`;}
function draftSubject(instruction:string){if(/document/i.test(instruction))return'Documentación · Fénix Capital';if(/tasaci/i.test(instruction))return'Tasación · Fénix Capital';if(/fein|firma/i.test(instruction))return'Operación hipotecaria · Fénix Capital';return'Fénix Capital';}

export default function CommunicationsShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname.replace(/\/+$/,'')==='/comunicaciones'||location.pathname.replace(/\/+$/,'')==='/comunicaciones/nueva';const params=useMemo(()=>new URLSearchParams(location.search),[location.search]);
 const initialChannel=params.get('channel')||'Email';const initialInstruction=params.get('instruction')||'';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false);const [role,setRole]=useState('');const [contextReady,setContextReady]=useState(false);const [items,setItems]=useState<AnyRow[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const[loading,setLoading]=useState(false);const[sourceStatus,setSourceStatus]=useState<number|null>(null);const [advice,setAdvice]=useState<Advice|null>(null);const[pending,setPending]=useState<PendingAction>(null);const[nav,setNav]=useState<NavItem[]>([]);const[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');const[query,setQuery]=useState('');const[correction,setCorrection]=useState('');const[reason,setReason]=useState('');
 const [scopeType,setScopeType]=useState(params.get('scope_type')||'expediente');const [scopeCode,setScopeCode]=useState(params.get('scope_code')||'');const [canal,setCanal]=useState(['Email','WhatsApp','Llamada'].includes(initialChannel)?initialChannel:'Email');const [recipient,setRecipient]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');const[instruction,setInstruction]=useState(initialInstruction);const[resolving,setResolving]=useState(false);const[recipientResolution,setRecipientResolution]=useState('');const[whatsappConsent,setWhatsappConsent]=useState(false);
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[]);
 async function load(){setLoading(true);setContextReady(false);setPending(null);setRole('');setItems([]);setAdvice(null);setMsg('');setSourceStatus(null);try{const[c,n]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]);setNav(n.status===200?normalizeNavigation(n.data):[]);if(c.status!==200){setContextReady(true);setSourceStatus(c.status);setMsg(c.status===0?'No se pudo conectar con el contexto autorizado.':c.status===403?'Tu perfil no tiene acceso al módulo de Comunicaciones.':'No se pudo validar el contexto autorizado.');return;}const nextRole=String(c.data?.context?.role??c.data?.role??'');setRole(nextRole);setContextReady(true);if(nextRole!=='Direccion'){setSourceStatus(403);setMsg('Tu perfil no tiene acceso al módulo de Comunicaciones.');return;}const ctx=await commApi('/comunicaciones');setSourceStatus(ctx.status);if(ctx.status===200){setItems(Array.isArray(ctx.data?.comunicaciones)?ctx.data.comunicaciones:Array.isArray(ctx.data?.items)?ctx.data.items:[]);setMsg('');}else if(ctx.status===403)setMsg('Tu perfil no tiene acceso al módulo de Comunicaciones.');else if(ctx.status===0)setMsg('No se pudo conectar con el servicio de comunicaciones.');else setMsg('No se pudieron cargar las comunicaciones.');}finally{setLoading(false)}}
 useEffect(()=>{if(active&&logged)void load()},[active,logged]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!contextReady||role!=='Direccion'||scopeType!=='expediente'||!scopeCode||instruction)return;let alive=true;setAdvice(null);adviceApi(scopeCode).then(r=>{if(!alive||r.status!==200||!r.data)return;const styled=applyAnaRelationalStyle({...r.data,name:r.data.client?.name});setAdvice(styled);applyDraft(canal,styled)});return()=>{alive=false}},[active,contextReady,role,scopeType,scopeCode,instruction]);
 useEffect(()=>{if(!active||!contextReady||role!=='Direccion'||!initialInstruction)return;void resolveInstruction(initialInstruction)},[active,contextReady,role]);
 function applyDraft(next:string,a=advice){setCanal(next);if(!a)return;if(next==='Email'){setRecipient(a.client?.email||'');setSubject(a.channels?.email?.asunto||'');setBody(a.channels?.email?.cuerpo||'')}else if(next==='WhatsApp'){setRecipient(a.client?.phone||'');setSubject('');setBody(a.channels?.whatsapp?.texto||'')}else{setRecipient(a.client?.phone||'');setSubject('');const x=a.channels?.llamada;setBody(x?`${x.guion||''}\n\nPreguntas clave:\n${(x.preguntas||[]).map(q=>`• ${q}`).join('\n')}\n\nResultado esperado: ${x.resultado_esperado||''}`:'')}}
 async function resolveInstruction(text=instruction){const value=text.trim();if(!value)return;setResolving(true);setRecipientResolution('');const inferred=/\bwhats?app\b/i.test(value)?'WhatsApp':/\b(email|correo)\b/i.test(value)?'Email':canal;setCanal(inferred);try{const r=await fetchNotionRuntime<unknown>('/contactos-bancarios');const rows=r.status===200?rowsFrom(r.data):[];const tokens=meaningfulTokens(value);const ranked=rows.map(row=>{const hay=normalize(Object.values(row).filter(v=>typeof v==='string'||typeof v==='number').join(' '));const score=tokens.reduce((n,t)=>n+(hay.includes(t)?1:0),0);return{row,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const top=ranked[0],second=ranked[1];if(top&&top.score>=1&&(!second||top.score>second.score)){const name=first(top.row,['nombre','name','contacto'])||'Contacto';const destination=inferred==='WhatsApp'?first(top.row,['telefono','phone','movil']):first(top.row,['email','correo']);if(destination){setRecipient(destination);setSubject(inferred==='Email'?draftSubject(value):'');setBody(draftBody(value,name,inferred));setRecipientResolution(`Destinatario identificado en la fuente canónica: ${name}. Revisa antes de enviar.`);}else{setRecipient('');setSubject(inferred==='Email'?draftSubject(value):'');setBody(draftBody(value,name,inferred));setRecipientResolution(`${name} coincide con la orden, pero no tiene ${inferred==='Email'?'email':'teléfono'} disponible. No se inventa ningún dato.`);}}else{setRecipient('');setSubject(inferred==='Email'?draftSubject(value):'');setBody(draftBody(value,'',inferred));setRecipientResolution(r.status===200?'No he encontrado un único destinatario. Elige o escribe el dato correcto antes de preparar.':'No se pudo consultar la fuente canónica de contactos. Escribe el destinatario manualmente antes de preparar.');}}finally{setResolving(false)}}
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 function prepareCorrection(){if(!correction.trim()||!reason.trim())return;const q=new URLSearchParams({mode:'help',resource:'comunicaciones',correction:correction.trim(),reason:reason.trim()});navigate(`/ana?${q.toString()}`)}
 async function prepare(e:FormEvent){e.preventDefault();if(role!=='Direccion'||sourceStatus!==200){setMsg('Tu perfil no puede preparar comunicaciones.');return;}if(canal==='Llamada'){setMsg('El guion de llamada está preparado. En esta fase la llamada se realiza manualmente y después se registra el resultado; Ana no marca una llamada como realizada sin evidencia.');return;}if(canal==='WhatsApp'&&!whatsappConsent){setMsg('Confirma primero que existe consentimiento válido para contactar por WhatsApp. No se ha enviado nada.');return;}setBusy(true);setMsg('');const r=await commApi('/comunicaciones/prepare',{method:'POST',body:JSON.stringify({scope_type:scopeType,scope_code:scopeCode,canal,recipient_alias:recipient,asunto:subject,cuerpo:body,consentimiento_requerido:canal==='WhatsApp',consentimiento_valido:canal==='WhatsApp'?whatsappConsent:false,no_contactar:false,idempotency_key:`ui-${scopeType}-${scopeCode}-${canal}-${Date.now()}`})});setBusy(false);if(r.status===200||r.status===201){setMsg('Comunicación preparada. Queda pendiente de revisión y autorización antes de cualquier envío.');void load()}else if(r.data?.error==='consent_required')setMsg('WhatsApp requiere consentimiento válido registrado antes de preparar el envío. No se ha enviado nada.');else setMsg(r.status===0?'No se pudo conectar con el servicio de comunicaciones.':`No se pudo preparar (${r.data?.error||r.status}).`)}
 async function authorize(x:AnyRow){if(role!=='Direccion'||sourceStatus!==200)return;setBusy(true);const r=await commApi(`/comunicaciones/${encodeURIComponent(x.communication_code)}/authorize`,{method:'POST',body:JSON.stringify({expectedVersion:x.version,payload_hash:x.payload_hash})});setBusy(false);setPending(null);setMsg(r.status===200?'Comunicación autorizada. Ya puedes revisar el envío real.':r.status===0?'No se pudo conectar con el servicio de comunicaciones.':`No autorizada (${r.data?.error||r.status}).`);void load()}
 async function simulate(x:AnyRow){if(role!=='Direccion'||sourceStatus!==200)return;setBusy(true);const r=await commApi(`/comunicaciones/${encodeURIComponent(x.communication_code)}/send`,{method:'POST',body:JSON.stringify({expectedVersion:x.version,payload_hash:x.payload_hash,idempotency_key:`sim-${x.communication_code}`,mode:'SIMULATED'})});setBusy(false);setPending(null);setMsg(r.status===200?'Simulación completada sin envío externo.':r.status===0?'No se pudo conectar con el servicio de comunicaciones.':`Simulación bloqueada (${r.data?.error||r.status}).`);void load()}
 async function sendReal(x:AnyRow){if(role!=='Direccion'||sourceStatus!==200)return;setBusy(true);const r=await commApi(`/comunicaciones/${encodeURIComponent(x.communication_code)}/send`,{method:'POST',body:JSON.stringify({expectedVersion:x.version,payload_hash:x.payload_hash,idempotency_key:`real-${x.communication_code}-${x.version}`,mode:'REAL'})});setBusy(false);setPending(null);if(r.status===200)setMsg('Envío real completado y registrado.');else if(r.data?.error==='whatsapp_not_configured')setMsg('WhatsApp todavía no está operativo en Meta/Supabase. No se ha enviado nada.');else if(r.data?.error==='brevo_not_configured')setMsg('Brevo todavía no está configurado completamente. No se ha enviado nada.');else setMsg(r.status===0?'No se pudo conectar con el servicio de comunicaciones.':`Envío real bloqueado (${r.data?.error||r.status}).`);void load()}
 async function confirmPending(){if(!pending||busy)return;if(pending.kind==='authorize')await authorize(pending.item);else if(pending.kind==='real')await sendReal(pending.item);else await simulate(pending.item)}
 const pendingItem=pending?.item;const effectiveNav=nav.length?nav:fallbackNav;const visibleItems=sourceStatus===200?items.filter(x=>{const q=query.trim().toLowerCase();return !q||Object.values(x).join(' ').toLowerCase().includes(q)}):[];
 return <OperationalShellFrame className="comm-root" theme={theme} navigation={effectiveNav} activeRoute="/comunicaciones" anaSubtitle="Te ayuda a revisar antes de comunicar." anaRoute="/ana" query={query} onQueryChange={setQuery} searchPlaceholder="Buscar comunicación, canal o destinatario..." name={role||'Usuario'} role="" initials={(role||'Usuario').slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="comm-content">
   <section className="comm-ana-hero"><div className="comm-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="comm-ana-body"><span>ANA · COMUNICACIONES</span><h2>Revisamos antes de enviar</h2><p>{advice?.action?<>La acción pendiente es <b>{advice.action}</b>. {advice.why} Ana adapta el mensaje con empatía, preguntas útiles y un siguiente paso claro.</>:'Puedes darle una orden natural a Ana desde cualquier pantalla. Ana intenta identificar al destinatario con datos existentes y nunca inventa un correo o teléfono.'}</p></div><article className="comm-correct"><span>CORREGIR A ANA</span><h3>¿En qué me equivoco?</h3><p>Preparo tu corrección con contexto para revisión; no modifica reglas automáticamente.</p><textarea rows={3} value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="Qué cambiarías..."/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo de la corrección"/><button disabled={!correction.trim()||!reason.trim()} onClick={prepareCorrection}>Preparar para revisión</button></article></section>
   <div className="ops-title"><div><span className="ops-icon"><MessageCircle size={20}/></span><div><h1>Llamada, WhatsApp y Email</h1><p>Ana enseña primero exactamente qué diría o escribiría. El envío real solo ocurre después de tu autorización y confirmación final.</p></div></div><span className={sourceStatus===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':sourceStatus===200?'Servicio disponible':'Sin conexión'}</span></div>
   {loading&&<div className="ops-empty" data-testid="communications-loading"><strong>Cargando…</strong><span>Validando contexto y comunicaciones autorizadas.</span></div>}
   {!loading&&msg&&<div className="ops-message" data-testid={sourceStatus===403?'communications-forbidden':sourceStatus!==null&&sourceStatus!==200?'communications-error':undefined}>{msg}</div>}
   {!loading&&contextReady&&role==='Direccion'&&sourceStatus===200&&<><form className="ops-message comm-form" onSubmit={prepare}><strong>Vista previa exacta antes de actuar</strong><label>Orden dada a Ana<textarea aria-label="Orden de comunicación" value={instruction} onChange={e=>setInstruction(e.target.value)} rows={3} placeholder="Ej.: Manda a Elena de BBVA un email diciendo que te mando la documentación."/></label><div className="comm-actions"><button type="button" onClick={()=>void resolveInstruction()} disabled={busy||resolving||!instruction.trim()}>{resolving?'Buscando…':'Interpretar orden y localizar destinatario'}</button></div>{recipientResolution&&<div className="ops-message comm-reason" data-testid="communication-recipient-resolution"><b>Ana:</b> {recipientResolution}</div>}<div className="comm-form-grid"><label>Ámbito<select value={scopeType} onChange={e=>setScopeType(e.target.value)}><option value="expediente">Expediente</option><option value="contacto">Contacto</option><option value="contacto_b2b">Contacto B2B</option><option value="inmobiliaria">Inmobiliaria</option><option value="banco">Banco</option><option value="tasacion">Tasación</option><option value="firma">Firma</option><option value="documento">Documento</option><option value="tarea">Tarea</option><option value="general">General</option></select></label><label>Código / contexto<input value={scopeCode} onChange={e=>setScopeCode(e.target.value)} required={scopeType!=='general'}/></label><label>Canal<select value={canal} onChange={e=>applyDraft(e.target.value)}><option>Email</option><option>WhatsApp</option><option>Llamada</option></select></label><label>{canal==='Email'?'Destinatario email':'Teléfono / destinatario'}<input value={recipient} onChange={e=>setRecipient(e.target.value)} required/></label></div>{canal==='Email'&&<label>Asunto<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label>}<label>{canal==='Llamada'?'Guion exacto de la llamada':'Texto exacto que se preparará'}<textarea value={body} onChange={e=>setBody(e.target.value)} rows={canal==='Llamada'?10:7} required/></label>{canal==='WhatsApp'&&<label className="ops-message comm-reason"><input type="checkbox" checked={whatsappConsent} onChange={e=>setWhatsappConsent(e.target.checked)}/> Confirmo que existe consentimiento válido para contactar a este destinatario por WhatsApp. Esta confirmación se registra en la preparación y nunca viene marcada por defecto.</label>}<div className="ops-message comm-reason"><b>Motivo:</b> {advice?.why||instruction||'Todavía no hay motivo calculado para este contexto.'}</div><button className="primary" disabled={busy}>{canal==='Llamada'?<Phone size={16}/>:<Mail size={16}/>} {canal==='Llamada'?'Usar este guion y registrar resultado':'Preparar para revisión'}</button></form>
   {pending&&pendingItem&&<div className="ops-message" data-testid="communication-transition-preview"><strong>{pending.kind==='authorize'?'Revisar autorización':pending.kind==='real'?'Revisar envío real':'Revisar simulación'}</strong><p>{pending.kind==='real'?'Al confirmar, este mensaje SE ENVIARÁ realmente al destinatario mediante el proveedor configurado.':'No se ejecutará ningún cambio hasta confirmar.'}</p><div>Canal: {pendingItem.canal||'—'}</div><div>Ámbito: {pendingItem.scope_type||'—'} · {pendingItem.scope_code||'—'}</div><div>Destinatario: {pendingItem.recipient_alias||'—'}</div>{pendingItem.asunto&&<div>Asunto: {pendingItem.asunto}</div>}{pendingItem.cuerpo&&<div style={{whiteSpace:'pre-wrap'}}>Mensaje: {pendingItem.cuerpo}</div>}<div>Estado actual: {pendingItem.estado||'—'}</div><div>Versión: {pendingItem.version??'—'}</div><div className="comm-actions"><button type="button" onClick={()=>setPending(null)} disabled={busy}>Cancelar</button><button type="button" className="primary" onClick={()=>void confirmPending()} disabled={busy}>{pending.kind==='authorize'?<ShieldCheck size={15}/>:<Send size={15}/>} {busy?'Procesando…':pending.kind==='authorize'?'Confirmar autorización':pending.kind==='real'?'Mandar ahora':'Confirmar simulación'}</button></div></div>}
   <div className="ops-table-card"><div className="ops-table-head"><strong>{visibleItems.length} comunicaciones visibles</strong><span>Sin datos inventados</span></div><div className="ops-table-wrap"><table><thead><tr><th>Canal</th><th>Ámbito</th><th>Destinatario</th><th>Estado</th><th>Versión</th><th>Acciones</th></tr></thead><tbody>{visibleItems.map(x=><tr key={x.communication_code}><td>{x.canal}</td><td>{x.scope_type} · {x.scope_code}</td><td>{x.recipient_alias}</td><td>{x.estado}</td><td>{x.version}</td><td className="comm-row-actions">{x.estado==='Preparada'&&<button type="button" onClick={()=>setPending({kind:'authorize',item:x})} disabled={busy}><ShieldCheck size={15}/> Revisar autorización</button>}{x.estado==='Autorizada'&&<><button type="button" className="primary" onClick={()=>setPending({kind:'real',item:x})} disabled={busy}><Send size={15}/> Revisar envío real</button><button type="button" onClick={()=>setPending({kind:'simulate',item:x})} disabled={busy}>Revisar simulación</button></>}{x.transport_status==='sent'||x.estado==='Enviada'?<CheckCircle2 size={17}/>:null}{x.transport_test_status==='simulated_ok'?<CheckCircle2 size={17}/>:null}{x.last_error?<XCircle size={17}/>:null}</td></tr>)}</tbody></table></div></div></>}
 </OperationalShellFrame>;
}
