import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Mail,MessageCircle,Phone,ShieldCheck,Send,CheckCircle2,XCircle,LogOut,Moon,Search,Sun} from 'lucide-react';
import {fetchAppApi,SUPABASE_URL,supabase} from './supabase';
import {anaAvatar,anaVertical,fenixLogo} from './assets/visualAssets';
import './operational.css';
import './communications-shell.css';

type Theme='light'|'dark';
type AnyRow=Record<string,any>;
type NavItem={label:string;route:string};
type Ctx={role?:string;context?:{role?:string}};
type Advice={action?:string|null;why?:string;client?:{name?:string|null;email?:string|null;phone?:string|null};channels?:{llamada?:{objetivo?:string;guion?:string;preguntas?:string[];resultado_esperado?:string}|null;whatsapp?:{texto?:string}|null;email?:{asunto?:string;cuerpo?:string}|null}};
type PendingAction={kind:'authorize'|'simulate';item:AnyRow}|null;
function normalizeNav(data:unknown):NavItem[]{if(!data||typeof data!=='object')return[];const items=(data as{items?:unknown[]}).items;if(!Array.isArray(items))return[];return items.map(x=>{if(typeof x==='string')return{label:x.replace(/^\//,'')||'Inicio',route:x};if(x&&typeof x==='object'){const o=x as Record<string,unknown>;if(typeof o.route==='string')return{label:typeof o.label==='string'&&o.label.trim()?o.label:o.route.replace(/^\//,''),route:o.route};}return null;}).filter((x):x is NavItem=>Boolean(x));}
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
async function commApi(path:string,init?:RequestInit){try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return {status:401,data:null as any};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-communications-gateway-test${path}`,{...init,headers:{'content-type':'application/json',...(init?.headers||{}),Authorization:`Bearer ${session.access_token}`}});let data:any=null;try{data=await r.json()}catch{}return {status:r.status,data};}catch{return{status:0,data:null as any}}}
async function adviceApi(expedienteId:string){try{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return{status:401,data:null as Advice|null};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-expediente-assistant-test/expedientes/${encodeURIComponent(expedienteId)}/advice`,{headers:{Authorization:`Bearer ${session.access_token}`}});let data:Advice|null=null;try{data=await r.json()}catch{}return{status:r.status,data}}catch{return{status:0,data:null as Advice|null}}}

export default function CommunicationsShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname.replace(/\/+$/,'')==='/comunicaciones'||location.pathname.replace(/\/+$/,'')==='/comunicaciones/nueva';const params=useMemo(()=>new URLSearchParams(location.search),[location.search]);
 const initialChannel=params.get('channel')||'Email';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false);const [role,setRole]=useState('');const [contextReady,setContextReady]=useState(false);const [items,setItems]=useState<AnyRow[]>([]);const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const[loading,setLoading]=useState(false);const[sourceStatus,setSourceStatus]=useState<number|null>(null);const [advice,setAdvice]=useState<Advice|null>(null);const[pending,setPending]=useState<PendingAction>(null);const[nav,setNav]=useState<NavItem[]>([]);const[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');const[query,setQuery]=useState('');const[correction,setCorrection]=useState('');const[reason,setReason]=useState('');
 const [scopeType,setScopeType]=useState(params.get('scope_type')||'expediente');const [scopeCode,setScopeCode]=useState(params.get('scope_code')||'');const [canal,setCanal]=useState(['Email','WhatsApp','Llamada'].includes(initialChannel)?initialChannel:'Email');const [recipient,setRecipient]=useState('');const [subject,setSubject]=useState('');const [body,setBody]=useState('');
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[]);
 async function load(){setLoading(true);setContextReady(false);setPending(null);setRole('');setItems([]);setAdvice(null);setMsg('');setSourceStatus(null);try{const[c,n]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]);setNav(n.status===200?normalizeNav(n.data):[]);if(c.status!==200){setContextReady(true);setSourceStatus(c.status);setMsg(c.status===0?'No se pudo conectar con el contexto autorizado.':c.status===403?'Tu perfil no tiene acceso al módulo de Comunicaciones.':'No se pudo validar el contexto autorizado.');return;}const nextRole=String(c.data?.context?.role??c.data?.role??'');setRole(nextRole);setContextReady(true);if(nextRole!=='Direccion'){setSourceStatus(403);setMsg('Tu perfil no tiene acceso al módulo de Comunicaciones.');return;}const ctx=await commApi('/comunicaciones');setSourceStatus(ctx.status);if(ctx.status===200){setItems(Array.isArray(ctx.data?.comunicaciones)?ctx.data.comunicaciones:Array.isArray(ctx.data?.items)?ctx.data.items:[]);setMsg('');}else if(ctx.status===403)setMsg('Tu perfil no tiene acceso al módulo de Comunicaciones.');else if(ctx.status===0)setMsg('No se pudo conectar con el servicio de comunicaciones.');else setMsg('No se pudieron cargar las comunicaciones.');}finally{setLoading(false)}}
 useEffect(()=>{if(active&&logged)void load()},[active,logged]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!contextReady||role!=='Direccion'||scopeType!=='expediente'||!scopeCode)return;let alive=true;setAdvice(null);adviceApi(scopeCode).then(r=>{if(!alive||r.status!==200||!r.data)return;setAdvice(r.data);applyDraft(canal,r.data)});return()=>{alive=false}},[active,contextReady,role,scopeType,scopeCode]);
 function applyDraft(next:string,a=advice){setCanal(next);if(!a)return;if(next==='Email'){setRecipient(a.client?.email||'');setSubject(a.channels?.email?.asunto||'');setBody(a.channels?.email?.cuerpo||'')}else if(next==='WhatsApp'){setRecipient(a.client?.phone||'');setSubject('');setBody(a.channels?.whatsapp?.texto||'')}else{setRecipient(a.client?.phone||'');setSubject('');const x=a.channels?.llamada;setBody(x?`${x.guion||''}\n\nPreguntas clave:\n${(x.preguntas||[]).map(q=>`• ${q}`).join('\n')}\n\nResultado esperado: ${x.resultado_esperado||''}`:'')}}
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 function prepareCorrection(){if(!correction.trim()||!reason.trim())return;const q=new URLSearchParams({mode:'help',resource:'comunicaciones',correction:correction.trim(),reason:reason.trim()});navigate(`/ana?${q.toString()}`)}
 async function prepare(e:FormEvent){e.preventDefault();if(role!=='Direccion'||sourceStatus!==200){setMsg('Tu perfil no puede preparar comunicaciones.');return;}if(canal==='Llamada'){setMsg('El guion de llamada está preparado. En esta fase la llamada se realiza manualmente y después se registra el resultado; Ana no marca una llamada como realizada sin evidencia.');return;}setBusy(true);setMsg('');const r=await commApi('/comunicaciones/prepare',{method:'POST',body:JSON.stringify({scope_type:scopeType,scope_code:scopeCode,canal,recipient_alias:recipient,asunto:subject,cuerpo:body,consentimiento_requerido:canal==='WhatsApp',consentimiento_valido:false,no_contactar:false,idempotency_key:`ui-${scopeType}-${scopeCode}-${canal}-${Date.now()}`})});setBusy(false);if(r.status===200||r.status===201){setMsg('Comunicación preparada. Queda pendiente de revisión y autorización antes de cualquier envío.');void load()}else setMsg(r.status===0?'No se pudo conectar con el servicio de comunicaciones.':`No se pudo preparar (${r.data?.error||r.status}).`)}
 async function authorize(x:AnyRow){if(role!=='Direccion'||sourceStatus!==200)return;setBusy(true);const r=await commApi(`/comunicaciones/${encodeURIComponent(x.communication_code)}/authorize`,{method:'POST',body:JSON.stringify({expectedVersion:x.version,payload_hash:x.payload_hash})});setBusy(false);setPending(null);setMsg(r.status===200?'Comunicación autorizada.':r.status===0?'No se pudo conectar con el servicio de comunicaciones.':`No autorizada (${r.data?.error||r.status}).`);void load()}
 async function simulate(x:AnyRow){if(role!=='Direccion'||sourceStatus!==200)return;setBusy(true);const r=await commApi(`/comunicaciones/${encodeURIComponent(x.communication_code)}/send`,{method:'POST',body:JSON.stringify({expectedVersion:x.version,payload_hash:x.payload_hash,idempotency_key:`sim-${x.communication_code}`,mode:'SIMULATED'})});setBusy(false);setPending(null);setMsg(r.status===200?'Simulación completada sin envío externo.':r.status===0?'No se pudo conectar con el servicio de comunicaciones.':`Simulación bloqueada (${r.data?.error||r.status}).`);void load()}
 async function confirmPending(){if(!pending||busy)return;if(pending.kind==='authorize')await authorize(pending.item);else await simulate(pending.item)}
 const pendingItem=pending?.item;const effectiveNav=nav.length?nav:fallbackNav;const visibleItems=sourceStatus===200?items.filter(x=>{const q=query.trim().toLowerCase();return !q||Object.values(x).join(' ').toLowerCase().includes(q)}):[];
 return <div className="ops-root comm-root" data-theme={theme}>
  <aside className="ops-side"><button className="ops-brand" onClick={()=>navigate('/inicio')}><img src={fenixLogo} alt=""/><strong>FÉNIX CAPITAL</strong></button><nav>{effectiveNav.map(item=><button key={item.route} className={item.route==='/comunicaciones'?'active':''} onClick={()=>navigate(item.route)}>{item.label}</button>)}</nav><button className="ops-ana" onClick={()=>navigate('/ana')}><img src={anaAvatar} alt="Ana"/><span><strong>Ana está contigo</strong><small>Te ayuda a revisar antes de comunicar.</small></span></button></aside>
  <main className="ops-main"><header className="ops-top"><div className="ops-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar comunicación, canal o destinatario..."/></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Cambiar tema">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{role||'Usuario'}</strong></div><button onClick={logout} aria-label="Cerrar sesión"><LogOut size={17}/></button></div></header><section className="ops-content comm-content">
   <section className="comm-ana-hero"><div className="comm-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="comm-ana-body"><span>ANA · COMUNICACIONES</span><h2>Revisamos antes de enviar</h2><p>{advice?.action?<>La acción pendiente es <b>{advice.action}</b>. {advice.why}</>:'Selecciona el expediente o inmobiliaria. Si existe una siguiente acción canónica, prepararé el guion o mensaje sin inventar una nueva.'}</p></div><article className="comm-correct"><span>CORREGIR A ANA</span><h3>¿En qué me equivoco?</h3><p>Preparo tu corrección con contexto para revisión; no modifica reglas automáticamente.</p><textarea rows={3} value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="Qué cambiarías..."/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo de la corrección"/><button disabled={!correction.trim()||!reason.trim()} onClick={prepareCorrection}>Preparar para revisión</button></article></section>
   <div className="ops-title"><div><span className="ops-icon"><MessageCircle size={20}/></span><div><h1>Llamada, WhatsApp y Email</h1><p>Ana enseña primero exactamente qué diría o escribiría. Después se revisa y, cuando proceda, se autoriza.</p></div></div><span className={sourceStatus===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':sourceStatus===200?'PRE-PROD seguro':'PRE-PROD'}</span></div>
   {loading&&<div className="ops-empty" data-testid="communications-loading"><strong>Cargando…</strong><span>Validando contexto y comunicaciones autorizadas.</span></div>}
   {!loading&&msg&&<div className="ops-message" data-testid={sourceStatus===403?'communications-forbidden':sourceStatus!==null&&sourceStatus!==200?'communications-error':undefined}>{msg}</div>}
   {!loading&&contextReady&&role==='Direccion'&&sourceStatus===200&&<><form className="ops-message comm-form" onSubmit={prepare}><strong>Vista previa exacta antes de actuar</strong><div className="comm-form-grid"><label>Ámbito<select value={scopeType} onChange={e=>setScopeType(e.target.value)}><option value="expediente">Expediente</option><option value="inmobiliaria">Inmobiliaria</option></select></label><label>Código<input value={scopeCode} onChange={e=>setScopeCode(e.target.value)} required/></label><label>Canal<select value={canal} onChange={e=>applyDraft(e.target.value)}><option>Email</option><option>WhatsApp</option><option>Llamada</option></select></label><label>{canal==='Email'?'Destinatario email':'Teléfono / destinatario'}<input value={recipient} onChange={e=>setRecipient(e.target.value)} required/></label></div>{canal==='Email'&&<label>Asunto<input value={subject} onChange={e=>setSubject(e.target.value)} required/></label>}<label>{canal==='Llamada'?'Guion exacto de la llamada':'Texto exacto que se preparará'}<textarea value={body} onChange={e=>setBody(e.target.value)} rows={canal==='Llamada'?10:7} required/></label><div className="ops-message comm-reason"><b>Motivo:</b> {advice?.why||'Todavía no hay motivo canónico calculado para este contexto.'}</div><button className="primary" disabled={busy}>{canal==='Llamada'?<Phone size={16}/>:<Mail size={16}/>} {canal==='Llamada'?'Usar este guion y registrar resultado':'Preparar para revisión'}</button></form>
   {pending&&pendingItem&&<div className="ops-message" data-testid="communication-transition-preview"><strong>{pending.kind==='authorize'?'Revisar autorización':'Revisar simulación'}</strong><p>No se ejecutará ningún cambio hasta confirmar.</p><div>Canal: {pendingItem.canal||'—'}</div><div>Ámbito: {pendingItem.scope_type||'—'} · {pendingItem.scope_code||'—'}</div><div>Destinatario: {pendingItem.recipient_alias||'—'}</div><div>Estado actual: {pendingItem.estado||'—'}</div><div>Versión: {pendingItem.version??'—'}</div><div className="comm-actions"><button type="button" onClick={()=>setPending(null)} disabled={busy}>Cancelar</button><button type="button" className="primary" onClick={()=>void confirmPending()} disabled={busy}>{pending.kind==='authorize'?<ShieldCheck size={15}/>:<Send size={15}/>} {busy?'Procesando…':pending.kind==='authorize'?'Confirmar autorización':'Confirmar simulación'}</button></div></div>}
   <div className="ops-table-card"><div className="ops-table-head"><strong>{visibleItems.length} comunicaciones visibles</strong><span>Sin datos inventados</span></div><div className="ops-table-wrap"><table><thead><tr><th>Canal</th><th>Ámbito</th><th>Destinatario</th><th>Estado</th><th>Versión</th><th>Acciones</th></tr></thead><tbody>{visibleItems.map(x=><tr key={x.communication_code}><td>{x.canal}</td><td>{x.scope_type} · {x.scope_code}</td><td>{x.recipient_alias}</td><td>{x.estado}</td><td>{x.version}</td><td className="comm-row-actions">{x.estado==='Preparada'&&<button type="button" onClick={()=>setPending({kind:'authorize',item:x})} disabled={busy}><ShieldCheck size={15}/> Revisar autorización</button>}{x.estado==='Autorizada'&&<button type="button" onClick={()=>setPending({kind:'simulate',item:x})} disabled={busy}><Send size={15}/> Revisar simulación</button>}{x.transport_test_status==='simulated_ok'?<CheckCircle2 size={17}/>:null}{x.last_error?<XCircle size={17}/>:null}</td></tr>)}</tbody></table></div></div></>}
  </section></main>
 </div>;
}
