import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './contactos-polish.css';
import './inmobiliarias-polish.css';
import './sortable-table.css';

type Theme='light'|'dark';type Ctx={actor_code?:string;role?:string};type Row=Record<string,unknown>;type ContactMode='clientes'|'b2b';type SortKey='nombre'|'relacion'|'vinculo'|'seguimiento';type SortDir='asc'|'desc';type Focus='todos'|'seguimiento'|'sin-accion'|'formalizados';
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;return Array.isArray(d.items)?d.items as Row[]:[];}
function text(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function bool(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='boolean')return v;if(typeof v==='string'){const s=v.toLowerCase();if(['sí','si','true','yes'].includes(s))return true;if(['no','false'].includes(s))return false;}}return null;}
function idOf(row:Row){return text(row,['id','contact_id','contacto_id','contact_key']);}function stateOf(row:Row){return text(row,['estado','estado_comercial','estado_relacion','relacion','relación','activo']);}function phaseOf(row:Row){return text(row,['fase','fase_vinculada','expediente_fase']);}function followOf(row:Row){return text(row,['proxima_accion','próxima_acción','siguiente_accion','siguiente_acción','proximo_contacto','próximo_contacto','seguimiento','ultimo_contacto','último_contacto']);}function nameOf(row:Row){return text(row,['cliente','nombre','nombre_alias','contacto','contacto_inmobiliaria','title'])||'Contacto sin nombre';}function relationOf(row:Row){return text(row,['relacion','relación','tipo','perfil','estado_comercial','cargo'])||'—';}function expedienteOf(row:Row){return text(row,['expediente','expediente_code','codigo_expediente','código_expediente'])||'—';}function inmoOf(row:Row){return text(row,['inmobiliaria','inmobiliaria_nombre','nombre_inmobiliaria'])||'—';}function compareText(a:string,b:string){return a.localeCompare(b,'es',{sensitivity:'base',numeric:true});}
function roleKind(role?:string,actorCode?:string){const actor=(actorCode||'').toUpperCase();if(actor==='DIR-TEST'||actor==='CARLOS-ADMIN')return'direccion';const r=(role||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return r==='direccion'?'direccion':r==='visitador'?'visitador':r==='financiero'?'financiero':'otro';}
function needsFollow(r:Row){return bool(r,['requiere_seguimiento'])===true||/seguimiento|contactar|pendiente/i.test(`${stateOf(r)} ${followOf(r)}`)}function formalized(r:Row){return /formaliz|firmad|cerrad/i.test(stateOf(r))}

export default function ContactosShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/contactos';
 const[sessionReady,setSessionReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[mode,setMode]=useState<ContactMode>('clientes'),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const[state,setState]=useState(''),[phase,setPhase]=useState(''),[focus,setFocus]=useState<Focus>('todos'),[sortKey,setSortKey]=useState<SortKey>('nombre'),[sortDir,setSortDir]=useState<SortDir>('asc'),[globalQuery,setGlobalQuery]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setSessionReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setSessionReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);});return()=>{alive=false};},[active,logged]);
 const kind=roleKind(ctx?.role,ctx?.actor_code),isDirection=kind==='direccion',isVisitador=kind==='visitador';const effectiveMode:ContactMode=isVisitador?'b2b':kind==='financiero'?'clientes':mode;
 useEffect(()=>{if(!active||!logged||!ctx||kind==='otro')return;let alive=true;(async()=>{setLoading(true);setMessage('');setRows([]);setStatus(null);const endpoint=effectiveMode==='b2b'?'/contactos-inmobiliaria':'/clientes';const r=await fetchNotionRuntime<unknown>(endpoint);if(!alive)return;setStatus(r.status);setRows(r.status===200?rowsFrom(r.data):[]);if(r.status===403)setMessage(effectiveMode==='b2b'?'Tu perfil no tiene acceso a contactos B2B fuera de su cartera o zona autorizada.':'Tu perfil no tiene acceso a clientes hipotecarios fuera de su ámbito.');else if(r.status!==200)setMessage('No se pudo leer la información actualizada de Contactos.');setLoading(false);})();return()=>{alive=false}},[active,logged,ctx,kind,effectiveMode]);
 const effectiveNav=nav.length?nav:fallbackNav,states=useMemo(()=>Array.from(new Set(rows.map(stateOf).filter(Boolean))).sort(compareText),[rows]),phases=useMemo(()=>Array.from(new Set(rows.map(phaseOf).filter(Boolean))).sort(compareText),[rows]);
 const visible=useMemo(()=>{const out=rows.filter(r=>(!state||stateOf(r)===state)&&(!phase||phaseOf(r)===phase)&&(focus==='todos'||(focus==='seguimiento'&&needsFollow(r))||(focus==='sin-accion'&&!followOf(r))||(focus==='formalizados'&&formalized(r))));const direction=sortDir==='asc'?1:-1;return[...out].sort((a,b)=>{let result=0;if(sortKey==='relacion')result=compareText(relationOf(a),relationOf(b));else if(sortKey==='vinculo')result=compareText(effectiveMode==='b2b'?inmoOf(a):expedienteOf(a),effectiveMode==='b2b'?inmoOf(b):expedienteOf(b));else if(sortKey==='seguimiento')result=compareText(followOf(a),followOf(b));else result=compareText(nameOf(a),nameOf(b));if(result===0)result=compareText(nameOf(a),nameOf(b));return result*direction;});},[rows,state,phase,focus,sortKey,sortDir,effectiveMode]);
 const seguimiento=useMemo(()=>rows.filter(needsFollow).length,[rows]),formalizados=useMemo(()=>rows.filter(formalized).length,[rows]),sinProxima=useMemo(()=>rows.filter(r=>!followOf(r)).length,[rows]);
 const stateRank=useMemo(()=>{const m=new Map<string,number>();rows.forEach(r=>{const x=stateOf(r)||'Sin estado';m.set(x,(m.get(x)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[rows]),maxState=useMemo(()=>Math.max(1,...stateRank.map(([,n])=>n)),[stateRank]);
 if(!active||!sessionReady||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}function switchMode(next:ContactMode){if(!isDirection)return;setState('');setPhase('');setFocus('todos');setSortKey('nombre');setSortDir('asc');setMode(next);}function applySort(key:SortKey){if(sortKey===key)setSortDir(v=>v==='asc'?'desc':'asc');else{setSortKey(key);setSortDir('asc')}}function sortArrow(key:SortKey){return sortKey===key?(sortDir==='asc'?'↑':'↓'):''}function ariaSort(key:SortKey){return sortKey===key?(sortDir==='asc'?'ascending':'descending'):undefined}function globalSearch(){const q=globalQuery.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 const role=ctx?.role||'Usuario',anaSummary=loading?'Estoy revisando tus contactos autorizados.':status!==200?'No tengo datos suficientes para priorizar contactos.':seguimiento?`Hay ${seguimiento} contactos que necesitan seguimiento. Empezaría por ellos.`:sinProxima?`Hay ${sinProxima} contactos sin siguiente acción registrada. Conviene cerrar ese hueco antes de abrir más seguimientos.`:`Veo ${rows.length} contactos y no detecto seguimientos urgentes con la información disponible.`;
 return <OperationalShellFrame className="inmo-root contactos-root" theme={theme} navigation={effectiveNav} activeRoute="/contactos" anaSubtitle="Cuando quieras, avanzamos paso a paso." query={globalQuery} onQueryChange={setGlobalQuery} searchPlaceholder="Buscar en toda la app..." searchActionLabel="Buscar" onSearchAction={globalSearch} name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content contactos-content">
  <section className="inmo-ana-hero contactos-ana-hero"><div className="inmo-ana-photo contactos-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · CONTACTOS</span><h2>Esto es lo que toca ahora</h2><p>{anaSummary}</p><div className="inmo-next contactos-next"><button onClick={()=>setFocus('seguimiento')}><b>1</b><strong>Atender seguimientos</strong><small>{seguimiento} contactos →</small></button><button onClick={()=>setFocus('sin-accion')}><b>2</b><strong>Completar siguiente acción</strong><small>{sinProxima} contactos →</small></button><button onClick={()=>navigate('/comunicaciones')}><b>3</b><strong>Preparar mensajes</strong><small>Abrir comunicaciones →</small></button></div></div><article className="inmo-correct"><span>CONTROL DE CONTACTOS</span><h3>Qué necesita atención</h3><p>{effectiveMode==='b2b'?'Relaciones B2B dentro de tu ámbito autorizado.':'Clientes hipotecarios y su siguiente paso.'}</p><textarea readOnly rows={3} value={`${seguimiento} contactos necesitan seguimiento`}/><input readOnly value={`${sinProxima} sin siguiente acción`}/><button onClick={()=>navigate('/ana?mode=help&resource=contactos')}>Revisar con Ana</button></article></section>
  <div className="contactos-title inmo-title"><div><small>{effectiveMode==='b2b'?'RELACIONES B2B AUTORIZADAS':'RELACIONES Y SEGUIMIENTO'}</small><h1>Contactos</h1><p>{status===200?`${rows.length} ${effectiveMode==='b2b'?'contactos B2B':'clientes hipotecarios'} visibles en tu ámbito autorizado.`:'Información disponible según permisos.'}</p></div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos actualizados':'Sin conexión'}</span>{effectiveMode==='clientes'&&!isVisitador?<button className="primary" onClick={()=>navigate('/contactos/nuevo')}>+ Nuevo contacto</button>:<button className="primary" onClick={()=>navigate('/inmobiliarias')}>+ Nuevo contacto B2B</button>}</div></div>
  {isDirection&&<div className="ops-message" data-testid="contact-scope-tabs" style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><strong>Ámbito de contactos</strong><button className={effectiveMode==='clientes'?'primary':''} onClick={()=>switchMode('clientes')}>Clientes hipotecarios</button><button className={effectiveMode==='b2b'?'primary':''} onClick={()=>switchMode('b2b')}>Contactos inmobiliaria</button></div>}
  {loading?<div className="ops-empty" data-testid="contact-loading"><strong>Cargando contactos…</strong><span>Consultando la información autorizada.</span></div>:message?<div className="ops-message" data-testid={status===403?'contact-forbidden':'contact-error'}>{message}</div>:null}
  {!loading&&status===200&&<><section className="inmo-kpis contactos-kpis"><article><small>CONTACTOS</small><strong>{rows.length}</strong><span>Visibles</span></article><article><small>CON SEGUIMIENTO</small><strong>{seguimiento}</strong><span>Necesitan atención</span></article><article><small>{effectiveMode==='b2b'?'B2B VISIBLES':'FORMALIZADOS'}</small><strong>{effectiveMode==='b2b'?rows.length:formalizados}</strong><span>Según estado disponible</span></article><article><small>SIN PRÓXIMA ACCIÓN</small><strong>{sinProxima}</strong><span>Necesitan siguiente paso</span></article></section><section className="inmo-insights inmo-live-charts"><article><span>DISTRIBUCIÓN POR ESTADO</span><h2>Situación de contactos</h2><div className="inmo-bars">{stateRank.map(([x,n])=><button key={x} className="inmo-bar-row inmo-bar-button" onClick={()=>setState(x==='Sin estado'?'':x)}><div className="inmo-bar-label"><strong>{x}</strong><span>{n}</span></div><div className="inmo-bar-track"><i style={{width:`${Math.max(8,n/maxState*100)}%`}}/></div></button>)}</div></article><article><span>LECTURA OPERATIVA</span><h2>Seguimiento inmediato</h2><strong className="inmo-priority">{seguimiento}</strong><p>Contactos con seguimiento explícito o pendiente. Puedes entrar con un toque en el grupo que necesite atención.</p></article></section>
  <section className="inmo-filter contactos-filter" data-testid="contactos-preset-search"><div className="inmo-filter-head contactos-filter-head"><div><small>BUSCADOR PREFIJADO</small><h2>Filtrar contactos sin escribir</h2></div><span>{visible.length} visibles</span></div><div className="inmo-filter-grid contactos-filter-grid"><label>VISTA RÁPIDA<select value={focus} onChange={e=>setFocus(e.target.value as Focus)}><option value="todos">Todos</option><option value="seguimiento">Con seguimiento</option><option value="sin-accion">Sin siguiente acción</option>{effectiveMode==='clientes'&&<option value="formalizados">Formalizados</option>}</select></label><label>ESTADO<select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos</option>{states.map(v=><option key={v}>{v}</option>)}</select></label>{effectiveMode==='clientes'&&<label>FASE VINCULADA<select value={phase} onChange={e=>setPhase(e.target.value)}><option value="">Todas</option>{phases.map(v=><option key={v}>{v}</option>)}</select></label>}<label>ORDENAR<select value={sortKey} onChange={e=>{setSortKey(e.target.value as SortKey);setSortDir('asc')}}><option value="nombre">Nombre</option><option value="relacion">Relación</option><option value="vinculo">Vínculo</option><option value="seguimiento">Seguimiento</option></select></label><button onClick={()=>{setState('');setPhase('');setFocus('todos');setSortKey('nombre');setSortDir('asc')}}>Limpiar</button></div></section>
  {visible.length===0?<div className="ops-empty" data-testid="contact-empty"><strong>Sin contactos visibles</strong><span>No hay registros para estos filtros o para tu ámbito actual.</span></div>:<div className="ops-table-card contactos-table"><div className="ops-table-head"><strong>{visible.length} registros</strong><span>Contactos</span></div><div className="ops-table-wrap ops-sortable-wrap"><table className="ops-sortable-table"><thead><tr><th aria-sort={ariaSort('nombre')}><button type="button" onClick={()=>applySort('nombre')}>Contacto <span>{sortArrow('nombre')}</span></button></th><th aria-sort={ariaSort('relacion')}><button type="button" onClick={()=>applySort('relacion')}>{effectiveMode==='b2b'?'Cargo / relación':'Relación'} <span>{sortArrow('relacion')}</span></button></th><th aria-sort={ariaSort('vinculo')}><button type="button" onClick={()=>applySort('vinculo')}>{effectiveMode==='b2b'?'Inmobiliaria':'Expediente'} <span>{sortArrow('vinculo')}</span></button></th><th aria-sort={ariaSort('seguimiento')}><button type="button" onClick={()=>applySort('seguimiento')}>Seguimiento <span>{sortArrow('seguimiento')}</span></button></th><th></th></tr></thead><tbody>{visible.map((r,i)=>{const id=idOf(r);const destino=effectiveMode==='b2b'?`/contactos-b2b/${encodeURIComponent(id)}`:`/contactos/${encodeURIComponent(id)}`;return <tr key={id||i} className={id?'ops-clickable-row':''} tabIndex={id?0:undefined} onClick={()=>id&&navigate(destino)} onKeyDown={e=>{if(id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();navigate(destino)}}}><td><strong>{nameOf(r)}</strong></td><td>{relationOf(r)}</td><td>{effectiveMode==='b2b'?inmoOf(r):expedienteOf(r)}</td><td>{followOf(r)||'—'}</td><td>{id?'→':''}</td></tr>})}</tbody></table></div></div>}</>}
 </OperationalShellFrame>;
}
