import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {LogOut,Moon,Search,Sun} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {anaAvatar,anaVertical,fenixLogo} from './assets/visualAssets';
import './operational.css';
import './contactos-polish.css';
import './sortable-table.css';

type Theme='light'|'dark';
type Ctx={actor_code?:string;role?:string};
type NavItem={label:string;route:string};
type Row=Record<string,unknown>;
type ContactMode='clientes'|'b2b';
type SortKey='nombre'|'relacion'|'vinculo'|'seguimiento';
type SortDir='asc'|'desc';
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function normalizeNav(data:unknown):NavItem[]{if(!data||typeof data!=='object')return[];const items=(data as{items?:unknown[]}).items;if(!Array.isArray(items))return[];return items.map(x=>{if(typeof x==='string')return{label:x.replace(/^\//,'')||'Inicio',route:x};if(x&&typeof x==='object'){const o=x as Record<string,unknown>;if(typeof o.route==='string')return{label:typeof o.label==='string'?o.label:o.route.replace(/^\//,''),route:o.route};}return null;}).filter((x):x is NavItem=>Boolean(x));}
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;return Array.isArray(d.items)?d.items as Row[]:[];}
function text(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function bool(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='boolean')return v;if(typeof v==='string'){const s=v.toLowerCase();if(['sí','si','true','yes'].includes(s))return true;if(['no','false'].includes(s))return false;}}return null;}
function idOf(row:Row){return text(row,['id','contact_id','contacto_id','contact_key']);}
function stateOf(row:Row){return text(row,['estado','estado_comercial','estado_relacion','relacion','relación','activo']);}
function phaseOf(row:Row){return text(row,['fase','fase_vinculada','expediente_fase']);}
function followOf(row:Row){return text(row,['proxima_accion','próxima_acción','siguiente_accion','siguiente_acción','proximo_contacto','próximo_contacto','seguimiento','ultimo_contacto','último_contacto']);}
function nameOf(row:Row){return text(row,['cliente','nombre','nombre_alias','contacto','contacto_inmobiliaria','title'])||'Contacto sin nombre';}
function relationOf(row:Row){return text(row,['relacion','relación','tipo','perfil','estado_comercial','cargo'])||'—';}
function expedienteOf(row:Row){return text(row,['expediente','expediente_code','codigo_expediente','código_expediente'])||'—';}
function inmoOf(row:Row){return text(row,['inmobiliaria','inmobiliaria_nombre','nombre_inmobiliaria'])||'—';}
function compareText(a:string,b:string){return a.localeCompare(b,'es',{sensitivity:'base',numeric:true});}
function roleKind(role?:string,actorCode?:string){const actor=(actorCode||'').toUpperCase();if(actor==='DIR-TEST'||actor==='CARLOS-ADMIN')return'direccion';const r=(role||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return r==='direccion'?'direccion':r==='visitador'?'visitador':r==='financiero'?'financiero':'otro';}

export default function ContactosShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/contactos';
 const[sessionReady,setSessionReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[mode,setMode]=useState<ContactMode>('clientes');
 const[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const[query,setQuery]=useState(''),[state,setState]=useState(''),[phase,setPhase]=useState(''),[sortKey,setSortKey]=useState<SortKey>('nombre'),[sortDir,setSortDir]=useState<SortDir>('asc');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setSessionReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setSessionReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNav(n.data):[]);});return()=>{alive=false};},[active,logged]);
 const kind=roleKind(ctx?.role,ctx?.actor_code),isDirection=kind==='direccion',isVisitador=kind==='visitador';
 const effectiveMode:ContactMode=isVisitador?'b2b':kind==='financiero'?'clientes':mode;
 useEffect(()=>{if(!active||!logged||!ctx||kind==='otro')return;let alive=true;(async()=>{setLoading(true);setMessage('');setRows([]);setStatus(null);const endpoint=effectiveMode==='b2b'?'/contactos-inmobiliaria':'/clientes';const r=await fetchNotionRuntime<unknown>(endpoint);if(!alive)return;setStatus(r.status);setRows(r.status===200?rowsFrom(r.data):[]);if(r.status===403)setMessage(effectiveMode==='b2b'?'Tu perfil no tiene acceso a contactos B2B fuera de su cartera o zona autorizada.':'Tu perfil no tiene acceso a clientes hipotecarios fuera de su ámbito.');else if(r.status!==200)setMessage(effectiveMode==='b2b'?'No se pudo leer la fuente canónica de contactos de inmobiliaria.':'No se pudo leer la fuente canónica de clientes hipotecarios.');setLoading(false);})();return()=>{alive=false}},[active,logged,ctx,kind,effectiveMode]);
 const effectiveNav=nav.length?nav:fallbackNav;
 const states=useMemo(()=>Array.from(new Set(rows.map(stateOf).filter(Boolean))).sort(compareText),[rows]);
 const phases=useMemo(()=>Array.from(new Set(rows.map(phaseOf).filter(Boolean))).sort(compareText),[rows]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();const out=rows.filter(r=>{const hay=Object.values(r).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase();return(!q||hay.includes(q))&&(!state||stateOf(r)===state)&&(!phase||phaseOf(r)===phase)});const direction=sortDir==='asc'?1:-1;return[...out].sort((a,b)=>{let result=0;if(sortKey==='relacion')result=compareText(relationOf(a),relationOf(b));else if(sortKey==='vinculo')result=compareText(effectiveMode==='b2b'?inmoOf(a):expedienteOf(a),effectiveMode==='b2b'?inmoOf(b):expedienteOf(b));else if(sortKey==='seguimiento')result=compareText(followOf(a),followOf(b));else result=compareText(nameOf(a),nameOf(b));if(result===0)result=compareText(nameOf(a),nameOf(b));return result*direction;});},[rows,query,state,phase,sortKey,sortDir,effectiveMode]);
 const seguimiento=useMemo(()=>rows.filter(r=>bool(r,['requiere_seguimiento'])===true||/seguimiento|contactar|pendiente/i.test(`${stateOf(r)} ${followOf(r)}`)).length,[rows]);
 const formalizados=useMemo(()=>rows.filter(r=>/formaliz|firmad|cerrad/i.test(stateOf(r))).length,[rows]);
 const sinProxima=useMemo(()=>rows.filter(r=>!followOf(r)).length,[rows]);
 if(!active||!sessionReady||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 function switchMode(next:ContactMode){if(!isDirection)return;setQuery('');setState('');setPhase('');setSortKey('nombre');setSortDir('asc');setMode(next);}
 function applySort(key:SortKey){if(sortKey===key)setSortDir(v=>v==='asc'?'desc':'asc');else{setSortKey(key);setSortDir('asc');}}
 function sortArrow(key:SortKey){return sortKey===key?(sortDir==='asc'?'↑':'↓'):'';}
 function ariaSort(key:SortKey){return sortKey===key?(sortDir==='asc'?'ascending':'descending'):undefined;}
 return <div className="ops-root contactos-root" data-theme={theme}>
  <aside className="ops-side"><button className="ops-brand" onClick={()=>navigate('/inicio')}><img src={fenixLogo} alt=""/><strong>FÉNIX CAPITAL</strong></button><nav>{effectiveNav.map(item=><button key={item.route} className={item.route==='/contactos'?'active':''} onClick={()=>navigate(item.route)}>{item.label}</button>)}</nav><button className="ops-ana" onClick={()=>navigate('/ana')}><img src={anaAvatar} alt="Ana"/><span><strong>Ana está contigo</strong><small>Cuando quieras, avanzamos paso a paso.</small></span></button></aside>
  <main className="ops-main"><header className="ops-top"><div className="ops-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={effectiveMode==='b2b'?'Buscar contacto B2B o inmobiliaria...':'Buscar contacto, expediente o seguimiento...'}/><button>Buscar</button></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Cambiar tema">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{ctx?.role||'Usuario'}</strong></div><button onClick={logout} aria-label="Cerrar sesión"><LogOut size={17}/></button></div></header>
   <section className="ops-content contactos-content">
    <section className="contactos-ana-hero"><div className="contactos-ana-photo"><img src={anaVertical} alt="Ana"/></div><div><span>ANA · EN ESTA PANTALLA</span><h2>¿Qué hacemos ahora?</h2><p>{effectiveMode==='b2b'?'Aquí trabajamos únicamente relaciones con inmobiliarias dentro de tu ámbito B2B autorizado.':'Cada conversación cuenta: te ayudo a escuchar, responder y dar el siguiente paso con cercanía.'}</p><div className="contactos-next"><button onClick={()=>setState(states.find(s=>/seguimiento|pendiente/i.test(s))||'')}><b>1</b><strong>Atender seguimientos</strong><small>Ver y preparar →</small></button><button onClick={()=>navigate('/comunicaciones')}><b>2</b><strong>Preparar un mensaje</strong><small>Ver y preparar →</small></button><button onClick={()=>{setSortKey('seguimiento');setSortDir('asc')}}><b>3</b><strong>Completar datos pendientes</strong><small>Ver y preparar →</small></button></div></div></section>
    <div className="contactos-title"><div><small>{effectiveMode==='b2b'?'RELACIONES B2B AUTORIZADAS':'RELACIONES Y SEGUIMIENTO'}</small><h1>Contactos</h1><p>{status===200?`${rows.length} ${effectiveMode==='b2b'?'contactos B2B':'clientes hipotecarios'} visibles en tu ámbito autorizado.`:'Lectura canónica según permisos.'}</p></div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos vivos':'PRE-PROD'}</span>{effectiveMode==='b2b'?<button className="primary" onClick={()=>navigate('/inmobiliarias')}>+ Nuevo contacto desde inmobiliaria</button>:!isVisitador&&<button className="primary" onClick={()=>navigate('/ana?mode=do&resource=contacto')}>+ Crear con Ana</button>}</div></div>
    {isDirection&&<div className="ops-message" data-testid="contact-scope-tabs" style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><strong>Ámbito de contactos</strong><button className={effectiveMode==='clientes'?'primary':''} onClick={()=>switchMode('clientes')}>Clientes hipotecarios</button><button className={effectiveMode==='b2b'?'primary':''} onClick={()=>switchMode('b2b')}>Contactos inmobiliaria</button></div>}
    {!isDirection&&kind==='financiero'&&<div className="ops-message">Ves únicamente clientes hipotecarios de tus expedientes y contactos autorizados.</div>}
    {!isDirection&&isVisitador&&<div className="ops-message">Ves únicamente contactos B2B de inmobiliarias asignadas o de tu zona autorizada. No se muestran clientes hipotecarios.</div>}
    {loading?<div className="ops-empty" data-testid="contact-loading"><strong>Cargando contactos…</strong><span>Consultando la fuente canónica autorizada.</span></div>:message?<div className="ops-message" data-testid={status===403?'contact-forbidden':'contact-error'}>{message}</div>:null}
    {!loading&&status===200&&<><section className="contactos-kpis"><article><small>CON SEGUIMIENTO</small><strong>{seguimiento}</strong><span>Derivado de los campos visibles</span></article><article><small>{effectiveMode==='b2b'?'CONTACTOS VISIBLES':'FORMALIZADOS'}</small><strong>{effectiveMode==='b2b'?rows.length:formalizados}</strong><span>{effectiveMode==='b2b'?'Solo ámbito B2B autorizado':'Según estado canónico disponible'}</span></article><article><small>SIN PRÓXIMA ACCIÓN</small><strong>{sinProxima}</strong><span>Sin seguimiento registrado visible</span></article></section>
    <section className="contactos-filter"><div className="contactos-filter-head"><div><small>{effectiveMode==='b2b'?'CONTACTOS DE INMOBILIARIA':'RELACIONES ACTIVAS'}</small><h2>Contactos disponibles</h2></div><span>{visible.length} visibles</span></div><label>BUSCAR<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={effectiveMode==='b2b'?'Nombre, cargo o inmobiliaria':'Nombre, expediente o dato relacionado'}/></label><div className="contactos-filter-grid"><label>ESTADO<select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos</option>{states.map(v=><option key={v}>{v}</option>)}</select></label>{effectiveMode==='clientes'&&<label>FASE VINCULADA<select value={phase} onChange={e=>setPhase(e.target.value)}><option value="">Todas</option>{phases.map(v=><option key={v}>{v}</option>)}</select></label>}<label>ORDENAR POR<select value={sortKey} onChange={e=>{setSortKey(e.target.value as SortKey);setSortDir('asc')}}><option value="nombre">Nombre</option><option value="seguimiento">Seguimiento</option></select></label><button onClick={()=>{setQuery('');setState('');setPhase('');setSortKey('nombre');setSortDir('asc')}}>Limpiar</button></div></section>
    {visible.length===0?<div className="ops-empty" data-testid="contact-empty"><strong>Sin contactos visibles</strong><span>No hay registros para estos filtros o para tu ámbito actual.</span></div>:<div className="ops-table-card contactos-table"><div className="ops-table-head"><strong>{visible.length} registros</strong><span>Fuente canónica Notion</span></div><div className="ops-table-wrap ops-sortable-wrap"><table className="ops-sortable-table"><thead><tr><th aria-sort={ariaSort('nombre')}><button type="button" onClick={()=>applySort('nombre')}>Contacto <span>{sortArrow('nombre')}</span></button></th><th aria-sort={ariaSort('relacion')}><button type="button" onClick={()=>applySort('relacion')}>{effectiveMode==='b2b'?'Cargo / relación':'Relación'} <span>{sortArrow('relacion')}</span></button></th><th aria-sort={ariaSort('vinculo')}><button type="button" onClick={()=>applySort('vinculo')}>{effectiveMode==='b2b'?'Inmobiliaria':'Expediente'} <span>{sortArrow('vinculo')}</span></button></th><th aria-sort={ariaSort('seguimiento')}><button type="button" onClick={()=>applySort('seguimiento')}>Seguimiento <span>{sortArrow('seguimiento')}</span></button></th><th></th></tr></thead><tbody>{visible.map((r,i)=>{const id=idOf(r);const destino=effectiveMode==='b2b'?`/contactos-b2b/${encodeURIComponent(id)}`:`/contactos/${encodeURIComponent(id)}`;return <tr key={id||i} className={id?'ops-clickable-row':''} tabIndex={id?0:undefined} onClick={()=>id&&navigate(destino)} onKeyDown={e=>{if(id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();navigate(destino)}}}><td><strong>{nameOf(r)}</strong></td><td>{relationOf(r)}</td><td>{effectiveMode==='b2b'?inmoOf(r):expedienteOf(r)}</td><td>{followOf(r)||'—'}</td><td>{id?'→':''}</td></tr>})}</tbody></table></div></div>}</>}
   </section>
  </main>
 </div>;
}
