import {ChangeEvent,useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {FileUp,X} from 'lucide-react';
import {useLocation} from 'react-router-dom';
import {IS_PRODUCTION,SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL,supabase} from './supabase';
import {evidenceContextFromPath,type EvidenceOrigin} from './evidenceContext';

const BUCKET=IS_PRODUCTION?'fenix-prod-documents':'fenix-preprod-documents-test';
const FUNCTION=IS_PRODUCTION?'fenix-evidence-api':'fenix-evidence-universal-test';
const ALLOWED_MIME=new Set(['application/pdf','image/png','image/jpeg','image/webp','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']);
const ACCEPT='.pdf,.png,.jpg,.jpeg,.webp,.txt,.doc,.docx,.xls,.xlsx';
const MIME_BY_EXT:Record<string,string>={'.pdf':'application/pdf','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.txt':'text/plain','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xls':'application/vnd.ms-excel','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};
type Prepare={ok?:boolean;upload_id?:string;storage_path?:string;token?:string;max_bytes?:number};
type Complete={ok?:boolean;reused?:boolean;document_page_id?:string};
type Queue={originType:string;files:File[]};
function mimeOf(file:File){const direct=(file.type||'').trim().toLowerCase();if(direct)return direct;const lower=file.name.toLowerCase();for(const[ext,mime]of Object.entries(MIME_BY_EXT))if(lower.endsWith(ext))return mime;return'application/octet-stream';}
async function evidenceFetch<T>(path:string,init?:RequestInit):Promise<{status:number;data:T|null}>{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return{status:401,data:null};let response:Response;try{response=await fetch(`${SUPABASE_URL}/functions/v1/${FUNCTION}${path}`,{...init,headers:{'content-type':'application/json',apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`}})}catch{return{status:0,data:null}}let data:T|null=null;try{data=await response.json()}catch{}return{status:response.status,data};}

export default function ContextEvidenceUpload(){
 const location=useLocation();const context=evidenceContextFromPath(location.pathname,location.search);
 const[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[queue,setQueue]=useState<Queue|null>(null),[host,setHost]=useState<HTMLElement|null>(null);const auto=useRef(false);
 useEffect(()=>{if(!context){setHost(null);return;}const active=context;const h=document.createElement('div');h.className='context-evidence-inline-host';h.dataset.originType=active.type;h.dataset.originCode=active.code;const place=()=>{const content=document.querySelector<HTMLElement>('.ops-content,.dir-content');if(!content)return;const kpis=content.querySelector<HTMLElement>(':scope > .tas-kpis,:scope > .firmas-kpis,:scope > .fin-kpis,:scope > .vis-kpis,:scope > .inmo-kpis,:scope > [class$="-kpis"]');const hero=content.querySelector<HTMLElement>(':scope > [class*="-ana-hero"],:scope > [class*="-ana"],:scope > .ops-ana-card,:scope > .dir-priority-copy');const anchor=kpis??hero;if(anchor){if(anchor.nextElementSibling!==h)content.insertBefore(h,anchor.nextElementSibling)}else if(h.parentElement!==content)content.insertBefore(h,content.firstChild);for(const duplicate of document.querySelectorAll<HTMLElement>('.firma-upload-inline,.doc-upload-inline'))duplicate.style.setProperty('display','none','important');};place();const ob=new MutationObserver(place);ob.observe(document.body,{childList:true,subtree:true});setHost(h);return()=>{ob.disconnect();h.remove();setHost(null)}},[location.pathname,location.search,context?.type,context?.code]);
 useEffect(()=>{const active=context;if(!queue||!active||active.staging||!active.code||queue.originType!==active.type||busy||auto.current)return;auto.current=true;const files=queue.files;setQueue(null);setOpen(true);void uploadFiles(files,active).finally(()=>{auto.current=false})},[context?.type,context?.code,context?.staging,queue,busy]);
 if(!context)return null;
 async function uploadFiles(files:File[],target:EvidenceOrigin){if(!target.code)return;setBusy(true);setMsg(`Vinculando ${files.length} archivo${files.length===1?'':'s'} a ${target.label}…`);let saved=0,reused=0,failed=0,blocked=0,oversize=0;for(const file of files){const mime=mimeOf(file);if(!ALLOWED_MIME.has(mime)){blocked++;continue;}const prep=await evidenceFetch<Prepare>('/prepare',{method:'POST',body:JSON.stringify({origin_type:target.type,origin_code:target.code,evidence_kind:'documento',filename:file.name,mime_type:mime})});if(prep.status!==200||!prep.data?.upload_id||!prep.data.storage_path||!prep.data.token){failed++;continue;}if(prep.data.max_bytes&&file.size>prep.data.max_bytes){oversize++;continue;}const up=await supabase.storage.from(BUCKET).uploadToSignedUrl(prep.data.storage_path,prep.data.token,file,{contentType:mime});if(up.error){failed++;continue;}const done=await evidenceFetch<Complete>('/complete',{method:'POST',body:JSON.stringify({upload_id:prep.data.upload_id,title:file.name})});if(done.status===200&&done.data?.ok){done.data.reused?reused++:saved++;}else failed++;}setBusy(false);const bits:string[]=[];if(saved)bits.push(`${saved} guardado${saved===1?'':'s'} y enlazado${saved===1?'':'s'}`);if(reused)bits.push(`${reused} ya existía${reused===1?'':'n'}`);if(oversize)bits.push(`${oversize} supera${oversize===1?'':'n'} 12 MB`);if(blocked)bits.push(`${blocked} formato${blocked===1?'':'s'} no admitido${blocked===1?'':'s'}`);if(failed)bits.push(`${failed} con error`);setMsg(bits.join(' · ')||'No se seleccionaron archivos.');}
 async function choose(e:ChangeEvent<HTMLInputElement>){const files=[...(e.target.files??[])];e.target.value='';if(!files.length)return;if(context.staging){const allowed=files.filter(f=>ALLOWED_MIME.has(mimeOf(f)));if(!allowed.length){setMsg('No se seleccionaron documentos admitidos.');return;}setQueue({originType:context.type,files:allowed});setMsg(`${allowed.length} documento${allowed.length===1?'':'s'} preparado${allowed.length===1?'':'s'}. Se enlazará${allowed.length===1?'':'n'} al abrir la ficha creada.`);return;}await uploadFiles(files,context);}
 const staged=queue?.originType===context.type?queue.files.length:0;const launcher=<button type="button" data-testid="context-evidence-open" onClick={()=>setOpen(true)} style={{width:'100%',border:'1px solid #f4741f',borderRadius:12,padding:'12px 16px',display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,background:'#f4741f',color:'#fff',fontWeight:800,cursor:'pointer'}}><FileUp size={17}/>{staged?`${staged} documento${staged===1?'':'s'} preparado${staged===1?'':'s'}`:'Subir documentos'}</button>;
 return <>{host&&createPortal(launcher,host)}{open&&createPortal(<div role="presentation" style={{position:'fixed',inset:0,zIndex:9999,background:'rgba(20,16,24,.42)',display:'grid',placeItems:'center',padding:18}}><section className="ops-message" style={{display:'grid',gap:14,border:'2px solid #870064',width:'min(620px,100%)',maxHeight:'88vh',overflow:'auto',background:'var(--panel,#fff)',boxShadow:'0 24px 70px rgba(0,0,0,.28)'}} aria-label="Subir archivos contextuales"><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong style={{fontSize:18}}>{context.staging?`Preparar documentos para ${context.label}`:`Subir documentos a ${context.label}`}</strong><p style={{margin:'5px 0 0'}}>El original se conserva intacto y queda enlazado al contexto real. La lectura inteligente aparece justo debajo de esta franja.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar"><X size={16}/></button></div>{context.staging&&<div style={{padding:11,borderRadius:12,background:'rgba(135,0,100,.07)'}}><strong>La ficha aún no existe.</strong><div>Los documentos quedan preparados en esta sesión y se vinculan cuando abras la ficha creada.</div></div>}<label className="primary" style={{display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,cursor:busy?'wait':'pointer',padding:12,borderRadius:12}}><FileUp size={18}/>{busy?'Subiendo y enlazando…':'Elegir documentos'}<input type="file" multiple accept={ACCEPT} onChange={e=>void choose(e)} disabled={busy} style={{display:'none'}}/></label>{msg&&<strong>{msg}</strong>}<small>Tamaño máximo actual: 12 MB por archivo. PDF, JPG/PNG/WEBP, TXT, Word y Excel. El análisis inteligente trabaja con foto/PDF; los demás formatos se conservan como evidencia.</small></section></div>,document.body)}</>;
}
