import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Plus,Save,UserRound,X} from 'lucide-react';
import {fetchAppApi,IS_PRODUCTION,SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './contact-detail.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';type Ctx={role?:string;display_name?:string};type Row=Record<string,unknown>;
type ContactType='cliente_hipoteca_particular'|'cliente_hipoteca_inmobiliaria'|'cliente_deuda_refinanciacion'|'cliente_herencia'|'cliente_obra_nueva'|'trabajador_inmobiliaria'|'contacto_bancario'|'trabajador_notaria'|'trabajador_registro'|'tasador'|'proveedor'|'otro';
type CreateResponse={ok?:boolean;status?:number;id?:string;destino?:string;error?:string;existing_id?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
const TYPES:Array<{value:ContactType;label:string;supportedProd:boolean;entity:'inmobiliaria'|'banco'|'';cargo:boolean}>=[
 {value:'cliente_hipoteca_particular',label:'Cliente hipotecario particular',supportedProd:true,entity:'',cargo:false},{value:'cliente_hipoteca_inmobiliaria',label:'Cliente derivado de inmobiliaria',supportedProd:true,entity:'inmobiliaria',cargo:false},{value:'cliente_deuda_refinanciacion',label:'Cliente deuda / refinanciación',supportedProd:true,entity:'',cargo:false},{value:'cliente_herencia',label:'Cliente herencia',supportedProd:true,entity:'',cargo:false},{value:'cliente_obra_nueva',label:'Cliente obra nueva',supportedProd:true,entity:'',cargo:false},{value:'trabajador_inmobiliaria',label:'Trabajador de inmobiliaria',supportedProd:true,entity:'inmobiliaria',cargo:true},{value:'contacto_bancario',label:'Contacto bancario',supportedProd:true,entity:'banco',cargo:true},{value:'trabajador_notaria',label:'Trabajador de notaría',supportedProd:false,entity:'',cargo:true},{value:'trabajador_registro',label:'Trabajador de Registro',supportedProd:false,entity:'',cargo:true},{value:'tasador',label:'Tasador',supportedProd:false,entity:'',cargo:true},{value:'proveedor',label:'Proveedor',supportedProd:false,entity:'',cargo:true},{value:'otro',label:'Otro contacto',supportedProd:false,entity:'',cargo:true}
];
const changeAt=(items:string[],index:number,value:string)=>items.map((x,i)=>i===index?value:x);
function rows(data:any){return Array.isArray(data?.items)?data.items:[] as Row[]}
function text(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim()}return''}
function idOf(r:Row){return text(r,['id','inmobiliaria_code','bank_code','code'])}function nameOf(r:Row){return text(r,['nombre','inmobiliaria','nombre_alias','banco'])||idOf(r)}

export default function ContactCreateShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/contactos/nuevo';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[query,setQuery]=useState('');
 const[tipo,setTipo]=useState<ContactType>('cliente_hipoteca_particular'),[nombre,setNombre]=useState(''),[apellidos,setApellidos]=useState(''),[emails,setEmails]=useState<string[]>(['']),[telefonos,setTelefonos]=useState<string[]>(['']),[cargo,setCargo]=useState(''),[entityId,setEntityId]=useState(''),[entityRows,setEntityRows]=useState<Row[]>([]),[observaciones,setObservaciones]=useState(''),[consent,setConsent]=useState(false),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<CreateResponse|null>(null);
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()}},[active]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[])});return()=>{alive=false}},[active,logged]);
 const cfg=useMemo(()=>TYPES.find(x=>x.value===tipo)!,[tipo]);
 useEffect(()=>{if(!active||!logged||!cfg.entity){setEntityRows([]);setEntityId('');return}let alive=true;fetchNotionRuntime<any>(cfg.entity==='inmobiliaria'?'/inmobiliarias':'/bancos').then(r=>{if(alive)setEntityRows(r.status===200?rows(r.data):[])});return()=>{alive=false}},[active,logged,cfg.entity]);
 if(!active||!ready||!logged)return null;
 const allowed=ctx?.role==='Direccion'||ctx?.role==='Financiero'||(ctx?.role==='Visitador'&&tipo==='trabajador_inmobiliaria');const prodSupported=!IS_PRODUCTION||cfg.supportedProd;const cleanPhones=telefonos.map(x=>x.trim()).filter(Boolean),cleanEmails=emails.map(x=>x.trim()).filter(Boolean);const valid=allowed&&prodSupported&&nombre.trim().length>=2&&(!cfg.entity||entityId||tipo==='contacto_bancario');
 function edit(){setPreview(false);setMessage('');setResult(null)}
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}function search(){const q=query.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 async function submit(e:FormEvent){e.preventDefault();if(!valid)return;if(!preview){setPreview(true);return}setBusy(true);setMessage('');let r:{status:number;data:CreateResponse|null};if(IS_PRODUCTION){const {data,error}=await supabase.rpc('fenix_prod_contact_create',{p_tipo:tipo,p_nombre:nombre.trim(),p_apellidos:apellidos.trim()||null,p_email:cleanEmails[0]||null,p_telefono:cleanPhones[0]||null,p_cargo:cargo.trim()||null,p_entidad_id:entityId||null,p_observaciones:observaciones.trim()||null,p_consentimiento_comercial:consent});r={status:error?500:Number(data?.status||200),data:(data||{error:error?.message}) as CreateResponse}}else{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)r={status:401,data:null};else{const resp=await fetch(`${SUPABASE_URL}/functions/v1/fenix-contactos-unified-test`,{method:'POST',headers:{'content-type':'application/json',apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({tipo_contacto:tipo,nombre:nombre.trim(),apellidos:apellidos.trim(),email:cleanEmails[0]||'',telefono:cleanPhones[0]||'',emails:cleanEmails,telefonos:cleanPhones,entidad_id:entityId,cargo:cargo.trim(),observaciones:observaciones.trim(),consentimiento_comercial:consent})});let data:CreateResponse|null=null;try{data=await resp.json()}catch{}r={status:resp.status,data}}}setBusy(false);setResult(r.data);setPreview(false);if((r.status===200||r.status===201)&&r.data?.ok)setMessage('Contacto creado correctamente en la fuente canónica.');else if(r.status===409)setMessage('Ya existe un contacto con ese email o teléfono. No se ha creado un duplicado.');else if(r.status===422)setMessage('Este tipo de contacto todavía no dispone de tabla canónica PROD. No se ha enviado a TEST.');else if(r.status===403)setMessage('Tu perfil no puede crear este contacto.');else setMessage(`No se pudo crear el contacto (${r.data?.error||r.status}).`)}
 const displayName=ctx?.display_name||ctx?.role||'Usuario';return <OperationalShellFrame className="contact-create-root" theme={theme} navigation={nav.length?nav:fallbackNav} activeRoute="/contactos" anaSubtitle="Primero clasificamos el contacto; después pedimos sólo lo necesario." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar en toda la app..." searchActionLabel="Buscar" onSearchAction={search} name={displayName} role={ctx?.role||''} initials={displayName.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout}>
  <div className="ops-title"><div><span className="ops-icon"><UserRound size={20}/></span><div><h1>Nuevo contacto</h1><p>Alta canónica con clasificación y vinculación opcional.</p></div></div><span className="ops-live ok">{IS_PRODUCTION?'PROD':'PRE-PROD'}</span></div>
  <section className="contact-create-ana-hero"><div className="contact-detail-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="contact-detail-ana-body"><span>ANA · NUEVO CONTACTO</span><h2>Primero dime quién es</h2><p>La app no mezclará datos de prueba con producción. Sólo se guardan tipos que tienen destino canónico.</p></div></section>
  {!allowed&&<div className="ops-message">Tu perfil no puede crear este tipo de contacto.</div>}{IS_PRODUCTION&&!cfg.supportedProd&&<div className="ops-message">Este tipo aún no tiene destino canónico en PROD. No se enviará a PRE-PROD.</div>}
  {allowed&&<form className="ops-message" onSubmit={submit} style={{display:'grid',gap:12}} data-testid="contact-create-form"><label>Tipo<select value={tipo} onChange={e=>{setTipo(e.target.value as ContactType);setEntityId('');edit()}}>{TYPES.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{cfg.entity&&<label>{cfg.entity==='inmobiliaria'?'Inmobiliaria':'Banco'}<select value={entityId} onChange={e=>{setEntityId(e.target.value);edit()}}><option value="">Selecciona</option>{entityRows.map(r=>{const id=idOf(r);return id?<option key={id} value={id}>{nameOf(r)}</option>:null})}</select></label>}{cfg.cargo&&<label>Cargo<input value={cargo} onChange={e=>{setCargo(e.target.value);edit()}}/></label>}<label>Nombre<input value={nombre} onChange={e=>{setNombre(e.target.value);edit()}} required/></label><label>Apellidos<input value={apellidos} onChange={e=>{setApellidos(e.target.value);edit()}}/></label><div className="multi-contact-group"><div className="multi-contact-head"><strong>Teléfonos</strong><button type="button" onClick={()=>setTelefonos(v=>[...v,''])}><Plus size={15}/> Añadir</button></div>{telefonos.map((v,i)=><label key={i}>Teléfono {i+1}<span className="multi-contact-row"><input value={v} onChange={e=>{setTelefonos(x=>changeAt(x,i,e.target.value));edit()}}/>{telefonos.length>1&&<button type="button" onClick={()=>setTelefonos(x=>x.filter((_,j)=>j!==i))}><X size={15}/></button>}</span></label>)}</div><div className="multi-contact-group"><div className="multi-contact-head"><strong>Correos</strong><button type="button" onClick={()=>setEmails(v=>[...v,''])}><Plus size={15}/> Añadir</button></div>{emails.map((v,i)=><label key={i}>Email {i+1}<span className="multi-contact-row"><input type="email" value={v} onChange={e=>{setEmails(x=>changeAt(x,i,e.target.value));edit()}}/>{emails.length>1&&<button type="button" onClick={()=>setEmails(x=>x.filter((_,j)=>j!==i))}><X size={15}/></button>}</span></label>)}</div><label>Observaciones<textarea rows={4} value={observaciones} onChange={e=>{setObservaciones(e.target.value);edit()}}/></label><label><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);edit()}}/> Consentimiento comercial informado</label>{!preview?<button className="primary" disabled={!valid||busy}>Revisar antes de crear</button>:<div className="ops-message"><strong>Revisión previa</strong><p>{[nombre,apellidos].filter(Boolean).join(' ')} · {TYPES.find(x=>x.value===tipo)?.label}</p><button className="primary" disabled={busy}><Save size={16}/>{busy?'Creando…':'Confirmar y crear'}</button><button type="button" onClick={()=>setPreview(false)}>Seguir editando</button></div>}{message&&<div className="ops-message">{message}</div>}{result?.id&&<button type="button" onClick={()=>navigate(`/contactos/${encodeURIComponent(result.id!)}`)}>Abrir ficha creada →</button>}</form>}
 </OperationalShellFrame>
}
