import type {ExtractedDocument,ExtractedFields} from './browserDocumentOcr';

const clean=(v:string,max=260)=>v.replace(/[ \t]+/g,' ').replace(/^[:–—\s]+/,'').trim().slice(0,max);
const lines=(text:string)=>text.replace(/\r/g,'\n').split(/\n+/).map(x=>clean(x,1200)).filter(Boolean);

function valueAfterExactLabel(text:string,labels:string[],max=260){const ls=lines(text);for(let i=0;i<ls.length;i++){for(const label of labels){const exact=new RegExp(`^(?:${label})\\s*[:\\-–—]?\\s*$`,'i');const inline=new RegExp(`^(?:${label})\\s*[:\\-–—]\\s*(.{1,${max}})$`,'i');const m=ls[i].match(inline);if(m?.[1])return clean(m[1],max);if(exact.test(ls[i])&&ls[i+1])return clean(ls[i+1],max);}}return'';}
function directLabeledLine(text:string,labels:string[],max=260){const ls=text.replace(/\r/g,'\n').split(/\n+/);for(const raw of ls){for(const label of labels){const m=raw.match(new RegExp(`^\\s*(?:${label})\\s*[:\\-–—]\\s*(.+?)\\s*$`,'i'));if(m?.[1])return clean(m[1],max);}}return'';}
function safePerson(v:string){const s=clean(v,160);if(!s||s.length<5||s.length>140)return'';if(/r[eé]gimen|seguridad social|trabajadores|sistema|prestaci[oó]n|protecci[oó]n de datos|fecha de efecto|cuenta propia|aut[oó]nomos|cotizaci[oó]n|modelo\s+\d+|base\s+de\s+cotizaci[oó]n|empresa|pagador/i.test(s))return'';const words=s.split(/\s+/);return words.length>=2&&words.length<=8?s:'';}
function safeCompany(v:string){const s=clean(v,220);if(!s||s.length<2)return'';if(/modelo\s+\d+|base\s+(?:de\s+)?cotizaci[oó]n|grupo\s+de\s+cotizaci[oó]n|periodo|devengos|deducciones|trabajador|empleado/i.test(s))return'';return s;}
function personAfterHonorific(text:string){const ls=lines(text);for(let i=0;i<ls.length;i++){if(/^(?:D\.?\s*\/?\s*D(?:ÑA|NA|ª)\.?|DON|DOÑA)\s*[:\-–—]?\s*$/i.test(ls[i])&&ls[i+1]){const p=safePerson(ls[i+1]);if(p)return p;}const m=ls[i].match(/^(?:D\.?\s*\/?\s*D(?:ÑA|NA|ª)\.?|DON|DOÑA)\s*[:\-–—]?\s+(.+)$/i);if(m?.[1]){const p=safePerson(m[1]);if(p)return p;}}return'';}
function parseDate(raw:string){const m=raw.match(/\b(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})\b/);if(!m)return'';const y=m[3].length===2?`20${m[3]}`:m[3];return`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;}
function strictDateRange(text:string){const period=valueAfterExactLabel(text,['PER[IÍ]ODO','DESDE'],220);const source=period||text;const dates=[...source.matchAll(/\b\d{1,2}[.\/-]\d{1,2}[.\/-]\d{2,4}\b/g)].map(m=>parseDate(m[0])).filter(Boolean);const unique=[...new Set(dates)];return unique.length>=2?`${unique[0]} - ${unique[unique.length-1]}`:'';}
function parseMoney(raw:string){const m=raw.match(/(?:€|EUR)?\s*(-?\d{1,3}(?:[.\s]\d{3})*(?:,\d{1,2})|-?\d+(?:[.,]\d{1,2})?)\s*(?:€|EUR)?/i);if(!m)return null;const n=Number(m[1].replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));return Number.isFinite(n)?n:null;}
function strictMoney(text:string,labels:string[]){const ls=lines(text);for(let i=0;i<ls.length;i++){for(const label of labels){const inline=new RegExp(`^(?:${label})\\s*[:\-–—]?\\s*(.+)$`,'i');const exact=new RegExp(`^(?:${label})\\s*[:\-–—]?\\s*$`,'i');const m=ls[i].match(inline);if(m?.[1]){const n=parseMoney(m[1]);if(n!==null)return n;}if(exact.test(ls[i])&&ls[i+1]&&!/^[A-ZÁÉÍÓÚÜÑ][A-ZÁÉÍÓÚÜÑ ]{3,}:?$/i.test(ls[i+1])){const n=parseMoney(ls[i+1]);if(n!==null)return n;}}}return null;}

function sanitizeVida(text:string,f:ExtractedFields){delete f.titular;const titular=safePerson(directLabeledLine(text,['NOMBRE Y APELLIDOS','NOMBRE COMPLETO','TRABAJADOR(?:A)?','INTERESADO(?:A)?'],220)||valueAfterExactLabel(text,['NOMBRE Y APELLIDOS','NOMBRE COMPLETO','TRABAJADOR(?:A)?','INTERESADO(?:A)?'],220))||personAfterHonorific(text);if(titular)f.titular=titular;}
function sanitizeNomina(text:string,f:ExtractedFields){delete f.titular;delete f.empresa;delete f.empresa_pagador;const titular=safePerson(directLabeledLine(text,['TRABAJADOR(?:A)?','EMPLEADO(?:A)?','NOMBRE Y APELLIDOS'],260)||valueAfterExactLabel(text,['TRABAJADOR(?:A)?','EMPLEADO(?:A)?','NOMBRE Y APELLIDOS'],260));if(titular)f.titular=titular;const empresa=safeCompany(directLabeledLine(text,['RAZ[ÓO]N SOCIAL','EMPRESA','PAGADOR'],300)||valueAfterExactLabel(text,['RAZ[ÓO]N SOCIAL','EMPRESA','PAGADOR'],300));if(empresa){f.empresa=empresa;f.empresa_pagador=empresa;}}
function sanitizeIrpf(text:string,f:ExtractedFields){for(const k of ['rendimientos_trabajo','base_imponible','base_liquidable','resultado','resultado_declaracion'])delete f[k];const trabajo=strictMoney(text,['RENDIMIENTOS DEL TRABAJO','RENDIMIENTO NETO DEL TRABAJO']);if(trabajo!==null)f.rendimientos_trabajo=trabajo;const base=strictMoney(text,['BASE IMPONIBLE GENERAL','BASE IMPONIBLE']);if(base!==null)f.base_imponible=base;const liquidable=strictMoney(text,['BASE LIQUIDABLE GENERAL','BASE LIQUIDABLE']);if(liquidable!==null)f.base_liquidable=liquidable;const resultado=strictMoney(text,['RESULTADO DE LA DECLARACI[ÓO]N','CUOTA DIFERENCIAL']);if(resultado!==null){f.resultado=resultado;f.resultado_declaracion=resultado;}}
function sanitizeMovimientos(text:string,f:ExtractedFields){delete f.periodo;const periodo=strictDateRange(text);if(periodo)f.periodo=periodo;}
function looksLikeNomina(text:string){return /recibo\s+(?:individual\s+justificativo\s+del\s+pago\s+de\s+salarios|de\s+salarios)|n[oó]mina|l[ií]quido\s+a\s+percibir|total\s+devengado|devengos/i.test(text);}
function looksLikeVida(text:string){return /informe\s+de\s+vida\s+laboral|vida\s+laboral|n[uú]mero\s+(?:de\s+)?seguridad\s+social/i.test(text);}

export function sanitizeCriticalDocumentFields(result:ExtractedDocument,rawText:string=result.rawText):ExtractedDocument{const fields:{[k:string]:string|number|boolean}={...result.fields};if(result.documentType==='Vida laboral'||looksLikeVida(rawText))sanitizeVida(rawText,fields);else if(result.documentType==='Nómina'||looksLikeNomina(rawText))sanitizeNomina(rawText,fields);else if(result.documentType==='IRPF')sanitizeIrpf(rawText,fields);else if(result.documentType==='Movimientos bancarios')sanitizeMovimientos(rawText,fields);return{...result,fields};}
