import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {MessageCircle,Save} from 'lucide-react';
import {SUPABASE_URL,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {anaAvatar} from './assets/visualAssets';
import ExpedientePeoplePanel from './ExpedientePeoplePanel';
import './operational.css';
import './detail-expediente.css';

type AnyRow=Record<string,any>;
async function legacyDetailApi(code:string){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return {status:401,data:null as any};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-detail-api-test/expedientes/${encodeURIComponent(code)}`,{headers:{Authorization:`Bearer ${session.access_token}`}});let data:any=null;try{data=await r.json()}catch{}return {status:r.status,data};}
async function notionActionApi(id:string,changes:Record<string,unknown>){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return {status:401,data:null as any};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-notion-actions-test/expedientes/${encodeURIComponent(id)}/action`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action:'update',changes})});let data:any=null;try{data=await r.json()}catch{}return {status:r.status,data};}
function isNotionId(v:string){return /^[0-9a-f]{32}$/i.test(v.replaceAll('-',''));}
async function detailApi(code:string){if(isNotionId(code)){const r=await fetchNotionRuntime<any>(`/expedientes/${encodeURIComponent(code)}`);if(r.status!==404)return r;}return legacyDetailApi(code);}
function val(v:any){if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'Sí':'No';if(Array.isArray(v))return v.length?v.map(x=>typeof x==='object'?(x.name||x.id||JSON.stringify(x)):String(x)).join(', '):'—';if(typeof v==='object')return JSON.stringify(v);return String(v)}
function pick(row:AnyRow|undefined,keys:string[]){if(!row)return null;for(const k of keys){const v=row[k];if(v!==undefined&&v!==null&&v!=='')return v}return null}
const phases=['Entrada','Documentación','Análisis','Banco','Tasación','Oferta','FEIN','Notaría','Firma','Cierre'];
function phaseIndex(raw:any){const s=String(raw||'').toLowerCase();const aliases=[['entrada','nuevo','inicial'],['document','doc'],['análisis','analisis','estudio'],['banco','banc'],['tasación','tasacion'],['oferta','aprob'],['fein'],['notar'],['firma'],['cierre','cerrado','final']];const i=aliases.findIndex(group=>group.some(x=>s.includes(x)));return i>=0?i:0}
function display(v:any){return v===null||v===undefined||v===''?'No disponible':val(v)}

export default function DetailShell(){
 const location=useLocation(),navigate=useNavigate();
 const match=location.pathname.match(/^\/expedientes\/([^/]+)$/);const active=Boolean(match)&&location.pathname!=='/expedientes/nuevo';const code=match?.[1]?decodeURIComponent(match[1]):'';
 const [data,setData]=useState<any>(null),[message,setMessage]=useState('');
 const [notes,setNotes]=useState(''),[nextAction,setNextAction]=useState(''),[actionBusy,setActionBusy]=useState(false),[actionMsg,setActionMsg]=useState('');
 const [anaChoice,setAnaChoice]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;(async()=>{setMessage('');setActionMsg('');const r=await detailApi(code);if(!alive)return;setData(r.data);if(r.status===403)setMessage('Tu perfil no puede abrir esta ficha.');else if(r.status===404)setMessage('No se ha encontrado la ficha.');else if(r.status!==200)setMessage('No se pudo cargar la ficha.');})();return()=>{alive=false}},[active,code]);
 const main=useMemo(()=>{if(!data)return null;if(data.source==='notion_canonical'&&data.item)return data.item;return data.expediente},[data]);
 const canonical=Boolean(data?.source==='notion_canonical');
 if(!active)return null;
 const displayName=main?.expediente||main?.cliente||main?.cliente_alias||main?.nombre_cliente||main?.nombre||'Expediente';
 const currentPhase=pick(main,['fase','fase_actual','estado_fase']);
 const pIndex=phaseIndex(currentPhase);
 const resumen={cliente:pick(main,['cliente','cliente_alias','nombre_cliente','nombre']),titulares:pick(main,['titulares','titular','numero_titulares']),inmobiliaria:pick(main,['inmobiliaria','agencia','inmobiliaria_nombre']),financiero:pick(main,['financiero','financiero_ficha','financiero_nombre','id_financiero_operativo']),visitador:pick(main,['visitador','visitador_ficha','visitador_nombre','id_visitador_operativo']),fase:currentPhase,riesgo:pick(main,['riesgo','nivel_riesgo','criticidad']),proxima:pick(main,['proxima_accion','próxima_acción','siguiente_accion'])};
 const economicos={precio:pick(main,['precio','precio_compra','importe_compra','precio_vivienda']),financiacion:pick(main,['financiacion','financiación','importe_financiacion','importe_financiación','importe_solicitado']),ahorro:pick(main,['ahorro','ahorros','aportacion','aportación']),ingresos:pick(main,['ingresos','ingresos_mensuales','ingresos_neto']),deudas:pick(main,['deudas','cuotas_deuda','deuda_mensual']),ratio:pick(main,['ratio','ratio_endeudamiento','endeudamiento']),ltv:pick(main,['ltv','LTV']),banco:pick(main,['banco','entidad','banco_objetivo'])};
 async function saveFollowUp(){if(!canonical||!isNotionId(code)||(!notes.trim()&&!nextAction))return;setActionBusy(true);setActionMsg('');const changes:Record<string,unknown>={};if(notes.trim())changes.notas=notes.trim();if(nextAction)changes.proxima_accion=nextAction;const r=await notionActionApi(code,changes);setActionBusy(false);if(r.status===200){setActionMsg('Seguimiento guardado y auditado en Notion.');setNotes('');setNextAction('');const fresh=await detailApi(code);if(fresh.status===200)setData(fresh.data)}else if(r.status===403)setActionMsg('Tu perfil no puede modificar esta ficha.');else setActionMsg(`No se pudo guardar el seguimiento (${r.data?.error||r.status}).`);}
 function ana(mode:'do'|'help'|'self'){setAnaChoice(mode);if(mode==='do')navigate(`/ana?mode=do&scope_type=expediente&scope_code=${encodeURIComponent(code)}`);else if(mode==='help')navigate(`/ana?mode=help&scope_type=expediente&scope_code=${encodeURIComponent(code)}`);else setTimeout(()=>document.getElementById('seguimiento-contextual')?.scrollIntoView({behavior:'smooth',block:'center'}),0)}
 return <div className="ops-root detail-exp-root" style={{zIndex:5200}} data-theme={(sessionStorage.getItem('fenix-theme')||'light')}>
  <main className="ops-main detail-exp-main" style={{gridColumn:'2'}}><header className="ops-top detail-exp-top"><button className="detail-filter" onClick={()=>navigate('/expedientes')}>Filtros avanzados</button><div className="detail-search">Buscar expediente, cliente o tarea…</div><button className="primary" onClick={()=>navigate('/expedientes')}>Buscar</button><strong>Expediente</strong></header>
  <section className="ops-content detail-exp-content">
   <article className="detail-ana-hero"><img src={anaAvatar} alt="Ana"/><div className="detail-ana-copy"><span>ANA · EN ESTA PANTALLA</span><h2>¿Qué hacemos ahora?</h2><p>Yo te iré diciendo el siguiente paso y el motivo. En cada acción podrás elegir si la hago yo cuando esté autorizada, si te ayudo o si la haces tú.</p><div className="detail-next-list"><button onClick={()=>navigate(`/documentacion?expediente=${encodeURIComponent(code)}`)}><b>1</b><strong>Revisar bloqueos</strong><em>Ver evidencia →</em></button><button onClick={()=>document.getElementById('seguimiento-contextual')?.scrollIntoView({behavior:'smooth'})}><b>2</b><strong>Priorizar próxima acción</strong><em>Ver motivo →</em></button><button onClick={()=>navigate(`/tasaciones?expediente=${encodeURIComponent(code)}`)}><b>3</b><strong>Comprobar riesgos</strong><em>Ver y preparar →</em></button></div><button className="primary detail-upload" onClick={()=>navigate(`/documentacion?expediente=${encodeURIComponent(code)}&upload=1`)}>↑ Subir documentación</button></div></article>
   <button className="detail-back" onClick={()=>navigate('/expedientes')}>← Volver a expedientes</button>
   <div className="detail-master-title"><span>FICHA MAESTRA</span><h1>{displayName}</h1><p>{canonical?'Fuente canónica Notion · acceso filtrado por tu rol.':'Ficha PRE-PROD autorizada por rol.'}</p></div>
   {message&&<div className="ops-message">{message}</div>}
   {main&&<>
    <section className="detail-journey"><div className="detail-section-label">RECORRIDO DEL EXPEDIENTE</div><div className="detail-phase-track">{phases.map((phase,i)=><div key={phase} className={i<pIndex?'done':i===pIndex?'current':''}><span>{i<pIndex?'✓':i+1}</span><small>{phase}</small></div>)}</div></section>
    <nav className="detail-tabs"><button className="active">Resumen</button><button onClick={()=>navigate(`/documentacion?expediente=${encodeURIComponent(code)}`)}>Documentación</button><button onClick={()=>setAnaChoice('analysis')}>Análisis</button><button onClick={()=>setAnaChoice('bank')}>Banco</button><button onClick={()=>navigate('/tareas')}>Tareas</button><button onClick={()=>navigate(`/comunicaciones/nueva?scope_type=expediente&scope_code=${encodeURIComponent(code)}`)}>Comunicaciones</button><button onClick={()=>setAnaChoice('activity')}>Actividad</button><button onClick={()=>setAnaChoice('history')}>Historial</button><button onClick={()=>navigate(`/ana?scope_type=expediente&scope_code=${encodeURIComponent(code)}`)}>Ana</button></nav>
    {anaChoice&&['analysis','bank','activity','history'].includes(anaChoice)&&<div className="detail-inline-note">Este bloque se abrirá cuando exista una fuente canónica conectada para esta sección. No se muestran datos inventados.</div>}
    <div className="detail-summary-grid"><article className="detail-summary-card"><span>SITUACIÓN ACTUAL</span><h2>{display(currentPhase)}</h2><div className="detail-kv"><div><small>Cliente</small><strong>{display(resumen.cliente)}</strong></div><div><small>Titulares</small><strong>{display(resumen.titulares)}</strong></div><div><small>Inmobiliaria</small><strong>{display(resumen.inmobiliaria)}</strong></div><div><small>Financiero</small><strong>{display(resumen.financiero)}</strong></div><div><small>Visitador</small><strong>{display(resumen.visitador)}</strong></div><div><small>Fase</small><strong>{display(resumen.fase)}</strong></div><div><small>Riesgo</small><strong>{display(resumen.riesgo)}</strong></div><div><small>Próxima acción</small><strong>{display(resumen.proxima)}</strong></div></div></article><article className="detail-summary-card"><span>OPERACIÓN</span><h2>Datos económicos</h2><div className="detail-kv"><div><small>Precio</small><strong>{display(economicos.precio)}</strong></div><div><small>Financiación</small><strong>{display(economicos.financiacion)}</strong></div><div><small>Ahorro</small><strong>{display(economicos.ahorro)}</strong></div><div><small>Ingresos</small><strong>{display(economicos.ingresos)}</strong></div><div><small>Deudas</small><strong>{display(economicos.deudas)}</strong></div><div><small>Ratio</small><strong>{display(economicos.ratio)}</strong></div><div><small>LTV</small><strong>{display(economicos.ltv)}</strong></div><div><small>Banco</small><strong>{display(economicos.banco)}</strong></div></div><p className="detail-source-note">Los campos sin fuente conectada se muestran vacíos, nunca inventados.</p></article></div>
    {canonical&&isNotionId(code)&&<ExpedientePeoplePanel expedienteId={code}/>} 
    <article className="detail-next-action"><img src={anaAvatar} alt="Ana"/><div><span>ANA · SIGUIENTE MEJOR ACCIÓN</span><h2>{resumen.proxima?display(resumen.proxima):'Confirmar el dato que desbloquee el caso'}</h2><p><b>Por qué:</b> {resumen.proxima?'es la próxima acción registrada en el expediente canónico y debe resolverse antes de avanzar.':'todavía no existe una próxima acción segura; primero hay que completar el dato que falta.'}</p><div className="detail-prepared"><small>SI LO HACES TÚ</small><p>Te indicaré el paso concreto y, al terminar, registrarás qué ocurrió para que yo recalcule el siguiente paso.</p></div><div className="detail-prepared"><small>SI LO HAGO YO</small><p>Te enseñaré exactamente qué voy a hacer, qué dato usaré, qué mensaje/guion aplicaré y qué resultado espero antes de ejecutar. Si mi capacidad todavía está bloqueada, no ejecutaré silenciosamente.</p></div><div className="detail-prepared"><small>CONTACTO · VISTA PREVIA OBLIGATORIA</small><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:8}}><button onClick={()=>navigate(`/comunicaciones/nueva?scope_type=expediente&scope_code=${encodeURIComponent(code)}&channel=Llamada`)}>Llamada · ver guion exacto</button><button onClick={()=>navigate(`/comunicaciones/nueva?scope_type=expediente&scope_code=${encodeURIComponent(code)}&channel=WhatsApp`)}>WhatsApp · ver texto exacto</button><button onClick={()=>navigate(`/comunicaciones/nueva?scope_type=expediente&scope_code=${encodeURIComponent(code)}&channel=Email`)}>Email · ver asunto y texto</button></div></div><div className="detail-ana-actions"><button onClick={()=>ana('do')}><strong>Que lo haga Ana</strong><small>Solo si el backend lo autoriza</small></button><button onClick={()=>ana('help')}><strong>Ayúdame</strong><small>Ver texto, motivo y pasos</small></button><button onClick={()=>ana('self')}><strong>Lo hago yo</strong><small>Registrar resultado real</small></button></div></div></article>
    <div className="detail-action-row"><button className="primary" onClick={()=>navigate(`/comunicaciones/nueva?scope_type=expediente&scope_code=${encodeURIComponent(code)}`)}><MessageCircle size={16}/> Preparar Email / WhatsApp / Llamada</button><button onClick={()=>navigate(`/documentacion?expediente=${encodeURIComponent(code)}&upload=1`)}>Documentación</button><button onClick={()=>navigate(`/tasaciones?expediente=${encodeURIComponent(code)}`)}>Tasaciones</button><button onClick={()=>navigate(`/firmas?expediente=${encodeURIComponent(code)}`)}>FEIN / Firma</button></div>
    {canonical&&isNotionId(code)&&<div className="ops-table-card" id="seguimiento-contextual"><div className="ops-table-head"><strong>Seguimiento contextual</strong><span>Escritura permitida y auditada · PRE-PROD</span></div><div className="ops-message" style={{display:'grid',gap:10}}><label>Notas<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Añade contexto operativo sin duplicar datos..."/></label><label>Próxima acción<input type="date" value={nextAction} onChange={e=>setNextAction(e.target.value)}/></label><div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}><button className="primary" disabled={actionBusy||(!notes.trim()&&!nextAction)} onClick={saveFollowUp}><Save size={16}/>{actionBusy?'Guardando…':'Guardar seguimiento'}</button>{actionMsg&&<span>{actionMsg}</span>}</div></div></div>}
   </>}
  </section></main></div>;
}
