import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,FileText,FolderOpen,Landmark,MessageCircle,Save} from 'lucide-react';
import {fetchAppApi,IS_PRODUCTION,SUPABASE_URL,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './detail-expediente.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';
type Ctx={role?:string;display_name?:string};
type Row=Record<string,any>;
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
const phases=['Entrada','Documentación','Análisis','Banco','Tasación','Oferta','FEIN','Notaría','Firma','Cierre'];
const stageOptions=['Entrada','Documentación','Análisis','Banco','Tasación','Oferta','FEIN','Notaría','Firma','Cierre','Revisión legado'];
function text(row:Row|null,keys:string[]){if(!row)return'';for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim()}return''}
function phaseIndex(raw:string){const s=raw.toLowerCase();const aliases=[['entrada','nuevo','inicial'],['document','doc'],['análisis','analisis','estudio'],['banco','banc'],['tasación','tasacion'],['oferta','aprob'],['fein'],['notar'],['firma'],['cierre','cerrado','final']];const i=aliases.findIndex(group=>group.some(x=>s.includes(x)));return i>=0?i:0}
function rowsFrom(data:any):Row[]{return Array.isArray(data?.items)?data.items:[]}
function idOf(r:Row){return text(r,['id','inmobiliaria_code','code'])}
function nameOf(r:Row){return text(r,['inmobiliaria','nombre','nombre_alias'])||idOf(r)}

export default function DetailShell(){
 const location=useLocation(),navigate=useNavigate();
 const match=location.pathname.match(/^\/expedientes\/([^/]+)$/);const code=match?.[1]?decodeURIComponent(match[1]):'';const active=Boolean(match&&code&&code!=='nuevo');
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[query,setQuery]=useState('');
 const[status,setStatus]=useState<number|null>(null),[row,setRow]=useState<Row|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[inmos,setInmos]=useState<Row[]>([]);
 const[cliente,setCliente]=useState(''),[stage,setStage]=useState(''),[inmo,setInmo]=useState(''),[notas,setNotas]=useState(''),[proxima,setProxima]=useState(''),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[saveMsg,setSaveMsg]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()}},[active]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchNotionRuntime<any>('/inmobiliarias')]).then(([c,n,i])=>{if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);setInmos(i.status===200?rowsFrom(i.data):[])});return()=>{alive=false}},[active,logged]);
 async function load(){setLoading(true);setMessage('');const r=await fetchNotionRuntime<any>(`/expedientes/${encodeURIComponent(code)}`);setStatus(r.status);const item=r.status===200?(r.data?.item||r.data?.expediente||null):null;setRow(item);if(item){setCliente(text(item,['cliente','cliente_alias']));setStage(text(item,['stage','fase','estado']));setInmo(text(item,['inmobiliaria_code']));setNotas(text(item,['notas']));setProxima(text(item,['proxima_accion']));setDirty(false);setPreview(false)}if(r.status===403)setMessage('Tu perfil no puede abrir este expediente.');else if(r.status===404)setMessage('No se ha encontrado el expediente.');else if(r.status!==200)setMessage('No se pudo cargar el expediente.');setLoading(false)}
 useEffect(()=>{if(active&&logged)void load()},[active,logged,code]);
 const effectiveNav=nav.length?nav:fallbackNav;const displayName=ctx?.display_name||ctx?.role||'Usuario';const version=Number(row?.version||0);const canEdit=ctx?.role==='Direccion'||ctx?.role==='Financiero';const title=cliente||text(row,['expediente','expediente_code'])||'Expediente';const pIndex=phaseIndex(stage||'Entrada');const inmoName=useMemo(()=>nameOf(inmos.find(x=>idOf(x)===inmo)||{})||'Sin inmobiliaria',[inmos,inmo]);
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}
 function search(){const q=query.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 function changed(){setDirty(true);setPreview(false);setSaveMsg('')}
 async function save(){if(!canEdit||!dirty||!row)return;setBusy(true);setSaveMsg('');let result:{status:number;data:any};if(IS_PRODUCTION){const {data,error}=await supabase.rpc('fenix_prod_exp_update',{p_code:code,p_expected_version:version,p_cliente_alias:cliente.trim()||null,p_stage:stage||null,p_inmobiliaria_code:inmo||null,p_notas:notas||null,p_proxima_accion:proxima||null});result={status:error?500:Number(data?.status||200),data:data||{error:error?.message}}}else{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token){result={status:401,data:null}}else{const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-notion-actions-test/expedientes/${encodeURIComponent(code)}/action`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action:'update',changes:{notas,proxima_accion:proxima,stage,cliente_alias:cliente,inmobiliaria_code:inmo}})});let data:any=null;try{data=await r.json()}catch{}result={status:r.status,data}}}setBusy(false);if(result.status===200&&result.data?.ok!==false){setSaveMsg('Cambios guardados correctamente.');await load()}else if(result.status===409){setSaveMsg('La ficha cambió mientras editabas. He recargado la versión actual para evitar sobrescribir datos.');await load()}else if(result.status===403)setSaveMsg('Tu perfil no puede modificar este expediente.');else setSaveMsg(`No se pudo guardar (${result.data?.error||result.status}).`)}
 return <OperationalShellFrame className="detail-exp-root" theme={theme} navigation={effectiveNav} activeRoute="/expedientes" anaSubtitle="Te digo qué revisar y puedes actualizar la ficha sin salir de aquí." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar expediente, cliente o tarea..." searchActionLabel="Buscar" onSearchAction={search} name={displayName} role={ctx?.role||''} initials={displayName.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="detail-exp-content">
  <section className="inmo-ana-hero" data-testid="expediente-detail-ana"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · EXPEDIENTE</span><h2>Trabaja toda la operación desde una sola ficha</h2><p>La fase, el seguimiento, la inmobiliaria y las acciones quedan visibles sin salir del shell normal de la aplicación.</p><div className="inmo-next"><button onClick={()=>navigate(`/documentacion?expediente=${encodeURIComponent(code)}`)}><b>1</b><strong>Documentación</strong><small>Revisar / subir →</small></button><button onClick={()=>navigate(`/bancos?expediente=${encodeURIComponent(code)}`)}><b>2</b><strong>Banco</strong><small>Comparar opciones →</small></button><button onClick={()=>navigate(`/firmas?expediente=${encodeURIComponent(code)}`)}><b>3</b><strong>FEIN / Firma</strong><small>Preparar →</small></button></div></div></section>
  <button className="detail-back" type="button" onClick={()=>navigate('/expedientes')}><ArrowLeft size={15}/> Volver a expedientes</button>
  <div className="ops-title"><div><span className="ops-icon"><FolderOpen size={20}/></span><div><h1>{title}</h1><p>Ficha operativa · {IS_PRODUCTION?'PROD':'PRE-PROD'} · versión {version}</p></div></div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos actualizados':'Sin conexión'}</span></div>
  {loading&&<div className="ops-empty"><strong>Cargando expediente…</strong></div>}{message&&<div className="ops-message">{message}</div>}
  {row&&<>
   <section className="detail-journey" data-testid="expediente-phase-line"><div className="detail-section-label">FASE DEL EXPEDIENTE</div><div className="detail-phase-track">{phases.map((phase,i)=><div key={phase} className={i<pIndex?'done':i===pIndex?'current':''}><span>{i<pIndex?'✓':i+1}</span><small>{phase}</small></div>)}</div></section>
   <section className="inmo-kpis"><article><FolderOpen/><small>FASE</small><strong>{stage||'Sin fase'}</strong><span>Situación actual</span></article><article><Landmark/><small>INMOBILIARIA</small><strong>{inmoName}</strong><span>Origen / colaboración</span></article><article><FileText/><small>PRÓXIMA ACCIÓN</small><strong>{proxima||'Sin fecha'}</strong><span>Seguimiento</span></article><article><MessageCircle/><small>RESPONSABLE</small><strong>{text(row,['owner_actor_code'])||'Sin asignar'}</strong><span>Ámbito autorizado</span></article></section>
   <section className="ops-table-card" style={{padding:20,display:'grid',gap:14}} data-testid="expediente-operational-edit"><div className="ops-table-head"><strong>Trabajar expediente</strong><span>{canEdit?'Escritura auditada':'Solo lectura'}</span></div><label>Cliente / alias<input value={cliente} disabled={!canEdit} onChange={e=>{setCliente(e.target.value);changed()}}/></label><label>Fase<select value={stage} disabled={!canEdit} onChange={e=>{setStage(e.target.value);changed()}}><option value="">Sin fase</option>{stageOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Inmobiliaria<select value={inmo} disabled={!canEdit} onChange={e=>{setInmo(e.target.value);changed()}}><option value="">Sin inmobiliaria</option>{inmos.map(x=>{const id=idOf(x);return id?<option key={id} value={id}>{nameOf(x)}</option>:null})}</select></label><label>Próxima acción<input type="date" value={proxima} disabled={!canEdit} onChange={e=>{setProxima(e.target.value);changed()}}/></label><label>Notas<textarea rows={5} value={notas} disabled={!canEdit} onChange={e=>{setNotas(e.target.value);changed()}} placeholder="Contexto operativo y próximos pasos"/></label>{canEdit&&!preview?<button className="primary" disabled={!dirty||busy} onClick={()=>setPreview(true)}>Revisar cambios</button>:canEdit&&preview?<div className="ops-message"><strong>Vista previa</strong><p>Cliente: {cliente||'—'} · Fase: {stage||'—'} · Inmobiliaria: {inmoName} · Próxima acción: {proxima||'—'}</p><button type="button" onClick={()=>setPreview(false)}>Seguir editando</button><button className="primary" type="button" disabled={busy} onClick={save}><Save size={16}/>{busy?'Guardando…':'Confirmar y guardar'}</button></div>:null}{saveMsg&&<div className="ops-message">{saveMsg}</div>}</section>
   <div className="detail-action-row"><button className="primary" onClick={()=>navigate(`/comunicaciones/nueva?scope_type=expediente&scope_code=${encodeURIComponent(code)}`)}><MessageCircle size={16}/> Preparar comunicación</button><button onClick={()=>navigate(`/documentacion?expediente=${encodeURIComponent(code)}&upload=1`)}>Subir documentación</button><button onClick={()=>navigate(`/tasaciones?expediente=${encodeURIComponent(code)}`)}>Tasaciones</button><button onClick={()=>navigate(`/firmas?expediente=${encodeURIComponent(code)}`)}>FEIN / Firma</button></div>
  </>}
 </OperationalShellFrame>
}
