import {FormEvent,useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Building2,Plus,Save,Trash2,Users,X} from 'lucide-react';
import {fetchAppApi,fetchEnvironmentApi,supabase} from './supabase';
import {anaVertical} from './assets/visualAssets';
import type {NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './inmobiliarias-polish.css';
import './directory-create.css';

type Theme='light'|'dark';type Ctx={role?:string};type Staff={id:string;nombre:string;apellidos:string;cargo:string;telefonos:string[];emails:string[];observaciones:string};
type Def={route:'/notarias/nueva'|'/registros-propiedad/nuevo';back:string;label:string;singular:string;kind:'notaria'|'registro'};
const defs:Def[]=[{route:'/notarias/nueva',back:'/notarias',label:'Nueva notaría',singular:'notaría',kind:'notaria'},{route:'/registros-propiedad/nuevo',back:'/registros-propiedad',label:'Nuevo registro de la propiedad',singular:'registro de la propiedad',kind:'registro'}];
const blank=():Staff=>({id:crypto.randomUUID(),nombre:'',apellidos:'',cargo:'',telefonos:[''],emails:[''],observaciones:''});
const changeAt=(items:string[],index:number,value:string)=>items.map((x,i)=>i===index?value:x);
async function createDirectory(path:string,payload:any){return fetchEnvironmentApi<any>('fenix-directory-actions',`/${path}`,{method:'POST',body:JSON.stringify(payload)});}
export default function DirectoryCreateShell(){const location=useLocation(),navigate=useNavigate(),found=defs.find(d=>d.route===location.pathname);const active=Boolean(found);const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[query,setQuery]=useState('');const[nombre,setNombre]=useState(''),[provincia,setProvincia]=useState('Córdoba'),[localidad,setLocalidad]=useState(''),[direccion,setDireccion]=useState(''),[cp,setCp]=useState(''),[telefonos,setTelefonos]=useState<string[]>(['']),[emails,setEmails]=useState<string[]>(['']),[horario,setHorario]=useState(''),[municipios,setMunicipios]=useState(''),[staff,setStaff]=useState<Staff[]>([blank()]),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<any>(null);
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;fetchAppApi<Ctx>('/session/context').then(r=>{if(alive)setCtx(r.status===200?r.data:null)});return()=>{alive=false}},[active,logged]);
 if(!active||!found||!ready||!logged)return null;
 const def:Def=found;
 const validPeople=staff.filter(p=>p.nombre.trim().length>=2),valid=ctx?.role==='Direccion'&&nombre.trim().length>=2;const nav:NavItem[]=[{label:`Volver a ${def.kind==='notaria'?'Notarías':'Registros'}`,route:def.back}];
 const attention=!nombre.trim()?`Falta identificar ${def.singular}.`:validPeople.length===0?'La ficha base está preparada. Añade el personal que conozcas para dejarla operativa.':`${validPeople.length} persona${validPeople.length===1?'':'s'} quedará${validPeople.length===1?'':'n'} vinculada${validPeople.length===1?'':'s'} automáticamente.`;
 const next=!nombre.trim()?'Empieza por el nombre.':!localidad.trim()?'Completa la localidad o municipio sede.':validPeople.length===0?'Añade notario, registrador, oficial, administración u otro personal si lo conoces.':'Revisa y confirma el alta.';
 const cargoOptions=def.kind==='notaria'?['Notario/a','Oficial','Administración','Empleado/a','Otro']:['Registrador/a','Oficial','Administración','Empleado/a','Otro'];
 function edit(){setPreview(false);setMessage('');setResult(null)}function updatePerson(id:string,patch:Partial<Staff>){setStaff(list=>list.map(p=>p.id===id?{...p,...patch}:p));edit()}function remove(id:string){setStaff(list=>list.length===1?[blank()]:list.filter(p=>p.id!==id));edit()}
 async function submit(e:FormEvent){e.preventDefault();if(!valid)return;if(!preview){setPreview(true);return}setBusy(true);setMessage('');const cleanPhones=telefonos.map(x=>x.trim()).filter(Boolean),cleanEmails=emails.map(x=>x.trim()).filter(Boolean);const personal=validPeople.map(p=>({...p,telefono:p.telefonos.map(x=>x.trim()).filter(Boolean)[0]||'',email:p.emails.map(x=>x.trim()).filter(Boolean)[0]||'',telefonos:p.telefonos.map(x=>x.trim()).filter(Boolean),emails:p.emails.map(x=>x.trim()).filter(Boolean)}));const payload=def.kind==='notaria'?{nombre,provincia,localidad,direccion,telefono:cleanPhones[0]||'',email:cleanEmails[0]||'',telefonos:cleanPhones,emails:cleanEmails,horario,personal}:{nombre,provincia,municipio:localidad,direccion,cp,telefono:cleanPhones[0]||'',email:cleanEmails[0]||'',telefonos:cleanPhones,emails:cleanEmails,horario,municipios_cubiertos:municipios,personal};const r=await createDirectory(def.kind==='notaria'?'notarias/create':'registros/create',payload);setBusy(false);setResult(r.data);if((r.status===200||r.status===201)&&r.data?.ok){const p=r.data.personal??{};setMessage(`${def.label.replace(/^Nuev[oa] /,'')} ${r.data.reused?'ya existía y se ha reutilizado':'creado correctamente'}. Personal: ${p.created??0} creado y ${p.reused??0} reutilizado.`);setPreview(false)}else if(r.status===403)setMessage('Solo Dirección puede realizar esta alta.');else setMessage(`No se pudo completar el alta (${r.data?.error||r.status}).`)}
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}function search(){const q=query.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 const peopleTitle=def.kind==='notaria'?'Personal de la notaría':'Personal del registro de la propiedad';
 return <OperationalShellFrame className="inmo-root inmo-create-root" theme={theme} navigation={nav} activeRoute={def.back} anaSubtitle="Te guío en la ficha y en todo el personal relacionado." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar en toda la app..." searchActionLabel="Buscar" onSearchAction={search} name={ctx?.role||'Usuario'} role={ctx?.role||''} initials={(ctx?.role||'U').slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content">
 <div className="ops-title"><div><span className="ops-icon"><Building2 size={20}/></span><div><h1>{def.label}</h1><p>Ficha del directorio y personal relacionado en una sola operación.</p></div></div></div>
 <section className="inmo-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · {def.label.toUpperCase()}</span><h2>La dejamos completa desde el alta</h2><p>Creo la ficha principal y, en el mismo proceso, cada persona queda vinculada. Teléfonos y correos se pueden repetir tantas veces como haga falta.</p><div className="inmo-next"><button type="button"><b>1</b><strong>Qué necesita atención</strong><small>{attention}</small></button><button type="button"><b>2</b><strong>Qué estoy comprobando</strong><small>Identidad, ubicación, contacto general y personal relacionado sin inventar datos.</small></button><button type="button"><b>3</b><strong>Siguiente paso</strong><small>{next}</small></button></div></div><article className="inmo-correct"><span>CONTROL ANTES DE GUARDAR</span><h3>Revisión guiada</h3><p>Puedes añadir tantas personas, teléfonos y correos como necesites.</p><textarea readOnly value={attention}/><input readOnly value={next}/><button type="button" disabled={!valid} onClick={()=>setPreview(true)}>Revisar alta con Ana</button></article></section>
 {ctx?.role!=='Direccion'?<div className="ops-message">Solo Dirección puede crear esta ficha.</div>:<form className="ops-message" onSubmit={submit} style={{display:'grid',gap:16}}><section className="directory-form-grid"><label>Nombre<input value={nombre} onChange={e=>{setNombre(e.target.value);edit()}} required/></label><label>Provincia<select value={provincia} onChange={e=>{setProvincia(e.target.value);edit()}}><option>Córdoba</option><option>Jaén</option></select></label><label>{def.kind==='notaria'?'Localidad':'Municipio sede'}<input value={localidad} onChange={e=>{setLocalidad(e.target.value);edit()}}/></label><label>Dirección<input value={direccion} onChange={e=>{setDireccion(e.target.value);edit()}}/></label>{def.kind==='registro'&&<label>CP<input value={cp} onChange={e=>{setCp(e.target.value);edit()}}/></label>}<div className="multi-contact-group"><div className="multi-contact-head"><strong>Teléfonos</strong><button type="button" onClick={()=>setTelefonos(v=>[...v,''])}><Plus size={15}/> Añadir teléfono</button></div>{telefonos.map((v,i)=><label key={i}>{i===0?'Teléfono':`Teléfono ${i+1}`}<span className="multi-contact-row"><input value={v} onChange={e=>setTelefonos(x=>changeAt(x,i,e.target.value))} inputMode="tel"/>{telefonos.length>1&&<button type="button" onClick={()=>setTelefonos(x=>x.filter((_,j)=>j!==i))}><X size={15}/></button>}</span></label>)}</div><div className="multi-contact-group"><div className="multi-contact-head"><strong>Correos</strong><button type="button" onClick={()=>setEmails(v=>[...v,''])}><Plus size={15}/> Añadir correo</button></div>{emails.map((v,i)=><label key={i}>{i===0?'Email':`Email ${i+1}`}<span className="multi-contact-row"><input type="email" value={v} onChange={e=>setEmails(x=>changeAt(x,i,e.target.value))}/>{emails.length>1&&<button type="button" onClick={()=>setEmails(x=>x.filter((_,j)=>j!==i))}><X size={15}/></button>}</span></label>)}</div><label>Horario / observaciones<input value={horario} onChange={e=>{setHorario(e.target.value);edit()}}/></label>{def.kind==='registro'&&<label>Municipios cubiertos<input value={municipios} onChange={e=>{setMunicipios(e.target.value);edit()}}/></label>}</section>
 <details className="directory-people-panel" data-testid={def.kind==='notaria'?'notaria-create-people':'registro-create-people'} open><summary><span><Users size={18}/> {peopleTitle}</span><small>{validPeople.length} preparado{validPeople.length===1?'':'s'}</small></summary><p>Añade tantas personas como necesites. Cada persona puede tener varios teléfonos y correos.</p><div className="directory-people-list">{staff.map((p,i)=><article className="directory-person-card" key={p.id}><div className="directory-person-head"><strong>Contacto {i+1}</strong><button type="button" onClick={()=>remove(p.id)} aria-label={`Quitar contacto ${i+1}`}><Trash2 size={15}/></button></div><div className="directory-person-grid"><label>Nombre<input value={p.nombre} onChange={e=>updatePerson(p.id,{nombre:e.target.value})}/></label><label>Apellidos<input value={p.apellidos} onChange={e=>updatePerson(p.id,{apellidos:e.target.value})}/></label><label>Cargo<select value={p.cargo} onChange={e=>updatePerson(p.id,{cargo:e.target.value})}><option value="">Seleccionar</option>{cargoOptions.map(x=><option key={x}>{x}</option>)}</select></label><div className="multi-contact-group"><div className="multi-contact-head"><strong>Teléfonos</strong><button type="button" onClick={()=>updatePerson(p.id,{telefonos:[...p.telefonos,'']})}><Plus size={14}/></button></div>{p.telefonos.map((v,j)=><label key={j}>Teléfono {j+1}<span className="multi-contact-row"><input value={v} onChange={e=>updatePerson(p.id,{telefonos:changeAt(p.telefonos,j,e.target.value)})}/>{p.telefonos.length>1&&<button type="button" onClick={()=>updatePerson(p.id,{telefonos:p.telefonos.filter((_,k)=>k!==j)})}><X size={14}/></button>}</span></label>)}</div><div className="multi-contact-group"><div className="multi-contact-head"><strong>Correos</strong><button type="button" onClick={()=>updatePerson(p.id,{emails:[...p.emails,'']})}><Plus size={14}/></button></div>{p.emails.map((v,j)=><label key={j}>Correo {j+1}<span className="multi-contact-row"><input type="email" value={v} onChange={e=>updatePerson(p.id,{emails:changeAt(p.emails,j,e.target.value)})}/>{p.emails.length>1&&<button type="button" onClick={()=>updatePerson(p.id,{emails:p.emails.filter((_,k)=>k!==j)})}><X size={14}/></button>}</span></label>)}</div><label>Observaciones<input value={p.observaciones} onChange={e=>updatePerson(p.id,{observaciones:e.target.value})}/></label></div></article>)}</div><button type="button" className="directory-add-person" onClick={()=>setStaff(list=>[...list,blank()])}><Plus size={16}/> Añadir otra persona</button></details>
 {preview&&<div className="ops-message"><strong>Vista previa</strong><div>{def.kind==='notaria'?'Notaría':'Registro'}: {nombre}</div><div>Ubicación: {localidad||'No indicada'} · {provincia}</div><div>Personal a crear/vincular: {validPeople.length}</div></div>}{message&&<div className="ops-message">{message}</div>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{preview&&<button type="button" onClick={()=>setPreview(false)}>Volver</button>}<button className="primary" disabled={!valid||busy}><Save size={16}/>{busy?'Creando y vinculando…':preview?'Confirmar y crear':'Revisar antes de crear'}</button>{result?.destino&&<button type="button" onClick={()=>navigate(result.destino)}>Abrir ficha</button>}</div></form>}
 </OperationalShellFrame>}
