import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Building2,Plus,Save,Trash2,Users} from 'lucide-react';
import {fetchAppApi,SUPABASE_URL,supabase} from './supabase';
import {anaVertical} from './assets/visualAssets';
import type {NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './inmobiliarias-polish.css';
import './directory-create.css';

type Theme='light'|'dark';type Ctx={role?:string};type Staff={id:string;nombre:string;apellidos:string;cargo:string;telefono:string;email:string;observaciones:string};
type Def={route:'/notarias/nueva'|'/registros-propiedad/nuevo';back:string;label:string;singular:string;kind:'notaria'|'registro'};
const defs:Def[]=[{route:'/notarias/nueva',back:'/notarias',label:'Nueva notaría',singular:'notaría',kind:'notaria'},{route:'/registros-propiedad/nuevo',back:'/registros-propiedad',label:'Nuevo registro de la propiedad',singular:'registro de la propiedad',kind:'registro'}];
const blank=():Staff=>({id:crypto.randomUUID(),nombre:'',apellidos:'',cargo:'',telefono:'',email:'',observaciones:''});
async function createDirectory(path:string,payload:any){const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return{status:401,data:null as any};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-directory-actions-test/${path}`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});let data:any=null;try{data=await r.json()}catch{}return{status:r.status,data};}
export default function DirectoryCreateShell(){const location=useLocation(),navigate=useNavigate(),def=defs.find(d=>d.route===location.pathname);const active=Boolean(def);const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[query,setQuery]=useState('');const[nombre,setNombre]=useState(''),[provincia,setProvincia]=useState('Córdoba'),[localidad,setLocalidad]=useState(''),[direccion,setDireccion]=useState(''),[cp,setCp]=useState(''),[telefono,setTelefono]=useState(''),[email,setEmail]=useState(''),[horario,setHorario]=useState(''),[municipios,setMunicipios]=useState(''),[staff,setStaff]=useState<Staff[]>([blank()]),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<any>(null);
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;fetchAppApi<Ctx>('/session/context').then(r=>{if(alive)setCtx(r.status===200?r.data:null)});return()=>{alive=false}},[active,logged]);
 const validPeople=staff.filter(p=>p.nombre.trim().length>=2),valid=ctx?.role==='Direccion'&&nombre.trim().length>=2;const nav:NavItem[]=def?[{label:`Volver a ${def.kind==='notaria'?'Notarías':'Registros'}`,route:def.back}]:[];
 const attention=!nombre.trim()?`Falta identificar ${def?.singular||'el registro'}.`:validPeople.length===0?'La ficha base está preparada. Añade el personal que conozcas para dejarla operativa.':`${validPeople.length} persona${validPeople.length===1?'':'s'} quedará${validPeople.length===1?'':'n'} vinculada${validPeople.length===1?'':'s'} automáticamente.`;
 const next=!nombre.trim()?'Empieza por el nombre.':!localidad.trim()?'Completa la localidad o municipio sede.':validPeople.length===0?'Añade notario, registrador, oficial, administración u otro personal si lo conoces.':'Revisa y confirma el alta.';
 const cargoOptions=def?.kind==='notaria'?['Notario/a','Oficial','Administración','Empleado/a','Otro']:['Registrador/a','Oficial','Administración','Empleado/a','Otro'];
 if(!active||!def||!ready||!logged)return null;function edit(){setPreview(false);setMessage('');setResult(null)}function updatePerson(id:string,patch:Partial<Staff>){setStaff(list=>list.map(p=>p.id===id?{...p,...patch}:p));edit()}function remove(id:string){setStaff(list=>list.length===1?[blank()]:list.filter(p=>p.id!==id));edit()}
 async function submit(e:FormEvent){e.preventDefault();if(!valid)return;if(!preview){setPreview(true);return}setBusy(true);setMessage('');const payload=def.kind==='notaria'?{nombre,provincia,localidad,direccion,telefono,email,horario,personal:validPeople}:{nombre,provincia,municipio:localidad,direccion,cp,telefono,email,horario,municipios_cubiertos:municipios,personal:validPeople};const r=await createDirectory(def.kind==='notaria'?'notarias/create':'registros/create',payload);setBusy(false);setResult(r.data);if((r.status===200||r.status===201)&&r.data?.ok){const p=r.data.personal??{};setMessage(`${def.label.replace(/^Nuev[oa] /,'')} ${r.data.reused?'ya existía y se ha reutilizado':'creado correctamente'}. Personal: ${p.created??0} creado y ${p.reused??0} reutilizado.`);setPreview(false)}else if(r.status===403)setMessage('Solo Dirección puede realizar esta alta.');else setMessage(`No se pudo completar el alta (${r.data?.error||r.status}).`)}
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}function search(){const q=query.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 return <OperationalShellFrame className="inmo-root inmo-create-root" theme={theme} navigation={nav} activeRoute={def.back} anaSubtitle="Te guío en la ficha y en todo el personal relacionado." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar en toda la app..." searchActionLabel="Buscar" onSearchAction={search} name={ctx?.role||'Usuario'} role={ctx?.role||''} initials={(ctx?.role||'U').slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content">
 <section className="inmo-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · {def.label.toUpperCase()}</span><h2>La dejamos completa desde el alta</h2><p>Creo la ficha principal y, en el mismo proceso, cada persona que añadas queda vinculada como personal del directorio para que luego aparezca como contacto relacionado.</p><div className="inmo-next"><button type="button"><b>1</b><strong>Qué necesita atención</strong><small>{attention}</small></button><button type="button"><b>2</b><strong>Qué estoy comprobando</strong><small>Identidad, ubicación, contacto general y personal relacionado sin inventar datos.</small></button><button type="button"><b>3</b><strong>Siguiente paso</strong><small>{next}</small></button></div></div><article className="inmo-correct"><span>CONTROL ANTES DE GUARDAR</span><h3>Revisión guiada</h3><p>Puedes añadir tantas personas como necesites. Si no conoces un dato, lo dejamos vacío; no lo completamos por intuición.</p><textarea readOnly value={attention}/><input readOnly value={next}/><button type="button" disabled={!valid} onClick={()=>setPreview(true)}>Revisar alta con Ana</button></article></section>
 <div className="ops-title"><div><span className="ops-icon"><Building2 size={20}/></span><div><h1>{def.label}</h1><p>Ficha del directorio y personal relacionado en una sola operación.</p></div></div></div>
 {ctx?.role!=='Direccion'?<div className="ops-message">Solo Dirección puede crear esta ficha.</div>:<form className="ops-message" onSubmit={submit} style={{display:'grid',gap:16}}><section className="directory-form-grid"><label>Nombre<input value={nombre} onChange={e=>{setNombre(e.target.value);edit()}} required/></label><label>Provincia<select value={provincia} onChange={e=>{setProvincia(e.target.value);edit()}}><option>Córdoba</option><option>Jaén</option></select></label><label>{def.kind==='notaria'?'Localidad':'Municipio sede'}<input value={localidad} onChange={e=>{setLocalidad(e.target.value);edit()}}/></label><label>Dirección<input value={direccion} onChange={e=>{setDireccion(e.target.value);edit()}}/></label>{def.kind==='registro'&&<label>CP<input value={cp} onChange={e=>{setCp(e.target.value);edit()}}/></label>}<label>Teléfono<input value={telefono} onChange={e=>{setTelefono(e.target.value);edit()}}/></label><label>Email<input type="email" value={email} onChange={e=>{setEmail(e.target.value);edit()}}/></label><label>Horario / observaciones<input value={horario} onChange={e=>{setHorario(e.target.value);edit()}}/></label>{def.kind==='registro'&&<label>Municipios cubiertos<input value={municipios} onChange={e=>{setMunicipios(e.target.value);edit()}}/></label>}</section>
 <details className="directory-people-panel" open><summary><span><Users size={18}/> Personal de {def.kind==='notaria'?'la notaría':'el registro'}</span><small>{validPeople.length} preparado{validPeople.length===1?'':'s'}</small></summary><p>Incluye todas las personas que necesites. Se crearán en el maestro de personal y quedarán relacionadas con esta ficha.</p><div className="directory-people-list">{staff.map((p,i)=><article className="directory-person-card" key={p.id}><div className="directory-person-head"><strong>Persona {i+1}</strong><button type="button" onClick={()=>remove(p.id)}><Trash2 size={15}/></button></div><div className="directory-person-grid"><label>Nombre<input value={p.nombre} onChange={e=>updatePerson(p.id,{nombre:e.target.value})}/></label><label>Apellidos<input value={p.apellidos} onChange={e=>updatePerson(p.id,{apellidos:e.target.value})}/></label><label>Cargo<select value={p.cargo} onChange={e=>updatePerson(p.id,{cargo:e.target.value})}><option value="">Seleccionar</option>{cargoOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>Teléfono directo<input value={p.telefono} onChange={e=>updatePerson(p.id,{telefono:e.target.value})}/></label><label>Email directo<input type="email" value={p.email} onChange={e=>updatePerson(p.id,{email:e.target.value})}/></label><label>Observaciones<input value={p.observaciones} onChange={e=>updatePerson(p.id,{observaciones:e.target.value})}/></label></div></article>)}</div><button type="button" className="directory-add-person" onClick={()=>setStaff(list=>[...list,blank()])}><Plus size={16}/> Añadir otra persona</button></details>
 {preview&&<div className="ops-message"><strong>Vista previa</strong><div>{def.kind==='notaria'?'Notaría':'Registro'}: {nombre}</div><div>Ubicación: {localidad||'No indicada'} · {provincia}</div><div>Personal a crear/vincular: {validPeople.length}</div></div>}{message&&<div className="ops-message">{message}</div>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{preview&&<button type="button" onClick={()=>setPreview(false)}>Volver</button>}<button className="primary" disabled={!valid||busy}><Save size={16}/>{busy?'Creando y vinculando…':preview?'Confirmar y crear':'Revisar antes de crear'}</button>{result?.destino&&<button type="button" onClick={()=>navigate(result.destino)}>Abrir ficha</button>}</div></form>}
 </OperationalShellFrame>}
