import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import {IS_PRODUCTION,fetchEnvironmentApi} from './supabase';
import './direction-kpi-drilldown.css';

type Row=Record<string,unknown>;
type Payload={ok?:boolean;key?:string;month?:string;count?:number;complete?:boolean;total?:number|null;total_known?:number;unresolved?:number;items?:Row[];error?:string};
type Spec={key:string;title:string;route:string;summary:string;columns:Array<[string,string]>};

const SPECS:Record<string,Spec>={
 'expedientes-en-curso':{key:'expedientes-en-curso',title:'Expedientes en curso',route:'/expedientes?estado=en-curso&kpi=expedientes-en-curso',summary:'Expedientes cuya fase no es Firmado, Posventa ni Perdido.',columns:[['expediente','Expediente'],['fase','Fase'],['semaforo','Semáforo'],['proxima_accion','Próxima acción'],['importe_solicitado','Importe solicitado']]},
 'firmas-previstas':{key:'firmas-previstas',title:'Firmas previstas este mes',route:'/firmas?firma=mes-actual&estado=prevista&kpi=firmas-previstas',summary:'Firmas con fecha dentro del mes actual cuyo estado todavía no es Firmado.',columns:[['firma','Firma'],['fecha_firma','Fecha firma'],['estado','Estado'],['notaria','Notaría']]},
 'firmadas':{key:'firmadas',title:'Firmados este mes',route:'/firmas?firma=mes-actual&estado=firmada&kpi=firmadas',summary:'Firmas del mes actual cuyo estado canónico es Firmado.',columns:[['firma','Firma'],['fecha_firma','Fecha firma'],['estado','Estado'],['notaria','Notaría']]},
 'expedientes-en-riesgo':{key:'expedientes-en-riesgo',title:'Expedientes en riesgo',route:'/expedientes?riesgo=si&kpi=expedientes-en-riesgo',summary:'Expedientes abiertos cuyo semáforo canónico está en Atención o Urgente.',columns:[['expediente','Expediente'],['fase','Fase'],['semaforo','Semáforo'],['proxima_accion','Próxima acción'],['importe_solicitado','Importe solicitado']]},
 'honorarios-pendientes':{key:'honorarios-pendientes',title:'Honorarios pendientes este mes',route:'/economia?honorarios=pendientes&mes=actual&kpi=honorarios-pendientes',summary:'Honorarios Fénix de operaciones con firma prevista este mes y aún no firmadas, menos la comisión inmobiliaria aplicable cuando procede.',columns:[['expediente','Expediente'],['fecha_firma','Firma prevista'],['honorarios_fenix_base','Honorarios Fénix'],['comision_inmobiliaria','Comisión inmobiliaria'],['neto_pendiente_base','Neto pendiente']]}
};

function monthNow(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function euro(v:unknown){if(typeof v!=='number'||!Number.isFinite(v))return'—';const negative=v<0;const absolute=Math.abs(v);const fixed=absolute.toFixed(2);const[whole,decimals]=fixed.split('.');const grouped=whole.replace(/\B(?=(\d{3})+(?!\d))/g,'.');const cents=decimals==='00'?'':`,`+decimals.replace(/0$/,'');return `${negative?'-':''}${grouped}${cents} €`;}
function pretty(v:unknown,key:string){if(v===null||v===undefined||v==='')return'—';if(key.includes('honorarios')||key.includes('comision')||key.includes('neto')||key.includes('importe'))return euro(v);if(Array.isArray(v))return v.length?v.join(', '):'—';return String(v);}
async function fetchKpi(key:string):Promise<{status:number;data:Payload|null}>{
 // Direction KPI drilldowns remain PRE-PROD-only until a dedicated PROD KPI contract is deployed and validated.
 if(IS_PRODUCTION)return{status:503,data:null};
 const q=new URLSearchParams({key,month:monthNow()});
 return fetchEnvironmentApi<Payload>('fenix-direction-kpis',`?${q.toString()}`,undefined,{productionAvailable:false});
}

function kpiFromButton(button:HTMLElement){const t=(button.textContent||'').toUpperCase();if(t.includes('HONORARIOS'))return'honorarios-pendientes';if(t.includes('EN RIESGO'))return'expedientes-en-riesgo';if(t.includes('FIRMADOS'))return'firmadas';if(t.includes('FIRMAS'))return'firmas-previstas';if(t.includes('EXPEDIENTES'))return'expedientes-en-curso';return'';}

export default function DirectionKpiDrilldownGuard(){
 const location=useLocation(),navigate=useNavigate();const params=useMemo(()=>new URLSearchParams(location.search),[location.search]);const activeKey=params.get('kpi')||'';const spec=SPECS[activeKey];const[portal,setPortal]=useState<HTMLElement|null>(null);const[status,setStatus]=useState<number|null>(null);const[data,setData]=useState<Payload|null>(null);
 useEffect(()=>{const handler=(ev:MouseEvent)=>{if(location.pathname!=='/inicio')return;const target=ev.target as Element|null;const button=target?.closest('.dir-kpi') as HTMLElement|null;if(!button)return;const key=kpiFromButton(button);const s=SPECS[key];if(!s)return;ev.preventDefault();ev.stopPropagation();navigate(s.route);};document.addEventListener('click',handler,true);return()=>document.removeEventListener('click',handler,true);},[location.pathname,navigate]);
 useEffect(()=>{if(!spec){setPortal(null);return;}let cancelled=false;let obs:MutationObserver|null=null;const attach=()=>{if(cancelled)return;const target=document.querySelector('.ops-content,.eco-content') as HTMLElement|null;if(target){setPortal(target);const root=target.closest('.ops-root') as HTMLElement|null;root?.setAttribute('data-kpi-drilldown','true');return;}obs=new MutationObserver(()=>attach());obs.observe(document.body,{childList:true,subtree:true});};attach();return()=>{cancelled=true;obs?.disconnect();document.querySelectorAll('.ops-root[data-kpi-drilldown]').forEach(el=>el.removeAttribute('data-kpi-drilldown'));setPortal(null);};},[spec?.key,location.pathname]);
 useEffect(()=>{if(!spec)return;let alive=true;setStatus(null);setData(null);fetchKpi(spec.key).then(r=>{if(!alive)return;setStatus(r.status);setData(r.data)}).catch(()=>{if(alive){setStatus(0);setData(null)}});return()=>{alive=false};},[spec?.key]);
 useEffect(()=>{if(location.pathname!=='/inicio')return;let alive=true;(async()=>{const r=await fetchKpi('honorarios-pendientes');if(!alive||r.status!==200||!r.data)return;const buttons=Array.from(document.querySelectorAll('.dir-kpi')) as HTMLElement[];const b=buttons.find(x=>(x.textContent||'').toUpperCase().includes('HONORARIOS'));if(!b)return;const value=b.querySelector('strong');const note=b.querySelector('small');if(value)value.textContent=r.data.complete&&typeof r.data.total==='number'?euro(r.data.total):'—';if(note)note.textContent=r.data.complete?'Neto base: honorarios − comisión inmobiliaria':`${r.data.unresolved??0} operación(es) requieren completar comisión`;})();return()=>{alive=false};},[location.pathname]);
 if(!spec||!portal)return null;const rows=data?.items??[];const metric=spec.key==='honorarios-pendientes'?(data?.complete&&typeof data.total==='number'?euro(data.total):'—'):String(data?.count??rows.length);
 return createPortal(<section className="fenix-kpi-drilldown" data-testid="direction-kpi-drilldown"><div className="fenix-kpi-head"><div><small>INICIO · DESGLOSE CANÓNICO</small><h1>{spec.title}</h1><p>{spec.summary}</p></div><button onClick={()=>navigate('/inicio')}>← Volver a Inicio</button></div><div className="fenix-kpi-metric"><span>{spec.key==='honorarios-pendientes'?'TOTAL NETO PENDIENTE (BASE)':'REGISTROS QUE EXPLICAN EL KPI'}</span><strong>{status===200?metric:'—'}</strong>{spec.key==='honorarios-pendientes'&&!data?.complete&&status===200?<small>No se muestra un total incompleto. {data?.unresolved??0} operación(es) requieren una comisión explícita.</small>:<small>Fuente canónica Notion · PRE-PROD</small>}</div>{status===null?<div className="fenix-kpi-state">Cargando desglose canónico…</div>:status!==200?<div className="fenix-kpi-state error">No se pudo cargar el desglose exacto del KPI.</div>:rows.length===0?<div className="fenix-kpi-state">No hay registros que cumplan este KPI en el mes/ámbito actual.</div>:<div className="fenix-kpi-table-wrap"><table><thead><tr>{spec.columns.map(([,label])=><th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={String(row.id??row.expediente_id??i)}>{spec.columns.map(([key])=><td key={key}>{pretty(row[key],key)}</td>)}</tr>)}</tbody></table></div>}</section>,portal);
}
