export type SummaryRow=Record<string,unknown>;

function clean(v:unknown){return typeof v==='string'?v.trim():'';}
function first(row:SummaryRow,keys:string[]){for(const k of keys){const v=row[k];if(v!==null&&v!==undefined&&String(v).trim()!=='')return String(v).trim();}return'';}
function push(parts:string[],label:string,value:string){if(value)parts.push(`${label}: ${value}`);}
function parseLegacyStoredSummary(row:SummaryRow){
 const notes=first(row,['resumen_documento','summary','resumen','notas','Notas','notes']);
 if(!notes)return'';
 if(!notes.includes('[CEREBRO · LECTURA DOCUMENTAL]'))return'';
 const idx=notes.indexOf('{');if(idx<0)return'';
 try{return clean(JSON.parse(notes.slice(idx))?.summary);}catch{return'';}
}
function typeOf(row:SummaryRow){return first(row,['tipo_canónico','tipo_canonico','tipo','categoria','categoría','document_type','detected_document_type']).toLocaleLowerCase('es');}
const hidden=new Set(['id','synthetic','fuente','destino','url','archivo_url','url_archivo','file_url','source_url','original_url','pdf','url_pdf','documento_url','enlace','link','archivo','notas','Notas','notes','summary','resumen','resumen_documento','tipo_canónico','tipo_canonico','tipo','categoria','categoría','document_type','detected_document_type','estado','status','title','created_at','updated_at','deleted_at','scope_code','scope_type','document_code','origin_code','origin_type','created_by','updated_by','source_payload','storage_path','upload_id','document_page_id','actor_code']);
function technicalKey(k:string){const key=k.toLocaleLowerCase('es');return hidden.has(k)||hidden.has(key)||/(?:^|_)(?:id|url|code|payload)$/.test(key)||/^(?:created|updated|deleted)_at$/.test(key)||/^(?:scope|origin|source|storage)_/.test(key);}
function hasStructuredValues(row:SummaryRow){return Object.entries(row).some(([k,v])=>!technicalKey(k)&&v!==null&&v!==undefined&&String(v).trim()!=='');}
function generic(row:SummaryRow){const entries=Object.entries(row).filter(([k,v])=>!technicalKey(k)&&v!==null&&v!==undefined&&String(v).trim()!=='').slice(0,8);if(!entries.length)return'Documento registrado sin datos suficientes para elaborar un resumen operativo. No se han inferido datos ausentes.';return entries.map(([k,v])=>`${k.replaceAll('_',' ')}: ${String(v)}`).join(' · ')+'.';}
function yesNoEvidence(row:SummaryRow,positive:string[],negative:string[]=[]){const pos=first(row,positive);if(pos)return`Sí (${pos})`;const neg=first(row,negative);if(neg)return`No (${neg})`;return'No consta';}
export function buildDocumentOperationalSummary(row:SummaryRow|null){
 if(!row)return'';
 const type=typeOf(row),parts:string[]=[];
 if(type.includes('vida laboral')){push(parts,'Titular',first(row,['titular']));push(parts,'Fecha informe',first(row,['fecha_informe']));push(parts,'Situación',first(row,['situacion_actual']));push(parts,'Régimen',first(row,['regimen']));push(parts,'Empresa actual',first(row,['empresa_actual','empresa']));push(parts,'Alta actual',first(row,['fecha_alta_actual','fecha_alta']));push(parts,'Antigüedad',first(row,['antiguedad']));push(parts,'Días en alta',first(row,['total_dias','dias_alta','días_alta','dias_cotizados']));push(parts,'Incidencias',first(row,['incidencias','solapamientos']));}
 else if(type.includes('nómina')||type.includes('nomina')){push(parts,'Trabajador',first(row,['trabajador','titular']));push(parts,'Empresa',first(row,['empresa','empresa_pagador']));push(parts,'CIF',first(row,['cif_empresa']));push(parts,'Periodo',first(row,['periodo','mes']));push(parts,'Antigüedad',first(row,['antiguedad']));push(parts,'Categoría',first(row,['categoria_profesional']));push(parts,'Bruto',first(row,['bruto','total_devengado']));push(parts,'Base cotización',first(row,['base_cotizacion']));push(parts,'IRPF',first(row,['irpf']));push(parts,'Deducciones',first(row,['deducciones']));push(parts,'Neto',first(row,['neto','liquido']));parts.push(`Embargo/anticipo: ${yesNoEvidence(row,['embargos','anticipos'],['sin_embargos'])}`);}
 else if(type.includes('irpf')||type.includes('renta')){push(parts,'Titular',first(row,['titulares','titular']));push(parts,'Ejercicio',first(row,['ejercicio']));push(parts,'Modalidad',first(row,['modalidad']));push(parts,'Rendimientos del trabajo',first(row,['rendimientos_trabajo']));push(parts,'Actividades económicas',first(row,['rendimientos_actividad']));push(parts,'Capital',first(row,['rendimientos_capital']));push(parts,'Inmobiliarios',first(row,['rendimientos_inmobiliarios']));push(parts,'Ganancias/pérdidas',first(row,['ganancias_perdidas']));push(parts,'Base imponible',first(row,['base_imponible']));push(parts,'Base liquidable',first(row,['base_liquidable']));push(parts,'Resultado',first(row,['resultado','resultado_declaracion']));}
 else if(type.includes('movimientos')){push(parts,'Titular',first(row,['titulares','titular']));push(parts,'Banco',first(row,['banco','entidad']));push(parts,'IBAN',first(row,['iban']));push(parts,'Periodo',first(row,['periodo']));push(parts,'Saldo inicial',first(row,['saldo_inicial']));push(parts,'Saldo final',first(row,['saldo_final']));push(parts,'Saldo disponible',first(row,['saldo_disponible','saldo']));push(parts,'Ingresos recurrentes',first(row,['ingresos_recurrentes']));push(parts,'Nóminas',first(row,['nominas']));push(parts,'Préstamos',first(row,['cuotas_prestamos']));push(parts,'Descubiertos',first(row,['descubiertos']));push(parts,'Comisiones',first(row,['comisiones']));}
 else if(type.includes('tasaci')){push(parts,'Inmueble',first(row,['inmueble','direccion','dirección','ubicacion','ubicación']));push(parts,'Superficie',first(row,['superficie','metros','metros_cuadrados','m2','superficie_construida','superficie_util']));push(parts,'Valor de tasación',first(row,['valor_tasacion','valor_tasación','importe','valor']));push(parts,'Fecha',first(row,['fecha_tasacion','fecha_tasación','fecha']));push(parts,'Finalidad',first(row,['finalidad']));push(parts,'Condicionantes',first(row,['condicionantes','condiciones','limitaciones']));push(parts,'Observaciones del tasador',first(row,['observaciones_tasador','observaciones','anotaciones','comentarios']));push(parts,'Excepciones',first(row,['excepciones','salvedades','advertencias']));}
 else if(type.includes('oferta')||type.includes('fein')||type.includes('fiae')){push(parts,'Entidad',first(row,['entidad','banco']));push(parts,'Prestatarios',first(row,['prestatarios','titulares']));push(parts,'Importe',first(row,['importe_prestamo','importe']));push(parts,'Plazo',first(row,['plazo','duracion']));push(parts,'TIN',first(row,['tin']));push(parts,'TAE',first(row,['tae']));push(parts,'Cuota',first(row,['cuota']));push(parts,'Vinculaciones',first(row,['vinculaciones']));push(parts,'Comisiones',first(row,['comisiones']));}
 else if(type.includes('préstamo')||type.includes('prestamo')||type.includes('deuda')){push(parts,'Entidad',first(row,['entidad','banco','acreedor']));push(parts,'Titular',first(row,['titular']));push(parts,'Cuota',first(row,['cuota']));push(parts,'Capital pendiente',first(row,['capital_pendiente','saldo_pendiente']));push(parts,'Tipo',first(row,['tipo_interes','tin']));push(parts,'Vencimiento',first(row,['vencimiento']));}
 else if(type.includes('nota simple')){push(parts,'Registro',first(row,['registro']));push(parts,'Finca',first(row,['numero_finca','finca']));push(parts,'Titularidad',first(row,['titulares','titularidad','titular']));push(parts,'Referencia catastral',first(row,['referencia_catastral']));push(parts,'Cargas',first(row,['cargas']));}
 else if(type.includes('cirbe')){push(parts,'Titular',first(row,['titular']));push(parts,'Riesgo dispuesto',first(row,['riesgo_dispuesto']));push(parts,'Riesgo disponible',first(row,['riesgo_disponible']));push(parts,'Situaciones especiales',first(row,['situaciones_especiales']));}
 else if(type.includes('seguro')){push(parts,'Aseguradora',first(row,['aseguradora','entidad']));push(parts,'Tomador',first(row,['tomador','titular']));push(parts,'Prima',first(row,['prima']));push(parts,'Coberturas',first(row,['coberturas']));push(parts,'Exclusiones',first(row,['exclusiones']));}
 if(parts.length)return parts.join(' · ')+'.';
 if(!hasStructuredValues(row)){const legacy=parseLegacyStoredSummary(row);if(legacy)return legacy;}
 return generic(row);
}
