import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,FileText} from 'lucide-react';
import {useLocation,useNavigate} from 'react-router-dom';
import {fetchNotionRuntime} from './notionRuntime';

type Row=Record<string,unknown>;
const css=`
.doc-view-root{position:relative;z-index:5600;min-height:100vh;background:var(--bg,#f6f7f9);color:var(--text,#171717);padding:28px}.doc-view-shell{max-width:1040px;margin:0 auto;display:grid;gap:18px}.doc-view-back{justify-self:start;border:1px solid var(--border,#ddd);border-radius:12px;background:var(--surface,#fff);padding:10px 13px;color:inherit;font-weight:800;display:flex;align-items:center;gap:7px}.doc-view-card{border:1px solid var(--border,#e5e7eb);border-radius:24px;background:var(--surface,#fff);padding:22px}.doc-view-head{display:flex;align-items:flex-start;gap:12px}.doc-view-icon{width:44px;height:44px;border-radius:13px;background:rgba(244,116,31,.12);color:#f4741f;display:grid;place-items:center;flex:0 0 auto}.doc-view-head small{display:block;color:#f4741f;font-size:10px;font-weight:850;letter-spacing:.13em}.doc-view-head h1{margin:4px 0 5px;font-size:25px}.doc-view-head p{margin:0;color:var(--muted,#667085);font-size:12px}.doc-view-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:18px}.doc-view-field{border:1px solid var(--border,#e5e7eb);border-radius:14px;padding:12px;background:var(--surface,#fff)}.doc-view-field small{display:block;color:var(--muted,#667085);font-size:9.5px;text-transform:uppercase;letter-spacing:.08em}.doc-view-field strong{display:block;margin-top:5px;font-size:13px;word-break:break-word}.doc-view-state{border:1px dashed var(--border,#d0d5dd);border-radius:16px;padding:18px;color:var(--muted,#667085)}html[data-theme='dark'] .doc-view-root{background:#151517;color:#f4f4f5}html[data-theme='dark'] .doc-view-card,html[data-theme='dark'] .doc-view-back,html[data-theme='dark'] .doc-view-field{background:#202023;border-color:#39393e}@media(max-width:760px){.doc-view-root{padding:16px}.doc-view-grid{grid-template-columns:1fr}}
`;
function pretty(key:string){return key.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());}
function val(v:unknown){if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'Sí':'No';if(Array.isArray(v))return v.length?v.map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join(', '):'—';if(typeof v==='object')return JSON.stringify(v);return String(v);}
function text(row:Row|null,keys:string[]){if(!row)return'';for(const key of keys){const v=row[key];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
export default function DocumentViewerShell(){
 const location=useLocation(),navigate=useNavigate();const match=location.pathname.match(/^\/documentos\/([^/]+)$/);const id=match?.[1]?decodeURIComponent(match[1]):'';const active=Boolean(match);
 const[status,setStatus]=useState<number|null>(null),[item,setItem]=useState<Row|null>(null),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!active)return;let alive=true;(async()=>{setLoading(true);setStatus(null);setItem(null);try{const r=await fetchNotionRuntime<any>(`/documentos/${encodeURIComponent(id)}`);if(!alive)return;setStatus(r.status);setItem(r.status===200?(r.data?.item??null):null);}catch{if(alive)setStatus(0);}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,id]);
 const returnTo=useMemo(()=>new URLSearchParams(location.search).get('returnTo')||'/documentacion',[location.search]);
 if(!active)return null;
 const title=text(item,['title','documento','nombre','titulo','título'])||'Documento';
 const fields=item?Object.keys(item).filter(k=>!['id','synthetic','fuente','destino'].includes(k)):[];
 return <div className="doc-view-root" data-testid="document-single-view"><style>{css}</style><div className="doc-view-shell"><button type="button" className="doc-view-back" onClick={()=>navigate(returnTo)}><ArrowLeft size={16}/> Volver al expediente</button><article className="doc-view-card">{loading?<div className="doc-view-state">Cargando documento autorizado…</div>:status!==200||!item?<div className="doc-view-state">{status===403?'No tienes permiso para abrir este documento.':status===404?'No se ha encontrado este documento.':'No se pudo cargar este documento.'}</div>:<><div className="doc-view-head"><div className="doc-view-icon"><FileText size={21}/></div><div><small>DOCUMENTO DEL EXPEDIENTE</small><h1>{title}</h1><p>Vista aislada del documento seleccionado. No se ha abierto la biblioteca general de Documentación.</p></div></div><div className="doc-view-grid">{fields.map(key=><div className="doc-view-field" key={key}><small>{pretty(key)}</small><strong>{val(item[key])}</strong></div>)}</div></>}</article></div></div>;
}
