export type DocFamily='identity'|'payroll'|'employment_contract'|'work_history'|'land_registry'|'tax_return'|'withholding_certificate'|'bank_statement'|'bank_certificate'|'loan_debt'|'sale_contract'|'cadastre'|'self_employed_tax'|'tax_ss_certificate'|'divorce_judgment'|'rental_contract'|'other';
export type FieldDef={key:string;label:string;priority?:'essential'|'secondary'|'alert';money?:boolean};
export type FamilyDef={label:string;fields:FieldDef[]};
const f=(key:string,label:string,priority:'essential'|'secondary'|'alert'='secondary',money=false):FieldDef=>({key,label,priority,money});
export const FAMILY_DEFS:Record<DocFamily,FamilyDef>={
 identity:{label:'DNI / NIE / Pasaporte',fields:[f('nombre','Nombre','essential'),f('apellidos','Apellidos','essential'),f('documento_identidad','Documento','essential'),f('fecha_nacimiento','Fecha nacimiento','essential'),f('fecha_caducidad_documento','Caducidad / validez','alert'),f('fecha_expedicion_documento','Fecha expedición'),f('numero_soporte','Nº soporte'),f('nacionalidad','Nacionalidad'),f('sexo','Sexo'),f('domicilio','Domicilio'),f('localidad','Localidad'),f('provincia','Provincia'),f('lugar_nacimiento','Lugar nacimiento'),f('mrz','MRZ')]},
 payroll:{label:'Nómina',fields:[f('nombre','Titular','essential'),f('apellidos','Apellidos','essential'),f('empresa','Empresa','essential'),f('empresa_cif','CIF empresa'),f('periodo_nomina','Periodo','essential'),f('antiguedad_laboral','Antigüedad','essential'),f('categoria_profesional','Categoría / puesto'),f('salario_base','Salario base','secondary',true),f('complementos_salariales','Complementos','secondary',true),f('pagas_extra_prorrata','Pagas extra / prorrata','secondary',true),f('total_devengado','Bruto / total devengado','essential',true),f('irpf_porcentaje','IRPF %'),f('retencion_irpf','Retención IRPF','secondary',true),f('cotizacion_ss','Cotización SS','secondary',true),f('otras_deducciones','Otras deducciones','secondary',true),f('base_cotizacion','Base cotización','secondary',true),f('ingresos_netos_mensuales','Líquido / neto','essential',true),f('tipo_contrato','Tipo de contrato si consta','alert')]},
 employment_contract:{label:'Contrato de trabajo',fields:[f('nombre','Trabajador','essential'),f('apellidos','Apellidos','essential'),f('empresa','Empresa','essential'),f('empresa_cif','CIF empresa'),f('tipo_contrato','Tipo de contrato','essential'),f('fecha_inicio_contrato','Fecha inicio','essential'),f('fecha_fin_contrato','Fecha fin','alert'),f('jornada','Jornada'),f('horas_semanales','Horas semanales'),f('categoria_profesional','Puesto / categoría'),f('salario_pactado','Salario pactado','essential',true),f('periodo_prueba','Periodo de prueba'),f('convenio','Convenio')]},
 work_history:{label:'Vida laboral',fields:[f('nombre','Titular','essential'),f('apellidos','Apellidos','essential'),f('naf','NAF / Nº Seguridad Social','essential'),f('situacion_laboral_actual','Situación actual','essential'),f('empresa','Empresa actual','essential'),f('fecha_alta_actual','Fecha alta actual','essential'),f('antiguedad_laboral','Antigüedad calculable','essential'),f('regimen_ss','Régimen'),f('tipo_contrato','Tipo contrato si consta'),f('jornada','Jornada si consta'),f('grupo_cotizacion','Grupo cotización'),f('dias_totales_alta','Días totales en alta','essential'),f('resumen_periodos_laborales','Periodos / empleadores')]},
 land_registry:{label:'Nota simple',fields:[f('direccion_inmueble','Dirección inmueble','essential'),f('localidad','Municipio','essential'),f('registro_propiedad','Registro','essential'),f('finca_registral','Finca registral','essential'),f('cru','CRU / IDUFIR','essential'),f('referencia_catastral','Referencia catastral'),f('titulares_registrales','Titulares','essential'),f('porcentajes_titularidad','% titularidad','essential'),f('derechos_titularidad','Derechos'),f('descripcion_finca','Descripción finca'),f('cargas_registrales','Cargas','alert'),f('hipotecas_registrales','Hipotecas','alert'),f('embargos','Embargos','alert'),f('servidumbres','Servidumbres','alert'),f('afecciones','Afecciones','alert'),f('restricciones_disposicion','Restricciones','alert')]},
 tax_return:{label:'IRPF / Declaración de la renta',fields:[f('nombre','Titular','essential'),f('apellidos','Apellidos','essential'),f('documento_identidad','NIF','essential'),f('ejercicio_fiscal','Ejercicio','essential'),f('tipo_declaracion','Tipo declaración'),f('rendimientos_trabajo','Rendimientos trabajo','essential',true),f('rendimientos_capital','Capital mobiliario','secondary',true),f('rendimientos_inmuebles','Inmuebles','secondary',true),f('rendimientos_actividades','Actividad económica','secondary',true),f('base_imponible_general','Base imponible general','essential',true),f('base_imponible_ahorro','Base ahorro','secondary',true),f('base_liquidable','Base liquidable','secondary',true),f('cuota_resultante','Cuota','secondary',true),f('resultado_declaracion','Resultado ingresar / devolver','essential')]},
 withholding_certificate:{label:'Certificado de retenciones',fields:[f('nombre','Titular','essential'),f('apellidos','Apellidos','essential'),f('documento_identidad','NIF','essential'),f('empresa','Pagador','essential'),f('empresa_cif','CIF pagador'),f('ejercicio_fiscal','Ejercicio','essential'),f('retribucion_integra','Retribución íntegra','essential',true),f('retencion_irpf','Retenciones IRPF','essential',true),f('gastos_deducibles','Gastos deducibles','secondary',true)]},
 bank_statement:{label:'Movimientos / extracto bancario',fields:[f('titular_cuenta','Titular','essential'),f('entidad_bancaria','Entidad','essential'),f('iban','IBAN','essential'),f('periodo_extracto','Periodo','essential'),f('saldo_inicial','Saldo inicial','secondary',true),f('saldo_final','Saldo final','essential',true),f('ingresos_recurrentes','Ingresos recurrentes','essential',true),f('nominas_detectadas','Nóminas detectadas','essential',true),f('cuotas_prestamos_detectadas','Cuotas préstamos','alert',true),f('descubiertos_detectados','Descubiertos','alert'),f('devoluciones_detectadas','Devoluciones','alert'),f('transferencias_significativas','Transferencias significativas','alert')]},
 bank_certificate:{label:'Certificado de cuenta',fields:[f('titular_cuenta','Titular/es','essential'),f('entidad_bancaria','Entidad','essential'),f('iban','IBAN','essential'),f('fecha_certificado','Fecha certificado','essential'),f('condicion_titular','Condición titular / cotitular')]},
 loan_debt:{label:'Préstamo / deuda',fields:[f('nombre','Titular','essential'),f('entidad_acreedora','Entidad acreedora','essential'),f('tipo_prestamo','Tipo préstamo','essential'),f('capital_pendiente','Capital pendiente','essential',true),f('cuota_deuda_mensual','Cuota mensual','essential',true),f('fecha_vencimiento_deuda','Vencimiento','essential'),f('tipo_interes','Tipo interés'),f('impagos','Impagos','alert')]},
 sale_contract:{label:'Arras / compraventa',fields:[f('compradores','Comprador/es','essential'),f('vendedores','Vendedor/es','essential'),f('direccion_inmueble','Inmueble','essential'),f('precio_vivienda','Precio compraventa','essential',true),f('importe_arras','Importe arras','essential',true),f('fecha_limite_firma','Fecha límite','alert'),f('cargas_declaradas','Cargas declaradas','alert'),f('condiciones_suspensivas','Condiciones suspensivas','alert'),f('inmobiliaria','Inmobiliaria'),f('gastos_operacion','Gastos','secondary',true)]},
 cadastre:{label:'Catastro',fields:[f('referencia_catastral','Referencia catastral','essential'),f('direccion_inmueble','Dirección','essential'),f('uso_inmueble','Uso','essential'),f('superficie_construida','Superficie construida'),f('superficie_parcela','Superficie parcela'),f('ano_construccion','Año construcción'),f('titulares_catastrales','Titulares'),f('coeficiente_participacion','Coeficiente')]},
 self_employed_tax:{label:'Modelo fiscal autónomo / empresa',fields:[f('nombre','Titular / empresa','essential'),f('documento_identidad','NIF / CIF','essential'),f('modelo_fiscal','Modelo','essential'),f('ejercicio_fiscal','Ejercicio','essential'),f('periodo_fiscal','Periodo','essential'),f('ingresos_actividad','Ingresos','essential',true),f('gastos_actividad','Gastos','essential',true),f('rendimiento_neto','Rendimiento neto','essential',true),f('resultado_modelo','Resultado','essential',true),f('iva_devengado','IVA devengado','secondary',true),f('iva_deducible','IVA deducible','secondary',true)]},
 tax_ss_certificate:{label:'Certificado AEAT / Seguridad Social',fields:[f('nombre','Titular','essential'),f('documento_identidad','NIF','essential'),f('organismo_emisor','Organismo','essential'),f('fecha_certificado','Fecha expedición','essential'),f('situacion_corriente_pago','Situación','alert'),f('importe_deuda','Importe deuda','alert',true),f('fecha_validez_certificado','Validez','alert'),f('csv','Código seguro verificación')]},
 divorce_judgment:{label:'Sentencia / convenio de divorcio',fields:[f('intervinientes','Intervinientes','essential'),f('organo_judicial','Órgano judicial','essential'),f('fecha_resolucion','Fecha','essential'),f('hijos_menores','Hijos / cargas familiares','essential'),f('pension_alimentos','Pensión alimentos','alert',true),f('pension_compensatoria','Pensión compensatoria','alert',true),f('custodia','Custodia'),f('vivienda_familiar','Vivienda familiar'),f('obligaciones_economicas','Otras obligaciones','alert')]},
 rental_contract:{label:'Contrato de alquiler',fields:[f('arrendador','Arrendador','essential'),f('arrendatario','Arrendatario','essential'),f('direccion_inmueble','Inmueble','essential'),f('renta_mensual','Renta mensual','essential',true),f('fecha_inicio_contrato','Inicio','essential'),f('fecha_fin_contrato','Fin','alert'),f('duracion_contrato','Duración'),f('fianza','Fianza','secondary',true),f('obligaciones_economicas','Obligaciones','alert')]},
 other:{label:'Documento',fields:[f('nombre','Titular','essential'),f('documento_identidad','Identificación'),f('fecha_documento','Fecha documento'),f('importe_principal','Importe principal','secondary',true),f('summary','Resumen','secondary')]}
};
export function inferFamily(documentType='',title=''):DocFamily{const s=`${documentType} ${title}`.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(/\b(dni|nie|pasaporte)\b/.test(s))return'identity';if(/nomina|nmina/.test(s))return'payroll';if(/vida[ _-]*laboral/.test(s))return'work_history';if(/nota[ _-]*simple|registro[ _-]*prop/.test(s))return'land_registry';if(/contrato.*trabajo|trabajo.*contrato|modificacion.*contrato.*trabajo/.test(s))return'employment_contract';if(/declaracion.*renta|\birpf\b|renta[- _]?(20\d\d)?/.test(s))return'tax_return';if(/retencion/.test(s))return'withholding_certificate';if(/movimientos|extracto.*operaciones/.test(s))return'bank_statement';if(/certificado.*cuenta/.test(s))return'bank_certificate';if(/prestamo|deuda[ _-]*pendiente/.test(s))return'loan_debt';if(/arras|compraventa|alquiler.*compra/.test(s))return'sale_contract';if(/catastro|catastral/.test(s))return'cadastre';if(/modelo[ _-]*(130|303|390|200)|\b(130|303|390|200)\b.*(iva|irpf)/.test(s))return'self_employed_tax';if(/certif.*(hacienda|aeat|seguridad social|seg[. _-]*social)/.test(s))return'tax_ss_certificate';if(/sentencia|divorcio|convenio regulador/.test(s))return'divorce_judgment';if(/contrato.*alquiler|alquiler/.test(s))return'rental_contract';return'other';}
export function visibleFields(family:DocFamily){return FAMILY_DEFS[family].fields;}
