export type OperationalRow=Record<string,unknown>;
export type OperationalField={label:string;value:unknown;expected:true;derived:true};
function s(v:unknown){return typeof v==='string'?v.trim():'';}
function n(v:unknown){if(typeof v==='number')return Number.isFinite(v)?v:null;const raw=s(v);if(!raw)return null;const token=(raw.match(/-?\d{1,3}(?:\.\d{3})*(?:,\d+)?|-?\d+(?:[.,]\d+)?/)||[])[0];if(!token)return null;const x=Number(token.includes(',')?token.replace(/\./g,'').replace(',','.') : token);return Number.isFinite(x)?x:null;}
function iso(v:unknown){const x=s(v);if(!/^\d{4}-\d{2}-\d{2}$/.test(x))return null;const d=new Date(`${x}T00:00:00Z`);return Number.isFinite(d.getTime())?d:null;}
function years(a:unknown,b:unknown){const x=iso(a),y=iso(b);if(!x||!y||y<x)return null;return Math.round(((y.getTime()-x.getTime())/86400000/365.25)*10)/10;}
function decimalEs(v:number,digits:number){const sign=v<0?'-':'';const fixed=Math.abs(v).toFixed(digits);const [int,dec]=fixed.split('.');const grouped=int.replace(/\B(?=(\d{3})+(?!\d))/g,'.');return digits?`${sign}${grouped},${dec}`:`${sign}${grouped}`;}
function fmtYears(v:number){return `${decimalEs(v,1)} años`;}
function money(v:number){return `${decimalEs(v,2)} €`;}
function percent(v:number){return `${decimalEs(v,1)} %`;}
function add(out:OperationalField[],label:string,value:unknown){if(value!==undefined&&value!==null&&String(value).trim()!=='')out.push({label,value,expected:true,derived:true});}
function familyText(row:OperationalRow){return ['tipo-canónico','tipo_canónico','tipo_canonico','tipo','categoria','categoría','document_type','title','titulo','documento'].map(k=>s(row[k])).filter(Boolean).join(' ');}
function todayIso(){return new Date().toISOString().slice(0,10);}
function segments(v:unknown){return s(v).split(/\s*\|\s*|\n+/).map(x=>x.trim()).filter(Boolean);}
function signedAmounts(v:unknown){const out:number[]=[];for(const line of segments(v)){const all=[...line.matchAll(/(?:\+\s*)?(\d{1,3}(?:\.\d{3})*,\d{2}|\d+,\d{2})/g)];if(!all.length)continue;const token=all[all.length-1][1];const x=Number(token.replace(/\./g,'').replace(',','.'));if(Number.isFinite(x))out.push(x);}return out;}
export function getDocumentOperationalFields(row:OperationalRow|null):OperationalField[]{if(!row)return[];const type=familyText(row),out:OperationalField[]=[];
 if(/vida laboral/i.test(type)){const days=n(row.total_dias??row.dias_cotizados??row.total_dias_cotizados);if(days!==null&&days>0)add(out,'Años totales cotizados',fmtYears(Math.round((days/365.25)*10)/10));const report=s(row.fecha_informe)||todayIso();const tenure=years(row.fecha_alta_actual??row.fecha_alta,report);if(tenure!==null)add(out,'Antigüedad empleo actual',fmtYears(tenure));add(out,'Empresa actual desde',row.fecha_alta_actual??row.fecha_alta);add(out,'Últimos trabajos / periodos',row.ultimos_trabajos??row.periodos_trabajados);if(row.incidencias||row.solapamientos)add(out,'Incidencias laborales',row.incidencias??row.solapamientos);}
 else if(/n[oó]mina/i.test(type)){const gross=n(row.bruto??row.total_devengado),net=n(row.neto??row.liquido),ded=n(row.deducciones);if(gross!==null&&net!==null&&gross>0)add(out,'Neto sobre bruto',percent(Math.round((net/gross)*1000)/10));if(ded!==null)add(out,'Deducciones totales',money(ded));add(out,'Conceptos salariales relevantes',row.complementos??row.pagas_extra??row.prorrata);if(row.embargos||row.anticipos)add(out,'Alerta embargos / anticipos',[row.embargos,row.anticipos].filter(Boolean).join(' · '));}
 else if(/renta|irpf|declaraci[oó]n/i.test(type)){const work=n(row.rendimientos_trabajo);if(work!==null)add(out,'Media mensual trabajo (anual / 12)',money(work/12));const rent=n(row.rendimientos_inmobiliarios);if(rent!==null)add(out,'Media mensual inmobiliaria (anual / 12)',money(rent/12));add(out,'Patrimonio / inmuebles declarados',row.inmuebles);add(out,'Préstamos / hipotecas declarados',row.prestamos_hipotecas);}
 else if(/movimientos|extracto bancario/i.test(type)){const salaryLines=segments(row.nominas).filter(x=>/n[oó]mina/i.test(x));if(salaryLines.length)add(out,'Nóminas detectadas en el periodo',salaryLines.length);const amounts=signedAmounts(row.nominas);if(amounts.length)add(out,'Media de abonos de nómina detectados',money(amounts.reduce((a,b)=>a+b,0)/amounts.length));add(out,'Cuotas / financiación detectada',row.cuotas_prestamos);if(row.descubiertos)add(out,'Alerta descubiertos',row.descubiertos);if(row.comisiones)add(out,'Comisiones detectadas',row.comisiones);}
 else if(/nota simple/i.test(type)){const risks=[row.hipotecas&&'Hipotecas',row.embargos&&'Embargos',row.limitaciones&&'Limitaciones',row.anotaciones&&'Anotaciones preventivas'].filter(Boolean);add(out,'Alertas registrales',risks.length?risks.join(' · '):'Sin alertas estructuradas detectadas');add(out,'Titularidad operativa',row.titulares??row.titularidad??row.titular);add(out,'Cargas relevantes',row.cargas);}
 else if(/\bfein\b|fiae/i.test(type)){const amount=n(row.importe_prestamo??row.importe),payment=n(row.cuota),months=n(row.numero_cuotas??row.plazo_meses??row.plazo);if(payment!==null&&months!==null&&months>0)add(out,'Total nominal de cuotas',money(payment*months));if(amount!==null&&payment!==null&&months!==null&&months>0)add(out,'Diferencia cuotas - capital',money(payment*months-amount));add(out,'Vinculaciones que revisar',row.vinculaciones??row.productos);add(out,'Coste / gastos declarados',row.coste_total??row.gastos);add(out,'Riesgo de impago / vencimiento',row.impago??row.vencimiento_anticipado);}
 else if(/tasaci[oó]n/i.test(type)){const value=n(row.valor_tasacion??row.importe);if(value!==null)add(out,'Valor operativo de referencia',money(value));const warnings=[row.condicionantes,row.advertencias,row.salvedades??row.excepciones,row.documentacion_pendiente].filter(Boolean);if(warnings.length)add(out,'Bloqueos / salvedades a revisar',warnings.join(' · '));}
 else if(/dni|nie|pasaporte/i.test(type)){const age=years(row.fecha_nacimiento,todayIso());if(age!==null)add(out,'Edad',`${Math.floor(age)} años`);const expiry=iso(row.fecha_caducidad);if(expiry)add(out,'Estado de vigencia',expiry.getTime()>=Date.now()?'Vigente':'Caducado');}
 else if(/pr[eé]stamo|deuda|hipoteca/i.test(type)){const capital=n(row.capital_pendiente??row.saldo_pendiente),payment=n(row.cuota);if(capital!==null)add(out,'Deuda pendiente',money(capital));if(payment!==null)add(out,'Carga mensual',money(payment));const remain=years(todayIso(),row.vencimiento??row.fecha_fin);if(remain!==null)add(out,'Tiempo aproximado hasta vencimiento',fmtYears(remain));}
 return out;}
