import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,CalendarCheck2,Landmark,Moon,Search,Sun,TrendingUp} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {fetchSpecialCasesRuntime} from './specialCasesRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import {FENIX_COMMERCIAL_KNOWLEDGE} from './fenixCommercialKnowledge';
import {buildEconomyProjection} from './economyProjection';
import './operational.css';
import './economia-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown,keys:string[]):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of keys)if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function dateOf(r:Row){const raw=first(r,['fecha_hora_firma','fecha_firma','fecha','date']);const d=raw?new Date(raw):null;return d&&Number.isFinite(d.getTime())?d:null;}
function signed(r:Row){return /firmad|cerrad|complet/i.test(first(r,['estado','status','fase']));}
function openExp(r:Row){const s=first(r,['estado','status','fase','phase']).toLowerCase();return !/(firmad|cerrad|cancel|anulad|archivad|complet|ca[ií]d|perdid|rechaz|desist|no viable)/i.test(s);}
function money(n:number){return new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)}
export default function EconomiaShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/economia';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[exp,setExp]=useState<Row[]>([]),[fir,setFir]=useState<Row[]>([]),[her,setHer]=useState<Row[]>([]),[obr,setObr]=useState<Row[]>([]),[specialComplete,setSpecialComplete]=useState(true),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setExp([]);setFir([]);setHer([]);setObr([]);setSpecialComplete(true);try{const[c,n]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]);if(!alive)return;const context=c.status===200?c.data:null;setCtx(context);setNav(n.status===200?normalizeNavigation(n.data):[]);if(c.status!==200){setStatus(c.status||0);setMessage('No se pudo validar el acceso al panel económico.');return;}if(context?.role!=='Direccion'){setStatus(403);setMessage('Economía global está reservada a Dirección.');return;}const[e,f,h,o]=await Promise.all([fetchNotionRuntime<unknown>('/expedientes'),fetchNotionRuntime<unknown>('/firmas'),fetchSpecialCasesRuntime<unknown>('/herencias'),fetchSpecialCasesRuntime<unknown>('/obras-nuevas')]);if(!alive)return;if(e.status!==200||f.status!==200){const failed=e.status!==200?e.status:f.status;setStatus(failed);setMessage('No hay fuente suficiente para construir el panel económico completo.');return;}setExp(rowsFrom(e.data,['items','expedientes','results']));setFir(rowsFrom(f.data,['items','firmas','results']));if(h.status===200)setHer(rowsFrom(h.data,['items','herencias','results']));else setSpecialComplete(false);if(o.status===200)setObr(rowsFrom(o.data,['items','obras_nuevas','obras','results']));else setSpecialComplete(false);setStatus(200);}catch{if(!alive)return;setCtx(null);setNav([]);setExp([]);setFir([]);setHer([]);setObr([]);setStatus(0);setMessage('No se pudo conectar con las fuentes autorizadas del panel económico.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,logged]);
 const derived=useMemo(()=>{const now=new Date();const sameMonth=(d:Date|null)=>Boolean(d&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth());return{open:exp.filter(openExp).length,firmasMes:fir.filter(r=>sameMonth(dateOf(r))).length,firmadasMes:fir.filter(r=>signed(r)&&sameMonth(dateOf(r))).length};},[exp,fir]);
 const projection=useMemo(()=>buildEconomyProjection(exp,her,obr),[exp,her,obr]);
 const effectiveNav=nav.length?nav:fallbackNav;
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 const role=ctx?.role||'Usuario';
 const topbar=<header className="ops-top"><div className="ops-search"><Search size={17}/><input readOnly value="" placeholder="Economía es un panel informativo de solo lectura"/></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{role}</strong></div></div></header>;
 return <OperationalShellFrame className="eco-root" theme={theme} navigation={effectiveNav} activeRoute="/economia" anaSubtitle="Interpreta datos disponibles sin completar cifras económicas ausentes." anaRoute="/ana?mode=help&resource=economia" query="" onQueryChange={()=>{}} searchPlaceholder="Economía es un panel informativo de solo lectura" name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} topbar={topbar} contentClassName="eco-content">
  <div className="eco-title"><div><small>ECONOMÍA · SOLO LECTURA</small><h1>Economía</h1><p>{loading?'Cargando fuentes autorizadas…':status===200?'Previsión económica desde el alta de cada operación. IVA siempre separado del ingreso y del margen.':'Lectura según permisos y fuentes disponibles.'}</p></div><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos vivos':'PRE-PROD'}</span></div>
  <section className="eco-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · ECONOMÍA</span><h2>Te enseño lo que puede entrar, lo avanzado y lo que se ha perdido</h2><p>La previsión nace al dar de alta la operación. Si cae o se cancela, deja de sumar en cartera activa y pasa a potencial perdido. En hipotecas de inmobiliaria descuento por defecto 1.100 € de comisión, salvo que la operación tenga un importe canónico distinto.</p><div className="inmo-next"><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia')}><b>1</b><strong>Explícame los datos</strong><small>Analizar →</small></button><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia&intent=objetivos')}><b>2</b><strong>Revisar objetivos</strong><small>Con datos disponibles →</small></button><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia&intent=alertas')}><b>3</b><strong>Qué vigilar</strong><small>Prioridades →</small></button></div></div></section>
  {loading&&<div className="ops-empty" data-testid="economia-loading"><strong>Cargando…</strong><span>Consultando fuentes autorizadas.</span></div>}{!loading&&message&&<div className="ops-message" data-testid={status===403?'economia-forbidden':'economia-error'}>{message}</div>}{!loading&&status===200&&<><section className="eco-kpis"><article><Landmark/><small>EXPEDIENTES EN CURSO</small><strong>{derived.open}</strong><span>Excluye caídos, cancelados y cerrados</span></article><article><CalendarCheck2/><small>FIRMAS ESTE MES</small><strong>{derived.firmasMes}</strong><span>Derivado de fechas canónicas</span></article><article><TrendingUp/><small>FIRMADOS ESTE MES</small><strong>{derived.firmadasMes}</strong><span>Estado + fecha canónicos</span></article></section>
  <section className="eco-money" aria-label="Previsión económica"><article data-testid="economia-active"><small>CARTERA PREVISTA ACTIVA</small><strong>{money(projection.active.grossBaseEur)}</strong><b>Margen Fénix: {money(projection.active.marginBaseEur)}</b><span>{projection.active.count} operaciones tipificadas · base sin IVA</span></article><article data-testid="economia-advanced"><small>PREVISIÓN AVANZADA</small><strong>{money(projection.advanced.grossBaseEur)}</strong><b>Margen Fénix: {money(projection.advanced.marginBaseEur)}</b><span>FEIN, aprobada, notaría o firma · base sin IVA</span></article><article data-testid="economia-signed"><small>FIRMADO / DEVENGADO</small><strong>{money(projection.signed.grossBaseEur)}</strong><b>Margen Fénix: {money(projection.signed.marginBaseEur)}</b><span>Operaciones firmadas no marcadas como cobradas</span></article><article data-testid="economia-collected"><small>COBRADO</small><strong>{projection.collectionKnown?money(projection.collected.grossBaseEur):'No disponible'}</strong><b>{projection.collectionKnown?`Margen Fénix: ${money(projection.collected.marginBaseEur)}`:'Falta señal canónica de cobro'}</b><span>No se presume cobro por el mero hecho de firmar</span></article><article data-testid="economia-lost"><small>POTENCIAL PERDIDO</small><strong>{money(projection.lost.grossBaseEur)}</strong><b>Margen potencial: {money(projection.lost.marginBaseEur)}</b><span>Caídas, canceladas, anuladas o perdidas · histórico, no cartera activa</span></article><article data-testid="economia-typing"><small>TIPIFICACIÓN ECONÓMICA</small><strong>{projection.typedCount} tipificadas</strong><b>{projection.untypedCount} pendientes</b><span>Inmobiliaria: comisión por defecto 1.100 €, editable por operación</span></article></section>
  {!specialComplete&&<div className="ops-message">Herencias u Obras Nuevas no han respondido; la previsión visible puede ser parcial y no se completa por suposición.</div>}
  <section className="eco-grid"><article><BarChart3/><div><small>VOLUMEN FINANCIADO</small><strong>No disponible</strong><p>La fuente actual no garantiza un importe financiero agregable sin ambigüedad.</p></div></article><article data-testid="economia-fee-knowledge"><BarChart3/><div><small>HONORARIOS / COMISIONES</small><strong>Tarifario cargado</strong><p>{FENIX_COMMERCIAL_KNOWLEDGE.mortgage.rule} {FENIX_COMMERCIAL_KNOWLEDGE.mortgage.agencyRule} {FENIX_COMMERCIAL_KNOWLEDGE.newBuild.rule} {FENIX_COMMERCIAL_KNOWLEDGE.inheritance.rule}</p></div></article><article><BarChart3/><div><small>GASTOS GENERALES Y RENTABILIDAD FINAL</small><strong>No disponible</strong><p>El margen mostrado arriba descuenta la comisión de inmobiliaria cuando procede, pero no inventa otros gastos que aún no tengan fuente económica validada.</p></div></article><article><BarChart3/><div><small>PROYECCIÓN Y OBJETIVOS</small><strong>No disponible</strong><p>No se extrapolan objetivos o crecimiento a partir de datos incompletos.</p></div></article></section><section className="eco-readonly"><strong>Panel 100% informativo</strong><span>Las cifras son base sin IVA. La cartera prevista se recalcula con los datos canónicos; una operación caída deja de sumar inmediatamente y queda registrada como potencial perdido.</span></section></>}
 </OperationalShellFrame>;
}
