import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,CalendarCheck2,Landmark,Moon,Search,Sun,TrendingUp} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchEconomiaRuntime} from './economiaRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './economia-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};
type Pipeline={expedientes?:number;expedientes_inmobiliaria?:number;expedientes_sin_inmobiliaria?:number;importe_solicitado?:number;honorario_base_por_expediente?:number;comision_inmobiliaria_por_expediente?:number;ingreso_bruto_esperado?:number;comisiones_inmobiliarias_esperadas?:number;ingreso_fenix_esperado?:number};
type EcoEnvelope={items?:Row[];kpis?:{total_movimientos?:number;importe_base?:number;iva?:number;total?:number};pipeline_activo?:Pipeline};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown,keys:string[]):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of keys)if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function dateOf(r:Row){const raw=first(r,['fecha_hora_firma','fecha_firma','fecha','date']);const d=raw?new Date(raw):null;return d&&Number.isFinite(d.getTime())?d:null;}
function num(v:unknown){return typeof v==='number'&&Number.isFinite(v)?v:Number(v)||0;}
function money(n:number){const rounded=Math.round(n);return `${String(rounded).replace(/\B(?=(\d{3})+(?!\d))/g,'.')} €`;}
export default function EconomiaProdShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/economia';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[fir,setFir]=useState<Row[]>([]),[eco,setEco]=useState<EcoEnvelope>({}),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;let timer:number|undefined;const load=async()=>{setLoading(true);setMessage('');try{const[c,n,f,real]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchAppApi<unknown>('/firmas'),fetchEconomiaRuntime<EcoEnvelope>()]);if(!alive)return;const context=c.status===200?c.data:null;setCtx(context);setNav(n.status===200?normalizeNavigation(n.data):[]);if(c.status!==200){setStatus(c.status||0);setMessage('No se pudo validar el acceso al panel económico.');return;}if(context?.role!=='Direccion'){setStatus(403);setMessage('Economía global está reservada a Dirección.');return;}if(f.status!==200||real.status!==200){setStatus(f.status!==200?f.status:real.status);setMessage('No hay fuente suficiente para construir el panel económico con datos reales.');return;}setFir(rowsFrom(f.data,['items','firmas','results']));setEco(real.data||{});setStatus(200);}catch{if(alive){setStatus(0);setMessage('No se pudo conectar con las fuentes autorizadas del panel económico.')}}finally{if(alive)setLoading(false)}};void load();timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},10000);const focus=()=>void load();window.addEventListener('focus',focus);window.addEventListener('fenix-operational-data-changed',focus as EventListener);return()=>{alive=false;if(timer)window.clearInterval(timer);window.removeEventListener('focus',focus);window.removeEventListener('fenix-operational-data-changed',focus as EventListener)};},[active,logged]);
 const firmasMes=useMemo(()=>{const now=new Date();return fir.filter(r=>{const d=dateOf(r);return Boolean(d&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth())}).length},[fir]);
 const movements=Array.isArray(eco.items)?eco.items:[];const kpis=eco.kpis||{};const p=eco.pipeline_activo||{};const activeCount=num(p.expedientes),activeInmo=num(p.expedientes_inmobiliaria),activeNoInmo=num(p.expedientes_sin_inmobiliaria),activeRequested=num(p.importe_solicitado),gross=num(p.ingreso_bruto_esperado),commissions=num(p.comisiones_inmobiliarias_esperadas),net=num(p.ingreso_fenix_esperado),totalMov=num(kpis.total_movimientos??movements.length),materializedBase=num(kpis.importe_base),materializedIva=num(kpis.iva),materializedTotal=num(kpis.total),hasMaterialized=totalMov>0;const effectiveNav=nav.length?nav:fallbackNav;
 if(!active||!ready||!logged)return null;async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}const role=ctx?.role||'Usuario';const topbar=<header className="ops-top"><div className="ops-search"><Search size={17}/><input readOnly value="" placeholder="Economía es un panel informativo de solo lectura"/></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{role}</strong></div></div></header>;
 return <OperationalShellFrame className="eco-root" theme={theme} navigation={effectiveNav} activeRoute="/economia" anaSubtitle="Separa previsión activa de cobros ya materializados." anaRoute="/ana?mode=help&resource=economia" query="" onQueryChange={()=>{}} searchPlaceholder="Economía es un panel informativo de solo lectura" name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} topbar={topbar} contentClassName="eco-content">
  <div className="eco-title"><div><small>ECONOMÍA · SOLO LECTURA</small><h1>Economía</h1><p>{loading?'Actualizando datos vivos…':status===200?'Previsión calculada exclusivamente sobre expedientes activos.':'Lectura según permisos y fuentes disponibles.'}</p></div><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Actualizando…':status===200?'Datos PROD':'Sin datos'}</span></div>
  <section className="eco-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · ECONOMÍA</span><h2>Lo que Fénix espera ingresar de la cartera activa</h2><p>Cada expediente activo aporta 3.500 € base. Si está asociado a inmobiliaria, se descuentan 1.100 € de comisión y aporta 2.400 € netos esperados.</p><div className="inmo-next"><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia')}><b>1</b><strong>Explícame los datos</strong><small>Analizar →</small></button><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia&intent=alertas')}><b>2</b><strong>Qué vigilar</strong><small>Revisar cartera →</small></button></div></div></section>
  {loading&&status===null&&<div className="ops-empty"><strong>Cargando…</strong><span>Consultando fuentes autorizadas.</span></div>}{message&&status!==200&&<div className="ops-message">{message}</div>}{status===200&&<><section className="eco-kpis"><article data-testid="economia-active-expedientes"><Landmark/><small>EXPEDIENTES EN CURSO</small><strong>{activeCount}</strong><span>Definición activa canónica</span></article><article><CalendarCheck2/><small>FIRMAS ESTE MES</small><strong>{firmasMes}</strong><span>Actividad real registrada</span></article><article data-testid="economia-active-requested"><TrendingUp/><small>IMPORTE SOLICITADO ACTIVO</small><strong>{money(activeRequested)}</strong><span>Volumen hipotecario, no ingreso Fénix</span></article></section>
  <section className="eco-money" aria-label="Previsión económica activa"><article data-testid="economia-expected-net"><small>INGRESO FÉNIX ESPERADO</small><strong>{money(net)}</strong><b>Base sin IVA · solo cartera activa</b><span>{activeNoInmo} × 3.500 € + {activeInmo} × 2.400 €</span></article><article data-testid="economia-expected-gross"><small>HONORARIOS BRUTOS ESPERADOS</small><strong>{money(gross)}</strong><b>{activeCount} × 3.500 €</b><span>Antes de comisiones de inmobiliaria</span></article><article data-testid="economia-expected-commissions"><small>COMISIONES INMOBILIARIAS PREVISTAS</small><strong>−{money(commissions)}</strong><b>{activeInmo} × 1.100 €</b><span>Solo expedientes activos con inmobiliaria asociada</span></article><article data-testid="economia-materialized"><small>MOVIMIENTOS YA MATERIALIZADOS</small><strong>{money(materializedBase)}</strong><b>{hasMaterialized?`${totalMov} movimientos económicos`:'Aún sin movimientos económicos'}</b><span>{hasMaterialized?`IVA: ${money(materializedIva)} · Total: ${money(materializedTotal)}`:'No se confunde previsión con cobro'}</span></article></section>
  <section className="eco-grid"><article><BarChart3/><div><small>DESGLOSE ACTIVO</small><strong>{activeCount} expedientes</strong><p>{activeInmo} de inmobiliaria · {activeNoInmo} sin inmobiliaria. Firmados, cerrados y bajas no entran en esta previsión.</p></div></article><article><BarChart3/><div><small>FACTURACIÓN / COBROS</small><strong>{hasMaterialized?'Según movimientos registrados':'0 € materializado'}</strong><p>La previsión no se considera cobrada hasta que exista movimiento económico real.</p></div></article></section><section className="eco-readonly"><strong>Panel vivo</strong><span>Se actualiza al entrar, al volver a la ventana y periódicamente mientras la pantalla está visible.</span></section></>}
 </OperationalShellFrame>;
}
