import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,CalendarCheck2,Landmark,Moon,Search,Sun,TrendingUp} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {fetchEconomiaRuntime} from './economiaRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import {buildEconomyProjection} from './economyProjection';
import './operational.css';
import './economia-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};type EcoEnvelope={items?:Row[];kpis?:{total_movimientos?:number;importe_base?:number;iva?:number;total?:number}};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown,keys:string[]):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of keys)if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function dateOf(r:Row){const raw=first(r,['fecha_hora_firma','fecha_firma','fecha','date']);const d=raw?new Date(raw):null;return d&&Number.isFinite(d.getTime())?d:null;}
function openExp(r:Row){const s=first(r,['estado','status','fase','phase','stage']).toLowerCase();return !/(firmad|cerrad|cancel|anulad|archivad|complet|ca[ií]d|perdid|rechaz|desist|no viable)/i.test(s);}
function num(v:unknown){return typeof v==='number'&&Number.isFinite(v)?v:Number(v)||0;}
function money(n:number){const rounded=Math.round(n);return `${String(rounded).replace(/\B(?=(\d{3})+(?!\d))/g,'.')} €`;}
export default function EconomiaProdShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/economia';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[exp,setExp]=useState<Row[]>([]),[fir,setFir]=useState<Row[]>([]),[eco,setEco]=useState<EcoEnvelope>({}),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setExp([]);setFir([]);setEco({});try{const[c,n]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]);if(!alive)return;const context=c.status===200?c.data:null;setCtx(context);setNav(n.status===200?normalizeNavigation(n.data):[]);if(c.status!==200){setStatus(c.status||0);setMessage('No se pudo validar el acceso al panel económico.');return;}if(context?.role!=='Direccion'){setStatus(403);setMessage('Economía global está reservada a Dirección.');return;}const[e,f,real]=await Promise.all([fetchNotionRuntime<unknown>('/expedientes'),fetchNotionRuntime<unknown>('/firmas'),fetchEconomiaRuntime<EcoEnvelope>()]);if(!alive)return;if(e.status!==200||f.status!==200||real.status!==200){const failed=e.status!==200?e.status:f.status!==200?f.status:real.status;setStatus(failed);setMessage('No hay fuente suficiente para construir el panel económico con datos reales.');return;}setExp(rowsFrom(e.data,['items','expedientes','results']));setFir(rowsFrom(f.data,['items','firmas','results']));setEco(real.data||{});setStatus(200);}catch{if(!alive)return;setCtx(null);setNav([]);setExp([]);setFir([]);setEco({});setStatus(0);setMessage('No se pudo conectar con las fuentes autorizadas del panel económico.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,logged]);
 const derived=useMemo(()=>{const now=new Date();const sameMonth=(d:Date|null)=>Boolean(d&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth());return{open:exp.filter(openExp).length,firmasMes:fir.filter(r=>sameMonth(dateOf(r))).length};},[exp,fir]);
 const projection=useMemo(()=>buildEconomyProjection(exp),[exp]);
 const movements=Array.isArray(eco.items)?eco.items:[];const kpis=eco.kpis||{};const totalMov=num(kpis.total_movimientos??movements.length),materializedBase=num(kpis.importe_base),materializedIva=num(kpis.iva),materializedTotal=num(kpis.total),hasMaterialized=totalMov>0;const effectiveNav=nav.length?nav:fallbackNav;
 if(!active||!ready||!logged)return null;async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}const role=ctx?.role||'Usuario';const topbar=<header className="ops-top"><div className="ops-search"><Search size={17}/><input readOnly value="" placeholder="Economía es un panel informativo de solo lectura"/></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{role}</strong></div></div></header>;
 return <OperationalShellFrame className="eco-root" theme={theme} navigation={effectiveNav} activeRoute="/economia" anaSubtitle="Separa cartera registrada esperada de cobros y movimientos ya materializados." anaRoute="/ana?mode=help&resource=economia" query="" onQueryChange={()=>{}} searchPlaceholder="Economía es un panel informativo de solo lectura" name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} topbar={topbar} contentClassName="eco-content">
  <div className="eco-title"><div><small>ECONOMÍA · SOLO LECTURA</small><h1>Economía</h1><p>{loading?'Cargando fuentes autorizadas…':status===200?'Cartera registrada esperada calculada desde los expedientes activos reales. Los cobros materializados se mantienen separados.':'Lectura según permisos y fuentes disponibles.'}</p></div><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos PROD':'Sin datos'}</span></div>
  <section className="eco-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · ECONOMÍA</span><h2>Esto es lo que debería entrar si la cartera activa firma</h2><p>La cartera registrada usa cada expediente activo real. Si falta importe hipotecario legacy, aplica el tarifario vigente: 3.500 € base; si procede de inmobiliaria descuenta 1.100 € de comisión, salvo negociación o comisión específica registrada.</p><div className="inmo-next"><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia')}><b>1</b><strong>Explícame los datos</strong><small>Analizar →</small></button><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia&intent=alertas')}><b>2</b><strong>Qué vigilar</strong><small>Revisar cartera →</small></button></div></div></section>
  {loading&&<div className="ops-empty" data-testid="economia-loading"><strong>Cargando…</strong><span>Consultando fuentes autorizadas.</span></div>}{!loading&&message&&<div className="ops-message" data-testid={status===403?'economia-forbidden':'economia-error'}>{message}</div>}{!loading&&status===200&&<><section className="eco-kpis"><article><Landmark/><small>EXPEDIENTES EN CURSO</small><strong>{derived.open}</strong><span>Cartera real activa</span></article><article><CalendarCheck2/><small>FIRMAS ESTE MES</small><strong>{derived.firmasMes}</strong><span>Actividad real registrada</span></article><article><TrendingUp/><small>OPERACIONES TIPIFICADAS</small><strong>{projection.active.count}</strong><span>Con previsión económica calculada</span></article></section><section className="eco-money" aria-label="Economía registrada"><article data-testid="economia-registered-margin"><small>CARTERA REGISTRADA ESPERADA</small><strong>{money(projection.active.marginBaseEur)}</strong><b>Ingreso Fénix esperado · base sin IVA</b><span>{projection.active.count} operaciones activas; descuenta comisión inmobiliaria cuando procede</span></article><article data-testid="economia-registered-gross"><small>HONORARIOS BRUTOS REGISTRADOS</small><strong>{money(projection.active.grossBaseEur)}</strong><b>Antes de comisiones de inmobiliaria</b><span>Tarifario o negociación canónica por operación</span></article><article data-testid="economia-materialized"><small>MOVIMIENTOS YA MATERIALIZADOS</small><strong>{money(materializedBase)}</strong><b>{hasMaterialized?`${totalMov} movimientos económicos`:'Aún sin movimientos económicos'}</b><span>{hasMaterialized?`IVA: ${money(materializedIva)} · Total: ${money(materializedTotal)}`:'No se confunde previsión con cobro'}</span></article></section><section className="eco-grid"><article><BarChart3/><div><small>CRITERIO DE CÁLCULO</small><strong>Tarifario vigente</strong><p>Sin importe legacy disponible: 3.500 € base. Origen inmobiliaria: se descuenta 1.100 € por defecto. Cualquier honorario o comisión negociada registrada prevalece.</p></div></article><article><BarChart3/><div><small>FACTURACIÓN / COBROS</small><strong>{hasMaterialized?'Según movimientos registrados':'0 € materializado'}</strong><p>Firmar o estar activo genera previsión; no se presume cobro hasta que exista movimiento económico real.</p></div></article><article><BarChart3/><div><small>PENDIENTE DE TIPIFICAR</small><strong>{projection.untypedCount}</strong><p>Operaciones que no pueden clasificarse de forma segura con las reglas comerciales disponibles.</p></div></article></section><section className="eco-readonly"><strong>Panel 100% informativo</strong><span>La cartera registrada esperada representa el ingreso base que debería entrar si las operaciones activas llegan a firma. Los movimientos económicos materializados permanecen separados para no confundir previsión con cobro.</span></section></>}
 </OperationalShellFrame>;
}
