import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,CalendarCheck2,Landmark,Moon,Search,Sun} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {fetchEconomiaRuntime} from './economiaRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './economia-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};type EcoEnvelope={items?:Row[];kpis?:{total_movimientos?:number;importe_base?:number;iva?:number;total?:number}};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown,keys:string[]):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of keys)if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function dateOf(r:Row){const raw=first(r,['fecha_hora_firma','fecha_firma','fecha','date']);const d=raw?new Date(raw):null;return d&&Number.isFinite(d.getTime())?d:null;}
function openExp(r:Row){const s=first(r,['estado','status','fase','phase','stage']).toLowerCase();return !/(firmad|cerrad|cancel|anulad|archivad|complet|ca[ií]d|perdid|rechaz|desist|no viable)/i.test(s);}
function num(v:unknown){return typeof v==='number'&&Number.isFinite(v)?v:Number(v)||0;}
function money(n:number){const rounded=Math.round(n);return `${String(rounded).replace(/\B(?=(\d{3})+(?!\d))/g,'.')} €`;}
export default function EconomiaProdShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/economia';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[exp,setExp]=useState<Row[]>([]),[fir,setFir]=useState<Row[]>([]),[eco,setEco]=useState<EcoEnvelope>({}),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setExp([]);setFir([]);setEco({});try{const[c,n]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]);if(!alive)return;const context=c.status===200?c.data:null;setCtx(context);setNav(n.status===200?normalizeNavigation(n.data):[]);if(c.status!==200){setStatus(c.status||0);setMessage('No se pudo validar el acceso al panel económico.');return;}if(context?.role!=='Direccion'){setStatus(403);setMessage('Economía global está reservada a Dirección.');return;}const[e,f,real]=await Promise.all([fetchNotionRuntime<unknown>('/expedientes'),fetchNotionRuntime<unknown>('/firmas'),fetchEconomiaRuntime<EcoEnvelope>()]);if(!alive)return;if(e.status!==200||f.status!==200||real.status!==200){const failed=e.status!==200?e.status:f.status!==200?f.status:real.status;setStatus(failed);setMessage('No hay fuente suficiente para construir el panel económico con datos reales.');return;}setExp(rowsFrom(e.data,['items','expedientes','results']));setFir(rowsFrom(f.data,['items','firmas','results']));setEco(real.data||{});setStatus(200);}catch{if(!alive)return;setCtx(null);setNav([]);setExp([]);setFir([]);setEco({});setStatus(0);setMessage('No se pudo conectar con las fuentes autorizadas del panel económico.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,logged]);
 const derived=useMemo(()=>{const now=new Date();const sameMonth=(d:Date|null)=>Boolean(d&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth());return{open:exp.filter(openExp).length,firmasMes:fir.filter(r=>sameMonth(dateOf(r))).length};},[exp,fir]);
 const movements=Array.isArray(eco.items)?eco.items:[];const kpis=eco.kpis||{};const totalMov=num(kpis.total_movimientos??movements.length),base=num(kpis.importe_base),iva=num(kpis.iva),grand=num(kpis.total),hasReal=totalMov>0;const effectiveNav=nav.length?nav:fallbackNav;
 if(!active||!ready||!logged)return null;async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}const role=ctx?.role||'Usuario';const topbar=<header className="ops-top"><div className="ops-search"><Search size={17}/><input readOnly value="" placeholder="Economía es un panel informativo de solo lectura"/></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{role}</strong></div></div></header>;
 return <OperationalShellFrame className="eco-root" theme={theme} navigation={effectiveNav} activeRoute="/economia" anaSubtitle="Distingue datos económicos reales de indicadores operativos. Nunca completa cifras ausentes." anaRoute="/ana?mode=help&resource=economia" query="" onQueryChange={()=>{}} searchPlaceholder="Economía es un panel informativo de solo lectura" name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} topbar={topbar} contentClassName="eco-content">
  <div className="eco-title"><div><small>ECONOMÍA · SOLO LECTURA</small><h1>Economía</h1><p>{loading?'Cargando fuentes autorizadas…':status===200?(hasReal?'Movimientos económicos reales materializados en PROD.':'No hay movimientos económicos reales materializados en PROD. Los indicadores operativos se muestran separados y no se convierten en ingresos.'):'Lectura según permisos y fuentes disponibles.'}</p></div><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos PROD':'Sin datos'}</span></div>
  <section className="eco-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · ECONOMÍA</span><h2>Solo te enseño dinero que exista como dato económico real</h2><p>{hasReal?'Hay movimientos económicos reales registrados. Los importes de esta pantalla proceden exclusivamente de esa fuente.':'Ahora mismo la fuente económica real está a cero. No convierto expedientes, firmas ni tarifas en facturación, cobros o rentabilidad ficticios.'}</p><div className="inmo-next"><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia')}><b>1</b><strong>Explícame los datos</strong><small>Analizar →</small></button><button type="button" onClick={()=>navigate('/ana?mode=help&resource=economia&intent=alertas')}><b>2</b><strong>Qué falta</strong><small>Revisar fuente →</small></button></div></div></section>
  {loading&&<div className="ops-empty" data-testid="economia-loading"><strong>Cargando…</strong><span>Consultando fuentes autorizadas.</span></div>}{!loading&&message&&<div className="ops-message" data-testid={status===403?'economia-forbidden':'economia-error'}>{message}</div>}{!loading&&status===200&&<><section className="eco-kpis"><article><Landmark/><small>EXPEDIENTES EN CURSO</small><strong>{derived.open}</strong><span>Indicador operativo, no ingreso</span></article><article><CalendarCheck2/><small>FIRMAS ESTE MES</small><strong>{derived.firmasMes}</strong><span>Indicador operativo, no cobro</span></article><article><BarChart3/><small>MOVIMIENTOS ECONÓMICOS REALES</small><strong>{totalMov}</strong><span>Fuente económica PROD</span></article></section><section className="eco-money" aria-label="Economía real"><article data-testid="economia-real-base"><small>BASE REAL REGISTRADA</small><strong>{money(base)}</strong><b>{hasReal?'Dato económico materializado':'Sin movimientos reales'}</b><span>No incluye previsiones inferidas</span></article><article data-testid="economia-real-iva"><small>IVA REAL REGISTRADO</small><strong>{money(iva)}</strong><b>{hasReal?'Dato económico materializado':'Sin movimientos reales'}</b><span>No se calcula desde tarifas</span></article><article data-testid="economia-real-total"><small>TOTAL REAL REGISTRADO</small><strong>{money(grand)}</strong><b>{hasReal?'Dato económico materializado':'Sin movimientos reales'}</b><span>Solo fuente económica PROD</span></article></section>{!hasReal&&<div className="ops-message" data-testid="economia-no-real-data">Economía está operativa y en estado vacío correcto: 0 movimientos reales. No se muestran los 11 registros TEST detectados en Notion ni se fabrican ingresos a partir de expedientes.</div>}<section className="eco-grid"><article><BarChart3/><div><small>FACTURACIÓN / COBROS</small><strong>{hasReal?'Según movimientos registrados':'0 € / sin datos reales'}</strong><p>No se presume cobro por una firma ni por el estado de un expediente.</p></div></article><article><BarChart3/><div><small>GASTOS / RENTABILIDAD</small><strong>{hasReal?'Según movimientos registrados':'0 € / sin datos reales'}</strong><p>La rentabilidad no se inventa mientras no exista una fuente contable validada.</p></div></article><article><BarChart3/><div><small>PREVISIÓN</small><strong>No contabilizada</strong><p>Las previsiones operativas, cuando se implanten, deberán aparecer separadas de los datos reales.</p></div></article></section><section className="eco-readonly"><strong>Panel 100% informativo</strong><span>Los importes visibles proceden exclusivamente de la tabla económica real de PROD. Expedientes y firmas se muestran solo como contexto operativo.</span></section></>}
 </OperationalShellFrame>;
}
