import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import {FileText} from 'lucide-react';
import {IS_PRODUCTION,fetchAppApi} from './supabase';
import ExpedientePeoplePanel from './ExpedientePeoplePanel';

type Row=Record<string,any>;
type DocsResponse={items?:Row[]};
const css=`
.prod-master-recovery{display:grid;gap:18px;margin:18px 0}.prod-master-recovery .pmr-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.prod-master-recovery .pmr-card{border:1px solid var(--border,#e5e7eb);border-radius:18px;background:var(--surface,#fff);padding:18px}.prod-master-recovery .pmr-card>span{font-size:10px;font-weight:850;letter-spacing:.11em;color:#f4741f}.prod-master-recovery .pmr-card h2{margin:6px 0 14px}.prod-master-recovery .pmr-kv{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.prod-master-recovery .pmr-kv div{display:grid;gap:3px}.prod-master-recovery .pmr-kv small{color:var(--muted,#667085)}.prod-master-recovery .pmr-docs{display:grid;gap:12px}.prod-master-recovery .pmr-doc-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.prod-master-recovery .pmr-doc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px}.prod-master-recovery .pmr-doc{border:1px solid var(--border,#e5e7eb);border-radius:14px;padding:13px;background:var(--surface,#fff);display:grid;gap:5px;text-align:left;color:inherit}.prod-master-recovery .pmr-doc small{color:#f4741f}.detail-exp-root .exp-docs-host{display:none!important}.detail-exp-root .ops-message[data-prod-recovery-hidden="true"]{display:none!important}@media(max-width:800px){.prod-master-recovery .pmr-grid,.prod-master-recovery .pmr-kv{grid-template-columns:1fr}}
`;
function show(v:any){return v===null||v===undefined||v===''?'—':String(v)}
function matchDoc(row:Row,code:string){const scope=String(row.scope_code||row.expediente_code||'');if(scope===code)return true;const rel=row.expediente_id;if(typeof rel==='string')return rel===code;if(Array.isArray(rel))return rel.some(x=>String(x?.id??x)===code);return false}
function docId(r:Row){return String(r.document_code||r.document_id||r.id||'')}

export default function ExpedienteProdMasterRecoveryGuard(){
 const {pathname}=useLocation(),navigate=useNavigate();
 const m=pathname.match(/^\/expedientes\/([^/]+)$/);const code=m?.[1]?decodeURIComponent(m[1]):'';const active=IS_PRODUCTION&&Boolean(code)&&code!=='nuevo';
 const[host,setHost]=useState<HTMLElement|null>(null),[exp,setExp]=useState<Row|null>(null),[docs,setDocs]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null);
 useEffect(()=>{if(!active){setHost(null);return}const mount=()=>{const root=document.querySelector<HTMLElement>('.detail-exp-content');if(!root)return;let node=root.querySelector<HTMLElement>(':scope > .prod-master-recovery-host');if(!node){node=document.createElement('section');node.className='prod-master-recovery-host';const title=root.querySelector(':scope > .detail-master-title');title?.insertAdjacentElement('afterend',node);if(!title)root.prepend(node)}setHost(node);const titleCopy=root.querySelector<HTMLElement>(':scope > .detail-master-title p');if(titleCopy)titleCopy.textContent='Ficha operativa PROD · vista completa del expediente.';document.querySelectorAll<HTMLElement>('.detail-exp-root .ops-message').forEach(el=>{if((el.textContent||'').includes('No se pudo cargar la ficha'))el.dataset.prodRecoveryHidden='true'})};mount();const o=new MutationObserver(mount);o.observe(document.body,{childList:true,subtree:true});return()=>{o.disconnect();document.querySelector('.prod-master-recovery-host')?.remove();document.querySelectorAll<HTMLElement>('[data-prod-recovery-hidden="true"]').forEach(el=>delete el.dataset.prodRecoveryHidden)}},[active,code]);
 useEffect(()=>{if(!active)return;let alive=true;(async()=>{const [d,dl]=await Promise.all([fetchAppApi<any>(`/expedientes/${encodeURIComponent(code)}`),fetchAppApi<DocsResponse>('/documentos')]);if(!alive)return;setStatus(d.status);setExp(d.status===200?(d.data?.expediente??null):null);setDocs(dl.status===200?(dl.data?.items??[]).filter(r=>matchDoc(r,code)):[])})();return()=>{alive=false}},[active,code]);
 const name=useMemo(()=>String(exp?.cliente_alias||exp?.expediente_code||code||'Expediente'),[exp,code]);
 if(!active||!host)return null;
 const content=<><style>{css}</style><div className="prod-master-recovery" data-testid="prod-expediente-master-recovery">{status!==200?<div className="pmr-card"><strong>Cargando ficha operativa de PROD…</strong></div>:<><div className="pmr-grid"><article className="pmr-card"><span>SITUACIÓN ACTUAL</span><h2>{show(exp?.stage)}</h2><div className="pmr-kv"><div><small>Expediente</small><strong>{name}</strong></div><div><small>Responsable</small><strong>{show(exp?.owner_actor_code)}</strong></div><div><small>Inmobiliaria</small><strong>{show(exp?.inmobiliaria_code)}</strong></div><div><small>Próxima acción</small><strong>{show(exp?.proxima_accion)}</strong></div></div></article><article className="pmr-card"><span>OPERACIÓN</span><h2>Datos principales</h2><div className="pmr-kv"><div><small>Localidad</small><strong>{show(exp?.localidad)}</strong></div><div><small>Precio vivienda</small><strong>{show(exp?.precio_vivienda)}</strong></div><div><small>Importe solicitado</small><strong>{show(exp?.importe_solicitado)}</strong></div><div><small>Versión</small><strong>{show(exp?.version)}</strong></div></div></article></div><ExpedientePeoplePanel expedienteId={code}/><article className="pmr-card pmr-docs"><div className="pmr-doc-head"><div><span>DOCUMENTACIÓN DEL EXPEDIENTE</span><h2>Archivos vinculados</h2></div><strong>{docs.length} documento{docs.length===1?'':'s'}</strong></div>{docs.length===0?<p>No hay documentación vinculada visible a este expediente.</p>:<div className="pmr-doc-grid">{docs.map(r=>{const id=docId(r);return <button type="button" className="pmr-doc" key={id} onClick={()=>navigate(`/documentos/${encodeURIComponent(id)}?returnTo=${encodeURIComponent(pathname)}`)}><FileText size={17}/><small>{show(r.tipo)}</small><strong>{show(r.title||r.documento)}</strong><span>{show(r.estado)} · Abrir documento →</span></button>})}</div>}</article></>}</div></>;
 return createPortal(content,host);
}
