import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {SUPABASE_URL,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {FENIX_COMMERCIAL_KNOWLEDGE,quoteMortgageFee} from './fenixCommercialKnowledge';
import './commercial-terms.css';

type AnyRow=Record<string,unknown>;
function n(row:AnyRow,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'&&v.trim()){const x=Number(v.trim().replace(/\s/g,'').replace(/€/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));if(Number.isFinite(x))return x}}return null}
function t(row:AnyRow,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim()}return''}
function b(row:AnyRow,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='boolean')return v;if(typeof v==='string'){if(/^(sí|si|true|1)$/i.test(v.trim()))return true;if(/^(no|false|0)$/i.test(v.trim()))return false}}return null}
function fromAgency(row:AnyRow){const explicit=b(row,['origen_inmobiliaria','procede_inmobiliaria','es_inmobiliaria']);if(explicit!==null)return explicit;const origin=t(row,['origen','procedencia','canal','fuente']);if(/inmobiliaria|agencia/i.test(origin))return true;return Boolean(t(row,['inmobiliaria_id','inmobiliaria','agencia_id','agencia']))}
function notionId(v:string){return /^[0-9a-f]{32}$/i.test(v.replaceAll('-',''))}
async function contextRole(){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return'';const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-app-gateway-test/session/context`,{headers:{Authorization:`Bearer ${session.access_token}`}});let data:any=null;try{data=await r.json()}catch{}return String(data?.role||data?.context?.role||'')}
async function saveTerms(id:string,changes:Record<string,unknown>){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return{status:401,data:null as any};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-notion-actions-test/expedientes/${encodeURIComponent(id)}/action`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action:'update',changes})});let data:any=null;try{data=await r.json()}catch{}return{status:r.status,data}}

export default function ExpedienteCommercialTermsGuard(){
 const [host,setHost]=useState<HTMLElement|null>(null),[row,setRow]=useState<AnyRow|null>(null),[role,setRole]=useState(''),[id,setId]=useState('');
 const [fee,setFee]=useState(''),[commission,setCommission]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let alive=true;async function sync(){const match=window.location.pathname.match(/^\/expedientes\/([^/]+)$/);const nextId=match?.[1]?decodeURIComponent(match[1]):'';if(!nextId||nextId==='nuevo'||!notionId(nextId)){setHost(null);setRow(null);setId('');return}const grid=document.querySelector('.detail-exp-content .detail-summary-grid') as HTMLElement|null;if(!grid){setHost(null);return}let h=document.querySelector('.exp-commercial-terms-host') as HTMLElement|null;if(!h){h=document.createElement('div');h.className='exp-commercial-terms-host';grid.insertAdjacentElement('afterend',h)}setHost(h);setId(nextId);const [runtime,nextRole]=await Promise.all([fetchNotionRuntime<any>(`/expedientes/${encodeURIComponent(nextId)}`),contextRole()]);if(!alive)return;setRole(nextRole);const item=runtime.status===200?(runtime.data?.item||runtime.data?.expediente||null):null;setRow(item);setReview(false);setMessage('');if(item){const recommendedAmount=n(item,['importe_hipoteca','importe_solicitado','importe_financiacion','capital_hipoteca','importe']);const negotiated=n(item,['honorarios_finales_eur','honorarios_finales','honorarios_negociados_eur','honorarios_negociados','honorarios_base_eur','honorarios_base']);const q=recommendedAmount!==null?quoteMortgageFee(recommendedAmount):null;setFee(String(negotiated??q?.baseEur??''));const agency=fromAgency(item);const existingCommission=n(item,['comision_inmobiliaria_eur','comision_inmobiliaria','comision_agencia_eur','comision_agencia']);setCommission(String(agency?(existingCommission??FENIX_COMMERCIAL_KNOWLEDGE.mortgage.realEstateAgencyDefaultCommissionEur):0))}}
 const observer=new MutationObserver(()=>void sync());observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('popstate',sync);void sync();return()=>{alive=false;observer.disconnect();window.removeEventListener('popstate',sync)}},[]);
 const model=useMemo(()=>{if(!row)return null;const amount=n(row,['importe_hipoteca','importe_solicitado','importe_financiacion','capital_hipoteca','importe']);const quote=amount!==null?quoteMortgageFee(amount):null;const agency=fromAgency(row);const feeN=fee.trim()===''?null:Number(fee);const commissionN=commission.trim()===''?null:Number(commission);return{amount,recommended:quote?.recommendedBaseEur??null,agency,feeN:Number.isFinite(feeN)?feeN:null,commissionN:Number.isFinite(commissionN)?commissionN:null}},[row,fee,commission]);
 if(!host||!row||!model)return null;const canEdit=/direcci[oó]n|direccion/i.test(role);const valid=model.feeN!==null&&model.feeN>=0&&(!model.agency||(model.commissionN!==null&&model.commissionN>=0));
 const reset=()=>{setFee(String(model.recommended??''));setCommission(String(model.agency?FENIX_COMMERCIAL_KNOWLEDGE.mortgage.realEstateAgencyDefaultCommissionEur:0));setReview(false);setMessage('')};
 const changeFee=(v:string)=>{setFee(v);setReview(false);setMessage('')},changeCommission=(v:string)=>{setCommission(v);setReview(false);setMessage('')};
 async function confirm(){if(!canEdit||!valid||!id)return;setBusy(true);setMessage('');const changes:Record<string,unknown>={honorarios_finales_eur:model.feeN};if(model.agency)changes.comision_inmobiliaria_eur=model.commissionN;const r=await saveTerms(id,changes);setBusy(false);if(r.status===200){setMessage('Importes guardados en la operación canónica. CEREBRO y Economía usarán estos valores.');setReview(false)}else if(r.status===403)setMessage('Tu perfil no puede modificar las condiciones económicas.');else setMessage(`No se pudieron guardar los importes (${r.data?.error||r.status}).`)}
 return createPortal(<section className="exp-commercial-terms" aria-label="Condiciones económicas de la operación" data-testid="exp-commercial-terms"><div className="exp-commercial-terms-head"><div><span>CEREBRO · CONDICIONES ECONÓMICAS</span><h2>Honorarios y comisión</h2><p>La APP propone la tarifa vigente y permite reflejar un acuerdo distinto por operación.</p></div><strong>{model.recommended!==null?`Tarifa recomendada: ${model.recommended.toLocaleString('es-ES')} € + IVA`:'Tarifa pendiente de datos canónicos'}</strong></div><div className="exp-commercial-terms-grid"><label>Honorarios acordados (€ + IVA)<input type="number" min="0" step="50" value={fee} onChange={e=>changeFee(e.target.value)} readOnly={!canEdit}/></label><label>Comisión inmobiliaria (€ base)<input type="number" min="0" step="50" value={commission} onChange={e=>changeCommission(e.target.value)} readOnly={!canEdit||!model.agency}/><small>{model.agency?'Por defecto 1.100 €, editable por operación.':'Origen directo: 0 €.'}</small></label><div className="exp-commercial-margin"><small>Margen Fénix base</small><strong>{model.feeN!==null&&model.commissionN!==null?`${(model.feeN-(model.agency?model.commissionN:0)).toLocaleString('es-ES')} €`:'—'}</strong><em>IVA separado</em></div></div>{canEdit&&<div className="exp-commercial-actions"><button type="button" onClick={reset}>Restaurar tarifa por defecto</button>{!review?<button type="button" className="primary" disabled={!valid} onClick={()=>setReview(true)}>Revisar cambios</button>:<><span>Se guardarán {model.feeN?.toLocaleString('es-ES')} € de honorarios{model.agency?` y ${model.commissionN?.toLocaleString('es-ES')} € de comisión`:''}.</span><button type="button" className="primary" disabled={busy} onClick={confirm}>{busy?'Guardando…':'Confirmar y guardar'}</button></>}</div>}{!canEdit&&<p className="exp-commercial-readonly">Consulta visible. La modificación queda reservada a Dirección y al backend autorizado.</p>}{message&&<div className="ops-message">{message}</div>}</section>,host)
}
