import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import {Landmark,ShieldCheck} from 'lucide-react';
import {fetchAppApi} from './supabase';

type Row=Record<string,unknown>;
type Candidate={bank_code:string;nombre:string;active?:boolean};
type CandidateEnvelope={ok?:boolean;bancos?:Candidate[]};
type SendEnvelope={ok?:boolean;envios?:Row[]};
type OfferEnvelope={ok?:boolean;ofertas?:Row[]};
type Rank={bank_id:string;bank:string;score:number;reasons:string[];risks:string[]};
type LoadResult={ok:boolean;items:Rank[];error?:string};
const text=(v:unknown)=>typeof v==='string'?v.trim():'';
const bankCode=(r:Row)=>text(r.bank_code)||text(r.banco_code)||text(r.bank_id)||text(r.banco_id);
const state=(r:Row)=>[r.status,r.estado,r.result,r.resultado,r.decision].map(text).filter(Boolean).join(' ').toLocaleLowerCase('es');
function score(c:Candidate,sends:Row[],offers:Row[],index:number):Rank{const ownS=sends.filter(x=>bankCode(x)===c.bank_code),ownO=offers.filter(x=>bankCode(x)===c.bank_code);let n=50-Math.min(index,5);const reasons:string[]=[],risks:string[]=[];const joined=[...ownS,...ownO].map(state).join(' ');if(ownS.length){n+=Math.min(12,ownS.length*3);reasons.push(`${ownS.length} envío(s) registrado(s).`)}if(ownO.length){n+=Math.min(18,ownO.length*6);reasons.push(`${ownO.length} oferta(s) recibida(s).`)}if(/aprob|acept|viable|ofert|conced|formaliz|firmad/.test(joined)){n+=15;reasons.push('Tiene señales positivas registradas.')}if(/rechaz|deneg|cancel|fall|error|no viable/.test(joined)){n-=18;risks.push('Tiene algún resultado negativo registrado.')}if(!ownS.length&&!ownO.length)reasons.push('Candidato activo; todavía sin histórico suficiente en esta operación.');return{bank_id:c.bank_code,bank:c.nombre,score:Math.max(0,Math.min(100,Math.round(n))),reasons,risks};}
async function load(exp:string):Promise<LoadResult>{const[c,s,o]=await Promise.all([fetchAppApi<CandidateEnvelope>(`/expedientes/${encodeURIComponent(exp)}/bancos-candidatos`),fetchAppApi<SendEnvelope>(`/expedientes/${encodeURIComponent(exp)}/envios-banco`),fetchAppApi<OfferEnvelope>(`/expedientes/${encodeURIComponent(exp)}/ofertas`)]);if(c.status!==200||!c.data?.ok)return{ok:false,items:[],error:'No se pudieron cargar los candidatos bancarios.'};if(s.status!==200||!s.data?.ok||o.status!==200||!o.data?.ok)return{ok:false,items:[],error:'Ranking no disponible: faltan señales de envíos u ofertas. No se publica un Top 3 incompleto.'};const sends=s.data.envios||[],offers=o.data.ofertas||[];return{ok:true,items:(c.data.bancos||[]).filter(x=>x.active!==false).map((x,i)=>score(x,sends,offers,i)).sort((a,b)=>b.score-a.score||a.bank.localeCompare(b.bank,'es'))};}
export default function ExpedienteBankRankingProdGuard(){const location=useLocation(),navigate=useNavigate(),match=location.pathname.match(/^\/expedientes\/([^/]+)$/),id=match?.[1]?decodeURIComponent(match[1]):'',active=Boolean(match&&id&&id!=='nuevo');const[target,setTarget]=useState<Element|null>(null),[data,setData]=useState<Rank[]|null>(null),[error,setError]=useState('');useEffect(()=>{if(!active){setTarget(null);setData(null);setError('');return}const attach=()=>setTarget(document.querySelector('.detail-next-action'));attach();const obs=new MutationObserver(attach);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[active,id]);useEffect(()=>{if(!active)return;let alive=true;setError('');setData(null);void load(id).then(x=>{if(!alive)return;if(!x.ok){setError(x.error||'Ranking no disponible.');setData([]);return}setData(x.items)});return()=>{alive=false}},[active,id]);const top=useMemo(()=>(data||[]).slice(0,3),[data]);if(!active||!target)return null;if(error)return createPortal(<section className="exp-ana-memory" data-testid="expediente-bank-ranking-incomplete" style={{marginTop:14}}><div className="exp-ana-memory-head"><Landmark size={16}/><strong>Top 3 bancos</strong></div><div className="exp-ana-evidence-line"><ShieldCheck size={15}/><span>{error}</span></div></section>,target);if(!top.length)return null;return createPortal(<section className="exp-ana-memory" data-testid="expediente-bank-ranking-prod" style={{marginTop:14}}><div className="exp-ana-memory-head"><Landmark size={16}/><strong>Top 3 bancos para esta operación</strong></div>{top.map((x,i)=><article key={x.bank_id}><small>OPCIÓN {i+1} · PUNTUACIÓN {x.score}/100</small><p><b>{x.bank}</b></p><p>{x.reasons.join(' ')}</p>{x.risks.length>0&&<em>Revisar: {x.risks.join(' ')}</em>}<button type="button" onClick={()=>navigate(`/bancos/${encodeURIComponent(x.bank_id)}`)}>Ver ficha del banco</button></article>)}<div className="exp-ana-evidence-line"><ShieldCheck size={15}/><span>El orden cambia con envíos, ofertas y resultados registrados. Si falta una señal requerida, el ranking se oculta en lugar de asumir que no existe histórico.</span></div></section>,target)}