import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,UserRound} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {anaVertical} from './assets/visualAssets';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './financieros-polish.css';

type Theme='light'|'dark';
type Ctx={actor_code?:string;role?:string};
type Person={name?:string;role?:string;expedientes?:number;firmas_mes?:number;[key:string]:unknown};
type PersonalResponse={items?:Person[];pending_profiles?:number};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'FC';
function safeNumber(v:unknown){return typeof v==='number'&&Number.isFinite(v)?v:null;}
function idOf(p:Person){for(const k of ['id','actor_code','worker_id','personal_id','code']){const v=p[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function personName(p:Person){return typeof p.name==='string'&&p.name.trim()?p.name.trim():'Perfil sin nombre';}
export default function FinancierosShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/financieros';
 const[sessionReady,setSessionReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[items,setItems]=useState<Person[]>([]),[pendingProfiles,setPendingProfiles]=useState(0),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 const[correction,setCorrection]=useState(''),[correctionReason,setCorrectionReason]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setSessionReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive){setLogged(Boolean(s));setSessionReady(true)}});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setStatus(null);setMessage('');setCtx(null);setNav([]);setItems([]);setPendingProfiles(0);try{const[c,n,p]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchAppApi<PersonalResponse>('/personal')]);if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);setStatus(p.status);if(p.status===200){setItems(Array.isArray(p.data?.items)?p.data.items:[]);setPendingProfiles(typeof p.data?.pending_profiles==='number'&&Number.isFinite(p.data.pending_profiles)?p.data.pending_profiles:0);}else{setItems([]);setPendingProfiles(0);}if(p.status===403)setMessage('Tu perfil no tiene acceso a este módulo.');else if(p.status===0)setMessage('No se pudo conectar con el equipo financiero autorizado.');else if(p.status!==200)setMessage('No se pudo cargar el equipo financiero autorizado.');}catch{if(!alive)return;setCtx(null);setNav([]);setStatus(0);setItems([]);setPendingProfiles(0);setMessage('No se pudo conectar con el equipo financiero autorizado.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false}},[active,logged]);
 const effectiveNav=nav.length?nav:fallbackNav;
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(p=>!q||`${p.name||''} ${p.role||''}`.toLowerCase().includes(q));},[items,query]);
 const totalExp=useMemo(()=>items.reduce((a,p)=>a+(safeNumber(p.expedientes)??0),0),[items]);
 const totalFirmas=useMemo(()=>items.reduce((a,p)=>a+(safeNumber(p.firmas_mes)??0),0),[items]);
 const expRanking=useMemo(()=>items.map(p=>({name:personName(p),value:safeNumber(p.expedientes)})).filter((x):x is {name:string;value:number}=>x.value!==null).sort((a,b)=>b.value-a.value),[items]);
 const firmasRanking=useMemo(()=>items.map(p=>({name:personName(p),value:safeNumber(p.firmas_mes)})).filter((x):x is {name:string;value:number}=>x.value!==null).sort((a,b)=>b.value-a.value),[items]);
 const maxExp=expRanking[0]?.value??0,maxFirmas=firmasRanking[0]?.value??0;
 const anaText=useMemo(()=>{if(status!==200)return'Datos del equipo todavía no disponibles.';if(!items.length)return'No hay perfiles financieros completos visibles en este ámbito.';const parts=[`Veo ${items.length} perfil${items.length===1?'':'es'} financiero${items.length===1?'':'s'} con ${totalExp} expediente${totalExp===1?'':'s'} y ${totalFirmas} firma${totalFirmas===1?'':'s'} este mes.`];if(expRanking[0])parts.push(`${expRanking[0].name} concentra la mayor carga visible de expedientes (${expRanking[0].value}).`);if(firmasRanking[0]&&firmasRanking[0].value>0)parts.push(`${firmasRanking[0].name} encabeza las firmas visibles del mes (${firmasRanking[0].value}).`);if(pendingProfiles>0)parts.push(`${pendingProfiles} perfil${pendingProfiles===1?'':'es'} incompleto${pendingProfiles===1?'':'s'} permanece${pendingProfiles===1?'':'n'} fuera del análisis.`);return parts.join(' ');},[status,items,totalExp,totalFirmas,expRanking,firmasRanking,pendingProfiles]);
 if(!active||!sessionReady||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 function sendCorrection(){const text=correction.trim();if(!text)return;const q=new URLSearchParams({mode:'help',resource:'financieros',correction:text});if(correctionReason.trim())q.set('reason',correctionReason.trim());navigate(`/ana?${q.toString()}`);}
 const role=ctx?.role||'Usuario';
 return <OperationalShellFrame className="fin-root" theme={theme} navigation={effectiveNav} activeRoute="/financieros" anaSubtitle="Cuando quieras, avanzamos paso a paso." anaRoute="/ana" query={query} onQueryChange={setQuery} searchPlaceholder="Buscar financiero..." searchActionLabel="Buscar" onSearchAction={()=>{}} name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="fin-content">
  <section className="fin-ana-hero"><div className="fin-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="fin-ana-body"><span>ANA · EQUIPO FINANCIERO</span><h2>Lectura viva de carga y resultados</h2><p>{anaText}</p><div className="fin-next"><button onClick={()=>navigate('/expedientes')}><b>1</b><strong>Revisar expedientes</strong><small>Abrir cartera →</small></button><button onClick={()=>navigate('/firmas')}><b>2</b><strong>Revisar firmas del mes</strong><small>Abrir firmas →</small></button><button onClick={()=>navigate('/ana?mode=help&resource=financieros')}><b>3</b><strong>Analizar equipo</strong><small>Con Ana →</small></button></div></div></section>
  <section className="fin-correct" aria-label="Corregir a Ana"><div><small>¿EN QUÉ ME EQUIVOCO?</small><strong>Corrige esta lectura de Ana</strong><p>La corrección conserva el contexto de Financieros para que pueda revisarse antes de convertirse en aprendizaje.</p></div><textarea value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="Escribe qué está interpretando mal Ana..."/><input value={correctionReason} onChange={e=>setCorrectionReason(e.target.value)} placeholder="Motivo o contexto adicional (opcional)"/><button disabled={!correction.trim()} onClick={sendCorrection}>Pasar corrección a Ana</button></section>
  <div className="fin-title"><div><small>EQUIPO FINANCIERO</small><h1>Financieros</h1><p>{status===200?`${items.length} perfiles completos visibles.`:'Datos según permisos efectivos.'}</p></div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos vivos':'PRE-PROD'}</span></div>
  {loading&&status===null&&<div className="ops-message" role="status" data-testid="financieros-loading">Cargando equipo financiero autorizado…</div>}
  {status===403&&message&&<div className="ops-message" data-testid="financieros-forbidden">{message}</div>}
  {status!==null&&status!==200&&status!==403&&message&&<div className="ops-message" data-testid="financieros-error">{message}</div>}
  {!loading&&status===200&&<><section className="fin-kpis"><article><small>PERFILES VISIBLES</small><strong>{items.length}</strong><span>Devueltos por gateway autorizado</span></article><article><small>EXPEDIENTES</small><strong>{totalExp}</strong><span>Suma de valores expuestos por gateway</span></article><article><small>FIRMAS MES</small><strong>{totalFirmas}</strong><span>Suma de valores expuestos por gateway</span></article></section>{pendingProfiles>0&&<div className="ops-message">{pendingProfiles} perfil(es) incompletos permanecen ocultos hasta disponer de identidad real suficiente.</div>}<section className="fin-charts" aria-label="Gráficos vivos del equipo"><article><div className="fin-chart-head"><span><BarChart3 size={18}/> Carga por expedientes</span><small>Ranking con datos visibles</small></div>{expRanking.length?<div className="fin-bars">{expRanking.map(row=><div className="fin-bar-row" key={`exp-${row.name}`}><span>{row.name}</span><div><i style={{width:`${maxExp?Math.max(6,row.value/maxExp*100):0}%`}}/></div><b>{row.value}</b></div>)}</div>:<p className="fin-no-chart">Sin valores de expedientes disponibles para graficar.</p>}</article><article><div className="fin-chart-head"><span><BarChart3 size={18}/> Firmas del mes</span><small>Resultados visibles por financiero</small></div>{firmasRanking.length?<div className="fin-bars">{firmasRanking.map(row=><div className="fin-bar-row" key={`fir-${row.name}`}><span>{row.name}</span><div><i style={{width:`${maxFirmas?Math.max(6,row.value/maxFirmas*100):0}%`}}/></div><b>{row.value}</b></div>)}</div>:<p className="fin-no-chart">Sin valores de firmas disponibles para graficar.</p>}</article></section><section className="fin-filter"><label>BUSCAR<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o rol"/></label><span>{visible.length} visibles</span></section>{visible.length?<section className="fin-grid">{visible.map((p,i)=>{const name=personName(p);const exp=safeNumber(p.expedientes);const firmas=safeNumber(p.firmas_mes);const id=idOf(p);return <article key={id||`${name}-${i}`} className={id?'fin-openable':''} tabIndex={id?0:undefined} onClick={()=>id&&navigate(`/financieros/${encodeURIComponent(id)}`)} onKeyDown={e=>{if(id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();navigate(`/financieros/${encodeURIComponent(id)}`)}}}><div className="fin-avatar">{initials(name)}</div><div className="fin-person-copy"><h2>{name}</h2><p>{typeof p.role==='string'&&p.role.trim()?p.role:'Rol no disponible'}</p></div><dl><div><dt>Expedientes</dt><dd>{exp??'No disponible'}</dd></div><div><dt>Firmas mes</dt><dd>{firmas??'No disponible'}</dd></div></dl>{id&&<small className="fin-open-hint">Abrir ficha →</small>}</article>})}</section>:<div className="ops-empty" data-testid="financieros-empty"><UserRound size={22}/><strong>Sin financieros visibles</strong><span>No hay perfiles completos para este ámbito o filtro.</span></div>}</>}
 </OperationalShellFrame>;
}
