import {FormEvent,useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {CalendarDays,FileCheck2,Save} from 'lucide-react';
import {fetchAppApi,IS_PRODUCTION,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';type Ctx={role?:string;display_name?:string};type Row=Record<string,unknown>;type Resp={ok?:boolean;status?:number;id?:string;firma_code?:string;error?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function text(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim()}return''}
export default function FirmaCreateShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/firmas/nuevo'||location.pathname==='/firmas/nueva';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[query,setQuery]=useState('');
 const[expedientes,setExpedientes]=useState<Row[]>([]),[exp,setExp]=useState(()=>new URLSearchParams(location.search).get('expediente')||''),[fecha,setFecha]=useState(''),[notaria,setNotaria]=useState(''),[oficial,setOficial]=useState(''),[feinRecibida,setFeinRecibida]=useState(''),[feinFirmada,setFeinFirmada]=useState(''),[fechaMin,setFechaMin]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[created,setCreated]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()}},[active]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchNotionRuntime<any>('/expedientes')]).then(([c,n,e])=>{if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);setExpedientes(e.status===200&&Array.isArray(e.data?.items)?e.data.items:[])});return()=>{alive=false}},[active,logged]);
 if(!active||!ready||!logged)return null;const allowed=ctx?.role==='Direccion'||ctx?.role==='Financiero';const displayName=ctx?.display_name||ctx?.role||'Usuario';
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}function search(){const q=query.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}function edit(){setPreview(false);setMessage('');setCreated('')}
 async function submit(e:FormEvent){e.preventDefault();if(!allowed||!exp)return;if(!preview){setPreview(true);return}if(!IS_PRODUCTION){setPreview(false);setMessage('La creación de firma PRE-PROD queda aislada hasta disponer de su contrato de prueba; no se escribe en PROD.');return}setBusy(true);setMessage('');const toIso=(v:string)=>v?new Date(v).toISOString():null;const {data,error}=await supabase.rpc('fenix_prod_sign_create',{p_expediente_code:exp,p_fecha_firma:toIso(fecha),p_notaria:notaria.trim()||null,p_oficial:oficial.trim()||null,p_fein_recibida_at:toIso(feinRecibida),p_fein_firmada_at:toIso(feinFirmada),p_fecha_min_notaria:fechaMin||null});setBusy(false);const r=(data||{error:error?.message}) as Resp;const status=error?500:Number(r.status||200);setPreview(false);if(status===201&&r.ok){const code=r.firma_code||r.id||'';setCreated(code);setMessage('Firma creada correctamente en PROD.')}else if(status===409)setMessage('Este expediente ya tiene una firma activa. No se ha creado duplicado.');else if(status===404)setMessage('El expediente ya no existe o no está disponible.');else if(status===403)setMessage('Tu perfil no puede crear la firma.');else setMessage(`No se pudo crear la firma (${r.error||status}).`)}
 return <OperationalShellFrame className="firma-create-root" theme={theme} navigation={nav.length?nav:fallbackNav} activeRoute="/firmas" anaSubtitle="Preparamos FEIN, notaría y fecha sin perder el contexto del expediente." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar expediente o firma..." searchActionLabel="Buscar" onSearchAction={search} name={displayName} role={ctx?.role||''} initials={displayName.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout}>
  <div className="ops-title"><div><span className="ops-icon"><FileCheck2 size={20}/></span><div><h1>Nueva firma</h1><p>Alta canónica vinculada a un expediente real.</p></div></div><span className="ops-live ok">{IS_PRODUCTION?'PROD':'PRE-PROD'}</span></div>
  <section className="inmo-ana-hero" data-testid="firma-create-ana"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · NUEVA FIRMA</span><h2>Dejamos la firma preparada desde el expediente</h2><p>Selecciona operación, fechas FEIN y notaría. La ficha se crea en estado Preparación o Programada y conserva el control de cierre.</p></div></section>
  {!allowed?<div className="ops-message">Tu perfil no puede crear firmas.</div>:<form className="ops-table-card" style={{padding:20,display:'grid',gap:12}} onSubmit={submit} data-testid="firma-create-form"><label>Expediente<select value={exp} onChange={e=>{setExp(e.target.value);edit()}} required><option value="">Selecciona un expediente</option>{expedientes.map((r,i)=>{const code=text(r,['expediente_code','expediente']);return code?<option key={code} value={code}>{text(r,['cliente_alias','cliente'])||code} · {code}</option>:null})}</select></label><label>FEIN recibida<input type="datetime-local" value={feinRecibida} onChange={e=>{setFeinRecibida(e.target.value);edit()}}/></label><label>FEIN firmada<input type="datetime-local" value={feinFirmada} onChange={e=>{setFeinFirmada(e.target.value);edit()}}/></label><label>Fecha mínima notaría<input type="date" value={fechaMin} onChange={e=>{setFechaMin(e.target.value);edit()}}/></label><label>Fecha y hora de firma<input type="datetime-local" value={fecha} onChange={e=>{setFecha(e.target.value);edit()}}/></label><label>Notaría<input value={notaria} onChange={e=>{setNotaria(e.target.value);edit()}} placeholder="Notaría o lugar"/></label><label>Oficial / contacto<input value={oficial} onChange={e=>{setOficial(e.target.value);edit()}}/></label>{!preview?<button className="primary" disabled={!exp||busy}><CalendarDays size={16}/> Revisar antes de crear</button>:<div className="ops-message"><strong>Revisión previa</strong><p>Expediente: {exp} · Firma: {fecha||'sin fecha todavía'} · Notaría: {notaria||'por definir'}</p><button className="primary" disabled={busy}><Save size={16}/>{busy?'Creando…':'Confirmar y crear'}</button><button type="button" onClick={()=>setPreview(false)}>Seguir editando</button></div>}{message&&<div className="ops-message">{message}</div>}{created&&<button type="button" onClick={()=>navigate(`/firmas/${encodeURIComponent(created)}`)}>Abrir firma creada →</button>}</form>}
 </OperationalShellFrame>
}
