import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {CalendarClock,CheckCircle2,ExternalLink,FileText,MapPin,Landmark} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './firmas-polish.css';

type Theme='light'|'dark';type Ctx={actor_code?:string;role?:string};type Row=Record<string,unknown>;type Focus='todas'|'proximas'|'pendientes'|'firmadas';type SortKey='fecha'|'cliente'|'banco';
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;return Array.isArray(d.items)?d.items as Row[]:[];}
function text(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function urlFrom(v:unknown):string{if(typeof v==='string'&&/^https?:\/\//i.test(v.trim()))return v.trim();if(Array.isArray(v)){for(const x of v){const u=urlFrom(x);if(u)return u;}}if(v&&typeof v==='object'){const o=v as Record<string,unknown>;for(const k of ['url','href','file_url','external_url']){const u=urlFrom(o[k]);if(u)return u;}}return'';}
function firstUrl(r:Row,keys:string[]){for(const k of keys){const u=urlFrom(r[k]);if(u)return u;}return'';}
function idOf(r:Row){return text(r,['id','firma_id','firma_code','code']);}function clientOf(r:Row){return text(r,['cliente','titular','expediente','nombre','title'])||'Operación sin nombre visible';}function stateOf(r:Row){return text(r,['estado','estado_firma','status'])||'Sin estado';}function dateOf(r:Row){return text(r,['fecha_hora_firma','fecha_firma','fecha','fecha_fein'])||'No disponible';}function placeOf(r:Row){return text(r,['lugar','notaria','notaría','sucursal','ubicacion'])||'No disponible';}function bankOf(r:Row){return text(r,['banco','entidad'])||'No disponible';}function signed(r:Row){return /firmad|complet|cerrad/i.test(stateOf(r));}function scheduled(r:Row){return !signed(r)&&(/program|pendiente|agendad|notar/i.test(stateOf(r))||dateOf(r)!=='No disponible');}
function compareText(a:string,b:string){return a.localeCompare(b,'es',{sensitivity:'base',numeric:true});}function dateNum(v:string){const n=Date.parse(v.replace(' ','T'));return Number.isFinite(n)?n:Number.MAX_SAFE_INTEGER;}
function docsOf(r:Row){return [
 {label:'FEIN',url:firstUrl(r,['fein_url','url_fein','fein','documento_fein'])},
 {label:'Acta notarial',url:firstUrl(r,['acta_url','url_acta','acta_notarial','acta'])},
 {label:'Tasación',url:firstUrl(r,['tasacion_url','tasación_url','url_tasacion','url_tasación','tasacion_pdf'])},
 {label:'Nota simple',url:firstUrl(r,['nota_simple_url','url_nota_simple','nota_simple'])},
 {label:'Arras / compraventa',url:firstUrl(r,['arras_url','compraventa_url','url_arras','contrato_arras'])},
 {label:'Identificación',url:firstUrl(r,['dni_url','documentacion_identidad_url','identificacion_url'])}
 ];}

export default function FirmasShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/firmas';
 const[sessionReady,setSessionReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const[state,setState]=useState(''),[focus,setFocus]=useState<Focus>('todas'),[sortKey,setSortKey]=useState<SortKey>('fecha'),[globalQuery,setGlobalQuery]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setSessionReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setSessionReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);});},[active,logged]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setRows([]);try{const r=await fetchNotionRuntime<unknown>('/firmas');if(!alive)return;setStatus(r.status);setRows(r.status===200?rowsFrom(r.data):[]);if(r.status===403)setMessage('Tu perfil no tiene acceso a este módulo o registro.');else if(r.status!==200)setMessage('No se pudo leer la información actualizada de Firmas.');}catch{if(!alive)return;setStatus(0);setRows([]);setMessage('No se pudo conectar con Firmas.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false}},[active,logged]);
 const effectiveNav=nav.length?nav:fallbackNav,states=useMemo(()=>Array.from(new Set(rows.map(stateOf).filter(Boolean))).sort(compareText),[rows]);
 const visible=useMemo(()=>{const out=rows.filter(r=>(!state||stateOf(r)===state)&&(focus==='todas'||(focus==='proximas'&&scheduled(r))||(focus==='pendientes'&&!signed(r))||(focus==='firmadas'&&signed(r))));return[...out].sort((a,b)=>sortKey==='cliente'?compareText(clientOf(a),clientOf(b)):sortKey==='banco'?compareText(bankOf(a),bankOf(b)):dateNum(dateOf(a))-dateNum(dateOf(b)));},[rows,state,focus,sortKey]);
 const signedCount=useMemo(()=>rows.filter(signed).length,[rows]),scheduledCount=useMemo(()=>rows.filter(scheduled).length,[rows]),docsLinked=useMemo(()=>rows.reduce((n,r)=>n+docsOf(r).filter(d=>d.url).length,0),[rows]);
 if(!active||!sessionReady||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}function globalSearch(){const q=globalQuery.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 const role=ctx?.role||'Usuario';
 return <OperationalShellFrame className="firmas-root" theme={theme} navigation={effectiveNav} activeRoute="/firmas" anaSubtitle="Cuando quieras, avanzamos paso a paso." query={globalQuery} onQueryChange={setGlobalQuery} searchPlaceholder="Buscar en toda la app..." searchActionLabel="Buscar" onSearchAction={globalSearch} name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="firmas-content">
  <section className="firmas-ana-hero"><div className="firmas-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="firmas-ana-body"><span>ANA · FIRMAS</span><h2>Que ninguna firma llegue incompleta</h2><p>Reviso fecha, banco, notaría y los documentos vinculados a cada operación. Los documentos disponibles se abren en una pestaña nueva del navegador.</p><div className="firmas-next"><button onClick={()=>setFocus('proximas')}><b>1</b><strong>Próximas firmas</strong><small>{scheduledCount} casos →</small></button><button onClick={()=>setFocus('pendientes')}><b>2</b><strong>Revisar pendientes</strong><small>{rows.length-signedCount} casos →</small></button><button onClick={()=>navigate('/ana?mode=help&resource=firma')}><b>3</b><strong>Preparar con Ana</strong><small>Revisar documentación →</small></button></div></div></section>
  <div className="firmas-title"><div><small>FEIN · NOTARÍA · FIRMA</small><h1>Firmas</h1><p>{status===200?`${rows.length} firmas visibles en tu ámbito autorizado.`:'Información disponible según permisos.'}</p></div><div className="firmas-title-actions"><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos actualizados':'Sin conexión'}</span><button className="primary" onClick={()=>navigate('/firmas/nuevo')}>+ Nueva firma</button></div></div>
  {loading&&<div className="ops-empty" data-testid="firmas-loading"><strong>Cargando…</strong><span>Consultando Firmas.</span></div>}{!loading&&message&&<div className="ops-message" data-testid={status===403?'firmas-forbidden':'firmas-error'}>{message}</div>}
  {!loading&&status===200&&<><section className="firmas-kpis"><article><small>FIRMAS</small><strong>{rows.length}</strong><span>Visibles</span></article><article><CalendarClock size={18}/><small>PROGRAMADAS</small><strong>{scheduledCount}</strong><span>Con fecha o estado programado</span></article><article><CheckCircle2 size={18}/><small>FIRMADAS</small><strong>{signedCount}</strong><span>Según estado</span></article><article><FileText size={18}/><small>DOCUMENTOS VINCULADOS</small><strong>{docsLinked}</strong><span>Archivos disponibles</span></article></section>
   <section className="firmas-filter" data-testid="firmas-preset-search"><div className="firmas-filter-head"><div><small>BUSCADOR PREFIJADO</small><h2>Filtrar firmas sin escribir</h2></div><span>{visible.length} visibles</span></div><div className="firmas-filter-grid"><label>VISTA RÁPIDA<select value={focus} onChange={e=>setFocus(e.target.value as Focus)}><option value="todas">Todas</option><option value="proximas">Próximas / programadas</option><option value="pendientes">Pendientes</option><option value="firmadas">Firmadas</option></select></label><label>ESTADO<select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos los estados</option>{states.map(v=><option key={v}>{v}</option>)}</select></label><label>ORDEN<select value={sortKey} onChange={e=>setSortKey(e.target.value as SortKey)}><option value="fecha">Fecha</option><option value="cliente">Cliente</option><option value="banco">Banco</option></select></label><button onClick={()=>{setFocus('todas');setState('');setSortKey('fecha')}}>Limpiar</button></div></section>
   {visible.length===0?<div className="ops-empty" data-testid="firmas-empty"><strong>Sin firmas visibles</strong></div>:<section className="firmas-card-grid" data-testid="firmas-card-grid">{visible.map((r,i)=>{const id=idOf(r),docs=docsOf(r);return <article className="firma-card" key={id||i}><div className="firma-card-head"><div><small>{stateOf(r)}</small><h2>{clientOf(r)}</h2></div><span>{dateOf(r)}</span></div><div className="firma-card-meta"><span><Landmark size={15}/>{bankOf(r)}</span><span><MapPin size={15}/>{placeOf(r)}</span></div><div className="firma-card-docs"><strong>Documentación para firma</strong><div>{docs.map(d=>d.url?<a key={d.label} href={d.url} target="_blank" rel="noreferrer"><FileText size={15}/><span>{d.label}</span><ExternalLink size={13}/></a>:<span className="firma-doc-missing" key={d.label}><FileText size={15}/><span>{d.label}</span><b>Pendiente</b></span>)}</div></div>{id&&<button className="firma-open" onClick={()=>navigate(`/firmas/${encodeURIComponent(id)}`)}>Abrir ficha de firma →</button>}</article>})}</section>}
  </>}
 </OperationalShellFrame>;
}
