import {useEffect,useMemo,useState} from 'react';
import {Mail,MessageCircle,Send,X} from 'lucide-react';
import {useLocation,useNavigate} from 'react-router-dom';
import {supabase} from './supabase';

type Scope={type:string;code:string};
const HIDDEN=['/','/perfil','/ana','/comunicaciones','/comunicaciones/nueva'];
function scopeFromPath(path:string):Scope{
 const p=path.split('/').filter(Boolean),root=p[0]||'general',raw=p[1]||'';const code=['nuevo','nueva','new'].includes(raw.toLowerCase())?'':raw;
 const map:Record<string,string>={expedientes:'expediente',contactos:'contacto','contactos-b2b':'contacto_b2b',inmobiliarias:'inmobiliaria',tareas:'tarea',agenda:'tarea',visitas:'visita',bancos:'banco',tasaciones:'tasacion',firmas:'firma',documentacion:'documento',documentos:'documento',notarias:'notaria','registros-propiedad':'registro_propiedad',economia:'economia',inicio:'general'};
 return{type:map[root]||root,code};
}
function inferChannel(text:string){return /\bwhats?app\b/i.test(text)?'WhatsApp':/\b(email|correo)\b/i.test(text)?'Email':'Email';}
export default function GlobalCommunicationCommandGuard(){
 const location=useLocation(),navigate=useNavigate(),scope=useMemo(()=>scopeFromPath(location.pathname),[location.pathname]);
 const[logged,setLogged]=useState(false),[open,setOpen]=useState(false),[instruction,setInstruction]=useState('');
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>alive&&setLogged(Boolean(data.session)));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setLogged(Boolean(s)));return()=>{alive=false;subscription.unsubscribe()};},[]);
 if(!logged||HIDDEN.some(x=>location.pathname===x||location.pathname.startsWith(`${x}/`)))return null;
 function prepare(){const text=instruction.trim();if(!text)return;const q=new URLSearchParams({scope_type:scope.type,channel:inferChannel(text),instruction:text,return_to:`${location.pathname}${location.search}`});if(scope.code)q.set('scope_code',scope.code);navigate(`/comunicaciones/nueva?${q.toString()}`);setOpen(false);}
 return <div className="fenix-global-comm" data-testid="global-communication-command"><style>{`.fenix-global-comm{position:fixed;right:20px;bottom:92px;z-index:9050;font-family:inherit}.fenix-global-comm>button{border:0;border-radius:999px;background:#870064;color:#fff;padding:11px 15px;font-weight:800;box-shadow:0 8px 25px rgba(0,0,0,.22);display:flex;gap:8px;align-items:center;cursor:pointer}.fenix-global-comm-panel{width:min(390px,calc(100vw - 28px));margin-bottom:10px;background:var(--surface,#fff);color:var(--text,#222);border:1px solid var(--border,#ddd);border-radius:16px;padding:14px;box-shadow:0 14px 40px rgba(0,0,0,.25)}.fenix-global-comm-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.fenix-global-comm-head button{border:0;background:transparent;color:inherit;cursor:pointer}.fenix-global-comm textarea{width:100%;box-sizing:border-box;min-height:92px;border:1px solid var(--border,#ddd);border-radius:10px;padding:10px;background:var(--surface,#fff);color:var(--text,#222);resize:vertical}.fenix-global-comm-actions{display:flex;justify-content:flex-end;margin-top:9px}.fenix-global-comm-actions button{border:0;border-radius:9px;background:#870064;color:#fff;padding:9px 12px;font-weight:800;display:flex;align-items:center;gap:6px;cursor:pointer}.fenix-global-comm-actions button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:760px){.fenix-global-comm{right:12px;bottom:82px}}`}</style>{open&&<div className="fenix-global-comm-panel"><div className="fenix-global-comm-head"><strong>Ana · preparar comunicación</strong><button type="button" aria-label="Cerrar comunicación" onClick={()=>setOpen(false)}><X size={17}/></button></div><p style={{fontSize:12,margin:'0 0 8px'}}>Dímelo o díctalo como lo dirías normalmente. Ana preparará la vista previa; nada se envía todavía.</p><textarea aria-label="Orden de comunicación para Ana" value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Ej.: Manda a Elena de BBVA un email diciendo que te mando la documentación."/><div className="fenix-global-comm-actions"><button type="button" disabled={!instruction.trim()} onClick={prepare}><Send size={15}/> Preparar</button></div></div>}<button type="button" onClick={()=>setOpen(v=>!v)}>{open?<MessageCircle size={17}/>:inferChannel(instruction)==='WhatsApp'?<MessageCircle size={17}/>:<Mail size={17}/>} Ana · comunicar</button></div>;
}
