import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {AlertTriangle,FileScan,ShieldAlert,ShieldCheck} from 'lucide-react';
import {useLocation} from 'react-router-dom';
import {fetchNotionRuntime} from './notionRuntime';
import {projectDocumentIntelligence} from './documentIntelligenceProjection';
import {getDocumentPreviewFields,getDocumentPreviewSchema} from './documentPreviewMasterSchema';
import {ocrFile} from './browserDocumentOcr';
import {extractDocumentData} from './operationalDocumentExtraction';
import {sanitizeCriticalDocumentFields} from './criticalDocumentFieldSanitizer';

type Row=Record<string,unknown>;
type Expiry={kind:'ok'|'warning'|'critical'|'unknown';label:string;detail:string};
function text(row:Row|null,keys:string[]){if(!row)return'';for(const key of keys){const v=row[key];if(typeof v==='string'&&v.trim())return v.trim()}return''}
function safeUrl(row:Row|null){const raw=text(row,['url','archivo_url','url_archivo','file_url','source_url','original_url','pdf','url_pdf','documento_url','enlace','link','archivo']);if(!raw)return'';try{const u=new URL(raw);return u.protocol==='https:'||u.protocol==='http:'?u.toString():''}catch{return''}}
function identityType(row:Row|null){const raw=text(row,['tipo_canónico','tipo_canonico','tipo','categoria','categoría','document_type']).toLowerCase();return /(^|\b)(dni|nie|pasaporte)(\b|$)/i.test(raw)?raw:''}
function parseDate(raw:string){const s=raw.trim();const iso=s.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/);const eu=s.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})$/);const m=iso?{y:+iso[1],mo:+iso[2],d:+iso[3]}:eu?{y:+eu[3],mo:+eu[2],d:+eu[1]}:null;if(!m)return null;const d=new Date(Date.UTC(m.y,m.mo-1,m.d,23,59,59));return Number.isNaN(d.getTime())?null:d}
function expiry(row:Row|null):Expiry|null{if(!identityType(row))return null;const raw=text(row,['fecha_caducidad','caducidad','fecha_expiracion','fecha_vencimiento','vencimiento']);if(!raw)return{kind:'unknown',label:'Caducidad no reconocida',detail:'Revisar DNI, NIE o pasaporte antes de firma.'};const end=parseDate(raw);if(!end)return{kind:'unknown',label:`Caducidad: ${raw}`,detail:'Fecha no interpretable con seguridad.'};const now=new Date();const today=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());const days=Math.ceil((end.getTime()-today)/86400000);if(days<0)return{kind:'critical',label:`Documento CADUCADO · ${raw}`,detail:'Bloqueo operativo de firma hasta aportar identificación vigente.'};if(days<=90)return{kind:'warning',label:`Caduca pronto · ${raw}`,detail:`Quedan ${days} días. Revisar renovación antes de notaría.`};return{kind:'ok',label:`Documento vigente · ${raw}`,detail:`Quedan ${days} días hasta la caducidad.`}}

export default function HistoricalDocumentRecoveryFixedGuard(){
 const location=useLocation();const match=location.pathname.match(/^\/documentos\/([^/]+)$/);const id=match?.[1]?decodeURIComponent(match[1]):'';const active=Boolean(id);
 const[status,setStatus]=useState<number|null>(null),[row,setRow]=useState<Row|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[recovered,setRecovered]=useState<Row|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!active){setStatus(null);setRow(null);return;}let alive=true;(async()=>{try{const r=await fetchNotionRuntime<any>(`/documentos/${encodeURIComponent(id)}`);if(!alive)return;setStatus(r.status);setRow(r.status===200?(r.data?.item??null):null)}catch{if(alive)setStatus(0)}})();return()=>{alive=false}},[active,id]);
 const projected=useMemo(()=>projectDocumentIntelligence(row) as Row|null,[row]);const shown=recovered||projected;const fields=useMemo(()=>shown?getDocumentPreviewFields(shown):[],[shown]);const missing=fields.filter(f=>f.value===null||f.value===undefined||f.value==='').length;const original=safeUrl(projected);const exp=expiry(shown);
 async function recover(){if(!projected||!original||busy)return;setBusy(true);setError('');setRecovered(null);try{setProgress('Ana está releyendo el original ya guardado…');const response=await fetch(original,{credentials:'omit'});if(!response.ok)throw new Error(`No se pudo recuperar el original (${response.status}).`);const blob=await response.blob();const filename=text(projected,['title','documento','nombre','titulo','título'])||`documento-${id}`;const file=new File([blob],filename,{type:blob.type||'application/pdf'});const o=await ocrFile(file,setProgress);const schema=getDocumentPreviewSchema(projected);const hint=schema?.family||text(projected,['tipo_canónico','tipo_canonico','tipo','categoria','categoría']);const result=sanitizeCriticalDocumentFields(extractDocumentData(o.text,o.confidence,hint),o.text);setRecovered({...projected,...result.fields,document_type:result.documentType,resumen_documento:result.summary});setProgress('Relectura terminada. El original se conserva y no se ha creado ninguna copia.');}catch(e){setError(e instanceof Error?e.message:'No se pudo releer el documento existente.')}finally{setBusy(false)}}
 if(!active)return null;
 return createPortal(<section className="hist-fixed" data-testid="historical-document-recovery-fixed"><style>{`.hist-fixed{position:fixed;z-index:6900;right:max(18px,5vw);top:max(82px,10vh);width:min(360px,calc(100vw - 36px));display:grid;gap:9px;padding:14px;border:2px solid #f4741f;border-radius:16px;background:var(--surface,#fff);color:var(--text,#171717);box-shadow:0 18px 50px rgba(0,0,0,.3)}.hist-fixed h3{display:flex;align-items:center;gap:7px;margin:0;font-size:13px}.hist-fixed p,.hist-fixed small{margin:0;font-size:10.5px;line-height:1.45;color:var(--muted,#667085)}.hist-fixed button{border:1px solid #f4741f;background:#f4741f;color:#fff;border-radius:10px;padding:10px 12px;font-weight:850;cursor:pointer}.hist-fixed button:disabled{opacity:.5;cursor:not-allowed}.hist-exp{display:flex;gap:8px;align-items:flex-start;padding:9px;border:1px solid var(--border,#ddd);border-radius:11px}.hist-exp strong,.hist-exp span{display:block}.hist-exp span{font-size:10px;margin-top:2px}.hist-exp[data-kind='critical']{border-color:#dc2626;background:rgba(220,38,38,.08)}.hist-exp[data-kind='warning'],.hist-exp[data-kind='unknown']{border-color:#eab308;background:rgba(234,179,8,.08)}.hist-exp[data-kind='ok']{border-color:#16a34a;background:rgba(22,163,74,.07)}.hist-err{font-size:10.5px;color:#b91c1c}@media(max-width:900px){.hist-fixed{right:18px;top:72px;max-height:42vh;overflow:auto}}html[data-theme='dark'] .hist-fixed{background:#202023;color:#f4f4f5;border-color:#f4741f}`}</style><h3><FileScan size={16}/> Ana · documento existente</h3>{status===null?<p>Cargando control del documento…</p>:status!==200||!projected?<div className="hist-err">No se ha podido cargar el registro documental autorizado para esta vista.</div>:<><p>{missing>0?`${missing} campo${missing===1?'':'s'} sin dato visible. Relee el original sin volver a subirlo.`:'Puedes releer igualmente el original para verificar la lectura guardada.'}</p><button type="button" onClick={()=>void recover()} disabled={busy||!original}>{busy?'Releyendo…':'Releer original existente'}</button>{!original&&<small>El registro no expone una URL autorizada del archivo original. Hay que recuperar su referencia de almacenamiento para poder releerlo.</small>}</>}{exp&&<div className="hist-exp" data-kind={exp.kind}>{exp.kind==='critical'?<ShieldAlert size={17}/>:exp.kind==='ok'?<ShieldCheck size={17}/>:<AlertTriangle size={17}/>}<div><strong>{exp.label}</strong><span>{exp.detail}</span></div></div>}{progress&&<small>{progress}</small>}{error&&<div className="hist-err">{error}</div>}</section>,document.body);
}
