import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {AlertTriangle,FileScan,ShieldAlert,ShieldCheck} from 'lucide-react';
import {useLocation} from 'react-router-dom';
import {fetchNotionRuntime} from './notionRuntime';
import {projectDocumentIntelligence} from './documentIntelligenceProjection';
import {getDocumentPreviewFields,getDocumentPreviewSchema} from './documentPreviewMasterSchema';
import {ocrFile} from './browserDocumentOcr';
import {extractDocumentData} from './operationalDocumentExtraction';

type Row=Record<string,unknown>;

type ExpiryState={kind:'ok'|'warning'|'critical'|'unknown';label:string;detail:string};

function text(row:Row|null,keys:string[]){if(!row)return'';for(const key of keys){const v=row[key];if(typeof v==='string'&&v.trim())return v.trim()}return''}
function safeUrl(row:Row|null){const raw=text(row,['url','archivo_url','url_archivo','file_url','source_url','original_url','pdf','url_pdf','documento_url','enlace','link','archivo']);if(!raw)return'';try{const u=new URL(raw);return u.protocol==='https:'||u.protocol==='http:'?u.toString():''}catch{return''}}
function identityType(row:Row|null){const raw=text(row,['tipo_canónico','tipo_canonico','tipo','categoria','categoría','document_type']).toLowerCase();return /(^|\b)(dni|nie|pasaporte)(\b|$)/i.test(raw)?raw:''}
function parseDate(raw:string){const s=raw.trim();if(!s)return null;const iso=s.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/);const eu=s.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})$/);const m=iso?{y:+iso[1],mo:+iso[2],d:+iso[3]}:eu?{y:+eu[3],mo:+eu[2],d:+eu[1]}:null;if(!m)return null;const d=new Date(Date.UTC(m.y,m.mo-1,m.d,23,59,59));return Number.isNaN(d.getTime())?null:d}
function expiryState(row:Row|null):ExpiryState|null{if(!identityType(row))return null;const raw=text(row,['fecha_caducidad','caducidad','fecha_expiracion','fecha_vencimiento','vencimiento']);if(!raw)return{kind:'unknown',label:'Caducidad no reconocida',detail:'DNI, NIE o pasaporte sin fecha de caducidad extraída. Revisar antes de firma.'};const end=parseDate(raw);if(!end)return{kind:'unknown',label:`Caducidad: ${raw}`,detail:'La fecha existe pero no se ha podido interpretar con seguridad.'};const now=new Date();const today=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());const days=Math.ceil((end.getTime()-today)/86400000);if(days<0)return{kind:'critical',label:`Documento CADUCADO · ${raw}`,detail:'Bloqueo operativo de firma: debe aportarse identificación vigente antes de notaría.'};if(days<=90)return{kind:'warning',label:`Caduca pronto · ${raw}`,detail:`Quedan ${days} día${days===1?'':'s'}. Renovar o verificar vigencia antes de programar firma.`};return{kind:'ok',label:`Documento vigente · ${raw}`,detail:`Vigencia comprobada. Quedan ${days} días hasta la caducidad.`}}

export default function HistoricalDocumentRecoveryGuard(){
 const location=useLocation();const match=location.pathname.match(/^\/documentos\/([^/]+)$/);const id=match?.[1]?decodeURIComponent(match[1]):'';const active=Boolean(id);
 const[host,setHost]=useState<HTMLElement|null>(null),[row,setRow]=useState<Row|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[recovered,setRecovered]=useState<Row|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!active){setHost(null);return;}let mount:HTMLElement|null=null;const place=()=>{const side=document.querySelector<HTMLElement>('.doc-view-side');if(!side)return;if(!mount){mount=document.createElement('div');mount.className='historical-document-recovery-host';side.insertBefore(mount,side.firstChild);setHost(mount);}};place();const obs=new MutationObserver(place);obs.observe(document.body,{childList:true,subtree:true});return()=>{obs.disconnect();mount?.remove();setHost(null)}},[active,id]);
 useEffect(()=>{if(!active)return;let alive=true;(async()=>{try{const r=await fetchNotionRuntime<any>(`/documentos/${encodeURIComponent(id)}`);if(alive)setRow(r.status===200?(r.data?.item??null):null)}catch{if(alive)setRow(null)}})();return()=>{alive=false}},[active,id]);
 const projected=useMemo(()=>projectDocumentIntelligence(row) as Row|null,[row]);const expiry=useMemo(()=>expiryState(recovered||projected),[projected,recovered]);const baseFields=useMemo(()=>getDocumentPreviewFields(projected),[projected]);const missing=baseFields.filter(x=>x.value===null||x.value===undefined||x.value==='').length;const original=safeUrl(projected);const schema=getDocumentPreviewSchema(projected);
 async function recover(){if(!original||busy)return;setBusy(true);setError('');setRecovered(null);try{setProgress('Recuperando el original ya almacenado…');const response=await fetch(original,{credentials:'omit'});if(!response.ok)throw new Error(`No se pudo recuperar el original (${response.status}).`);const blob=await response.blob();const filename=text(projected,['title','documento','nombre','titulo','título'])||`documento-${id}`;const file=new File([blob],filename,{type:blob.type||'application/pdf'});const o=await ocrFile(file,setProgress);const hint=schema?.family||text(projected,['tipo_canónico','tipo_canonico','tipo','categoria','categoría']);const result=extractDocumentData(o.text,o.confidence,hint);setRecovered({...projected,...result.fields,document_type:result.documentType,resumen_documento:result.summary});setProgress(`Relectura terminada${o.confidence!==null?` · confianza ${Math.round(o.confidence)}%`:''}. No se ha creado ninguna copia del documento.`)}catch(e){setError(e instanceof Error?e.message:'No se pudo releer el documento existente.')}finally{setBusy(false)}}
 if(!active||!host||!projected)return null;const recoveredFields=recovered?getDocumentPreviewFields(recovered):[];return createPortal(<section className="hist-doc-panel" data-testid="historical-document-recovery"><h2><FileScan size={16}/> Documentos históricos</h2>{expiry&&<div className="hist-doc-status" data-kind={expiry.kind}>{expiry.kind==='critical'?<ShieldAlert size={18}/>:expiry.kind==='ok'?<ShieldCheck size={18}/>:<AlertTriangle size={18}/>}<div><strong>{expiry.label}</strong><span>{expiry.detail}</span></div></div>}{missing>0&&<><p>Este documento conserva {missing} punto{missing===1?'':'s'} maestro{missing===1?'':'s'} sin dato visible. Puedes releer el original existente sin volver a subirlo ni duplicarlo.</p><button type="button" disabled={busy||!original} onClick={()=>void recover()}>{busy?'Releyendo…':'Releer original existente'}</button>{!original&&<small>No hay URL autorizada del original disponible para relectura desde esta vista.</small>}</>}{progress&&<div className="hist-doc-progress">{progress}</div>}{error&&<div className="hist-doc-error" role="alert">{error}</div>}{recovered&&<div className="hist-doc-fields"><strong>Datos recuperados del original</strong>{recoveredFields.filter(x=>x.value!==null&&x.value!==undefined&&x.value!=='').map(field=><div key={field.label}><span>{field.label}</span><b>{String(field.value)}</b></div>)}</div>}<style>{`.hist-doc-panel{display:grid;gap:10px;margin-bottom:18px;padding-bottom:18px;border-bottom:1px solid var(--border,#e5e7eb)}.hist-doc-panel h2{display:flex;align-items:center;gap:7px;margin:0;font-size:14px}.hist-doc-panel p,.hist-doc-panel small{margin:0;color:var(--muted,#667085);font-size:11px;line-height:1.5}.hist-doc-panel button{border:1px solid #f4741f;background:#f4741f;color:#fff;border-radius:11px;padding:10px 12px;font-weight:850;cursor:pointer}.hist-doc-panel button:disabled{opacity:.55;cursor:not-allowed}.hist-doc-status{display:flex;gap:9px;align-items:flex-start;border:1px solid var(--border,#ddd);border-radius:12px;padding:11px}.hist-doc-status strong,.hist-doc-status span{display:block}.hist-doc-status span{margin-top:3px;font-size:10.5px;line-height:1.45}.hist-doc-status[data-kind='critical']{border-color:#dc2626;background:rgba(220,38,38,.08)}.hist-doc-status[data-kind='warning'],.hist-doc-status[data-kind='unknown']{border-color:#eab308;background:rgba(234,179,8,.08)}.hist-doc-status[data-kind='ok']{border-color:#16a34a;background:rgba(22,163,74,.07)}.hist-doc-progress{font-size:10.5px;color:var(--muted,#667085)}.hist-doc-error{font-size:10.5px;color:#b91c1c}.hist-doc-fields{display:grid;gap:6px;border:1px solid var(--border,#ddd);border-radius:12px;padding:10px}.hist-doc-fields>strong{font-size:11px}.hist-doc-fields div{display:grid;grid-template-columns:1fr 1.25fr;gap:8px;font-size:10.5px}.hist-doc-fields span{color:var(--muted,#667085)}.hist-doc-fields b{word-break:break-word}`}</style></section>,host);
}
