import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {Activity,ChevronRight,X} from 'lucide-react';
import {useLocation} from 'react-router-dom';
import {fetchEnvironmentApi,supabase} from './supabase';

type Row=Record<string,unknown>;
type EventRow={at?:string;local_datetime?:string;local_time?:string;actor?:string;actor_code?:string;role?:string;entity_type?:string;entity_code?:string;action?:string;changed_fields?:unknown[];source?:string};
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;return Array.isArray(d.items)?d.items as Row[]:[];}
function first(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number')return String(v);}return'';}
function events(row:Row|null):EventRow[]{return row&&Array.isArray(row.activity)?row.activity as EventRow[]:[];}
function labelEntity(raw:string){const m:Record<string,string>={expedientes:'Expediente',expediente_stage:'Expediente',clientes:'Cliente',contactos_inmobiliaria:'Contacto inmobiliaria',contactos_bancarios:'Contacto bancario',bancos:'Banco',inmobiliarias:'Inmobiliaria',tareas:'Tarea',documentos:'Documento',documento:'Documento',tasaciones:'Tasación',firmas:'Firma',firma:'Firma',envios_banco:'Envío a banco',ofertas:'Oferta',economia:'Economía',special_cases:'Caso especial',special_case_people:'Interviniente',usuario:'Usuario'};return m[raw]||raw||'Actividad';}
function labelAction(raw:string){const x=raw.toLowerCase();if(x==='insert'||x==='create')return'Creado';if(x==='delete')return'Eliminado';if(x==='password_reset')return'Contraseña cambiada';if(x==='update')return'Actualizado';return raw||'Actividad';}
function fmtDate(e:EventRow){if(e.local_datetime)return e.local_datetime;const raw=e.at||'';if(!raw)return'';const d=new Date(raw);return Number.isNaN(d.getTime())?raw:new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'medium',timeZone:'Europe/Madrid'}).format(d);}
async function fetchReports(){return fetchEnvironmentApi<unknown>('fenix-reports-api','');}

export default function InformesDailyActivityGuard(){
 const location=useLocation();const active=location.pathname.replace(/\/+$/,'')==='/informes';
 const[logged,setLogged]=useState(false),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[selected,setSelected]=useState<Row|null>(null);
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive)setLogged(Boolean(data.session))});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setLogged(Boolean(s)));return()=>{alive=false;subscription.unsubscribe()};},[]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;fetchReports().then(r=>{if(!alive)return;setStatus(r.status);setRows(r.status===200?rowsFrom(r.data).filter(x=>first(x,['tipo','categoria'])==='Actividad diaria'):[])}).catch(()=>alive&&setStatus(0));return()=>{alive=false};},[active,logged]);
 const host=useMemo(()=>typeof document==='undefined'?null:document.querySelector('.informes-content'),[active,status,rows.length]);
 if(!active||!logged||status!==200||!host)return null;
 const latest=rows[0]||null;
 const content=<section data-testid="daily-activity-reports" style={{margin:'18px 0',border:'1px solid var(--border,#e5e7eb)',borderRadius:18,padding:16,background:'var(--surface,#fff)',display:'grid',gap:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><small style={{fontWeight:850,letterSpacing:'.08em',color:'#870064'}}>ACTIVIDAD DIARIA AUDITADA</small><h2 style={{margin:'5px 0 3px',fontSize:20}}>Informe diario</h2><p style={{margin:0,fontSize:12,color:'var(--muted,#667085)'}}>Carlos y Dirección ven toda la actividad de empresa. Financiero y Visitador reciben exclusivamente su propia actividad diaria.</p></div><strong>{latest?`${first(latest,['activity_count'])||'0'} movimientos hoy`:'Sin movimientos hoy'}</strong></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10}}>{rows.slice(0,30).map((r,i)=><button key={first(r,['id'])||String(i)} type="button" onClick={()=>setSelected(r)} style={{textAlign:'left',border:'1px solid var(--border,#e5e7eb)',borderRadius:14,padding:12,background:'transparent',color:'inherit',cursor:'pointer',display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><span><strong style={{display:'block'}}>{first(r,['titulo','title'])||'Informe diario'}</strong><small>{first(r,['activity_count'])||'0'} movimientos · {first(r,['status'])||'completado'}</small></span><ChevronRight size={17}/></button>)}</div><small style={{color:'var(--muted,#667085)'}}>Zona horaria Europe/Madrid · precisión de segundos. Los informes se actualizan automáticamente al registrarse nueva actividad auditada.</small></section>;
 return <>{createPortal(content,host)}{selected&&createPortal(<div role="dialog" aria-modal="true" aria-label="Detalle de informe diario" style={{position:'fixed',inset:0,zIndex:12000,background:'rgba(15,15,18,.58)',display:'grid',placeItems:'center',padding:18}}><section style={{width:'min(1000px,94vw)',maxHeight:'88vh',overflow:'auto',border:'1px solid var(--border,#ddd)',borderRadius:20,background:'var(--surface,#fff)',color:'var(--text,#171717)',padding:18,boxShadow:'0 28px 80px rgba(0,0,0,.25)'}}><header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start',marginBottom:14}}><div><small style={{color:'#870064',fontWeight:850}}>INFORME AUDITADO</small><h2 style={{margin:'4px 0'}}>{first(selected,['titulo'])||'Informe diario'}</h2><p style={{margin:0,fontSize:12,color:'var(--muted,#667085)'}}>{first(selected,['activity_count'])||'0'} movimientos registrados · {first(selected,['timezone'])||'Europe/Madrid'}</p></div><button type="button" aria-label="Cerrar informe" onClick={()=>setSelected(null)} style={{width:40,height:40,borderRadius:10,border:'1px solid var(--border,#ddd)',background:'transparent',color:'inherit',cursor:'pointer'}}><X size={18}/></button></header><div style={{display:'grid',gap:9}}>{events(selected).length===0?<div style={{padding:16,border:'1px solid var(--border,#ddd)',borderRadius:12}}>No hay actividad auditada para este día.</div>:events(selected).map((e,i)=><article key={`${e.at||''}-${e.entity_code||''}-${i}`} style={{display:'grid',gridTemplateColumns:'auto 1fr',gap:10,padding:12,border:'1px solid var(--border,#e5e7eb)',borderRadius:12}}><Activity size={17}/><div><strong>{labelAction(e.action||'')} · {labelEntity(e.entity_type||'')}</strong><div style={{fontSize:12,marginTop:3}}>{e.entity_code||'Sin identificador'} · {e.actor||e.actor_code||'Sistema/No identificado'}{e.role?` · ${e.role}`:''}</div><small style={{color:'var(--muted,#667085)'}}>{fmtDate(e)}{Array.isArray(e.changed_fields)&&e.changed_fields.length?` · Campos: ${e.changed_fields.join(', ')}`:''}</small></div></article>)}</div><footer style={{marginTop:14,fontSize:11,color:'var(--muted,#667085)'}}>{first(selected,['coverage'])}</footer></section></div>,document.body)}</>;
}
