import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Clock3,FileText} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchReportsRuntime} from './reportsRuntime';
import {anaAvatar,anaVertical} from './assets/visualAssets';
import {directionSidebarNavigation,normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import DirectionOperationalFrame from './DirectionOperationalFrame';
import './operational.css';
import './informes-shell.css';

type Theme='light'|'dark';
type Row=Record<string,unknown>;
type Ctx={role?:string;actor_code?:string;display_name?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of ['items','reports','informes','results'])if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number')return String(v);}return'';}
function arrayOfRows(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(Array.isArray(v))return v.filter(x=>x&&typeof x==='object') as Row[];}return[];}
function isDirectionContext(ctx:Ctx|null){const role=(ctx?.role||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return ctx?.actor_code==='DIR-TEST'||role.includes('direccion');}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]?.toUpperCase()).join('')||'FC';}
function eventTime(row:Row){const raw=first(row,['hora','time','event_time','occurred_at','created_at','fecha_hora']);if(!raw)return'';const d=new Date(raw.includes('T')?raw:raw.replace(' ','T'));if(Number.isNaN(d.getTime()))return raw;return new Intl.DateTimeFormat('es-ES',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Europe/Madrid'}).format(d);}
function eventText(row:Row){return first(row,['accion','acción','evento','event','descripcion','descripción','detalle','summary','title','titulo'])||'Actividad registrada';}
export default function InformesShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname.replace(/\/+$/,'')==='/informes';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);localStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setRows([]);try{const[c,n,r]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchReportsRuntime<unknown>()]);if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);setStatus(r.status);setRows(r.status===200?rowsFrom(r.data):[]);if(r.status===403)setMessage('Tu perfil no tiene acceso a Informes.');else if(r.status===0)setMessage('No se pudo conectar con la fuente autorizada de Informes.');else if(r.status!==200)setMessage('No se pudieron cargar los informes autorizados.');}catch{if(!alive)return;setStatus(0);setRows([]);setMessage('No se pudo conectar con la fuente autorizada de Informes.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,logged]);
 const direction=isDirectionContext(ctx);
 const effectiveNav=nav.length?(direction?directionSidebarNavigation(nav):nav):fallbackNav;
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));},[rows,query]);
 const grouped=useMemo(()=>{const m=new Map<string,Row[]>();for(const r of visible){const category=first(r,['categoria','categoría','category','tipo','periodicidad'])||'Sin categoría';m.set(category,[...(m.get(category)||[]),r]);}return [...m.entries()];},[visible]);
 const latest=useMemo(()=>visible.map(r=>first(r,['generado_en','fecha','created_at','fecha_generacion','fecha_generación'])).filter(Boolean).sort().reverse()[0]||'No disponible',[visible]);
 if(!active||!ready||!logged)return null;
 function openReport(r:Row){const url=first(r,['pdf_url','url','archivo_url','download_url']);if(/^https?:\/\//i.test(url))window.open(url,'_blank','noopener,noreferrer');}
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 const body=<>
  <section className="informes-ana-hero"><div className="informes-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="informes-ana-body"><span>ANA · EN ESTA PANTALLA</span><h2>Te ayudo a interpretar los informes</h2><p>Revisa actividad diaria y semanal de tu ámbito autorizado. Las correcciones y el conocimiento se centralizan en el micrófono global para no duplicar controles.</p></div></section>
  <div className="informes-title"><div><small>INFORMACIÓN Y SEGUIMIENTO</small><h1>Informes</h1><p>{loading?'Cargando informes autorizados…':status===200?'Actividad diaria y semanal disponible según tu ámbito.':'Lectura según permisos.'}</p></div><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos autorizados':'Sin datos'}</span></div>
  <section className="informes-kpis"><article><FileText/><small>TOTAL INFORMES</small><strong>{status===200&&!loading?visible.length:'—'}</strong><span>Disponibles en tu ámbito</span></article><article><FileText/><small>CATEGORÍAS</small><strong>{status===200&&!loading?grouped.length:'—'}</strong><span>Diarios, semanales y otros registros reales</span></article><article><FileText/><small>ÚLTIMA FECHA INFORMADA</small><strong className="informes-date">{status===200&&!loading?latest:'—'}</strong><span>Sin completar fechas ausentes</span></article></section>
  {loading&&<div className="ops-empty" data-testid="informes-loading"><strong>Cargando…</strong><span>Consultando la fuente autorizada de Informes.</span></div>}
  {!loading&&message&&<div className="ops-message" data-testid={status===403?'informes-forbidden':'informes-error'}>{message}</div>}
  {!loading&&status===200&&visible.length===0&&<div className="ops-empty" data-testid="informes-empty"><strong>Sin informes visibles</strong><span>No hay informes reales materializados en PROD dentro de tu ámbito. La pantalla permanece vacía en lugar de mostrar registros TEST.</span></div>}
  {!loading&&status===200&&visible.length>0&&<section className="informes-groups">{grouped.map(([category,items])=><article className="informes-group" key={category}><div className="informes-group-head"><FileText/><div><small>CATEGORÍA</small><h2>{category}</h2></div><span>{items.length}</span></div><div className="informes-list">{items.slice(0,12).map((r,i)=>{const title=first(r,['titulo','title','nombre','informe'])||'Informe sin título';const date=first(r,['generado_en','fecha','created_at','fecha_generacion','fecha_generación'])||'Fecha no disponible';const url=first(r,['pdf_url','url','archivo_url','download_url']);const hasUrl=/^https?:\/\//i.test(url);const events=arrayOfRows(r,['eventos','events','actividad','activity','acciones','actions','items']);return <div key={first(r,['id','report_id'])||`${title}-${i}`} style={{display:'grid',gap:8,padding:'12px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><span><strong>{title}</strong><small style={{display:'block'}}>{date}</small></span>{hasUrl&&<button onClick={()=>openReport(r)}>Abrir PDF →</button>}</div>{events.length>0&&<div style={{display:'grid',gap:6}}>{events.slice(0,30).map((ev,j)=><div key={j} style={{display:'grid',gridTemplateColumns:'90px 1fr',gap:10,alignItems:'start'}}><span style={{display:'inline-flex',gap:6,alignItems:'center'}}><Clock3 size={14}/>{eventTime(ev)||'—'}</span><span>{eventText(ev)}</span></div>)}</div>}{!hasUrl&&events.length===0&&<small>Registro estructurado sin PDF ni eventos visibles.</small>}</div>})}</div></article>)}</section>}
  <section className="informes-note"><img src={anaAvatar} alt="Ana"/><div><strong>Actividad auditable</strong><p>Los eventos muestran su hora cuando la fuente la aporta. No se inventan duraciones. Un informe estructurado puede consultarse aunque no exista PDF.</p></div></section>
 </>;
 if(direction){const profileName=ctx?.display_name||ctx?.role||'Usuario';return <DirectionOperationalFrame className="dir-shell informes-root informes-direction" theme={theme} navigation={effectiveNav} search={query} profileName={profileName} initials={initials(profileName)} onSearchChange={setQuery} onSearch={()=>{}} onNavigate={route=>navigate(route)} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} activeRoute="/informes" contentClassName="dir-content informes-content">{body}</DirectionOperationalFrame>}
 return <OperationalShellFrame className="informes-root" theme={theme} navigation={effectiveNav} activeRoute="/informes" anaSubtitle="Cuando quieras, avanzamos paso a paso." sidebarVariant="default" query={query} onQueryChange={setQuery} searchPlaceholder="Buscar informe, categoría o periodo..." searchActionLabel="Buscar" onSearchAction={()=>{}} name={ctx?.role||'Usuario'} role={ctx?.role||''} initials={(ctx?.role||'U').slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="informes-content">{body}</OperationalShellFrame>;
}
