import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Building2,Plus,Save,Trash2,Users,X} from 'lucide-react';
import {fetchAppApi,fetchB2BActionsApi,IS_PRODUCTION,SUPABASE_URL,supabase} from './supabase';
import {anaVertical} from './assets/visualAssets';
import type {NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';
type Ctx={actor_code?:string;role?:string};
type Assignee={actor_code:string;name:string;role:string};
type VisitadoresResponse={items?:Array<{actor_code?:string;nombre?:string;rol?:string}>};
type CreateResponse={ok?:boolean;id?:string;destino?:string;error?:string;existing_id?:string;reused?:boolean;no_op?:boolean;zone?:string|null};
type Staff={id:string;nombre:string;apellidos:string;cargo:string;telefonos:string[];emails:string[];principal:boolean};

const createNav:NavItem[]=[{label:'Volver a Inmobiliarias',route:'/inmobiliarias'}];
const blankStaff=():Staff=>({id:crypto.randomUUID(),nombre:'',apellidos:'',cargo:'',telefonos:[''],emails:[''],principal:false});
const changeAt=(items:string[],index:number,value:string)=>items.map((x,i)=>i===index?value:x);

async function createLegacyInmobiliaria(payload:Record<string,unknown>){const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return{status:401,data:null as CreateResponse|null};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-notion-actions-test/inmobiliarias/create`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});let data:CreateResponse|null=null;try{data=await r.json()}catch{}return{status:r.status,data};}
async function createInmobiliaria(role:string|undefined,payload:Record<string,unknown>){if(IS_PRODUCTION||role==='Visitador')return fetchB2BActionsApi<CreateResponse>('/inmobiliarias/create',{method:'POST',body:JSON.stringify(payload)});return createLegacyInmobiliaria(payload);}
async function createStaff(inmobiliariaId:string,p:Staff){const telefonos=p.telefonos.map(x=>x.trim()).filter(Boolean),emails=p.emails.map(x=>x.trim()).filter(Boolean);return fetchB2BActionsApi<CreateResponse>('/contactos/create',{method:'POST',body:JSON.stringify({inmobiliaria_id:inmobiliariaId,nombre:p.nombre.trim(),apellidos:p.apellidos.trim(),cargo:p.cargo.trim(),telefono:telefonos[0]||'',email:emails[0]||'',telefonos,emails,contacto_principal:p.principal})});}

export default function InmobiliariaCreateShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/inmobiliarias/nueva';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[assignees,setAssignees]=useState<Assignee[]>([]),[nombre,setNombre]=useState(''),[localidad,setLocalidad]=useState(''),[direccion,setDireccion]=useState(''),[emails,setEmails]=useState<string[]>(['']),[telefonos,setTelefonos]=useState<string[]>(['']),[target,setTarget]=useState(''),[query,setQuery]=useState('');
 const[staff,setStaff]=useState<Staff[]>([blankStaff()]);
 const[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<CreateResponse|null>(null);
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{const c=await fetchAppApi<Ctx>('/session/context');if(!alive)return;const context=c.status===200?c.data:null;setCtx(context);if(context?.role==='Visitador'){setTarget(context.actor_code||'');setAssignees([]);return;}if(context?.role!=='Direccion'){setTarget('');setAssignees([]);return;}const v=await fetchAppApi<VisitadoresResponse>('/visitadores');if(!alive)return;setAssignees((v.status===200?v.data?.items??[]:[]).flatMap(x=>x.actor_code?[{actor_code:x.actor_code,name:x.nombre?.trim()||x.actor_code,role:x.rol?.trim()||'Visitador'}]:[]).sort((a,b)=>a.name.localeCompare(b.name,'es')));})();return()=>{alive=false};},[active,logged]);
 const allowed=ctx?.role==='Direccion'||ctx?.role==='Visitador';
 const cleanPhones=telefonos.map(x=>x.trim()).filter(Boolean),cleanEmails=emails.map(x=>x.trim()).filter(Boolean);
 const payload=useMemo(()=>({inmobiliaria:nombre.trim(),localidad:localidad.trim(),direccion:direccion.trim(),email:cleanEmails[0]||'',telefono:cleanPhones[0]||'',emails:cleanEmails,telefonos:cleanPhones,id_visitador_operativo:target}),[nombre,localidad,direccion,emails,telefonos,target]);
 const validStaff=staff.filter(p=>p.nombre.trim().length>=2);const valid=allowed&&nombre.trim().length>=2;
 const missing=[!nombre.trim()?'nombre de la inmobiliaria':'',!localidad.trim()?'localidad':'',!direccion.trim()?'dirección':'',!cleanPhones.length&&!cleanEmails.length?'al menos un teléfono o email':''].filter(Boolean);
 const attention=missing.length?`Faltan ${missing.join(', ')}.`:validStaff.length===0?'La ficha base está completa. Puedes añadir ahora director, asesores y demás personal.':`Ficha base completa y ${validStaff.length} contacto${validStaff.length===1?'':'s'} preparado${validStaff.length===1?'':'s'} para vincular.`;
 const checking=!nombre.trim()?'Estoy comprobando que exista un nombre suficiente para identificarla y evitar duplicados.':validStaff.some(p=>!p.cargo.trim())?'Hay personal sin cargo indicado; conviene completarlo para saber a quién acudir.':'Estoy comprobando identidad, ubicación, vías de contacto, personal y responsable antes de guardar.';
 const nextStep=!nombre.trim()?'Empieza por el nombre oficial o comercial.':!localidad.trim()?'Añade la localidad.':!direccion.trim()?'Completa la dirección de la oficina.':validStaff.length===0?'Añade al menos el contacto principal si lo conoces.':'Revisa el resumen y confirma el alta.';
 if(!active||!ready||!logged)return null;
 function edit(){setPreview(false);setMessage('');setResult(null);}
 function focusField(id:string){document.getElementById(id)?.focus();}
 function updateStaff(id:string,patch:Partial<Staff>){setStaff(list=>list.map(p=>p.id===id?{...p,...patch}:p));edit();}
 function removeStaff(id:string){setStaff(list=>list.length===1?[blankStaff()]:list.filter(p=>p.id!==id));edit();}
 async function submit(e:FormEvent){e.preventDefault();if(!valid)return;if(!preview){setPreview(true);setMessage('');return;}setBusy(true);setMessage('');const r=await createInmobiliaria(ctx?.role,payload);setResult(r.data);if((r.status===201||r.status===200)&&r.data?.ok&&r.data.id){let created=0;let failed=0;for(const person of validStaff){const cr=await createStaff(r.data.id,person);if((cr.status===200||cr.status===201)&&cr.data?.ok)created++;else failed++;}setBusy(false);setMessage(`${r.data.reused?'La inmobiliaria ya existía y se ha reutilizado.':'Inmobiliaria creada correctamente.'}${validStaff.length?` Personal: ${created} creado/vinculado${failed?` y ${failed} pendiente de revisar`:''}.`:''}`);setPreview(false);return;}setBusy(false);if(r.status===409&&r.data?.error==='duplicate_inmobiliaria')setMessage('Ya existe una inmobiliaria coincidente. No se ha creado un duplicado.');else if(r.status===409&&r.data?.error==='zone_not_configured')setMessage('Tu perfil de Visitador no tiene zona operativa configurada.');else if(r.status===403)setMessage('Tu perfil no puede crear esta inmobiliaria o queda fuera de tu ámbito.');else setMessage(`No se pudo crear la inmobiliaria (${r.data?.error||r.status}).`);}
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 function search(){const q=query.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar');}
 return <OperationalShellFrame className="inmo-root inmo-create-root" theme={theme} navigation={createNav} activeRoute="/inmobiliarias" anaSubtitle="Te acompaño en el alta y revisamos juntos cualquier corrección." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar en toda la app..." searchActionLabel="Buscar" onSearchAction={search} name={ctx?.role||'Usuario'} role={ctx?.role||''} initials={(ctx?.role||'U').slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content">
   <div className="ops-title"><div><span className="ops-icon"><Building2 size={20}/></span><div><h1>Nueva inmobiliaria</h1><p>Datos de la empresa, personal vinculado y responsable operativo en una sola alta.</p></div></div></div>
   <section className="inmo-ana-hero" data-testid="inmobiliaria-create-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · NUEVA INMOBILIARIA</span><h2>Vamos a crearla completa desde el principio</h2><p>Te guío por la inmobiliaria y por las personas que trabajan en ella. Cada teléfono y correo puede repetirse tantas veces como haga falta.</p><div className="inmo-next"><button type="button" onClick={()=>focusField(!nombre.trim()?'inmo-name':!localidad.trim()?'inmo-locality':!direccion.trim()?'inmo-address':'staff-0-name')}><b>1</b><strong>Qué necesita atención</strong><small>{attention}</small></button><button type="button"><b>2</b><strong>Qué estoy comprobando</strong><small>{checking}</small></button><button type="button" onClick={()=>focusField(!nombre.trim()?'inmo-name':validStaff.length===0?'staff-0-name':'inmo-name')}><b>3</b><strong>Siguiente paso</strong><small>{nextStep}</small></button></div></div><article className="inmo-correct"><span>CONTROL ANTES DE GUARDAR</span><h3>Revisión guiada</h3><p>Ana no inventa personas ni cargos. Si conoces al director, gerente, asesor o cualquier otro trabajador, añádelo aquí y quedará relacionado con la inmobiliaria.</p><textarea readOnly rows={3} value={attention}/><input readOnly value={nextStep}/><button type="button" onClick={()=>setPreview(true)} disabled={!valid}>Revisar alta con Ana</button></article></section>
    {!allowed?<div className="ops-message">Tu perfil no puede crear inmobiliarias.</div>:<form className="ops-message" onSubmit={submit} style={{display:'grid',gap:16}}>
      <section className="directory-form-grid"><label>Inmobiliaria<input id="inmo-name" value={nombre} onChange={e=>{setNombre(e.target.value);edit()}} maxLength={200} required/></label><label>Localidad<input id="inmo-locality" value={localidad} onChange={e=>{setLocalidad(e.target.value);edit()}} maxLength={160}/></label><label>Dirección<input id="inmo-address" value={direccion} onChange={e=>{setDireccion(e.target.value);edit()}} maxLength={300}/></label><div className="multi-contact-group"><div className="multi-contact-head"><strong>Teléfonos generales</strong><button type="button" onClick={()=>{setTelefonos(v=>[...v,'']);edit()}}><Plus size={15}/> Añadir teléfono</button></div>{telefonos.map((v,i)=><label key={`tel-${i}`}>{i===0?'Teléfono general':`Teléfono general ${i+1}`}<span className="multi-contact-row"><input id={i===0?'inmo-phone':undefined} value={v} onChange={e=>{setTelefonos(x=>changeAt(x,i,e.target.value));edit()}} maxLength={40} inputMode="tel"/>{telefonos.length>1&&<button type="button" aria-label={`Quitar teléfono ${i+1}`} onClick={()=>{setTelefonos(x=>x.filter((_,j)=>j!==i));edit()}}><X size={15}/></button>}</span></label>)}</div><div className="multi-contact-group"><div className="multi-contact-head"><strong>Correos generales</strong><button type="button" onClick={()=>{setEmails(v=>[...v,'']);edit()}}><Plus size={15}/> Añadir correo</button></div>{emails.map((v,i)=><label key={`mail-${i}`}>{i===0?'Email general':`Email general ${i+1}`}<span className="multi-contact-row"><input id={i===0?'inmo-email':undefined} value={v} onChange={e=>{setEmails(x=>changeAt(x,i,e.target.value));edit()}} maxLength={200} type="email"/>{emails.length>1&&<button type="button" aria-label={`Quitar correo ${i+1}`} onClick={()=>{setEmails(x=>x.filter((_,j)=>j!==i));edit()}}><X size={15}/></button>}</span></label>)}</div>{ctx?.role==='Direccion'?<label>Visitador responsable<select value={target} onChange={e=>{setTarget(e.target.value);edit()}}><option value="">Sin asignar por ahora</option>{assignees.map(a=><option key={a.actor_code} value={a.actor_code}>{a.name}</option>)}</select><small>No se asigna sin elección explícita.</small></label>:<label>Visitador responsable<input aria-label="Visitador responsable" value={target||ctx?.actor_code||''} readOnly/></label>}</section>
      <details className="directory-people-panel" open><summary><span><Users size={18}/> Personal de la inmobiliaria</span><small>{validStaff.length} preparado{validStaff.length===1?'':'s'}</small></summary><p>Añade tantas personas como necesites: director, gerente, asesor, administración, etc. Cada persona puede tener varios teléfonos y correos.</p><div className="directory-people-list">{staff.map((p,i)=><article className="directory-person-card" key={p.id}><div className="directory-person-head"><strong>Contacto {i+1}</strong><button type="button" onClick={()=>removeStaff(p.id)} aria-label={`Quitar contacto ${i+1}`}><Trash2 size={15}/></button></div><div className="directory-person-grid"><label>Nombre<input id={`staff-${i}-name`} value={p.nombre} onChange={e=>updateStaff(p.id,{nombre:e.target.value})}/></label><label>Apellidos<input value={p.apellidos} onChange={e=>updateStaff(p.id,{apellidos:e.target.value})}/></label><label>Cargo<input value={p.cargo} onChange={e=>updateStaff(p.id,{cargo:e.target.value})} placeholder="Director, asesor, gerente..."/></label><div className="multi-contact-group"><div className="multi-contact-head"><strong>Teléfonos</strong><button type="button" onClick={()=>updateStaff(p.id,{telefonos:[...p.telefonos,'']})}><Plus size={14}/></button></div>{p.telefonos.map((v,j)=><label key={j}>Teléfono {j+1}<span className="multi-contact-row"><input value={v} onChange={e=>updateStaff(p.id,{telefonos:changeAt(p.telefonos,j,e.target.value)})} inputMode="tel"/>{p.telefonos.length>1&&<button type="button" onClick={()=>updateStaff(p.id,{telefonos:p.telefonos.filter((_,k)=>k!==j)})}><X size={14}/></button>}</span></label>)}</div><div className="multi-contact-group"><div className="multi-contact-head"><strong>Correos</strong><button type="button" onClick={()=>updateStaff(p.id,{emails:[...p.emails,'']})}><Plus size={14}/></button></div>{p.emails.map((v,j)=><label key={j}>Correo {j+1}<span className="multi-contact-row"><input value={v} onChange={e=>updateStaff(p.id,{emails:changeAt(p.emails,j,e.target.value)})} type="email"/>{p.emails.length>1&&<button type="button" onClick={()=>updateStaff(p.id,{emails:p.emails.filter((_,k)=>k!==j)})}><X size={14}/></button>}</span></label>)}</div><label className="directory-check"><input type="checkbox" checked={p.principal} onChange={e=>updateStaff(p.id,{principal:e.target.checked})}/> Contacto principal</label></div></article>)}</div><button type="button" className="directory-add-person" onClick={()=>{setStaff(list=>[...list,blankStaff()]);edit()}}><Plus size={16}/> Añadir otra persona</button></details>
      {preview&&<div className="ops-message"><strong>Vista previa</strong><div>Inmobiliaria: {nombre.trim()}</div><div>Localidad: {localidad.trim()||'No indicada'}</div><div>Dirección: {direccion.trim()||'No indicada'}</div><div>Teléfonos: {cleanPhones.join(' · ')||'No indicados'}</div><div>Correos: {cleanEmails.join(' · ')||'No indicados'}</div><div>Personal a crear/vincular: {validStaff.length}</div><div>Visitador: {assignees.find(a=>a.actor_code===target)?.name||target||'Sin asignar'}</div><small>Confirma para crear la ficha y, después, cada contacto relacionado.</small></div>}
      {message&&<div className="ops-message">{message}</div>}
      {!result?.ok&&result?.error!=='duplicate_inmobiliaria'&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{preview&&<button type="button" onClick={()=>setPreview(false)}>Volver</button>}<button className="primary" disabled={!valid||busy}><Save size={16}/>{busy?'Creando y vinculando…':preview?'Confirmar y crear':'Revisar antes de crear'}</button></div>}
      {(result?.ok||result?.error==='duplicate_inmobiliaria')&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" onClick={()=>navigate('/inmobiliarias')}>Volver a Inmobiliarias</button>{result.destino&&<button type="button" className="primary" onClick={()=>navigate(result.destino!)}>{result.reused||result.error==='duplicate_inmobiliaria'?'Abrir inmobiliaria existente':'Abrir inmobiliaria creada'}</button>}</div>}
    </form>}
 </OperationalShellFrame>;
}