import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Building2,LogOut,Moon,Save,Sun} from 'lucide-react';
import {fetchAppApi,fetchB2BActionsApi,SUPABASE_URL,supabase} from './supabase';
import {anaVertical} from './assets/visualAssets';
import type {NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';
type Ctx={actor_code?:string;role?:string};
type Assignee={actor_code:string;name:string;role:string};
type VisitadoresResponse={items?:Array<{actor_code?:string;nombre?:string;rol?:string}>};
type CreateResponse={ok?:boolean;id?:string;destino?:string;error?:string;existing_id?:string;reused?:boolean;no_op?:boolean;zone?:string|null};

const createNav:NavItem[]=[{label:'Volver a Inmobiliarias',route:'/inmobiliarias'}];

async function createLegacyInmobiliaria(payload:Record<string,unknown>){const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return{status:401,data:null as CreateResponse|null};const r=await fetch(`${SUPABASE_URL}/functions/v1/fenix-notion-actions-test/inmobiliarias/create`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(payload)});let data:CreateResponse|null=null;try{data=await r.json()}catch{}return{status:r.status,data};}
async function createInmobiliaria(role:string|undefined,payload:Record<string,unknown>){if(role==='Visitador')return fetchB2BActionsApi<CreateResponse>('/inmobiliarias/create',{method:'POST',body:JSON.stringify(payload)});return createLegacyInmobiliaria(payload);}

export default function InmobiliariaCreateShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/inmobiliarias/nueva';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[assignees,setAssignees]=useState<Assignee[]>([]),[nombre,setNombre]=useState(''),[localidad,setLocalidad]=useState(''),[direccion,setDireccion]=useState(''),[email,setEmail]=useState(''),[telefono,setTelefono]=useState(''),[target,setTarget]=useState('');
 const[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<CreateResponse|null>(null);
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{const c=await fetchAppApi<Ctx>('/session/context');if(!alive)return;const context=c.status===200?c.data:null;setCtx(context);if(context?.role==='Visitador'){setTarget(context.actor_code||'');setAssignees([]);return;}if(context?.role!=='Direccion'){setTarget('');setAssignees([]);return;}const v=await fetchAppApi<VisitadoresResponse>('/visitadores');if(!alive)return;setAssignees((v.status===200?v.data?.items??[]:[]).flatMap(x=>x.actor_code?[{actor_code:x.actor_code,name:x.nombre?.trim()||x.actor_code,role:x.rol?.trim()||'Visitador'}]:[]).sort((a,b)=>a.name.localeCompare(b.name,'es')));})();return()=>{alive=false};},[active,logged]);
 const allowed=ctx?.role==='Direccion'||ctx?.role==='Visitador';const payload=useMemo(()=>({inmobiliaria:nombre.trim(),localidad:localidad.trim(),direccion:direccion.trim(),email:email.trim(),telefono:telefono.trim(),id_visitador_operativo:target}),[nombre,localidad,direccion,email,telefono,target]);const valid=allowed&&nombre.trim().length>=2;
 const missing=[!nombre.trim()?'nombre de la inmobiliaria':'',!localidad.trim()?'localidad':'',!direccion.trim()?'dirección':'',!telefono.trim()&&!email.trim()?'al menos un teléfono o email':''].filter(Boolean);
 const attention=missing.length?`Faltan ${missing.join(', ')}.`:'Los datos básicos están completos para revisar el alta.';
 const mistake=!nombre.trim()?'Sin nombre no puedo comprobar duplicados ni crear la ficha.':(!telefono.trim()&&!email.trim())?'Podrías crearla sin contacto, pero luego será más difícil detectar duplicados y coordinarla.':'No detecto un error evidente en los datos básicos. Antes de confirmar, revisa que nombre, localidad y contacto sean exactos.';
 const nextStep=!nombre.trim()?'Empieza por el nombre oficial o comercial.':!localidad.trim()?'Añade la localidad para identificar bien la inmobiliaria.':!direccion.trim()?'Completa la dirección de la oficina.':(!telefono.trim()&&!email.trim())?'Añade un teléfono o email de contacto.':'Revisa el resumen y confirma solo cuando todo sea correcto.';
 if(!active||!ready||!logged)return null;
 function edit(){setPreview(false);setMessage('');setResult(null);}
 function focusField(id:string){document.getElementById(id)?.focus();}
 async function submit(e:FormEvent){e.preventDefault();if(!valid)return;if(!preview){setPreview(true);setMessage('');return;}setBusy(true);setMessage('');const r=await createInmobiliaria(ctx?.role,payload);setBusy(false);setResult(r.data);if((r.status===201||r.status===200)&&r.data?.ok){setMessage(r.data?.reused?'La inmobiliaria ya existía: no se ha duplicado.':'Inmobiliaria creada y auditada.');setPreview(false);}else if(r.status===409&&r.data?.error==='duplicate_inmobiliaria'){setMessage('Ya existe una inmobiliaria coincidente. No se ha creado un duplicado.');setPreview(false);}else if(r.status===409&&r.data?.error==='zone_not_configured'){setMessage('Tu perfil de Visitador no tiene zona operativa configurada. La creación queda bloqueada.');setPreview(false);}else if(r.status===403)setMessage('Tu perfil no puede crear esta inmobiliaria o queda fuera de tu ámbito.');else setMessage(`No se pudo crear la inmobiliaria (${r.data?.error||r.status}).`);}
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 const topbar=<header className="ops-top"><strong>Nueva inmobiliaria</strong><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Cambiar tema">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{ctx?.role||'Usuario'}</strong></div><button onClick={logout} aria-label="Cerrar sesión"><LogOut size={17}/></button></div></header>;
 return <OperationalShellFrame className="inmo-root inmo-create-root" theme={theme} navigation={createNav} activeRoute="" anaSubtitle="Te guío paso a paso para que la ficha nazca completa y sin duplicados." query="" onQueryChange={()=>{}} searchPlaceholder="" name={ctx?.role||'Usuario'} role="" initials={(ctx?.role||'U').slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} topbar={topbar} contentClassName="inmo-content">
   <section className="inmo-ana-hero" data-testid="inmobiliaria-create-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · NUEVA INMOBILIARIA</span><h2>Vamos a crearla bien desde el principio</h2><p>Te voy guiando por identidad de la inmobiliaria, ubicación, contacto y responsable. Después completaremos en esta misma ficha sus contactos internos, documentación y condiciones económicas.</p><div className="inmo-next"><button type="button" onClick={()=>focusField(!nombre.trim()?'inmo-name':!localidad.trim()?'inmo-locality':!direccion.trim()?'inmo-address':'inmo-phone')}><b>1</b><strong>Qué necesita atención</strong><small>{attention}</small></button><button type="button" onClick={()=>setPreview(false)}><b>2</b><strong>En qué me puedo equivocar</strong><small>{mistake}</small></button><button type="button" onClick={()=>focusField(!nombre.trim()?'inmo-name':!localidad.trim()?'inmo-locality':!direccion.trim()?'inmo-address':(!telefono.trim()&&!email.trim())?'inmo-phone':'inmo-name')}><b>3</b><strong>Siguiente paso</strong><small>{nextStep}</small></button></div></div><article className="inmo-correct"><span>CONTROL ANTES DE GUARDAR</span><h3>Ana no completa datos por su cuenta</h3><p>Si falta un dato importante, lo marco para que lo revises. El sistema tampoco asigna un visitador por intuición ni duplica una inmobiliaria conocida.</p><textarea readOnly rows={3} value={attention}/><input readOnly value={nextStep}/><button type="button" onClick={()=>setPreview(true)} disabled={!valid}>Revisar alta con Ana</button></article></section>
   <div className="ops-title"><div><span className="ops-icon"><Building2 size={20}/></span><div><h1>Nueva inmobiliaria</h1><p>Primero creamos la ficha base. Después añadiremos contactos, documentos y condiciones económicas sin salir de la inmobiliaria.</p></div></div><span className="ops-live ok">Alta guiada</span></div>
    {!allowed?<div className="ops-message">Tu perfil no puede crear inmobiliarias.</div>:<form className="ops-message" onSubmit={submit} style={{display:'grid',gap:12}}>
      <label>Inmobiliaria<input id="inmo-name" value={nombre} onChange={e=>{setNombre(e.target.value);edit()}} maxLength={200} required/></label><label>Localidad<input id="inmo-locality" value={localidad} onChange={e=>{setLocalidad(e.target.value);edit()}} maxLength={160}/></label><label>Dirección<input id="inmo-address" value={direccion} onChange={e=>{setDireccion(e.target.value);edit()}} maxLength={300}/></label><label>Teléfono<input id="inmo-phone" value={telefono} onChange={e=>{setTelefono(e.target.value);edit()}} maxLength={40} inputMode="tel"/></label><label>Email<input id="inmo-email" value={email} onChange={e=>{setEmail(e.target.value);edit()}} maxLength={200} type="email"/></label>
      {ctx?.role==='Direccion'?<label>Visitador responsable<select value={target} onChange={e=>{setTarget(e.target.value);edit()}}><option value="">En Belén / sin asignar por ahora</option>{assignees.map(a=><option key={a.actor_code} value={a.actor_code}>{a.name}</option>)}</select><small>No se asigna visitador sin elección explícita.</small></label>:<label>Visitador responsable<input aria-label="Visitador responsable" value={target||ctx?.actor_code||''} readOnly/></label>}
      {preview&&<div className="ops-message"><strong>Vista previa</strong><div>Inmobiliaria: {nombre.trim()}</div><div>Localidad: {localidad.trim()||'No indicada'}</div><div>Dirección: {direccion.trim()||'No indicada'}</div><div>Teléfono: {telefono.trim()||'No indicado'}</div><div>Email: {email.trim()||'No indicado'}</div><div>Visitador: {assignees.find(a=>a.actor_code===target)?.name||target||'En Belén / sin asignar'}</div><div>Estado inicial: Sin revisar</div><small>Confirma para crear exactamente este registro B2B.</small></div>}
      {message&&<div className="ops-message">{message}</div>}
      {!result?.ok&&result?.error!=='duplicate_inmobiliaria'&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{preview&&<button type="button" onClick={()=>setPreview(false)}>Volver</button>}<button className="primary" disabled={!valid||busy}><Save size={16}/>{busy?'Creando…':preview?'Confirmar y crear':'Revisar antes de crear'}</button></div>}
      {(result?.ok||result?.error==='duplicate_inmobiliaria')&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" onClick={()=>navigate('/inmobiliarias')}>Volver a Inmobiliarias</button>{result.destino&&<button type="button" className="primary" onClick={()=>navigate(result.destino!)}>{result.reused||result.error==='duplicate_inmobiliaria'?'Abrir inmobiliaria existente':'Abrir inmobiliaria creada'}</button>}</div>}
    </form>}
 </OperationalShellFrame>;
}
