import {useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {Building2,FolderOpen,MapPin,Users} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './inmobiliaria-detail.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';type Ctx={role?:string;display_name?:string};type Row=Record<string,unknown>;
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function text(row:Row|null,keys:string[]){if(!row)return'';for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim()}return''}
function num(v:unknown){return typeof v==='number'?v:Number(v)||0}

export default function InmobiliariaDetailShell(){
 const location=useLocation(),navigate=useNavigate();const match=location.pathname.match(/^\/inmobiliarias\/([^/]+)$/);const id=match?.[1]?decodeURIComponent(match[1]):'';const active=Boolean(match&&id&&id!=='nueva');
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[query,setQuery]=useState('');
 const[status,setStatus]=useState<number|null>(null),[row,setRow]=useState<Row|null>(null),[stats,setStats]=useState<Row>({}),[expedientes,setExpedientes]=useState<Row[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()}},[active]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[])});return()=>{alive=false}},[active,logged]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');const r=await fetchNotionRuntime<any>(`/inmobiliarias/${encodeURIComponent(id)}`);if(!alive)return;setStatus(r.status);setRow(r.status===200?(r.data?.item||null):null);setStats(r.status===200&&r.data?.stats&&typeof r.data.stats==='object'?r.data.stats:{});setExpedientes(r.status===200&&Array.isArray(r.data?.expedientes)?r.data.expedientes:[]);if(r.status===403)setMessage('Tu perfil no puede abrir esta inmobiliaria.');else if(r.status===404)setMessage('No se ha encontrado la inmobiliaria.');else if(r.status!==200)setMessage('No se pudo cargar la inmobiliaria.');setLoading(false)})();return()=>{alive=false}},[active,logged,id]);
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}
 function search(){const q=query.trim();navigate(q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar')}
 const name=text(row,['inmobiliaria','nombre','nombre_alias','nombre_comercial'])||'Inmobiliaria';const locality=text(row,['localidad','municipio','provincia'])||'Sin localidad';const zone=text(row,['zona_operativa','zone_code','zona'])||'Sin zona';const state=text(row,['estado','estado_comercial'])||'Sin estado';const effectiveNav=nav.length?nav:fallbackNav;const displayName=ctx?.display_name||ctx?.role||'Usuario';
 return <OperationalShellFrame className="inmo-detail-root" theme={theme} navigation={effectiveNav} activeRoute="/inmobiliarias" anaSubtitle="Te acompaño en cada seguimiento B2B." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar inmobiliaria, contacto o expediente..." searchActionLabel="Buscar" onSearchAction={search} name={displayName} role={ctx?.role||''} initials={displayName.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content">
  <section className="inmo-ana-hero" data-testid="inmo-detail-ana"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · FICHA DE INMOBILIARIA</span><h2>Relación, expedientes y siguiente paso en una sola vista</h2><p>La ficha mantiene disponible el menú completo y el contexto de la colaboración mientras trabajas.</p><div className="inmo-next"><button onClick={()=>navigate(`/expedientes?inmobiliaria=${encodeURIComponent(id)}`)}><b>1</b><strong>Ver expedientes</strong><small>{expedientes.length} vinculados →</small></button><button onClick={()=>navigate(`/contactos?inmobiliaria=${encodeURIComponent(id)}`)}><b>2</b><strong>Ver contactos</strong><small>Abrir contactos →</small></button><button onClick={()=>navigate(`/agenda?inmobiliaria=${encodeURIComponent(id)}`)}><b>3</b><strong>Crear seguimiento</strong><small>Abrir Agenda →</small></button></div></div></section>
  <div className="ops-title"><div><span className="ops-icon"><Building2 size={20}/></span><div><h1>{name}</h1><p>{locality} · {zone}</p></div></div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos actualizados':'Sin conexión'}</span></div>
  {loading&&<div className="ops-empty"><strong>Cargando ficha…</strong></div>}{message&&<div className="ops-message">{message}</div>}
  {status===200&&row&&<><section className="inmo-kpis"><article><Building2/><small>ESTADO</small><strong>{state}</strong><span>Situación comercial</span></article><article><MapPin/><small>LOCALIDAD</small><strong>{locality}</strong><span>{zone}</span></article><article><FolderOpen/><small>EXPEDIENTES</small><strong>{num(stats.expedientes_total)||expedientes.length}</strong><span>Vinculados</span></article><article><Users/><small>FIRMADOS</small><strong>{num(stats.firmados)}</strong><span>Expedientes firmados</span></article></section><section className="ops-table-card" style={{padding:20,display:'grid',gap:12}}><div className="ops-table-head"><strong>Ficha canónica</strong><span>Inmobiliaria autorizada</span></div>{Object.entries(row).filter(([k])=>!['id'].includes(k)).map(([k,v])=><div key={k} style={{display:'grid',gridTemplateColumns:'minmax(150px,220px) 1fr',gap:12}}><small>{k.replaceAll('_',' ')}</small><strong>{v===null||v===undefined||v===''?'—':String(v)}</strong></div>)}</section>{expedientes.length>0&&<section className="ops-table-card"><div className="ops-table-head"><strong>Expedientes vinculados</strong><span>{expedientes.length}</span></div><div className="ops-table-wrap"><table><thead><tr><th>Expediente</th><th>Cliente</th><th>Fase</th><th></th></tr></thead><tbody>{expedientes.map((e,i)=>{const code=text(e,['expediente_code','expediente']);return <tr key={code||i}><td>{code||'—'}</td><td>{text(e,['cliente_alias','cliente'])||'—'}</td><td>{text(e,['stage','fase'])||'—'}</td><td>{code&&<button onClick={()=>navigate(`/expedientes/${encodeURIComponent(code)}`)}>Abrir →</button>}</td></tr>})}</tbody></table></div></section>}</>}
 </OperationalShellFrame>
}
