import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {fetchAnaCanonicalApi,fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {anaVertical} from './assets/visualAssets';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './inmobiliarias-polish.css';
import './sortable-table.css';

type Theme='light'|'dark';
type Ctx={actor_code?:string;role?:string};
type Row=Record<string,unknown>;
type SortKey='nombre'|'localidad'|'estado'|'control';
type SortDir='asc'|'desc';
type CanonicalRule={id:string;domain:string;rule:string;source:string;confidence:number;exception:boolean;test:boolean;approved:boolean;state:string;date:string};
type CanonicalEnvelope={ok?:boolean;items?:CanonicalRule[];domain?:string;canonical_only?:boolean};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;return Array.isArray(d.items)?d.items as Row[]:[];}
function text(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function idOf(r:Row){return text(r,['id','inmobiliaria_id','inmobiliaria_code','code','codigo']);}
function nameOf(r:Row){return text(r,['inmobiliaria','nombre','nombre_comercial','title'])||'Inmobiliaria sin nombre';}
function localityOf(r:Row){return text(r,['localidad','municipio','ciudad','poblacion','población','provincia'])||'Sin localidad';}
function stateOf(r:Row){return text(r,['estado','estado_colaboracion','estado_colaboración','estado_comercial'])||'Sin estado';}
function controlOf(r:Row){return text(r,['proximo_contacto_b2b','próximo_contacto_b2b','proxima_accion','próxima_acción','ultimo_resultado_contacto_b2b','último_contacto'])||'—';}
function isActive(r:Row){return /activ|colabor|formaliz/i.test(stateOf(r));}
function inProcess(r:Row){return /proceso|seguimiento|contact|pendiente|negoci/i.test(stateOf(r));}
function explicitNeverCalled(r:Row){const s=`${stateOf(r)} ${text(r,['ultimo_contacto','último_contacto','ultimo_resultado_contacto_b2b'])}`;return /sin llamar|no contact|pendiente primer|nunca contact/i.test(s);}
function businessStateRank(value:string){const s=value.toLocaleLowerCase('es');if(/activ|colabor|formaliz/.test(s))return 0;if(/proceso|seguimiento|contact|pendiente|negoci/.test(s))return 1;if(/enfri|fr[ií]a|pausa/.test(s))return 2;if(/inactiv|cerrad|descart|baja/.test(s))return 3;return 4;}
function compareText(a:string,b:string){return a.localeCompare(b,'es',{sensitivity:'base',numeric:true});}

export default function InmobiliariasShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/inmobiliarias';
 const[sessionReady,setSessionReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const[canonicalRules,setCanonicalRules]=useState<CanonicalRule[]>([]);
 const[query,setQuery]=useState(''),[state,setState]=useState(''),[locality,setLocality]=useState(''),[sortKey,setSortKey]=useState<SortKey>('nombre'),[sortDir,setSortDir]=useState<SortDir>('asc');const[correction,setCorrection]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setSessionReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setSessionReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);});},[active,logged]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;fetchAnaCanonicalApi<CanonicalEnvelope>('/rules?domain=Inmobiliarias%20B2B').then(r=>{if(alive)setCanonicalRules(r.status===200?(r.data?.items??[]):[])});return()=>{alive=false}},[active,logged]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setStatus(null);setRows([]);setMessage('');const r=await fetchNotionRuntime<unknown>('/inmobiliarias');if(!alive)return;setStatus(r.status);setRows(r.status===200?rowsFrom(r.data):[]);if(r.status===403)setMessage('Tu perfil no tiene acceso a este módulo o registro.');else if(r.status!==200)setMessage('No se pudo leer la información actualizada de Inmobiliarias.');setLoading(false);})();return()=>{alive=false}},[active,logged]);
 const effectiveNav=nav.length?nav:fallbackNav;
 const states=useMemo(()=>Array.from(new Set(rows.map(stateOf).filter(Boolean))).sort((a,b)=>{const rank=businessStateRank(a)-businessStateRank(b);return rank||compareText(a,b)}),[rows]);
 const localities=useMemo(()=>Array.from(new Set(rows.map(localityOf).filter(Boolean))).sort(compareText),[rows]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();const out=rows.filter(r=>{const hay=Object.values(r).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase();return(!q||hay.includes(q))&&(!state||stateOf(r)===state)&&(!locality||localityOf(r)===locality)});const direction=sortDir==='asc'?1:-1;return[...out].sort((a,b)=>{let result=0;if(sortKey==='localidad')result=compareText(localityOf(a),localityOf(b));else if(sortKey==='estado'){result=businessStateRank(stateOf(a))-businessStateRank(stateOf(b));if(result===0)result=compareText(stateOf(a),stateOf(b));}else if(sortKey==='control')result=compareText(controlOf(a),controlOf(b));else result=compareText(nameOf(a),nameOf(b));if(result===0)result=compareText(nameOf(a),nameOf(b));return result*direction;});},[rows,query,state,locality,sortKey,sortDir]);
 const activeCount=useMemo(()=>rows.filter(isActive).length,[rows]),processCount=useMemo(()=>rows.filter(inProcess).length,[rows]),neverCount=useMemo(()=>rows.filter(explicitNeverCalled).length,[rows]);
 const localityRank=useMemo(()=>{const m=new Map<string,number>();rows.forEach(r=>{const l=localityOf(r);m.set(l,(m.get(l)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[rows]);
 const stateRank=useMemo(()=>{const m=new Map<string,number>();rows.forEach(r=>{const s=stateOf(r);m.set(s,(m.get(s)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[rows]);
 const localityMax=useMemo(()=>Math.max(1,...localityRank.map(([,n])=>n)),[localityRank]);
 const stateMax=useMemo(()=>Math.max(1,...stateRank.map(([,n])=>n)),[stateRank]);
 const anaSummary=useMemo(()=>{
  let base:string;
  if(loading)base='Ahora mismo estoy leyendo la cartera autorizada para no darte una recomendación con datos incompletos.';
  else if(status!==200)base='No tengo información suficiente de esta cartera. No voy a inventar una prioridad.';
  else if(rows.length===0)base='No hay inmobiliarias visibles en tu ámbito actual, así que no hay una prioridad comercial que pueda justificar.';
  else{const top=localityRank[0];if(neverCount>0)base=`Hay ${neverCount} inmobiliarias con señal explícita de primer contacto pendiente. Empezaría por revisar esas antes de abrir nuevos seguimientos${top?`; ${top[0]} concentra ${top[1]} registros visibles`:''}.`;else if(processCount>0)base=`Hay ${processCount} inmobiliarias en proceso o seguimiento y ${activeCount} activas. Priorizaría las que ya tienen una relación abierta antes de dispersar actividad${top?`; la mayor concentración visible está en ${top[0]} con ${top[1]} registros`:''}.`;else base=`Veo ${rows.length} inmobiliarias en tu ámbito, de las que ${activeCount} aparecen activas. No detecto una señal explícita de primer contacto pendiente; revisaría la distribución por estado antes de decidir la siguiente acción.`;}
  const rule=canonicalRules[0];return rule?`${base} Criterio aprendido por Ana: ${rule.rule}`:base;
 },[loading,status,rows.length,localityRank,neverCount,processCount,activeCount,canonicalRules]);
 if(!active||!sessionReady||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 function prepareCorrection(){if(!correction.trim()||!reason.trim())return;const q=new URLSearchParams({mode:'help',resource:'inmobiliaria',correction:correction.trim(),reason:reason.trim()});navigate(`/ana?${q.toString()}`);}
 function applySort(key:SortKey){if(sortKey===key)setSortDir(v=>v==='asc'?'desc':'asc');else{setSortKey(key);setSortDir('asc');}}
 function sortArrow(key:SortKey){return sortKey===key?(sortDir==='asc'?'↑':'↓'):'';}
 function ariaSort(key:SortKey){return sortKey===key?(sortDir==='asc'?'ascending':'descending'):undefined;}
 const role=ctx?.role||'Usuario';
 return <OperationalShellFrame className="inmo-root" theme={theme} navigation={effectiveNav} activeRoute="/inmobiliarias" anaSubtitle="Cuando quieras, avanzamos paso a paso." query={query} onQueryChange={setQuery} searchPlaceholder="Buscar inmobiliaria, localidad o seguimiento..." name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content">
    <section className="inmo-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · LECTURA VIVA DE INMOBILIARIAS</span><h2>Esto es lo que veo ahora</h2><p data-testid="inmo-ana-live-summary">{anaSummary}</p><div className="inmo-next"><button onClick={()=>{setSortKey('estado');setSortDir('asc')}}><b>1</b><strong>Priorizar seguimientos</strong><small>Ver y preparar →</small></button><button onClick={()=>setState(states.find(s=>/activ|colabor/i.test(s))||'')}><b>2</b><strong>Revisar colaboradoras</strong><small>Ver y preparar →</small></button><button onClick={()=>navigate('/ana?mode=help&resource=inmobiliaria')}><b>3</b><strong>Comprobar condiciones</strong><small>Ver y preparar →</small></button></div></div><article className="inmo-correct"><span>CORREGIR A ANA</span><h3>¿En qué me equivoco?</h3><p>Preparo tu corrección con este contexto para revisión; no modifica criterios automáticamente.</p><textarea rows={3} value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="Qué cambiarías..."/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo de la corrección"/><button disabled={!correction.trim()||!reason.trim()} onClick={prepareCorrection}>Preparar para revisión</button></article></section>
    <div className="inmo-title"><div><small>COLABORACIÓN B2B</small><h1>Inmobiliarias</h1><p>{status===200?`${rows.length} inmobiliarias visibles en tu ámbito autorizado.`:'Información disponible según tus permisos.'}</p></div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos vivos':'Sin conexión'}</span></div>
    {loading?<div className="ops-empty" data-testid="inmo-loading"><strong>Cargando inmobiliarias…</strong><span>Consultando la información autorizada.</span></div>:message?<div className="ops-message" data-testid={status===403?'inmo-forbidden':'inmo-error'}>{message}</div>:null}
    {!loading&&status===200&&<><section className="inmo-kpis"><article><small>EN FUENTE</small><strong>{rows.length}</strong><span>Registros visibles</span></article><article><small>ACTIVAS</small><strong>{activeCount}</strong><span>Derivado del estado visible</span></article><article><small>EN PROCESO</small><strong>{processCount}</strong><span>Derivado del estado visible</span></article><article><small>SIN LLAMAR</small><strong>{neverCount}</strong><span>Solo señal explícita disponible</span></article></section>
     <section className="inmo-insights inmo-live-charts"><article><span>RANKING POR LOCALIDAD</span><h2>Presencia visible</h2><div className="inmo-bars" data-testid="inmo-locality-chart">{localityRank.map(([l,n])=><div className="inmo-bar-row" key={l}><div className="inmo-bar-label"><strong>{l}</strong><span>{n}</span></div><div className="inmo-bar-track"><i style={{width:`${Math.max(8,(n/localityMax)*100)}%`}}/></div></div>)}</div></article><article><span>DISTRIBUCIÓN POR ESTADO</span><h2>Situación comercial</h2><div className="inmo-bars" data-testid="inmo-state-chart">{stateRank.map(([s,n])=><button className="inmo-bar-row inmo-bar-button" key={s} onClick={()=>setState(s)}><div className="inmo-bar-label"><strong>{s}</strong><span>{n}</span></div><div className="inmo-bar-track"><i style={{width:`${Math.max(8,(n/stateMax)*100)}%`}}/></div></button>)}</div></article></section>
     <section className="inmo-filter"><div className="inmo-filter-head"><div><small>CARTERA B2B</small><h2>Inmobiliarias disponibles</h2></div><span>{visible.length} visibles</span></div><label>BUSCAR<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o dato relacionado"/></label><div className="inmo-filter-grid"><label>ESTADO<select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos</option>{states.map(v=><option key={v}>{v}</option>)}</select></label><label>LOCALIDAD<select value={locality} onChange={e=>setLocality(e.target.value)}><option value="">Todas</option>{localities.map(v=><option key={v}>{v}</option>)}</select></label><label>ORDENAR POR<select value={sortKey} onChange={e=>{setSortKey(e.target.value as SortKey);setSortDir('asc')}}><option value="nombre">Nombre</option><option value="localidad">Localidad</option><option value="estado">Estado</option><option value="control">Control</option></select></label><button onClick={()=>{setQuery('');setState('');setLocality('');setSortKey('nombre');setSortDir('asc')}}>Limpiar</button></div></section>
     {visible.length===0?<div className="ops-empty" data-testid="inmo-empty"><strong>Sin inmobiliarias visibles</strong><span>No hay registros para estos filtros o para tu ámbito actual.</span></div>:<div className="ops-table-card inmo-table"><div className="ops-table-head"><strong>{visible.length} registros</strong><span>Datos de Inmobiliarias</span></div><div className="ops-table-wrap ops-sortable-scroll"><table className="ops-sortable-table"><thead><tr><th data-sortable="true" aria-sort={ariaSort('nombre')}><button className="ops-sort-button" onClick={()=>applySort('nombre')}>Inmobiliaria <span className="ops-sort-arrow" aria-hidden="true">{sortArrow('nombre')}</span></button></th><th data-sortable="true" aria-sort={ariaSort('localidad')}><button className="ops-sort-button" onClick={()=>applySort('localidad')}>Localidad <span className="ops-sort-arrow" aria-hidden="true">{sortArrow('localidad')}</span></button></th><th data-sortable="true" aria-sort={ariaSort('estado')}><button className="ops-sort-button" onClick={()=>applySort('estado')}>Estado <span className="ops-sort-arrow" aria-hidden="true">{sortArrow('estado')}</span></button></th><th data-sortable="true" aria-sort={ariaSort('control')}><button className="ops-sort-button" onClick={()=>applySort('control')}>Control <span className="ops-sort-arrow" aria-hidden="true">{sortArrow('control')}</span></button></th><th aria-label="Abrir ficha"></th></tr></thead><tbody data-testid="inmo-sortable-body">{visible.map((r,i)=>{const id=idOf(r);return <tr key={id||i} className={id?'ops-clickable-row':''} tabIndex={id?0:undefined} onClick={()=>id&&navigate(`/inmobiliarias/${encodeURIComponent(id)}`)} onKeyDown={e=>{if(id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();navigate(`/inmobiliarias/${encodeURIComponent(id)}`)}}}><td><strong>{nameOf(r)}</strong></td><td>{localityOf(r)}</td><td>{stateOf(r)}</td><td>{controlOf(r)}</td><td>{id?'→':''}</td></tr>})}</tbody></table></div></div>}</>}
 </OperationalShellFrame>;
}