import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {LogOut,Moon,Search,Sun} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {anaAvatar,anaVertical,fenixLogo} from './assets/visualAssets';
import './operational.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';
type Ctx={actor_code?:string;role?:string};
type NavItem={label:string;route:string};
type Row=Record<string,unknown>;
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'},{label:'Expedientes',route:'/expedientes'},{label:'Bancos',route:'/bancos'},{label:'Contactos',route:'/contactos'},{label:'Inmobiliarias',route:'/inmobiliarias'},{label:'Tasaciones',route:'/tasaciones'},{label:'Firmas',route:'/firmas'},{label:'Documentación',route:'/documentacion'},{label:'Financieros',route:'/financieros'},{label:'Visitadores',route:'/visitadores'},{label:'Agenda',route:'/agenda'},{label:'Informes',route:'/informes'}];
function normalizeNav(data:unknown):NavItem[]{if(!data||typeof data!=='object')return[];const items=(data as{items?:unknown[]}).items;if(!Array.isArray(items))return[];return items.map(x=>{if(typeof x==='string')return{label:x.replace(/^\//,'')||'Inicio',route:x};if(x&&typeof x==='object'){const o=x as Record<string,unknown>;if(typeof o.route==='string')return{label:typeof o.label==='string'?o.label:o.route.replace(/^\//,''),route:o.route};}return null;}).filter((x):x is NavItem=>Boolean(x));}
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;return Array.isArray(d.items)?d.items as Row[]:[];}
function text(row:Row,keys:string[]){for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function idOf(r:Row){return text(r,['id','inmobiliaria_id','inmobiliaria_code','code','codigo']);}
function nameOf(r:Row){return text(r,['inmobiliaria','nombre','nombre_comercial','title'])||'Inmobiliaria sin nombre';}
function localityOf(r:Row){return text(r,['localidad','municipio','ciudad','poblacion','población','provincia'])||'Sin localidad';}
function stateOf(r:Row){return text(r,['estado','estado_colaboracion','estado_colaboración','estado_comercial'])||'Sin estado';}
function controlOf(r:Row){return text(r,['proximo_contacto_b2b','próximo_contacto_b2b','proxima_accion','próxima_acción','ultimo_resultado_contacto_b2b','último_contacto'])||'—';}
function isActive(r:Row){return /activ|colabor|formaliz/i.test(stateOf(r));}
function inProcess(r:Row){return /proceso|seguimiento|contact|pendiente|negoci/i.test(stateOf(r));}
function explicitNeverCalled(r:Row){const s=`${stateOf(r)} ${text(r,['ultimo_contacto','último_contacto','ultimo_resultado_contacto_b2b'])}`;return /sin llamar|no contact|pendiente primer|nunca contact/i.test(s);}

export default function InmobiliariasShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/inmobiliarias';
 const[sessionReady,setSessionReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const[query,setQuery]=useState(''),[state,setState]=useState(''),[locality,setLocality]=useState(''),[order,setOrder]=useState('nombre');const[correction,setCorrection]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setSessionReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setSessionReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNav(n.data):[]);});},[active,logged]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');const r=await fetchNotionRuntime<unknown>('/inmobiliarias');if(!alive)return;setStatus(r.status);setRows(r.status===200?rowsFrom(r.data):[]);if(r.status===403)setMessage('Tu perfil no tiene acceso a las inmobiliarias de este ámbito.');else if(r.status!==200)setMessage('No se pudo leer la fuente canónica de Inmobiliarias.');setLoading(false);})();return()=>{alive=false}},[active,logged]);
 const effectiveNav=nav.length?nav:fallbackNav;
 const states=useMemo(()=>Array.from(new Set(rows.map(stateOf).filter(Boolean))).sort(),[rows]);
 const localities=useMemo(()=>Array.from(new Set(rows.map(localityOf).filter(Boolean))).sort(),[rows]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();const out=rows.filter(r=>{const hay=Object.values(r).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase();return(!q||hay.includes(q))&&(!state||stateOf(r)===state)&&(!locality||localityOf(r)===locality)});return[...out].sort((a,b)=>order==='localidad'?localityOf(a).localeCompare(localityOf(b),'es'):order==='estado'?stateOf(a).localeCompare(stateOf(b),'es'):nameOf(a).localeCompare(nameOf(b),'es'));},[rows,query,state,locality,order]);
 const activeCount=useMemo(()=>rows.filter(isActive).length,[rows]),processCount=useMemo(()=>rows.filter(inProcess).length,[rows]),neverCount=useMemo(()=>rows.filter(explicitNeverCalled).length,[rows]);
 const localityRank=useMemo(()=>{const m=new Map<string,number>();rows.forEach(r=>{const l=localityOf(r);m.set(l,(m.get(l)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[rows]);
 if(!active||!sessionReady||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 function prepareCorrection(){if(!correction.trim()||!reason.trim())return;const q=new URLSearchParams({mode:'help',resource:'inmobiliaria',correction:correction.trim(),reason:reason.trim()});navigate(`/ana?${q.toString()}`);}
 return <div className="ops-root inmo-root" data-theme={theme}>
  <aside className="ops-side"><button className="ops-brand" onClick={()=>navigate('/inicio')}><img src={fenixLogo} alt=""/><strong>FÉNIX CAPITAL</strong></button><nav>{effectiveNav.map(item=><button key={item.route} className={item.route==='/inmobiliarias'?'active':''} onClick={()=>navigate(item.route)}>{item.label}</button>)}</nav><button className="ops-ana" onClick={()=>navigate('/ana')}><img src={anaAvatar} alt="Ana"/><span><strong>Ana está contigo</strong><small>Cuando quieras, avanzamos paso a paso.</small></span></button></aside>
  <main className="ops-main"><header className="ops-top"><div className="ops-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar inmobiliaria, localidad o seguimiento..."/><button>Buscar</button></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Cambiar tema">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{ctx?.role||'Usuario'}</strong></div><button onClick={logout} aria-label="Cerrar sesión"><LogOut size={17}/></button></div></header>
   <section className="ops-content inmo-content">
    <section className="inmo-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · EN ESTA PANTALLA</span><h2>¿Qué hacemos ahora?</h2><p>Las mejores colaboraciones se construyen con seguimiento, criterio y una próxima acción clara.</p><div className="inmo-next"><button onClick={()=>setOrder('estado')}><b>1</b><strong>Priorizar seguimientos</strong><small>Ver y preparar →</small></button><button onClick={()=>setState(states.find(s=>/activ|colabor/i.test(s))||'')}><b>2</b><strong>Revisar colaboradoras</strong><small>Ver y preparar →</small></button><button onClick={()=>navigate('/ana?mode=help&resource=inmobiliaria')}><b>3</b><strong>Comprobar condiciones</strong><small>Ver y preparar →</small></button></div></div><article className="inmo-correct"><span>CORREGIR A ANA</span><h3>¿En qué me equivoco?</h3><p>Preparo tu corrección con contexto para revisión; no modifica reglas automáticamente.</p><textarea rows={3} value={correction} onChange={e=>setCorrection(e.target.value)} placeholder="Qué cambiarías..."/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo de la corrección"/><button disabled={!correction.trim()||!reason.trim()} onClick={prepareCorrection}>Preparar para revisión</button></article></section>
    <div className="inmo-title"><div><small>COLABORACIÓN B2B</small><h1>Inmobiliarias</h1><p>{status===200?`${rows.length} inmobiliarias visibles en tu ámbito autorizado.`:'Lectura canónica según permisos.'}</p></div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos vivos':'PRE-PROD'}</span></div>
    {message&&<div className="ops-message">{message}</div>}
    {status===200&&<><section className="inmo-kpis"><article><small>EN FUENTE</small><strong>{rows.length}</strong><span>Registros visibles canónicos</span></article><article><small>ACTIVAS</small><strong>{activeCount}</strong><span>Derivado del estado visible</span></article><article><small>EN PROCESO</small><strong>{processCount}</strong><span>Derivado del estado visible</span></article><article><small>SIN LLAMAR</small><strong>{neverCount}</strong><span>Solo señal explícita disponible</span></article></section>
     <section className="inmo-insights"><article><span>DISTRIBUCIÓN POR LOCALIDAD</span><h2>Presencia visible</h2>{localityRank.map(([l,n])=><div className="inmo-locality" key={l}><strong>{l}</strong><span>{n}</span></div>)}</article><article><span>LECTURA RÁPIDA</span><h2>Prioridad comercial</h2><strong className="inmo-priority">{neverCount}</strong><p>{neverCount?'inmobiliarias con señal explícita de primer contacto pendiente.':'No hay una señal explícita suficiente para marcar inmobiliarias como “sin llamar”.'}</p><button onClick={()=>setOrder('estado')}>Revisar seguimiento</button></article></section>
     <section className="inmo-filter"><div className="inmo-filter-head"><div><small>CARTERA B2B</small><h2>Inmobiliarias disponibles</h2></div><span>{visible.length} visibles</span></div><label>BUSCAR<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre o dato relacionado"/></label><div className="inmo-filter-grid"><label>ESTADO<select value={state} onChange={e=>setState(e.target.value)}><option value="">Todos</option>{states.map(v=><option key={v}>{v}</option>)}</select></label><label>LOCALIDAD<select value={locality} onChange={e=>setLocality(e.target.value)}><option value="">Todas</option>{localities.map(v=><option key={v}>{v}</option>)}</select></label><label>ORDENAR POR<select value={order} onChange={e=>setOrder(e.target.value)}><option value="nombre">Nombre</option><option value="localidad">Localidad</option><option value="estado">Estado</option></select></label><button onClick={()=>{setQuery('');setState('');setLocality('');setOrder('nombre')}}>Limpiar</button></div></section>
     {loading?<div className="ops-empty"><strong>Cargando…</strong></div>:visible.length===0?<div className="ops-empty"><strong>Sin inmobiliarias visibles</strong><span>No hay registros para estos filtros o para tu ámbito actual.</span></div>:<div className="ops-table-card inmo-table"><div className="ops-table-head"><strong>{visible.length} registros</strong><span>Fuente canónica Notion</span></div><div className="ops-table-wrap"><table><thead><tr><th>Inmobiliaria</th><th>Localidad</th><th>Estado</th><th>Control</th><th></th></tr></thead><tbody>{visible.map((r,i)=>{const id=idOf(r);return <tr key={id||i} className={id?'ops-clickable-row':''} tabIndex={id?0:undefined} onClick={()=>id&&navigate(`/inmobiliarias/${encodeURIComponent(id)}`)} onKeyDown={e=>{if(id&&(e.key==='Enter'||e.key===' ')){e.preventDefault();navigate(`/inmobiliarias/${encodeURIComponent(id)}`)}}}><td><strong>{nameOf(r)}</strong></td><td>{localityOf(r)}</td><td>{stateOf(r)}</td><td>{controlOf(r)}</td><td>{id?'→':''}</td></tr>})}</tbody></table></div></div>}</>}
   </section>
  </main>
 </div>;
}
