import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {FileScan,ShieldCheck,Sparkles,X} from 'lucide-react';
import {useLocation} from 'react-router-dom';
import {IS_PRODUCTION,SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL,fetchAppApi,supabase} from './supabase';
import {extractDocumentData,ocrFile,type ExtractedDocument} from './browserDocumentOcr';

type Origin={type:'contacto'|'expediente';code:string};
type Prepare={ok?:boolean;upload_id?:string;storage_path?:string;token?:string;max_bytes?:number};
type Complete={ok?:boolean;document_page_id?:string;reused?:boolean};
type ApplyResult={ok?:boolean;status?:number;error?:string;conflicts?:Array<{field:string;current:string;proposed:string}>;updated?:Record<string,unknown>};
const BUCKET=IS_PRODUCTION?'fenix-prod-documents':'fenix-preprod-documents-test';
const EVIDENCE_FUNCTION=IS_PRODUCTION?'fenix-evidence-api':'fenix-evidence-universal-test';
const INTELLIGENCE_FUNCTION=IS_PRODUCTION?'fenix-document-intelligence':'fenix-document-intelligence-test';

function originFrom(path:string):Origin|null{const c=path.match(/^\/contactos\/([^/]+)$/);if(c&&c[1]!=='nuevo')return{type:'contacto',code:decodeURIComponent(c[1])};const e=path.match(/^\/expedientes\/([^/]+)$/);if(e&&e[1]!=='nuevo')return{type:'expediente',code:decodeURIComponent(e[1])};return null;}
async function authFetch<T>(fn:string,path:string,init?:RequestInit){const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)return{status:401,data:null as T|null};let r:Response;try{r=await fetch(`${SUPABASE_URL}/functions/v1/${fn}${path}`,{...init,headers:{'content-type':'application/json',apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`,...(init?.headers||{})}})}catch{return{status:0,data:null as T|null}}let data:T|null=null;try{data=await r.json()}catch{}return{status:r.status,data};}
async function uploadOriginal(file:File,origin:Origin){
 const mime=file.type||(/\.pdf$/i.test(file.name)?'application/pdf':'image/jpeg');
 const prep=await authFetch<Prepare>(EVIDENCE_FUNCTION,'/prepare',{method:'POST',body:JSON.stringify({origin_type:origin.type,origin_code:origin.code,evidence_kind:'documento',filename:file.name,mime_type:mime})});
 if(prep.status!==200||!prep.data?.upload_id||!prep.data.storage_path||!prep.data.token)throw new Error('No se pudo preparar el documento original.');
 if(prep.data.max_bytes&&file.size>prep.data.max_bytes)throw new Error('El archivo supera el tamaño máximo permitido.');
 const up=await supabase.storage.from(BUCKET).uploadToSignedUrl(prep.data.storage_path,prep.data.token,file,{contentType:mime});if(up.error)throw new Error('No se pudo conservar el documento original.');
 const done=await authFetch<Complete>(EVIDENCE_FUNCTION,'/complete',{method:'POST',body:JSON.stringify({upload_id:prep.data.upload_id,title:file.name,tipo:'Otro',sensibilidad:'Personal'})});
 if(done.status!==200||!done.data?.ok)throw new Error('El documento se subió, pero no pudo quedar vinculado.');return done.data;
}
function label(k:string){return k==='nombre'?'Nombre':k==='apellidos'?'Apellidos':k==='documento_identidad'?'DNI / NIE':'Fecha de nacimiento';}
function display(v:unknown){return v==null||v===''?'—':String(v);}

export default function IntelligentDocumentIngestionGuard(){
 const location=useLocation();const origin=useMemo(()=>originFrom(location.pathname),[location.pathname]);
 const[host,setHost]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null),[result,setResult]=useState<ExtractedDocument|null>(null),[progress,setProgress]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[current,setCurrent]=useState<Record<string,unknown>>({}),[conflicts,setConflicts]=useState<ApplyResult['conflicts']>([]),[overwrite,setOverwrite]=useState(false);
 useEffect(()=>{if(!origin){setHost(null);return;}const h=document.createElement('div');h.className='intelligent-ingestion-host';const place=()=>{const content=document.querySelector<HTMLElement>('.ops-content,.dir-content');if(!content)return;const evidence=content.querySelector<HTMLElement>('.context-evidence-inline-host');if(evidence?.parentElement===content){if(evidence.nextElementSibling!==h)content.insertBefore(h,evidence.nextElementSibling)}else if(h.parentElement!==content)content.insertBefore(h,content.firstChild)};place();const ob=new MutationObserver(place);ob.observe(document.body,{childList:true,subtree:true});setHost(h);return()=>{ob.disconnect();h.remove();setHost(null)}},[origin?.type,origin?.code]);
 useEffect(()=>{if(!origin||!open)return;let alive=true;(async()=>{const r=await fetchAppApi<any>(origin.type==='contacto'?`/contactos/${encodeURIComponent(origin.code)}`:`/expedientes/${encodeURIComponent(origin.code)}`);if(!alive)return;const item=origin.type==='contacto'?(r.data?.contacto||{}):(r.data?.expediente||{});setCurrent(item&&typeof item==='object'?item:{});})();return()=>{alive=false}},[open,origin?.type,origin?.code]);
 if(!origin||!host)return null;
 async function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]||null;e.target.value='';if(!f)return;setFile(f);setResult(null);setConflicts([]);setOverwrite(false);setMessage('');setBusy(true);try{const ocr=await ocrFile(f,setProgress);const extracted=extractDocumentData(ocr.text,ocr.confidence);setResult(extracted);setProgress(extracted.rawText?`Lectura terminada${ocr.confidence!==null?` · confianza OCR ${Math.round(ocr.confidence)}%`:''}.`:'No se ha podido leer texto suficiente.');}catch(err){setMessage(err instanceof Error?err.message:'No se pudo leer el documento.');setProgress('');}finally{setBusy(false)}}
 async function apply(){if(!origin||!file||!result||busy)return;const activeOrigin=origin;const fields=result.fields;if(!Object.keys(fields).length){setMessage('No hay datos suficientemente claros para autorrellenar. El original no se modificará.');return;}setBusy(true);setMessage('Conservando original y preparando cambios…');try{
   const saved=await uploadOriginal(file,activeOrigin);
   const payload={origin_type:activeOrigin.type,origin_code:activeOrigin.code,fields,summary:result.summary,document_type:result.documentType,document_page_id:saved.document_page_id||null,confidence:result.confidence,confirm_overwrite:overwrite,current};
   const r=await authFetch<ApplyResult>(INTELLIGENCE_FUNCTION,'/apply',{method:'POST',body:JSON.stringify(payload)});
   if(r.status===409&&r.data?.conflicts?.length){setConflicts(r.data.conflicts);setMessage('Hay datos existentes distintos. Revisa los conflictos antes de sobrescribir.');return;}
   if(r.status!==200||!r.data?.ok)throw new Error(r.data?.error||`No se pudo aplicar el autorrelleno (${r.status}).`);
   setMessage('Documento leído, original vinculado y datos confirmados. CEREBRO conserva el resumen y la procedencia.');setConflicts([]);setOverwrite(false);setTimeout(()=>window.location.reload(),900);
 }catch(err){setMessage(err instanceof Error?err.message:'No se pudo completar el tratamiento inteligente.');}finally{setBusy(false)}}
 const launcher=<button type="button" data-testid="intelligent-document-open" onClick={()=>{setOpen(true);setMessage('')}} style={{width:'100%',border:'1px solid #7d4bd1',borderRadius:12,padding:'12px 16px',display:'inline-flex',alignItems:'center',justifyContent:'center',gap:8,background:'#fff',color:'#5c2fa8',fontWeight:800,cursor:'pointer'}}><FileScan size={17}/> Leer foto/PDF y rellenar datos</button>;
 return <>{createPortal(launcher,host)}{open&&createPortal(<div className="intelligent-ingestion-backdrop" role="presentation"><section className="intelligent-ingestion-card" role="dialog" aria-modal="true" aria-label="Lectura inteligente de documento"><header><div><span><Sparkles size={17}/> CEREBRO · INGESTA INTELIGENTE</span><h2>Foto/PDF → datos → resumen → autorrelleno</h2><p>El original se conserva. Los datos no se modifican hasta que confirmes.</p></div><button onClick={()=>setOpen(false)} aria-label="Cerrar"><X size={18}/></button></header><label className="intelligent-file"><FileScan size={20}/>{busy?'Procesando…':'Elegir foto o PDF'}<input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>void choose(e)} disabled={busy}/></label>{file&&<small>Archivo: {file.name}</small>}{progress&&<div className="intelligent-status">{progress}</div>}{result&&<><article><strong>TIPO DETECTADO</strong><p>{result.documentType}</p><strong>RESUMEN</strong><p>{result.summary}</p></article><div className="intelligent-fields"><strong>DATOS PROPUESTOS</strong>{Object.entries(result.fields).length?Object.entries(result.fields).map(([k,v])=><div key={k}><span>{label(k)}</span><b>{display(v)}</b></div>):<p>No hay campos suficientemente fiables para completar automáticamente.</p>}</div><details><summary>Ver texto leído</summary><pre>{result.rawText||'Sin texto legible'}</pre></details></>}{conflicts?.length?<article className="intelligent-conflicts"><strong>CONFLICTOS A REVISAR</strong>{conflicts.map(c=><p key={c.field}>{label(c.field)}: actual <b>{c.current}</b> → documento <b>{c.proposed}</b></p>)}<label><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/> Confirmo que quiero sustituir estos datos existentes por los del documento.</label></article>:null}{message&&<div className="intelligent-status" role="status">{message}</div>}<footer><ShieldCheck size={17}/><span>Nada se sobrescribe a ciegas.</span><button className="primary" disabled={!file||!result||busy||Boolean(conflicts?.length&&!overwrite)} onClick={()=>void apply()}>{busy?'Procesando…':conflicts?.length?'Confirmar conflictos y aplicar':'Confirmar y aplicar datos'}</button></footer></section></div>,document.body)}<style>{`
.intelligent-ingestion-host{margin-top:10px}.intelligent-ingestion-backdrop{position:fixed;inset:0;z-index:10020;background:rgba(18,15,23,.58);display:grid;place-items:center;padding:18px}.intelligent-ingestion-card{width:min(760px,96vw);max-height:92vh;overflow:auto;background:#fff;color:#1d1d1f;border-radius:20px;padding:22px;border:1px solid #e7def6;box-shadow:0 28px 80px rgba(0,0,0,.25)}.intelligent-ingestion-card header{display:flex;justify-content:space-between;gap:14px}.intelligent-ingestion-card header span{display:flex;gap:7px;align-items:center;color:#6b39bb;font-size:11px;font-weight:900;letter-spacing:.06em}.intelligent-ingestion-card h2{margin:6px 0;font-size:22px}.intelligent-ingestion-card header p{margin:0;color:#6f6f75;font-size:12px}.intelligent-ingestion-card header button{align-self:flex-start;border:0;background:transparent;cursor:pointer}.intelligent-file{margin-top:18px;border:1px dashed #8d65cf;border-radius:14px;padding:15px;display:flex;align-items:center;justify-content:center;gap:8px;font-weight:800;cursor:pointer}.intelligent-file input{display:none}.intelligent-status,.intelligent-ingestion-card article,.intelligent-fields{margin-top:13px;border:1px solid #eee;border-radius:12px;padding:12px 14px;background:#fafafa}.intelligent-ingestion-card article p{margin:6px 0 10px;line-height:1.45}.intelligent-fields>div{display:flex;justify-content:space-between;gap:15px;border-top:1px solid #eee;padding:9px 0}.intelligent-fields>div:first-of-type{margin-top:7px}.intelligent-ingestion-card details{margin-top:12px}.intelligent-ingestion-card pre{white-space:pre-wrap;max-height:180px;overflow:auto;background:#f5f5f6;padding:10px;border-radius:9px;font-size:11px}.intelligent-conflicts{border-color:#f0b38e!important;background:#fff7f2!important}.intelligent-conflicts label{display:flex;gap:8px;align-items:flex-start;font-size:12px}.intelligent-ingestion-card footer{display:flex;gap:9px;align-items:center;margin-top:16px;flex-wrap:wrap}.intelligent-ingestion-card footer span{font-size:11px;color:#696970}.intelligent-ingestion-card footer .primary{margin-left:auto;border:0;background:#6b39bb;color:#fff;border-radius:10px;padding:11px 15px;font-weight:800;cursor:pointer}.intelligent-ingestion-card footer .primary:disabled{opacity:.45;cursor:not-allowed}[data-theme='dark'] .intelligent-ingestion-card{background:#202023;color:#f4f4f5;border-color:#493868}[data-theme='dark'] .intelligent-status,[data-theme='dark'] .intelligent-ingestion-card article,[data-theme='dark'] .intelligent-fields{background:#28282c;border-color:#3d3d43}@media(max-width:650px){.intelligent-ingestion-card{padding:16px}.intelligent-fields>div{display:grid}.intelligent-ingestion-card footer .primary{width:100%;margin-left:0}}
`}</style></>;
}
