import {useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,Mail,MapPin,Phone,Users} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotariasRuntime} from './notariasRuntime';
import {anaVertical} from './assets/visualAssets';
import {directionSidebarNavigation,isDirectionNavigation,normalizeNavigation,orderAuthorizedNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './notarias-polish.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};type DetailResponse={item?:Row;personal?:Row[]};
const ROUTE='/notarias',fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function txt(r:Row|null,k:string){const v=r?.[k];return typeof v==='string'&&v.trim()?v.trim():'No disponible'}function yes(v:unknown){return v===true?'Sí':v===false?'No':'No disponible'}
export default function NotariaDetailShell(){const location=useLocation(),navigate=useNavigate();const m=location.pathname.match(/^\/notarias\/([^/]+)$/),active=Boolean(m),id=m?.[1]?decodeURIComponent(m[1]):'';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[authorized,setAuthorized]=useState<boolean|null>(null),[row,setRow]=useState<Row|null>(null),[people,setPeople]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false);
useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);useEffect(()=>{if(active){document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)}},[active,theme]);useEffect(()=>{if(!active||!logged||!id)return;let alive=true;(async()=>{setLoading(true);try{const[c,n,r]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchNotariasRuntime<DetailResponse>(`${ROUTE}/${encodeURIComponent(id)}`)]);if(!alive)return;setCtx(c.status===200?c.data:null);const normalized=n.status===200?normalizeNavigation(n.data):[];setNav(isDirectionNavigation(normalized)?directionSidebarNavigation(normalized):orderAuthorizedNavigation(normalized));const canUse=normalized.some(i=>i.route===ROUTE);setAuthorized(canUse);if(!canUse){navigate('/inicio',{replace:true});return}setStatus(r.status);setRow(r.status===200?r.data?.item??null:null);setPeople(r.status===200&&Array.isArray(r.data?.personal)?r.data!.personal!:[])}catch{if(alive){setStatus(0);setRow(null);setPeople([])}}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[active,logged,id,navigate]);if(!active||!ready||!logged||authorized!==true)return null;const effectiveNav=nav.length?nav:fallbackNav,role=ctx?.role||'Usuario';async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}const anaSummary=loading?'Estoy leyendo esta ficha antes de orientarte.':status!==200||!row?'No tengo la ficha disponible para recomendar una gestión.':`La notaría está en ${txt(row,'localidad')}. ${people.length?`Hay ${people.length} persona${people.length===1?'':'s'} relacionada${people.length===1?'':'s'} disponible${people.length===1?'':'s'} para coordinación.`:'No hay personal relacionado visible todavía.'}`;
return <OperationalShellFrame className="inmo-root notarias-root" theme={theme} navigation={effectiveNav} activeRoute={ROUTE} anaSubtitle="Te ayudo con esta notaría, sus contactos y la preparación de la firma." query="" onQueryChange={()=>{}} searchPlaceholder="" name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="inmo-content notarias-content">
<section className="inmo-ana-hero" data-testid="notaria-detail-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · FICHA DE NOTARÍA</span><h2>Esto es lo que veo ahora</h2><p>{anaSummary}</p><div className="inmo-next"><button onClick={()=>navigate('/ana?mode=do&resource=notarias')}><b>1</b><strong>Que lo haga Ana</strong><small>Preparar coordinación →</small></button><button onClick={()=>navigate('/ana?mode=help&resource=notarias')}><b>2</b><strong>Ayúdame</strong><small>Guía paso a paso →</small></button><button onClick={()=>navigate('/ana?mode=manual&resource=notarias')}><b>3</b><strong>Lo hago yo</strong><small>Ver instrucciones →</small></button></div></div><article className="inmo-correct"><span>CONTROL DE INFORMACIÓN</span><h3>Datos disponibles y trazables</h3><p>Ana no completa contactos, horarios ni personas que no estén registrados.</p><textarea readOnly rows={3} value={row?txt(row,'horario_observaciones'):'No disponible'}/><input readOnly value={`${people.length} personas relacionadas`}/><button onClick={()=>navigate('/ana?mode=help&resource=notarias')}>Revisar con Ana</button></article></section>
<button className="inmo-detail-back" onClick={()=>navigate(ROUTE)}><ArrowLeft size={15}/> Volver a Notarías</button><div className="inmo-title"><div><small>FICHA MAESTRA</small><h1>{row?txt(row,'notaria'):'Notaría'}</h1><p>{row?txt(row,'localidad'):'Cargando información…'}</p></div><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos actualizados':status===403?'Sin acceso':'Sin conexión'}</span></div>{status===403&&<div className="ops-message">Tu perfil no tiene acceso a esta notaría.</div>}{status===404&&<div className="ops-message">No se ha encontrado la notaría.</div>}{status!==null&&status!==200&&status!==403&&status!==404&&<div className="ops-message">No se pudo cargar la notaría.</div>}{row&&<><section className="inmo-kpis"><article><small>LOCALIDAD</small><strong style={{fontSize:23}}>{txt(row,'localidad')}</strong><span>Ubicación</span></article><article><small>CONTACTO</small><strong style={{fontSize:23}}>{txt(row,'telefono')}</strong><span>{txt(row,'email')}</span></article><article><small>PERSONAL</small><strong>{people.length}</strong><span>Relacionado</span></article><article><small>ÚLTIMA FIRMA</small><strong style={{fontSize:23}}>{txt(row,'ultima_firma')}</strong><span>Dato disponible</span></article></section><section className="inmo-insights"><article><span>DATOS DE CONTACTO</span><h2>{txt(row,'notaria')}</h2><p><MapPin size={16}/> <b>Dirección:</b> {txt(row,'direccion')}</p><p><Phone size={16}/> <b>Teléfono:</b> {txt(row,'telefono')}</p><p><Mail size={16}/> <b>Email:</b> {txt(row,'email')}</p></article><article><span>DATOS DE TRABAJO</span><h2>Coordinación</h2><p><b>Notario / oficial principal:</b> {txt(row,'notario_oficial_principal')}</p><p><b>Horario / observaciones:</b> {txt(row,'horario_observaciones')}</p><p><b>Notas:</b> {txt(row,'notas')}</p></article></section><section className="ops-table-card" data-testid="notaria-staff"><div className="ops-table-head"><strong><Users size={16}/> Personal relacionado</strong><span>{people.length} contacto{people.length===1?'':'s'}</span></div>{people.length===0?<div className="ops-empty"><strong>Sin personal relacionado</strong><span>No hay personas vinculadas a esta notaría.</span></div>:<div className="ops-table-wrap"><table className="ops-table inmo-table"><thead><tr><th>PERSONA</th><th>CARGO</th><th>TELÉFONO</th><th>EXTENSIÓN</th><th>EMAIL</th><th>ACTIVO</th></tr></thead><tbody>{people.map((p,i)=><tr key={txt(p,'id')==='No disponible'?i:txt(p,'id')}><td><strong>{txt(p,'persona')}</strong><br/><small>{txt(p,'observaciones')}</small></td><td>{txt(p,'cargo')}</td><td>{txt(p,'telefono_directo')}</td><td>{txt(p,'extension')}</td><td>{txt(p,'email_directo')}</td><td>{yes(p.activo)}</td></tr>)}</tbody></table></div>}</section></>}
</OperationalShellFrame>}
