import {useEffect,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,Building2,Mail,MapPin,Phone} from 'lucide-react';
import {supabase} from './supabase';
import {fetchNotariasRuntime} from './notariasRuntime';
import {anaAvatar,fenixLogo} from './assets/visualAssets';
import './operational.css';
import './notarias-polish.css';

type Row=Record<string,unknown>;function txt(r:Row|null,k:string){const v=r?.[k];return typeof v==='string'&&v.trim()?v.trim():'No disponible'}
export default function NotariaDetailShell(){const location=useLocation(),navigate=useNavigate();const m=location.pathname.match(/^\/notarias\/([^/]+)$/),active=Boolean(m),id=m?.[1]?decodeURIComponent(m[1]):'';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[row,setRow]=useState<Row|null>(null),[status,setStatus]=useState<number|null>(null);useEffect(()=>{if(!active)return;supabase.auth.getSession().then(({data})=>{setLogged(Boolean(data.session));setReady(true)});},[active]);useEffect(()=>{if(!active||!logged||!id)return;fetchNotariasRuntime<any>(`/notarias/${encodeURIComponent(id)}`).then(r=>{setStatus(r.status);setRow(r.status===200?r.data?.item??null:null)});},[active,logged,id]);if(!active||!ready||!logged)return null;return <div className="ops-root notarias-root"><aside className="ops-side"><button className="ops-brand" onClick={()=>navigate('/inicio')}><img src={fenixLogo} alt=""/><strong>FÉNIX CAPITAL</strong></button><nav><button onClick={()=>navigate('/notarias')}><ArrowLeft size={15}/> Volver a Notarías</button></nav><button className="ops-ana" onClick={()=>navigate('/ana')}><img src={anaAvatar} alt="Ana"/><span><strong>Hablar con Ana</strong><small>Apoyo para notaría y firma.</small></span></button></aside><main className="ops-main"><header className="ops-top"><strong>Ficha de notaría</strong></header><section className="ops-content notarias-content"><div className="ops-title"><div><span className="ops-icon"><Building2 size={20}/></span><div><small>FICHA MAESTRA</small><h1>{row?txt(row,'notaria'):'Notaría'}</h1><p>Fuente canónica Notion · directorio, no registro de firma.</p></div></div><span className={status===200?'ops-live ok':'ops-live'}>{status===200?'Datos vivos':'PRE-PROD'}</span></div>{status===403&&<div className="ops-message">Tu perfil no tiene acceso a esta notaría.</div>}{status===404&&<div className="ops-message">No se ha encontrado la notaría.</div>}{row&&<><section className="profile-card"><div className="profile-main-copy"><h2>{txt(row,'notaria')}</h2><span>{txt(row,'localidad')}</span></div><div className="profile-data"><article><MapPin/><div><small>DIRECCIÓN</small><strong>{txt(row,'direccion')}</strong></div></article><article><Phone/><div><small>TELÉFONO</small><strong>{txt(row,'telefono')}</strong></div></article><article><Mail/><div><small>EMAIL</small><strong>{txt(row,'email')}</strong></div></article></div></section><section className="ops-table-card"><div className="ops-table-head"><strong>Datos de trabajo</strong><span>Sin completar campos ausentes</span></div><div className="ops-message"><p><b>Notario / oficial principal:</b> {txt(row,'notario_oficial_principal')}</p><p><b>Horario / observaciones:</b> {txt(row,'horario_observaciones')}</p><p><b>Notas:</b> {txt(row,'notas')}</p><p><b>Última firma:</b> {txt(row,'ultima_firma')}</p></div></section></>}</section></main></div>}
