import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {AlertTriangle,Bell,CalendarClock,CheckCircle2,Moon,Search,Sun} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchNotionRuntime} from './notionRuntime';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './notifications-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of ['items','tareas','results'])if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function done(r:Row){return r.completada===true||/(complet|hecha|cerrad|cancel)/i.test(first(r,['estado','status']));}
function deadline(r:Row){const raw=first(r,['fecha_limite','vencimiento','deadline','fecha']);if(!raw)return null;const d=new Date(raw);return Number.isFinite(d.getTime())?d:null;}
function critical(r:Row){return /(cr[ií]tic|urgente|alta)/i.test(first(r,['criticidad','prioridad','priority']));}
export default function NotificationsShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/notificaciones';const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive){setLogged(Boolean(s));setReady(true)}});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{setLoading(true);setMessage('');setStatus(null);setCtx(null);setNav([]);setRows([]);try{const[c,n,t]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchNotionRuntime<unknown>('/tareas')]);if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);setStatus(t.status);if(t.status===200){setRows(rowsFrom(t.data));}else{setRows([]);if(t.status===403)setMessage('Tu perfil no tiene acceso a estas tareas o avisos derivados.');else if(t.status===0)setMessage('No se pudo conectar con la fuente canónica de tareas.');else setMessage('No se pudo cargar la fuente canónica de tareas.');}}catch{if(!alive)return;setCtx(null);setNav([]);setRows([]);setStatus(0);setMessage('No se pudo conectar con la fuente canónica de tareas.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,logged]);
 const notices=useMemo(()=>{const now=Date.now();return rows.filter(r=>!done(r)).map(r=>{const d=deadline(r);const overdue=Boolean(d&&d.getTime()<now);return{row:r,overdue,isCritical:critical(r),date:d};}).filter(x=>x.overdue||x.isCritical||x.date).sort((a,b)=>Number(b.overdue)-Number(a.overdue)||(a.date?.getTime()??Infinity)-(b.date?.getTime()??Infinity));},[rows]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return notices;return notices.filter(x=>Object.values(x.row).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase().includes(q));},[notices,query]);
 if(!active||!ready||!logged)return null;
 const effectiveNav=nav.length?nav:fallbackNav;const role=ctx?.role||'Usuario';
 const topbar=<header className="ops-top"><div className="ops-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar aviso operativo..."/></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{role}</strong></div></div></header>;
 return <OperationalShellFrame className="notif-root" theme={theme} navigation={effectiveNav} activeRoute="/notificaciones" anaSubtitle="Prioriza avisos derivados de tareas reales." anaRoute="/ana?mode=help&resource=agenda" query={query} onQueryChange={setQuery} searchPlaceholder="Buscar aviso operativo..." name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={async()=>{await supabase.auth.signOut();}} topbar={topbar} contentClassName="notif-content">
  <div className="notif-title"><div><small>CENTRO DE AVISOS OPERATIVOS</small><h1>Notificaciones</h1><p>Esta pantalla convierte únicamente tareas canónicas pendientes con vencimiento o criticidad explícita en avisos operativos.</p></div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Fuente canónica':'PRE-PROD'}</span></div>
  <section className="notif-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · NOTIFICACIONES</span><h2>Te ayudo a separar lo urgente de lo que puede esperar</h2><p>Trabajo solo con avisos derivados de tareas reales y autorizadas. Puedo ayudarte a revisar prioridades sin fabricar notificaciones que no existan.</p><div className="inmo-next"><button type="button" onClick={()=>navigate('/ana?mode=help&resource=agenda&intent=prioridades')}><b>1</b><strong>Qué requiere atención</strong><small>Priorizar →</small></button><button type="button" onClick={()=>navigate('/agenda')}><b>2</b><strong>Ver tareas</strong><small>Abrir agenda →</small></button><button type="button" onClick={()=>navigate('/ana?mode=help&resource=agenda')}><b>3</b><strong>Ayúdame</strong><small>Revisar con Ana →</small></button></div></div></section>
  {loading&&status===null&&<div className="ops-message" role="status" data-testid="notifications-loading">Cargando avisos derivados de tareas autorizadas…</div>}{status===403&&message&&<div className="ops-message" data-testid="notifications-forbidden">{message}</div>}{status!==null&&status!==200&&status!==403&&message&&<div className="ops-message" data-testid="notifications-error">{message}</div>}{!loading&&status===200&&<><section className="notif-kpis"><article><Bell/><small>AVISOS VISIBLES</small><strong>{notices.length}</strong><span>Derivados de tareas pendientes</span></article><article><AlertTriangle/><small>VENCIDOS</small><strong>{notices.filter(n=>n.overdue).length}</strong><span>Fecha límite anterior a hoy</span></article><article><CalendarClock/><small>CRÍTICOS</small><strong>{notices.filter(n=>n.isCritical).length}</strong><span>Solo criticidad informada</span></article></section>{visible.length===0?<div className="ops-empty" data-testid="notifications-empty"><CheckCircle2/><strong>Sin avisos operativos pendientes</strong><span>No hay tareas visibles con vencimiento o criticidad que requieran aviso.</span></div>:<div className="notif-list">{visible.map((n,i)=>{const r=n.row;const id=first(r,['id','tarea_id','tarea_code']);const title=first(r,['tarea','titulo','title','nombre'])||'Tarea pendiente';const state=first(r,['estado','status'])||'Pendiente';const crit=first(r,['criticidad','prioridad','priority']);return <button key={id||`${title}-${i}`} disabled={!id} onClick={()=>id&&navigate(`/tareas/${encodeURIComponent(id)}`)}><span className={`notif-icon ${n.overdue?'danger':n.isCritical?'warning':''}`}>{n.overdue?<AlertTriangle/>:<Bell/>}</span><span><strong>{title}</strong><small>{state}{crit?` · ${crit}`:''}{n.date?` · ${n.date.toLocaleDateString('es-ES')}`:''}</small></span><b>{id?'Abrir tarea →':'Sin ruta disponible'}</b></button>})}</div>}<div className="notif-note">No existe todavía una fuente dedicada de notificaciones. Hasta que exista, este centro muestra solo avisos derivados de tareas canónicas y nunca genera mensajes ficticios.</div></>}
 </OperationalShellFrame>;
}
