import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {AlertTriangle,Archive,Bell,CalendarClock,CheckCircle2,Eye,Moon,Search,Sun} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './notifications-polish.css';

type Theme='light'|'dark';type Ctx={role?:string};
type Notice={notification_code:string;tarea_id:string;tarea_code:string;titulo:string;estado:string;criticidad?:string|null;fecha_limite?:string|null;bloqueante?:boolean;read_at?:string|null;action_route:string;source:string};
type NoticePayload={ok?:boolean;status?:number;items?:Notice[];error?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function deadline(n:Notice){if(!n.fecha_limite)return null;const d=new Date(n.fecha_limite);return Number.isFinite(d.getTime())?d:null;}
function critical(n:Notice){return Boolean(n.bloqueante)||/(cr[ií]tic|urgente|alta)/i.test(n.criticidad||'');}
export default function NotificationsShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/notificaciones';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[rows,setRows]=useState<Notice[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive){setLogged(Boolean(s));setReady(true)}});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 async function load(){if(!active||!logged)return;setLoading(true);setMessage('');setStatus(null);try{const[c,n,r]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),supabase.rpc('fenix_prod_notifications_list_user',{p_limit:100})]);setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);if(r.error){setRows([]);setStatus(0);setMessage('No se pudo cargar la fuente persistente de notificaciones.');return;}const payload=r.data as NoticePayload|null;const s=payload?.status??0;setStatus(s);setRows(s===200&&Array.isArray(payload?.items)?payload.items:[]);if(s===403)setMessage('Tu perfil no tiene acceso a estas notificaciones.');else if(s!==200)setMessage('No se pudo cargar la fuente persistente de notificaciones.');}catch{setRows([]);setStatus(0);setMessage('No se pudo conectar con la fuente persistente de notificaciones.');}finally{setLoading(false);}}
 useEffect(()=>{if(!active||!logged)return;void load();},[active,logged]);
 async function mark(tareaId:string,action:'read'|'dismiss'){const{data,error}=await supabase.rpc('fenix_prod_notification_mark_user',{p_tarea_id:tareaId,p_action:action});const payload=data as NoticePayload|null;if(error||payload?.status!==200){setMessage('No se pudo actualizar la notificación.');return false;}await load();return true;}
 const notices=useMemo(()=>rows.map(row=>{const d=deadline(row);return{row,date:d,overdue:Boolean(d&&d.getTime()<Date.now()),isCritical:critical(row)};}),[rows]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return notices;return notices.filter(x=>`${x.row.titulo} ${x.row.estado} ${x.row.criticidad||''}`.toLowerCase().includes(q));},[notices,query]);
 if(!active||!ready||!logged)return null;
 const effectiveNav=nav.length?nav:fallbackNav;const role=ctx?.role||'Usuario';
 const topbar=<header className="ops-top"><div className="ops-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar notificación..."/></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button><div className="ops-profile"><strong>{role}</strong></div></div></header>;
 return <OperationalShellFrame className="notif-root" theme={theme} navigation={effectiveNav} activeRoute="/notificaciones" anaSubtitle="Prioriza avisos reales y trazables." anaRoute="/ana?mode=help&resource=agenda" query={query} onQueryChange={setQuery} searchPlaceholder="Buscar notificación..." name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={async()=>{await supabase.auth.signOut();}} topbar={topbar} contentClassName="notif-content">
  <div className="notif-title"><div><small>CENTRO DE AVISOS OPERATIVOS</small><h1>Notificaciones</h1><p>Fuente persistente derivada exclusivamente de tareas canónicas autorizadas. Las lecturas y descartes quedan guardados por usuario.</p></div><span className={status===200?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Fuente persistente':'Error'}</span></div>
  <section className="notif-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · NOTIFICACIONES</span><h2>Te ayudo a separar lo urgente de lo que puede esperar</h2><p>Trabajo solo con avisos derivados de tareas reales y autorizadas. No creo notificaciones sin fuente.</p><div className="inmo-next"><button type="button" onClick={()=>navigate('/ana?mode=help&resource=agenda&intent=prioridades')}><b>1</b><strong>Qué requiere atención</strong><small>Priorizar →</small></button><button type="button" onClick={()=>navigate('/agenda')}><b>2</b><strong>Ver tareas</strong><small>Abrir agenda →</small></button><button type="button" onClick={()=>navigate('/ana?mode=help&resource=agenda')}><b>3</b><strong>Ayúdame</strong><small>Revisar con Ana →</small></button></div></div></section>
  {loading&&status===null&&<div className="ops-message" role="status">Cargando notificaciones autorizadas…</div>}{message&&<div className="ops-message">{message}</div>}{!loading&&status===200&&<><section className="notif-kpis"><article><Bell/><small>AVISOS VISIBLES</small><strong>{notices.length}</strong><span>Persistentes y trazables</span></article><article><AlertTriangle/><small>VENCIDOS</small><strong>{notices.filter(n=>n.overdue).length}</strong><span>Fecha límite anterior a hoy</span></article><article><CalendarClock/><small>CRÍTICOS</small><strong>{notices.filter(n=>n.isCritical).length}</strong><span>Criticidad o bloqueo explícito</span></article></section>{visible.length===0?<div className="ops-empty" data-testid="notifications-empty"><CheckCircle2/><strong>Sin avisos operativos pendientes</strong><span>No hay tareas autorizadas que requieran aviso.</span></div>:<div className="notif-list">{visible.map(({row,date,overdue,isCritical})=><div key={row.notification_code} className="notif-action-row"><button onClick={async()=>{if(!row.read_at)await mark(row.tarea_id,'read');navigate(row.action_route)}}><span className={`notif-icon ${overdue?'danger':isCritical?'warning':''}`}>{overdue?<AlertTriangle/>:<Bell/>}</span><span><strong>{row.titulo}</strong><small>{row.estado}{row.criticidad?` · ${row.criticidad}`:''}{date?` · ${date.toLocaleDateString('es-ES')}`:''}{row.read_at?' · Leída':''}</small></span><b>Abrir tarea →</b></button><button type="button" aria-label="Marcar como leída" onClick={()=>void mark(row.tarea_id,'read')}><Eye size={16}/></button><button type="button" aria-label="Descartar aviso" onClick={()=>void mark(row.tarea_id,'dismiss')}><Archive size={16}/></button></div>)}</div>}<div className="notif-note">Cada aviso conserva su procedencia en la tarea canónica; el cliente no puede elegir el actor y el backend filtra por identidad autenticada.</div></>}
 </OperationalShellFrame>;
}
