import {cloneElement,isValidElement,useEffect,useRef,useState,type ReactElement,type ReactNode} from 'react';
import {BarChart3,Building2,CalendarDays,FileText,FolderOpen,Menu,UserRound,X} from 'lucide-react';
import {useLocation,useNavigate} from 'react-router-dom';
import type {NavItem} from './masterNavigation';
import OperationalSidebar from './OperationalSidebar';
import OperationalTopbar from './OperationalTopbar';

type Theme='light'|'dark';
const THEME_KEY='fenix-theme';
const LEGACY_GLOBAL_THEME_KEY='fenix-global-theme';
function storedTheme(fallback:Theme):Theme{const local=localStorage.getItem(THEME_KEY);if(local==='light'||local==='dark')return local;const legacyGlobal=localStorage.getItem(LEGACY_GLOBAL_THEME_KEY);if(legacyGlobal==='light'||legacyGlobal==='dark')return legacyGlobal;const session=sessionStorage.getItem(THEME_KEY);return session==='light'||session==='dark'?session:fallback;}
function persistTheme(theme:Theme){localStorage.setItem(THEME_KEY,theme);localStorage.setItem(LEGACY_GLOBAL_THEME_KEY,theme);sessionStorage.setItem(THEME_KEY,theme);document.documentElement.dataset.theme=theme;}

type Props={className?:string;theme:Theme;navigation:NavItem[];activeRoute:string;anaSubtitle?:string;anaRoute?:string;sidebarVariant?:'default'|'direction';sidebarClassName?:string;query:string;onQueryChange:(value:string)=>void;searchPlaceholder:string;searchActionLabel?:string;onSearchAction?:()=>void;name:string;role:string;avatarUrl?:string;initials:string;onToggleTheme:()=>void;onLogout:()=>void|Promise<void>;topbar?:ReactNode;mainClassName?:string;contentClassName?:string;legacyDirectionTheme?:boolean;children:ReactNode;};

export default function OperationalShellFrame({className='',theme,navigation,activeRoute,anaSubtitle,anaRoute,sidebarVariant='default',sidebarClassName='',query,onQueryChange,searchPlaceholder,searchActionLabel,onSearchAction,name,role,avatarUrl='',initials,onToggleTheme,onLogout,topbar,mainClassName='',contentClassName='',legacyDirectionTheme=false,children}:Props){
 const navigate=useNavigate();const{pathname}=useLocation();const[effectiveTheme,setEffectiveTheme]=useState<Theme>(()=>storedTheme(theme));const[mobileNavOpen,setMobileNavOpen]=useState(false);const menuButtonRef=useRef<HTMLButtonElement>(null);const drawerRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{persistTheme(effectiveTheme)},[effectiveTheme]);useEffect(()=>{if(theme!==effectiveTheme)onToggleTheme()},[theme,effectiveTheme,onToggleTheme]);
 useEffect(()=>{if(!mobileNavOpen)return;const previous=document.activeElement as HTMLElement|null;drawerRef.current?.querySelector<HTMLButtonElement>('button')?.focus();function onKeyDown(event:KeyboardEvent){if(event.key==='Escape'){setMobileNavOpen(false);requestAnimationFrame(()=>menuButtonRef.current?.focus())}}window.addEventListener('keydown',onKeyDown);return()=>{window.removeEventListener('keydown',onKeyDown);if(previous&&document.contains(previous))previous.focus()}},[mobileNavOpen]);
 function toggleTheme(){setEffectiveTheme(current=>current==='light'?'dark':'light')}function closeMobileNav(){setMobileNavOpen(false);requestAnimationFrame(()=>menuButtonRef.current?.focus())}
 const forceStandardTopbar=pathname==='/expedientes/nuevo'||pathname==='/contactos/nuevo'||pathname==='/tareas/nueva'||pathname==='/perfil';
 const useExternalCreateSidebar=pathname==='/expedientes/nuevo'||pathname==='/contactos/nuevo';
 const standardTopbar=<OperationalTopbar theme={effectiveTheme} onToggleTheme={toggleTheme} query={query} onQueryChange={onQueryChange} placeholder={searchPlaceholder} searchActionLabel={searchActionLabel} onSearchAction={onSearchAction} name={name} role={role} avatarUrl={avatarUrl} initials={initials} onLogout={onLogout}/>;
 const renderedTopbar=!forceStandardTopbar&&topbar?(isValidElement(topbar)?cloneElement(topbar as ReactElement<any>,{theme:effectiveTheme,onToggleTheme:toggleTheme}):topbar):standardTopbar;
 const rootClass=`ops-root ${sidebarVariant==='direction'?'ops-direction-frame ':''}${className}`.trim();const authorized=new Set(navigation.map(item=>item.route));const can=(route:string)=>route==='/inicio'||authorized.has(route)||authorized.has(`/${route.split('/')[1]}`);const quickLinks=[{route:'/expedientes/nuevo',label:'+ Nuevo expediente',Icon:FolderOpen},{route:'/contactos/nuevo',label:'+ Nuevo contacto',Icon:UserRound},{route:'/inmobiliarias',label:'Inmobiliarias',Icon:Building2},{route:'/agenda',label:'Agenda',Icon:CalendarDays},{route:'/documentacion',label:'Documentación',Icon:FileText},{route:'/informes',label:'Informes',Icon:BarChart3}].filter(item=>can(item.route));const showSharedFooter=activeRoute!=='/inicio';
 return <div className={rootClass} data-theme={effectiveTheme} data-dir-theme={legacyDirectionTheme?effectiveTheme:undefined} data-mobile-nav={mobileNavOpen?'open':'closed'}>
  <style>{`.ops-root>.ops-side{grid-column:1!important;visibility:visible!important;opacity:1!important;z-index:7800!important}.ops-root>.ops-main{grid-column:2!important}.ops-root.ops-direction-frame{grid-template-columns:238px minmax(0,1fr)!important}@media(max-width:1000px) and (min-width:901px){.ops-root.ops-direction-frame{grid-template-columns:96px minmax(0,1fr)!important}}@media(max-width:900px){.ops-root.ops-direction-frame{grid-template-columns:96px minmax(0,1fr)!important}}@media(max-width:760px){.ops-root.ops-direction-frame{display:block!important}.ops-root.ops-direction-frame>.ops-main{grid-column:auto!important}}`}</style>
  {!useExternalCreateSidebar&&<button ref={menuButtonRef} type="button" className="ops-mobile-menu-button" aria-label={mobileNavOpen?'Cerrar menú':'Abrir menú'} aria-expanded={mobileNavOpen} aria-controls="ops-mobile-drawer" onClick={()=>setMobileNavOpen(open=>!open)}>{mobileNavOpen?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}<span>Menú</span></button>}
  {!useExternalCreateSidebar&&<OperationalSidebar navigation={navigation} activeRoute={activeRoute} anaSubtitle={anaSubtitle} anaRoute={anaRoute} variant={sidebarVariant} className={sidebarClassName}/>} 
  {!useExternalCreateSidebar&&mobileNavOpen&&<><div ref={drawerRef} id="ops-mobile-drawer" className="ops-mobile-drawer" role="dialog" aria-modal="true" aria-label="Navegación principal"><OperationalSidebar navigation={navigation} activeRoute={activeRoute} anaSubtitle={anaSubtitle} anaRoute={anaRoute} variant={sidebarVariant} className="ops-mobile-drawer-sidebar" onNavigate={closeMobileNav}/></div><button type="button" className="ops-mobile-backdrop" aria-label="Cerrar menú" onClick={closeMobileNav}/></>}
  <main className={`ops-main ${mainClassName}`.trim()}>{renderedTopbar}<section className={`ops-content ${contentClassName}`.trim()}>{children}{showSharedFooter&&quickLinks.length>0&&<section className="dir-quick ops-shared-quick" aria-label="Accesos rápidos"><h2>ACCESOS RÁPIDOS</h2><div className="dir-quick-grid">{quickLinks.map(({route,label,Icon})=><button key={route} type="button" onClick={()=>navigate(route)}><Icon/>{label}</button>)}</div></section>}</section></main>
 </div>;
}
