import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,BriefcaseBusiness,KeyRound,Mail,ShieldCheck,UserPlus,UserRound} from 'lucide-react';
import type {Session} from '@supabase/supabase-js';
import {fetchAppApi,fetchEnvironmentApi,supabase} from './supabase';
import {anaAvatar} from './assets/visualAssets';
import OperationalShellFrame from './OperationalShellFrame';
import type {NavItem} from './masterNavigation';
import './operational.css';
import './profile-shell.css';

type Theme='light'|'dark';
type Ctx={role?:string;actor_code?:string;worker_id?:string};
type Row=Record<string,unknown>;
type PersonalResponse={items?:Row[]};
type Profile={actor_code:string;display_name?:string;role:string;zone_code?:string;email?:string;active?:boolean};
type ProfileResponse={ok?:boolean;status?:number;profile?:Profile;error?:string};
type AdminUser={actor_code:string;display_name?:string;role:string;email?:string;active?:boolean};
type AdminResponse={ok?:boolean;status?:number;items?:AdminUser[];can_create_director?:boolean;error?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function labelFromRoute(route:string){return route.replace(/^\//,'').replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase())||'Inicio';}
function normalizeNav(data:unknown):NavItem[]{if(!data||typeof data!=='object')return[];const xs=(data as{items?:unknown[]}).items;if(!Array.isArray(xs))return[];return xs.map(x=>{if(typeof x==='string'&&x.startsWith('/'))return{label:labelFromRoute(x),route:x};if(x&&typeof x==='object'){const o=x as Record<string,unknown>;if(typeof o.route==='string'&&o.route.startsWith('/'))return{label:typeof o.label==='string'&&o.label.trim()?o.label.trim():labelFromRoute(o.route),route:o.route};}return null;}).filter((x):x is NavItem=>Boolean(x)).filter(x=>x.route!=='/buscar'&&x.route!=='/perfil');}
function sessionIdentity(session:Session|null){const meta=session?.user?.user_metadata as Record<string,unknown>|undefined;const candidate=[meta?.full_name,meta?.name,meta?.nombre].find(v=>typeof v==='string'&&v.trim());const image=[meta?.avatar_url,meta?.picture,meta?.photo_url,meta?.foto].find(v=>typeof v==='string'&&/^https:\/\//i.test(v.trim()));return{email:session?.user?.email??'',name:typeof candidate==='string'?candidate.trim():'',photo:typeof image==='string'?image.trim():''};}
function num(row:Row|null,keys:string[]){if(!row)return null;for(const k of keys){const v=row[k];if(typeof v==='number'&&Number.isFinite(v))return v;}return null;}
function matchesSelf(row:Row,ctx:Ctx|null){const actor=typeof ctx?.actor_code==='string'?ctx.actor_code.trim():'';const worker=typeof ctx?.worker_id==='string'?ctx.worker_id.trim():'';const rowActor=typeof row.actor_code==='string'?row.actor_code.trim():'';const rowWorker=typeof row.worker_id==='string'?row.worker_id.trim():'';return Boolean((actor&&rowActor===actor)||(worker&&rowWorker===worker));}
function normalizeRole(v:string|undefined){return(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();}
function isDirectionRole(v:string|undefined){const role=normalizeRole(v);return role==='direccion'||role==='direccion financiera'||role.startsWith('direccion ');}
function strongPassword(v:string){return v.length>=12&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/[0-9]/.test(v)&&/[^A-Za-z0-9]/.test(v);}
function temporaryPassword(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ',b='abcdefghijkmnopqrstuvwxyz',c='23456789',d='!@#$%*-_';const pick=(s:string)=>s[crypto.getRandomValues(new Uint32Array(1))[0]%s.length];const all=a+b+c+d;let value=pick(a)+pick(b)+pick(c)+pick(d);while(value.length<16)value+=pick(all);return value.split('').sort(()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296-.5).join('');}

export default function ProfileShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/perfil';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[email,setEmail]=useState(''),[name,setName]=useState(''),[photo,setPhoto]=useState('');
 const[personalStatus,setPersonalStatus]=useState<number|null>(null),[selfRow,setSelfRow]=useState<Row|null>(null);
 const[profile,setProfile]=useState<Profile|null>(null),[editProfile,setEditProfile]=useState(false),[profileName,setProfileName]=useState(''),[profileZone,setProfileZone]=useState(''),[profileMsg,setProfileMsg]=useState(''),[savingProfile,setSavingProfile]=useState(false);
 const[ownPassword,setOwnPassword]=useState(''),[ownConfirm,setOwnConfirm]=useState(''),[ownMsg,setOwnMsg]=useState(''),[savingOwn,setSavingOwn]=useState(false);
 const[adminUsers,setAdminUsers]=useState<AdminUser[]>([]),[adminReady,setAdminReady]=useState(false),[canCreateDirector,setCanCreateDirector]=useState(false),[adminMsg,setAdminMsg]=useState('');
 const[newName,setNewName]=useState(''),[newEmail,setNewEmail]=useState(''),[newRole,setNewRole]=useState('Financiero'),[newUserPassword,setNewUserPassword]=useState(''),[creating,setCreating]=useState(false);
 const[resetActor,setResetActor]=useState(''),[resetPassword,setResetPassword]=useState(''),[resetting,setResetting]=useState(false);
 useEffect(()=>{let alive=true;const apply=(session:Session|null)=>{if(!alive)return;const identity=sessionIdentity(session);setLogged(Boolean(session));setReady(true);setEmail(identity.email);setName(identity.name);setPhoto(identity.photo)};supabase.auth.getSession().then(({data})=>apply(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>apply(s));return()=>{alive=false;subscription.unsubscribe()};},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{const[c,n,p,pr]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchAppApi<PersonalResponse>('/personal'),fetchEnvironmentApi<ProfileResponse>('fenix-profile-api','')]);if(!alive)return;const nextCtx=c.status===200?c.data:null;setCtx(nextCtx);setNav(n.status===200?normalizeNav(n.data):[]);setPersonalStatus(p.status);const rows=p.status===200?(p.data?.items??[]):[];setSelfRow(rows.find(r=>matchesSelf(r,nextCtx))??null);if(pr.status===200&&pr.data?.profile){setProfile(pr.data.profile);setProfileName(pr.data.profile.display_name||'');setProfileZone(pr.data.profile.zone_code||'');}if(isDirectionRole(nextCtx?.role)){const adm=await fetchEnvironmentApi<AdminResponse>('fenix-user-admin','');if(!alive)return;setAdminReady(adm.status===200);setAdminUsers(adm.status===200?(adm.data?.items??[]):[]);setCanCreateDirector(Boolean(adm.data?.can_create_director));}})();return()=>{alive=false};},[active,logged]);
 const displayName=profile?.display_name||name||email||'Usuario';const initials=displayName.split(/\s+|@/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'FC';const effectiveNav=nav.length?nav:fallbackNav;
 const expedientes=num(selfRow,['expedientes','expedientes_en_curso']);const firmas=num(selfRow,['firmas_mes','firmas','firmas_del_mes']);const zone=profile?.zone_code||'';const statsAvailable=expedientes!==null||firmas!==null;
 const isDirection=isDirectionRole(ctx?.role);
 const anaText=useMemo(()=>{if(personalStatus===null)return'Estoy comprobando si existe una fuente autorizada de rendimiento para tu perfil.';if(personalStatus===403)return'Tus estadísticas personales no están disponibles para este ámbito. No voy a inferirlas.';if(personalStatus!==200)return'No he podido leer ahora la fuente autorizada de estadísticas personales.';if(!selfRow)return'La fuente de personal no identifica de forma inequívoca este usuario. Mantengo las estadísticas como no disponibles para no atribuirte datos de otra persona.';const parts:string[]=[];if(expedientes!==null)parts.push(`Tienes ${expedientes} expediente${expedientes===1?'':'s'} visible${expedientes===1?'':'s'} en tu ficha autorizada.`);if(firmas!==null)parts.push(`La fuente informa ${firmas} firma${firmas===1?'':'s'} este mes.`);if(!parts.length)return'Tu ficha está identificada, pero todavía no contiene métricas suficientes para analizar rendimiento.';return parts.join(' ');},[personalStatus,selfRow,expedientes,firmas]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();setProfileMsg('');const cleanName=profileName.trim(),cleanZone=profileZone.trim();if(cleanName.length<2){setProfileMsg('El nombre debe tener al menos 2 caracteres.');return}setSavingProfile(true);const r=await fetchEnvironmentApi<ProfileResponse>('fenix-profile-api','',{method:'PATCH',body:JSON.stringify({display_name:cleanName,zone_code:cleanZone})});setSavingProfile(false);if(r.status!==200||!r.data?.profile){setProfileMsg('No se pudo guardar el perfil.');return}setProfile(r.data.profile);setProfileName(r.data.profile.display_name||'');setProfileZone(r.data.profile.zone_code||'');setEditProfile(false);setProfileMsg('Perfil actualizado correctamente.');}
 function cancelProfileEdit(){setProfileName(profile?.display_name||'');setProfileZone(profile?.zone_code||'');setProfileMsg('');setEditProfile(false);}
 async function reloadAdmin(){const adm=await fetchEnvironmentApi<AdminResponse>('fenix-user-admin','');setAdminReady(adm.status===200);setAdminUsers(adm.status===200?(adm.data?.items??[]):[]);setCanCreateDirector(Boolean(adm.data?.can_create_director));}
 async function changeOwnPassword(e:React.FormEvent){e.preventDefault();setOwnMsg('');if(!strongPassword(ownPassword)){setOwnMsg('Usa al menos 12 caracteres, con mayúscula, minúscula, número y símbolo.');return}if(ownPassword!==ownConfirm){setOwnMsg('Las contraseñas no coinciden.');return}setSavingOwn(true);const{error}=await supabase.auth.updateUser({password:ownPassword});setSavingOwn(false);if(error){setOwnMsg('No se pudo cambiar la contraseña.');return}setOwnPassword('');setOwnConfirm('');setOwnMsg('Contraseña actualizada correctamente.');}
 async function createUser(e:React.FormEvent){e.preventDefault();setAdminMsg('');if(!strongPassword(newUserPassword)){setAdminMsg('La contraseña temporal debe tener al menos 12 caracteres, con mayúscula, minúscula, número y símbolo.');return}setCreating(true);const r=await fetchEnvironmentApi<{ok?:boolean;error?:string}>('fenix-user-admin','',{method:'POST',body:JSON.stringify({action:'create_user',email:newEmail,display_name:newName,role:newRole,password:newUserPassword})});setCreating(false);if(r.status!==201){setAdminMsg(r.data?.error==='email_exists'?'Ese email ya está dado de alta.':'No se pudo crear el usuario.');return}setNewName('');setNewEmail('');setNewRole('Financiero');setNewUserPassword('');setAdminMsg('Usuario creado y vinculado correctamente.');await reloadAdmin();}
 async function resetOtherPassword(e:React.FormEvent){e.preventDefault();setAdminMsg('');if(!resetActor||!strongPassword(resetPassword)){setAdminMsg('Selecciona un usuario y usa una contraseña de al menos 12 caracteres con mayúscula, minúscula, número y símbolo.');return}setResetting(true);const r=await fetchEnvironmentApi<{ok?:boolean;error?:string}>('fenix-user-admin','',{method:'POST',body:JSON.stringify({action:'reset_password',actor_code:resetActor,password:resetPassword})});setResetting(false);if(r.status!==200){setAdminMsg('No se pudo cambiar la contraseña de ese usuario.');return}setResetActor('');setResetPassword('');setAdminMsg('Contraseña del usuario actualizada correctamente.');}
 if(!active||!ready||!logged)return null;
 return <OperationalShellFrame className="profile-root" theme={theme} navigation={effectiveNav} activeRoute="/perfil" anaSubtitle="Tu asistente dentro de Fénix." anaRoute="/ana" query="" onQueryChange={()=>{}} searchPlaceholder="Buscar expediente, cliente, banco, inmobiliaria..." name={displayName} role={ctx?.role||''} avatarUrl={photo} initials={initials} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={async()=>{await supabase.auth.signOut();}} contentClassName="profile-content">
  <section className="profile-ana-hero"><img src={anaAvatar} alt="Ana"/><div><small>ANA · TU RENDIMIENTO</small><h2>Cómo vas y dónde mejorar</h2><p>{anaText}</p><div className="profile-ana-actions"><button onClick={()=>navigate('/expedientes')}>Revisar expedientes</button><button onClick={()=>navigate('/firmas')}>Revisar firmas</button><button onClick={()=>navigate('/ana?mode=help&resource=perfil')}>Analizar conmigo</button></div></div></section>
  <div className="profile-heading"><small>IDENTIDAD Y RENDIMIENTO</small><h1>Mi perfil</h1><p>Datos de perfil, seguridad de acceso y administración autorizada del equipo.</p></div>
  <section className="profile-card">{photo?<img className="profile-avatar-big" src={photo} alt={`Foto de ${displayName}`}/>:<div className="profile-avatar-big" aria-label="Foto de perfil no disponible">{initials}</div>}<div className="profile-main-copy"><h2>{displayName}</h2><span>{ctx?.role||'Rol no disponible'}</span>{zone&&<p>{zone}</p>}</div><div className="profile-data"><article><UserRound/><div><small>NOMBRE</small><strong>{displayName}</strong></div></article><article><Mail/><div><small>EMAIL</small><strong>{email||profile?.email||'No disponible'}</strong></div></article><article><ShieldCheck/><div><small>ROL</small><strong>{ctx?.role||'No disponible'}</strong></div></article></div></section>
  <section className="profile-grid"><article className="profile-professional"><div><BriefcaseBusiness size={19}/><strong>Ficha profesional</strong></div>{editProfile?<form onSubmit={saveProfile} style={{display:'grid',gap:10,marginTop:14}}><label>Nombre<input value={profileName} onChange={e=>setProfileName(e.target.value)} maxLength={120} required/></label><label>Zona<input value={profileZone} onChange={e=>setProfileZone(e.target.value)} maxLength={80} placeholder="Zona de actuación"/></label><div style={{display:'flex',gap:8}}><button className="primary" disabled={savingProfile}>{savingProfile?'Guardando…':'Guardar cambios'}</button><button type="button" onClick={cancelProfileEdit} disabled={savingProfile}>Cancelar</button></div></form>:<><dl><div><dt>Nombre</dt><dd>{displayName}</dd></div><div><dt>Zona</dt><dd>{zone||'No informada'}</dd></div><div><dt>Email</dt><dd>{email||profile?.email||'No disponible'}</dd></div><div><dt>Rol</dt><dd>{ctx?.role||'No disponible'}</dd></div></dl><button onClick={()=>{setProfileName(profile?.display_name||name);setProfileZone(profile?.zone_code||'');setProfileMsg('');setEditProfile(true)}}>Editar perfil</button></>}{profileMsg&&<p>{profileMsg}</p>}<small>El rol y los permisos no se pueden modificar desde el perfil.</small></article><article className="profile-professional"><div><KeyRound size={19}/><strong>Cambiar mi contraseña</strong></div><form onSubmit={changeOwnPassword} style={{display:'grid',gap:10,marginTop:14}}><input type="password" autoComplete="new-password" placeholder="Nueva contraseña" value={ownPassword} onChange={e=>setOwnPassword(e.target.value)} required/><input type="password" autoComplete="new-password" placeholder="Repite la nueva contraseña" value={ownConfirm} onChange={e=>setOwnConfirm(e.target.value)} required/><button className="primary" disabled={savingOwn}>{savingOwn?'Guardando…':'Cambiar contraseña'}</button>{ownMsg&&<p>{ownMsg}</p>}</form></article></section>
  {isDirection&&<section className="profile-professional" style={{marginTop:18}}><div><UserPlus size={19}/><strong>Alta y contraseñas del equipo</strong></div><p>{canCreateDirector?'Carlos puede crear Directores, Financieros y Visitadores.':'Dirección puede crear Financieros y Visitadores.'}</p><form onSubmit={createUser} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,marginTop:14}}><input placeholder="Nombre y apellidos" value={newName} onChange={e=>setNewName(e.target.value)} required/><input type="email" placeholder="Email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} required/><select value={newRole} onChange={e=>setNewRole(e.target.value)}><option value="Financiero">Financiero</option><option value="Visitador">Visitador</option>{canCreateDirector&&<option value="Direccion">Director</option>}</select><div style={{display:'flex',gap:8}}><input type="text" placeholder="Contraseña temporal" value={newUserPassword} onChange={e=>setNewUserPassword(e.target.value)} required style={{flex:1}}/><button type="button" onClick={()=>setNewUserPassword(temporaryPassword())}>Generar</button></div><button className="primary" disabled={creating}>{creating?'Creando…':'Dar de alta'}</button></form><form onSubmit={resetOtherPassword} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,marginTop:18}}><select value={resetActor} onChange={e=>setResetActor(e.target.value)} required><option value="">Selecciona usuario</option>{adminUsers.map(u=><option key={u.actor_code} value={u.actor_code}>{u.display_name||u.email||u.actor_code} · {u.role}</option>)}</select><div style={{display:'flex',gap:8}}><input type="text" placeholder="Nueva contraseña" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} required style={{flex:1}}/><button type="button" onClick={()=>setResetPassword(temporaryPassword())}>Generar</button></div><button className="primary" disabled={resetting||!adminReady}>{resetting?'Guardando…':'Cambiar contraseña'}</button></form>{adminMsg&&<p>{adminMsg}</p>}</section>}
  <section className="profile-kpis"><article><small>EXPEDIENTES</small><strong>{expedientes??'—'}</strong><span>{expedientes===null?'No disponible en fuente autorizada':'Valor personal expuesto por gateway'}</span></article><article><small>FIRMAS MES</small><strong>{firmas??'—'}</strong><span>{firmas===null?'No disponible en fuente autorizada':'Valor personal expuesto por gateway'}</span></article><article><small>ZONA</small><strong>{zone||'—'}</strong><span>{zone?'Informada en tu perfil':'No informada'}</span></article></section>
  <section className="profile-grid"><article className="profile-chart-card"><div><BarChart3 size={19}/><strong>Actividad personal</strong></div>{statsAvailable?<div className="profile-bars">{expedientes!==null&&<div><span>Expedientes</span><i><b style={{width:`${Math.min(100,Math.max(8,expedientes*10))}%`}}/></i><em>{expedientes}</em></div>}{firmas!==null&&<div><span>Firmas mes</span><i><b style={{width:`${Math.min(100,Math.max(8,firmas*20))}%`}}/></i><em>{firmas}</em></div>}</div>:<p>Histórico insuficiente o métricas personales no disponibles.</p>}<small>Visualización descriptiva de valores presentes; no representa objetivos ni porcentajes de rendimiento.</small></article></section>
 </OperationalShellFrame>;
}
