import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,BriefcaseBusiness,LockKeyhole,Mail,Save,ShieldCheck,UserRound} from 'lucide-react';
import type {Session} from '@supabase/supabase-js';
import {fetchAppApi,supabase} from './supabase';
import {anaAvatar} from './assets/visualAssets';
import OperationalShellFrame from './OperationalShellFrame';
import StaffAdminPanel from './StaffAdminPanel';
import type {NavItem} from './masterNavigation';
import './operational.css';
import './profile-shell.css';

type Theme='light'|'dark';
type Ctx={role?:string;actor_code?:string;worker_id?:string};
type Row=Record<string,unknown>;
type PersonalResponse={items?:Row[]};
type Profile={actor_code?:string;role?:string;display_name:string;username:string;birth_date:string;contact_email:string;phone:string;job_title:string;zone:string;bio:string;linkedin:string;instagram:string;website:string;avatar_url:string;login_email:string};
type ProfilePayload={ok?:boolean;status?:number;item?:Partial<Profile>;error?:string};
const emptyProfile:Profile={display_name:'',username:'',birth_date:'',contact_email:'',phone:'',job_title:'',zone:'',bio:'',linkedin:'',instagram:'',website:'',avatar_url:'',login_email:''};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function labelFromRoute(route:string){return route.replace(/^\//,'').replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase())||'Inicio';}
function normalizeNav(data:unknown):NavItem[]{if(!data||typeof data!=='object')return[];const xs=(data as{items?:unknown[]}).items;if(!Array.isArray(xs))return[];return xs.map(x=>{if(typeof x==='string'&&x.startsWith('/'))return{label:labelFromRoute(x),route:x};if(x&&typeof x==='object'){const o=x as Record<string,unknown>;if(typeof o.route==='string'&&o.route.startsWith('/'))return{label:typeof o.label==='string'&&o.label.trim()?o.label.trim():labelFromRoute(o.route),route:o.route};}return null;}).filter((x):x is NavItem=>Boolean(x)).filter(x=>x.route!=='/buscar'&&x.route!=='/perfil');}
function sessionIdentity(session:Session|null){const meta=session?.user?.user_metadata as Record<string,unknown>|undefined;const candidate=[meta?.full_name,meta?.name,meta?.nombre].find(v=>typeof v==='string'&&v.trim());const image=[meta?.avatar_url,meta?.picture,meta?.photo_url,meta?.foto].find(v=>typeof v==='string'&&/^https:\/\//i.test(v.trim()));return{email:session?.user?.email??'',name:typeof candidate==='string'?candidate.trim():'',photo:typeof image==='string'?image.trim():''};}
function num(row:Row|null,keys:string[]){if(!row)return null;for(const k of keys){const v=row[k];if(typeof v==='number'&&Number.isFinite(v))return v;}return null;}
function matchesSelf(row:Row,ctx:Ctx|null){const actor=typeof ctx?.actor_code==='string'?ctx.actor_code.trim():'';const worker=typeof ctx?.worker_id==='string'?ctx.worker_id.trim():'';const rowActor=typeof row.actor_code==='string'?row.actor_code.trim():'';const rowWorker=typeof row.worker_id==='string'?row.worker_id.trim():'';return Boolean((actor&&rowActor===actor)||(worker&&rowWorker===worker));}
function ageFromDate(value:string){if(!value)return null;const d=new Date(`${value}T00:00:00`);if(Number.isNaN(d.getTime()))return null;const now=new Date();let age=now.getFullYear()-d.getFullYear();const before=now.getMonth()<d.getMonth()||(now.getMonth()===d.getMonth()&&now.getDate()<d.getDate());if(before)age--;return age>=0?age:null;}
export default function ProfileShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/perfil';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[email,setEmail]=useState(''),[sessionName,setSessionName]=useState(''),[sessionPhoto,setSessionPhoto]=useState('');
 const[profile,setProfile]=useState<Profile>(emptyProfile),[profileBusy,setProfileBusy]=useState(false),[profileMessage,setProfileMessage]=useState(''),[profileError,setProfileError]=useState('');
 const[personalStatus,setPersonalStatus]=useState<number|null>(null),[selfRow,setSelfRow]=useState<Row|null>(null);
 const[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordBusy,setPasswordBusy]=useState(false),[passwordMessage,setPasswordMessage]=useState(''),[passwordError,setPasswordError]=useState('');
 useEffect(()=>{let alive=true;const apply=(session:Session|null)=>{if(!alive)return;const identity=sessionIdentity(session);setLogged(Boolean(session));setReady(true);setEmail(identity.email);setSessionName(identity.name);setSessionPhoto(identity.photo)};supabase.auth.getSession().then(({data})=>apply(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>apply(s));return()=>{alive=false;subscription.unsubscribe()};},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[theme]);
 async function loadProfile(){const r=await supabase.rpc('fenix_prod_profile_get_user');const d=r.data as ProfilePayload|null;if(r.error||!d?.ok||!d.item){setProfile(v=>({...v,display_name:v.display_name||sessionName||'',avatar_url:v.avatar_url||sessionPhoto||'',login_email:email}));return;}const item=d.item;setProfile({...emptyProfile,...item,display_name:String(item.display_name??sessionName??''),avatar_url:String(item.avatar_url??sessionPhoto??''),login_email:email});}
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{const[c,n,p]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchAppApi<PersonalResponse>('/personal')]);if(!alive)return;const nextCtx=c.status===200?c.data:null;setCtx(nextCtx);setNav(n.status===200?normalizeNav(n.data):[]);setPersonalStatus(p.status);const rows=p.status===200?(p.data?.items??[]):[];setSelfRow(rows.find(r=>matchesSelf(r,nextCtx))??null);await loadProfile();})();return()=>{alive=false};},[active,logged,email,sessionName,sessionPhoto]);
 const displayName=profile.display_name||sessionName||email||'Usuario';const photo=profile.avatar_url||sessionPhoto;const initials=displayName.split(/\s+|@/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'FC';const effectiveNav=nav.length?nav:fallbackNav;
 const expedientes=num(selfRow,['expedientes','expedientes_en_curso']);const firmas=num(selfRow,['firmas_mes','firmas','firmas_del_mes']);const age=ageFromDate(profile.birth_date);const statsAvailable=expedientes!==null||firmas!==null;
 const anaText=useMemo(()=>{if(personalStatus===null)return'Estoy comprobando si existe una fuente autorizada de rendimiento para tu perfil.';if(personalStatus===403)return'Tus estadísticas personales no están disponibles para este ámbito. No voy a inferirlas.';if(personalStatus!==200)return'No he podido leer ahora la fuente autorizada de estadísticas personales.';if(!selfRow)return'Tu perfil es editable, pero la fuente de rendimiento todavía no contiene métricas inequívocas para este usuario.';const parts:string[]=[];if(expedientes!==null)parts.push(`Tienes ${expedientes} expediente${expedientes===1?'':'s'} visible${expedientes===1?'':'s'} en tu ficha autorizada.`);if(firmas!==null)parts.push(`La fuente informa ${firmas} firma${firmas===1?'':'s'} este mes.`);return parts.length?parts.join(' '):'Tu ficha está identificada, pero todavía no contiene métricas suficientes para analizar rendimiento.';},[personalStatus,selfRow,expedientes,firmas]);
 function field<K extends keyof Profile>(key:K,value:Profile[K]){setProfile(v=>({...v,[key]:value}));setProfileError('');setProfileMessage('');}
 async function saveProfile(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setProfileError('');setProfileMessage('');if(!profile.display_name.trim()){setProfileError('El nombre visible es obligatorio.');return;}setProfileBusy(true);const payload={display_name:profile.display_name,username:profile.username,birth_date:profile.birth_date,contact_email:profile.contact_email,phone:profile.phone,job_title:profile.job_title,zone:profile.zone,bio:profile.bio,linkedin:profile.linkedin,instagram:profile.instagram,website:profile.website,avatar_url:profile.avatar_url};const r=await supabase.rpc('fenix_prod_profile_update_user',{p_profile:payload});const d=r.data as ProfilePayload|null;if(r.error||!d?.ok){setProfileBusy(false);setProfileError(d?.error==='username_taken'?'Ese nombre de usuario ya está en uso.':'No se pudo guardar el perfil.');return;}let authNote='';if(profile.login_email.trim()&&profile.login_email.trim().toLowerCase()!==email.toLowerCase()){const{error:mailError}=await supabase.auth.updateUser({email:profile.login_email.trim()});authNote=mailError?' El email de acceso no pudo cambiarse.':' Revisa el correo de confirmación para completar el cambio del email de acceso.';}setProfileBusy(false);setProfileMessage(`Perfil actualizado correctamente.${authNote}`);await loadProfile();}
 async function changeOwnPassword(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setPasswordError('');setPasswordMessage('');if(newPassword.length<8){setPasswordError('La nueva contraseña debe tener al menos 8 caracteres.');return;}if(newPassword!==confirmPassword){setPasswordError('Las contraseñas no coinciden.');return;}setPasswordBusy(true);const{error}=await supabase.auth.updateUser({password:newPassword});setPasswordBusy(false);if(error){setPasswordError('No se pudo cambiar la contraseña. Vuelve a intentarlo.');return;}setNewPassword('');setConfirmPassword('');setPasswordMessage('Contraseña actualizada correctamente.');}
 if(!active||!ready||!logged)return null;
 return <OperationalShellFrame className="profile-root" theme={theme} navigation={effectiveNav} activeRoute="/perfil" anaSubtitle="Tu asistente dentro de Fénix." anaRoute="/ana" query="" onQueryChange={()=>{}} searchPlaceholder="Buscar expediente, cliente, banco, inmobiliaria..." name={displayName} role={ctx?.role||profile.role||''} avatarUrl={photo} initials={initials} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={async()=>{await supabase.auth.signOut();}} contentClassName="profile-content">
  <style>{`.profile-edit-card{border:1px solid var(--border,#ddd);border-radius:18px;background:var(--panel,#fff);padding:18px;display:grid;gap:16px}.profile-edit-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.profile-edit-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.profile-edit-grid label{display:grid;gap:5px;font-size:12px;font-weight:800}.profile-edit-grid input,.profile-edit-grid textarea{width:100%;box-sizing:border-box;border:1px solid var(--border,#ddd);border-radius:10px;background:var(--surface,#fff);color:var(--text,#222);padding:10px;font:inherit}.profile-edit-grid textarea{min-height:100px;resize:vertical}.profile-edit-grid .wide{grid-column:1/-1}.profile-edit-actions{display:flex;justify-content:flex-end;align-items:center;gap:10px}.profile-edit-actions button{display:inline-flex;align-items:center;gap:7px;border:0;border-radius:10px;padding:10px 15px;background:var(--orange,#c97845);color:#fff;font-weight:800;cursor:pointer}.profile-edit-message{font-size:12px}.profile-edit-message.error{color:#b42318}.profile-edit-message.success{color:#18794e}html[data-theme='dark'] .profile-edit-card{background:#17191d;border-color:#3b4048;color:#f5f7fa}html[data-theme='dark'] .profile-edit-grid input,html[data-theme='dark'] .profile-edit-grid textarea{background:#101216;color:#fff;border-color:#4a505a}@media(max-width:760px){.profile-edit-grid{grid-template-columns:1fr}.profile-edit-grid .wide{grid-column:auto}}`}</style>
  <section className="profile-ana-hero"><img src={anaAvatar} alt="Ana"/><div><small>ANA · TU RENDIMIENTO</small><h2>Cómo vas y dónde mejorar</h2><p>{anaText}</p><div className="profile-ana-actions"><button onClick={()=>navigate('/expedientes')}>Revisar expedientes</button><button onClick={()=>navigate('/firmas')}>Revisar firmas</button><button onClick={()=>navigate('/ana?mode=help&resource=perfil')}>Analizar conmigo</button></div></div></section>
  <div className="profile-heading"><small>IDENTIDAD, PERFIL Y RENDIMIENTO</small><h1>Mi perfil</h1><p>Edita tus datos personales y profesionales. El rol y los permisos continúan protegidos por el sistema.</p></div>
  <section className="profile-card">{photo?<img className="profile-avatar-big" src={photo} alt={`Foto de ${displayName}`}/>:<div className="profile-avatar-big" aria-label="Foto de perfil no disponible">{initials}</div>}<div className="profile-main-copy"><h2>{displayName}</h2><span>{profile.username?`@${profile.username}`:ctx?.role||profile.role||'Rol no disponible'}</span>{profile.zone&&<p>{profile.zone}</p>}</div><div className="profile-data"><article><UserRound/><div><small>NOMBRE</small><strong>{displayName}</strong></div></article><article><Mail/><div><small>EMAIL</small><strong>{profile.contact_email||email||'No disponible'}</strong></div></article><article><ShieldCheck/><div><small>ROL</small><strong>{ctx?.role||profile.role||'No disponible'}</strong></div></article></div></section>
  <form className="profile-edit-card" onSubmit={saveProfile} data-testid="editable-profile-form"><div className="profile-edit-head"><div><strong>Editar perfil completo</strong><p>Nombre, usuario, edad/fecha de nacimiento, contacto, puesto, zona, bio, redes y foto.</p></div><BriefcaseBusiness size={22}/></div><div className="profile-edit-grid"><label>Nombre visible<input aria-label="Nombre visible" value={profile.display_name} onChange={e=>field('display_name',e.target.value)} required/></label><label>Nombre de usuario<input aria-label="Nombre de usuario" value={profile.username} onChange={e=>field('username',e.target.value)} placeholder="carlos"/></label><label>Fecha de nacimiento<input aria-label="Fecha de nacimiento" type="date" value={profile.birth_date||''} onChange={e=>field('birth_date',e.target.value)}/><small>{age!==null?`${age} años`:''}</small></label><label>Email de contacto<input aria-label="Email de contacto" type="email" value={profile.contact_email} onChange={e=>field('contact_email',e.target.value)}/></label><label>Email de acceso<input aria-label="Email de acceso" type="email" value={profile.login_email} onChange={e=>field('login_email',e.target.value)}/><small>Si cambia, Supabase pedirá confirmación por correo.</small></label><label>Teléfono<input aria-label="Teléfono" value={profile.phone} onChange={e=>field('phone',e.target.value)}/></label><label>Puesto / cargo<input aria-label="Puesto o cargo" value={profile.job_title} onChange={e=>field('job_title',e.target.value)}/></label><label>Zona<input aria-label="Zona" value={profile.zone} onChange={e=>field('zone',e.target.value)}/></label><label className="wide">Bio<textarea aria-label="Bio" value={profile.bio} onChange={e=>field('bio',e.target.value)} maxLength={3000}/></label><label>LinkedIn<input aria-label="LinkedIn" value={profile.linkedin} onChange={e=>field('linkedin',e.target.value)}/></label><label>Instagram<input aria-label="Instagram" value={profile.instagram} onChange={e=>field('instagram',e.target.value)}/></label><label>Web<input aria-label="Web" value={profile.website} onChange={e=>field('website',e.target.value)}/></label><label>Foto / avatar URL<input aria-label="Foto o avatar URL" value={profile.avatar_url} onChange={e=>field('avatar_url',e.target.value)}/></label></div><div className="profile-edit-actions">{profileError&&<span className="profile-edit-message error" role="alert">{profileError}</span>}{profileMessage&&<span className="profile-edit-message success" role="status">{profileMessage}</span>}<button type="submit" disabled={profileBusy}><Save size={16}/>{profileBusy?'Guardando…':'Guardar perfil'}</button></div></form>
  <section className="profile-password-card" aria-labelledby="profile-password-title"><div className="profile-password-copy"><LockKeyhole size={20}/><div><strong id="profile-password-title">Seguridad de la cuenta</strong><p>Cambia únicamente la contraseña de tu propia cuenta autenticada. La contraseña nunca se registra en el Diario ni en ningún informe.</p></div></div><form onSubmit={changeOwnPassword}><label>Nueva contraseña<input aria-label="Nueva contraseña de mi cuenta" type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></label><label>Repite la contraseña<input aria-label="Repetir nueva contraseña de mi cuenta" type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></label><button type="submit" disabled={passwordBusy}>{passwordBusy?'Guardando…':'Cambiar mi contraseña'}</button></form>{passwordError&&<p className="profile-password-error" role="alert">{passwordError}</p>}{passwordMessage&&<p className="profile-password-success" role="status">{passwordMessage}</p>}</section>
  <StaffAdminPanel ctx={ctx}/>
  <section className="profile-kpis"><article><small>EXPEDIENTES</small><strong>{expedientes??'—'}</strong><span>{expedientes===null?'No disponible en fuente autorizada':'Valor personal expuesto por gateway'}</span></article><article><small>FIRMAS MES</small><strong>{firmas??'—'}</strong><span>{firmas===null?'No disponible en fuente autorizada':'Valor personal expuesto por gateway'}</span></article><article><small>EDAD</small><strong>{age??'—'}</strong><span>{age===null?'Añade tu fecha de nacimiento':'Calculada desde tu fecha de nacimiento'}</span></article></section>
  <section className="profile-grid"><article className="profile-chart-card"><div><BarChart3 size={19}/><strong>Actividad personal</strong></div>{statsAvailable?<div className="profile-bars">{expedientes!==null&&<div><span>Expedientes</span><i><b style={{width:`${Math.min(100,Math.max(8,expedientes*10))}%`}}/></i><em>{expedientes}</em></div>}{firmas!==null&&<div><span>Firmas mes</span><i><b style={{width:`${Math.min(100,Math.max(8,firmas*20))}%`}}/></i><em>{firmas}</em></div>}</div>:<p>Histórico insuficiente o métricas personales no disponibles.</p>}</article><article className="profile-professional"><div><BriefcaseBusiness size={19}/><strong>Ficha profesional</strong></div><dl><div><dt>Teléfono</dt><dd>{profile.phone||'No disponible'}</dd></div><div><dt>Bio</dt><dd>{profile.bio||'No disponible'}</dd></div><div><dt>Redes / enlaces</dt><dd>{[profile.linkedin,profile.instagram,profile.website].filter(Boolean).join(' · ')||'No disponibles'}</dd></div></dl><p>Todos estos datos se editan arriba y se guardan en la fuente canónica Fénix.</p></article></section>
 </OperationalShellFrame>;
}
