import {useEffect,useMemo,useState} from 'react';
import {KeyRound,ShieldCheck,UserPlus} from 'lucide-react';
import {fetchUserAdminApi} from './supabase';

type AdminUser={actor_code?:string;display_name?:string;role?:string;email?:string;active?:boolean};
type AdminListResponse={ok?:boolean;status?:number;items?:AdminUser[];can_create_director?:boolean;error?:string};
type AdminActionResponse={ok?:boolean;status?:number;actor_code?:string;role?:string;error?:string};
type Role='Direccion'|'Financiero'|'Visitador';

function validPassword(v:string){return v.length>=12&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/[0-9]/.test(v)&&/[^A-Za-z0-9]/.test(v);}

export default function ProfileUserAdminPanel({actorCode,role}:{actorCode?:string;role?:string}){
 const authorized=role==='Direccion'&&(actorCode==='CARLOS-ADMIN'||actorCode==='BELEN-DIR');
 const[status,setStatus]=useState<number|null>(null),[users,setUsers]=useState<AdminUser[]>([]),[canCreateDirector,setCanCreateDirector]=useState(false);
 const[email,setEmail]=useState(''),[displayName,setDisplayName]=useState(''),[newRole,setNewRole]=useState<Role>('Financiero'),[password,setPassword]=useState(''),[createBusy,setCreateBusy]=useState(false),[createMessage,setCreateMessage]=useState('');
 const[target,setTarget]=useState(''),[resetPassword,setResetPassword]=useState(''),[resetConfirm,setResetConfirm]=useState(''),[resetBusy,setResetBusy]=useState(false),[resetMessage,setResetMessage]=useState('');
 const roles=useMemo<Role[]>(()=>canCreateDirector?['Direccion','Financiero','Visitador']:['Financiero','Visitador'],[canCreateDirector]);
 async function reload(){if(!authorized)return;const r=await fetchUserAdminApi<AdminListResponse>();setStatus(r.status);if(r.status===200){setUsers(r.data?.items??[]);setCanCreateDirector(Boolean(r.data?.can_create_director));}else{setUsers([]);setCanCreateDirector(false);}}
 useEffect(()=>{void reload();},[authorized,actorCode]);
 if(!authorized)return null;
 async function createUser(){setCreateMessage('');const cleanEmail=email.trim().toLowerCase(),cleanName=displayName.trim();if(!/^\S+@\S+\.\S+$/.test(cleanEmail)||!cleanName||!validPassword(password)){setCreateMessage('Revisa email, nombre y contraseña segura de 12+ caracteres con mayúscula, minúscula, número y símbolo.');return}if(newRole==='Direccion'&&!canCreateDirector){setCreateMessage('Este perfil no puede crear otra cuenta de Dirección.');return}setCreateBusy(true);const r=await fetchUserAdminApi<AdminActionResponse>('',{method:'POST',body:JSON.stringify({action:'create_user',email:cleanEmail,display_name:cleanName,role:newRole,password})});setCreateBusy(false);if(r.status===201&&r.data?.ok){setEmail('');setDisplayName('');setPassword('');setCreateMessage(`Usuario creado: ${r.data.actor_code||cleanEmail}.`);await reload();return}setCreateMessage(r.data?.error==='email_exists'?'Ese email ya está registrado.':'No se pudo crear el usuario autorizado.');}
 async function resetTargetPassword(){setResetMessage('');if(!target){setResetMessage('Selecciona un usuario.');return}if(resetPassword!==resetConfirm){setResetMessage('Las contraseñas no coinciden.');return}if(!validPassword(resetPassword)){setResetMessage('Usa 12+ caracteres con mayúscula, minúscula, número y símbolo.');return}setResetBusy(true);const r=await fetchUserAdminApi<AdminActionResponse>('',{method:'POST',body:JSON.stringify({action:'reset_password',actor_code:target,password:resetPassword})});setResetBusy(false);if(r.status===200&&r.data?.ok){setResetPassword('');setResetConfirm('');setResetMessage('Contraseña restablecida y operación auditada.');return}setResetMessage('No se pudo restablecer la contraseña del usuario seleccionado.');}
 return <section className="profile-grid profile-admin-grid" data-testid="profile-user-admin">
  <article className="profile-professional"><div><UserPlus size={19}/><strong>Crear usuario autorizado</strong></div><div className="profile-edit-form"><label>Nombre<input value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={120}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="off"/></label><label>Rol<select value={newRole} onChange={e=>setNewRole(e.target.value as Role)}>{roles.map(x=><option key={x} value={x}>{x}</option>)}</select></label><label>Contraseña inicial<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><button disabled={createBusy} onClick={createUser}>{createBusy?'Creando…':'Crear usuario'}</button>{createMessage&&<p>{createMessage}</p>}<small>La contraseña se envía al contrato administrativo existente; no se almacena ni se vuelve a mostrar en la interfaz.</small></div></article>
  <article className="profile-professional"><div><KeyRound size={19}/><strong>Restablecer contraseña de usuario</strong></div>{status===null?<p>Cargando usuarios administrables…</p>:status!==200?<p>No está disponible el contrato administrativo autorizado.</p>:<div className="profile-edit-form"><label>Usuario<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Selecciona…</option>{users.map(u=><option key={u.actor_code} value={u.actor_code}>{u.display_name||u.email||u.actor_code} · {u.role||'sin rol'}</option>)}</select></label><label>Nueva contraseña<input type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} autoComplete="new-password"/></label><label>Repetir contraseña<input type="password" value={resetConfirm} onChange={e=>setResetConfirm(e.target.value)} autoComplete="new-password"/></label><button disabled={resetBusy} onClick={resetTargetPassword}>{resetBusy?'Restableciendo…':'Restablecer contraseña'}</button>{resetMessage&&<p>{resetMessage}</p>}<small>No se puede consultar la contraseña existente. El backend limita el alcance a usuarios creados por este administrador.</small></div>}</article>
  <article className="profile-professional profile-admin-note"><div><ShieldCheck size={19}/><strong>Alcance administrativo</strong></div><p>Este panel envuelve el contrato existente de administración: alta con rol permitido y restablecimiento de contraseña. No modifica roles de usuarios ya existentes porque ese contrato no existe todavía.</p></article>
 </section>;
}
