import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {BarChart3,BriefcaseBusiness,KeyRound,Mail,Moon,ShieldCheck,Sun,UserRound} from 'lucide-react';
import type {Session} from '@supabase/supabase-js';
import {fetchAppApi,fetchProfileApi,supabase} from './supabase';
import {anaAvatar} from './assets/visualAssets';
import OperationalShellFrame from './OperationalShellFrame';
import ProfileUserAdminPanel from './ProfileUserAdminPanel';
import type {NavItem} from './masterNavigation';
import './operational.css';
import './profile-shell.css';

type Theme='light'|'dark';
type Ctx={role?:string;actor_code?:string;worker_id?:string};
type Row=Record<string,unknown>;
type PersonalResponse={items?:Row[]};
type Profile={actor_code?:string;display_name?:string;role?:string;zone_code?:string|null;email?:string;active?:boolean};
type ProfileResponse={ok?:boolean;status?:number;profile?:Profile;error?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function labelFromRoute(route:string){return route.replace(/^\//,'').replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase())||'Inicio';}
function normalizeNav(data:unknown):NavItem[]{if(!data||typeof data!=='object')return[];const xs=(data as{items?:unknown[]}).items;if(!Array.isArray(xs))return[];return xs.map(x=>{if(typeof x==='string'&&x.startsWith('/'))return{label:labelFromRoute(x),route:x};if(x&&typeof x==='object'){const o=x as Record<string,unknown>;if(typeof o.route==='string'&&o.route.startsWith('/'))return{label:typeof o.label==='string'&&o.label.trim()?o.label.trim():labelFromRoute(o.route),route:o.route};}return null;}).filter((x):x is NavItem=>Boolean(x)).filter(x=>x.route!=='/buscar'&&x.route!=='/perfil');}
function cachedNavKey(userId:string){return `fenix-authorized-nav:${userId}`;}
function readCachedNav(userId:string){try{const raw=sessionStorage.getItem(cachedNavKey(userId));if(!raw)return[];const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed.filter((x):x is NavItem=>Boolean(x&&typeof x.label==='string'&&typeof x.route==='string'&&x.route.startsWith('/'))):[];}catch{return[];}}
function writeCachedNav(userId:string,items:NavItem[]){if(items.length)sessionStorage.setItem(cachedNavKey(userId),JSON.stringify(items));}
function sessionIdentity(session:Session|null){const meta=session?.user?.user_metadata as Record<string,unknown>|undefined;const candidate=[meta?.full_name,meta?.name,meta?.nombre].find(v=>typeof v==='string'&&v.trim());const image=[meta?.avatar_url,meta?.picture,meta?.photo_url,meta?.foto].find(v=>typeof v==='string'&&/^https:\/\//i.test(v.trim()));return{email:session?.user?.email??'',name:typeof candidate==='string'?candidate.trim():'',photo:typeof image==='string'?image.trim():''};}
function str(row:Row|null,keys:string[]){if(!row)return'';for(const k of keys){const v=row[k];if(typeof v==='string'&&v.trim())return v.trim();}return'';}
function num(row:Row|null,keys:string[]){if(!row)return null;for(const k of keys){const v=row[k];if(typeof v==='number'&&Number.isFinite(v))return v;}return null;}
function matchesSelf(row:Row,ctx:Ctx|null){const actor=ctx?.actor_code?.trim()||'',worker=ctx?.worker_id?.trim()||'',rowActor=typeof row.actor_code==='string'?row.actor_code.trim():'',rowWorker=typeof row.worker_id==='string'?row.worker_id.trim():'';return Boolean((actor&&rowActor===actor)||(worker&&rowWorker===worker));}
function strongPassword(v:string){return v.length>=12&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/[0-9]/.test(v)&&/[^A-Za-z0-9]/.test(v);}

export default function ProfileShell(){
 const location=useLocation(),navigate=useNavigate(),active=location.pathname==='/perfil';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[sessionUserId,setSessionUserId]=useState(''),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[sessionEmail,setSessionEmail]=useState(''),[sessionName,setSessionName]=useState(''),[photo,setPhoto]=useState('');
 const[personalStatus,setPersonalStatus]=useState<number|null>(null),[selfRow,setSelfRow]=useState<Row|null>(null),[profileStatus,setProfileStatus]=useState<number|null>(null),[profile,setProfile]=useState<Profile|null>(null);
 const[editName,setEditName]=useState(''),[editZone,setEditZone]=useState(''),[saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState('');
 const[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordBusy,setPasswordBusy]=useState(false),[passwordMessage,setPasswordMessage]=useState('');
 useEffect(()=>{let alive=true;const apply=(session:Session|null)=>{if(!alive)return;const identity=sessionIdentity(session);setLogged(Boolean(session));setReady(true);setSessionUserId(session?.user?.id??'');setSessionEmail(identity.email);setSessionName(identity.name);setPhoto(identity.photo)};supabase.auth.getSession().then(({data})=>apply(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>apply(s));return()=>{alive=false;subscription.unsubscribe()};},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{const[c,n,p,pr]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchAppApi<PersonalResponse>('/personal'),fetchProfileApi<ProfileResponse>()]);if(!alive)return;const nextCtx=c.status===200?c.data:null;setCtx(nextCtx);const liveNav=n.status===200?normalizeNav(n.data):[];if(liveNav.length){setNav(liveNav);if(sessionUserId)writeCachedNav(sessionUserId,liveNav);}else setNav(sessionUserId?readCachedNav(sessionUserId):[]);setPersonalStatus(p.status);const rows=p.status===200?(p.data?.items??[]):[];setSelfRow(rows.find(r=>matchesSelf(r,nextCtx))??null);setProfileStatus(pr.status);const nextProfile=pr.status===200?pr.data?.profile??null:null;setProfile(nextProfile);setEditName(nextProfile?.display_name||sessionName||'');setEditZone(nextProfile?.zone_code||'');})();return()=>{alive=false};},[active,logged,sessionUserId,sessionName]);
 const displayName=profile?.display_name||sessionName||profile?.email||sessionEmail||'Usuario',email=profile?.email||sessionEmail,zone=profile?.zone_code||str(selfRow,['zona','zona_actuacion','provincia','area']);
 const initials=displayName.split(/\s+|@/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'FC',effectiveNav=nav.length?nav:fallbackNav;
 const expedientes=num(selfRow,['expedientes','expedientes_en_curso']),firmas=num(selfRow,['firmas_mes','firmas','firmas_del_mes']),phone=str(selfRow,['telefono','teléfono','phone']),bio=str(selfRow,['bio','descripcion','descripción']),socials=[str(selfRow,['linkedin']),str(selfRow,['instagram']),str(selfRow,['web','website'])].filter(Boolean),statsAvailable=expedientes!==null||firmas!==null;
 const anaText=useMemo(()=>{if(personalStatus===null)return'Estoy comprobando si existe una fuente autorizada de rendimiento para tu perfil.';if(personalStatus===403)return'Tus estadísticas personales no están disponibles para este ámbito. No voy a inferirlas.';if(personalStatus!==200)return'No he podido leer ahora la fuente autorizada de estadísticas personales.';if(!selfRow)return'La fuente de personal no identifica de forma inequívoca este usuario. Mantengo las estadísticas como no disponibles para no atribuirte datos de otra persona.';const parts:string[]=[];if(expedientes!==null)parts.push(`Tienes ${expedientes} expediente${expedientes===1?'':'s'} visible${expedientes===1?'':'s'} en tu ficha autorizada.`);if(firmas!==null)parts.push(`La fuente informa ${firmas} firma${firmas===1?'':'s'} este mes.`);if(!parts.length)return'Tu ficha está identificada, pero todavía no contiene métricas suficientes para analizar rendimiento.';return parts.join(' ');},[personalStatus,selfRow,expedientes,firmas]);
 async function saveProfile(){const cleanName=editName.trim(),cleanZone=editZone.trim();setSaveMessage('');if(cleanName.length<2||cleanName.length>120||cleanZone.length>80){setSaveMessage('Revisa nombre y zona.');return}setSaving(true);const r=await fetchProfileApi<ProfileResponse>('',{method:'PATCH',body:JSON.stringify({display_name:cleanName,zone_code:cleanZone||null})});setSaving(false);if(r.status===200&&r.data?.profile){setProfile(r.data.profile);setEditName(r.data.profile.display_name||'');setEditZone(r.data.profile.zone_code||'');setSaveMessage('Perfil actualizado y auditado.');}else setSaveMessage('No se pudo guardar el perfil autorizado.');}
 async function changePassword(){setPasswordMessage('');if(newPassword!==confirmPassword){setPasswordMessage('Las contraseñas no coinciden.');return}if(!strongPassword(newPassword)){setPasswordMessage('Usa 12+ caracteres con mayúscula, minúscula, número y símbolo.');return}setPasswordBusy(true);const{error}=await supabase.auth.updateUser({password:newPassword});setPasswordBusy(false);if(error){setPasswordMessage('No se pudo cambiar la contraseña.');return}setNewPassword('');setConfirmPassword('');setPasswordMessage('Contraseña cambiada. La contraseña anterior nunca se muestra ni se recupera.');}
 if(!active||!ready||!logged)return null;
 const topbar=<header className="ops-top"><div className="ops-profile"><strong>Mi perfil</strong></div><div className="ops-top-actions"><button onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Cambiar tema">{theme==='light'?<Moon size={17}/>:<Sun size={17}/>} {theme==='light'?'Oscuro':'Claro'}</button></div></header>;
 return <OperationalShellFrame className="profile-root" theme={theme} navigation={effectiveNav} activeRoute="/perfil" anaSubtitle="Tu asistente dentro de Fénix." anaRoute="/ana" query="" onQueryChange={()=>{}} searchPlaceholder="" name={displayName} role={profile?.role||ctx?.role||''} avatarUrl={photo} initials={initials} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={async()=>{await supabase.auth.signOut();}} topbar={topbar} contentClassName="profile-content">
  <section className="profile-ana-hero"><img src={anaAvatar} alt="Ana"/><div><small>ANA · TU RENDIMIENTO</small><h2>Cómo vas y dónde mejorar</h2><p>{anaText}</p><div className="profile-ana-actions"><button onClick={()=>navigate('/expedientes')}>Revisar expedientes</button><button onClick={()=>navigate('/firmas')}>Revisar firmas</button><button onClick={()=>navigate('/ana?mode=help&resource=perfil')}>Analizar conmigo</button></div></div></section>
  <div className="profile-heading"><small>IDENTIDAD Y RENDIMIENTO</small><h1>Mi perfil</h1><p>La identidad editable usa el contrato autorizado de Perfil; rol y email siguen protegidos.</p></div>
  <section className="profile-card">{photo?<img className="profile-avatar-big" src={photo} alt={`Foto de ${displayName}`}/>:<div className="profile-avatar-big">{initials}</div>}<div className="profile-main-copy"><h2>{displayName}</h2><span>{profile?.role||ctx?.role||'Rol no disponible'}</span>{zone&&<p>{zone}</p>}</div><div className="profile-data"><article><UserRound/><div><small>NOMBRE</small><strong>{displayName}</strong></div></article><article><Mail/><div><small>EMAIL</small><strong>{email||'No disponible'}</strong></div></article><article><ShieldCheck/><div><small>ROL</small><strong>{profile?.role||ctx?.role||'No disponible'}</strong></div></article></div></section>
  <section className="profile-kpis"><article><small>EXPEDIENTES</small><strong>{expedientes??'—'}</strong><span>{expedientes===null?'No disponible en fuente autorizada':'Valor personal expuesto por gateway'}</span></article><article><small>FIRMAS MES</small><strong>{firmas??'—'}</strong><span>{firmas===null?'No disponible en fuente autorizada':'Valor personal expuesto por gateway'}</span></article><article><small>ZONA</small><strong>{zone||'—'}</strong><span>{zone?'Informada por la fuente':'No informada'}</span></article></section>
  <section className="profile-grid"><article className="profile-chart-card"><div><BarChart3 size={19}/><strong>Actividad personal</strong></div>{statsAvailable?<div className="profile-bars">{expedientes!==null&&<div><span>Expedientes</span><i><b style={{width:`${Math.min(100,Math.max(8,expedientes*10))}%`}}/></i><em>{expedientes}</em></div>}{firmas!==null&&<div><span>Firmas mes</span><i><b style={{width:`${Math.min(100,Math.max(8,firmas*20))}%`}}/></i><em>{firmas}</em></div>}</div>:<p>Histórico insuficiente o métricas personales no disponibles.</p>}<small>Visualización descriptiva; no inventa objetivos ni porcentajes.</small></article><article className="profile-professional"><div><BriefcaseBusiness size={19}/><strong>Ficha profesional</strong></div><dl><div><dt>Teléfono</dt><dd>{phone||'No disponible'}</dd></div><div><dt>Bio</dt><dd>{bio||'No disponible'}</dd></div><div><dt>Redes / enlaces</dt><dd>{socials.length?socials.join(' · '):'No disponibles'}</dd></div></dl><p>Teléfono, bio, redes y objetivos permanecen solo lectura hasta extender el contrato canónico; no se crea persistencia paralela.</p></article></section>
  <section className="profile-grid"><article className="profile-professional"><div><UserRound size={19}/><strong>Editar identidad autorizada</strong></div>{profileStatus===200?<div className="profile-edit-form"><label>Nombre<input value={editName} onChange={e=>setEditName(e.target.value)} maxLength={120}/></label><label>Zona<input value={editZone} onChange={e=>setEditZone(e.target.value)} maxLength={80}/></label><button disabled={saving} onClick={saveProfile}>{saving?'Guardando…':'Guardar cambios'}</button>{saveMessage&&<p>{saveMessage}</p>}</div>:<p>El contrato de Perfil no está disponible ahora. No se habilita una vía alternativa.</p>}</article><article className="profile-professional"><div><KeyRound size={19}/><strong>Seguridad de acceso</strong></div><div className="profile-edit-form"><label>Nueva contraseña<input type="password" autoComplete="new-password" value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>Repetir contraseña<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button disabled={passwordBusy} onClick={changePassword}>{passwordBusy?'Cambiando…':'Cambiar mi contraseña'}</button>{passwordMessage&&<p>{passwordMessage}</p>}<small>La contraseña actual nunca se solicita, muestra ni almacena en la interfaz.</small></div></article></section>
  <ProfileUserAdminPanel actorCode={ctx?.actor_code} role={ctx?.role}/>
 </OperationalShellFrame>;
}
