import {FormEvent,useEffect,useState} from 'react';
import {KeyRound,Link2,Plus,Save,ShieldCheck,UserCog} from 'lucide-react';
import {fetchProfileApi,fetchUserAdminApi,supabase} from './supabase';
import './profile-account-controls.css';

type Profile={actor_code:string;display_name:string;role:string;zone_code?:string|null;email?:string|null;active?:boolean};
type ProfileResponse={ok?:boolean;status?:number;profile?:Profile;error?:string};
type AdminUser={actor_code:string;display_name:string;role:string;email?:string|null;active:boolean};
type AdminResponse={ok?:boolean;status?:number;items?:AdminUser[];can_create_director?:boolean;error?:string};
type Socials={linkedin:string;instagram:string;facebook:string;x:string;tiktok:string;youtube:string;website:string;other:string};
const blankSocials:Socials={linkedin:'',instagram:'',facebook:'',x:'',tiktok:'',youtube:'',website:'',other:''};
function strongPassword(v:string){return v.length>=12&&/[A-Z]/.test(v)&&/[a-z]/.test(v)&&/[0-9]/.test(v)&&/[^A-Za-z0-9]/.test(v)}

export default function ProfileAccountControls(){
 const[profile,setProfile]=useState<Profile|null>(null),[name,setName]=useState(''),[zone,setZone]=useState(''),[phone,setPhone]=useState(''),[bio,setBio]=useState(''),[avatar,setAvatar]=useState(''),[socials,setSocials]=useState<Socials>(blankSocials);
 const[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[password,setPassword]=useState(''),[password2,setPassword2]=useState('');
 const[adminUsers,setAdminUsers]=useState<AdminUser[]>([]),[canAdmin,setCanAdmin]=useState(false),[canDirector,setCanDirector]=useState(false),[newEmail,setNewEmail]=useState(''),[newName,setNewName]=useState(''),[newRole,setNewRole]=useState('Financiero'),[newPassword,setNewPassword]=useState(''),[resetActor,setResetActor]=useState(''),[resetPassword,setResetPassword]=useState('');

 async function load(){
  const[{data:{session}},p,a]=await Promise.all([supabase.auth.getSession(),fetchProfileApi<ProfileResponse>(),fetchUserAdminApi<AdminResponse>()]);
  if(p.status===200&&p.data?.profile){const x=p.data.profile;setProfile(x);setName(x.display_name||'');setZone(x.zone_code||'')}
  const m=(session?.user?.user_metadata||{}) as Record<string,unknown>;setPhone(typeof m.phone==='string'?m.phone:'');setBio(typeof m.bio==='string'?m.bio:'');setAvatar(typeof m.avatar_url==='string'?m.avatar_url:'');const raw=m.social_links&&typeof m.social_links==='object'?m.social_links as Record<string,unknown>:{};setSocials({...blankSocials,...Object.fromEntries(Object.keys(blankSocials).map(k=>[k,typeof raw[k]==='string'?raw[k]:'']))} as Socials);
  if(a.status===200&&a.data?.ok){setCanAdmin(true);setAdminUsers(a.data.items||[]);setCanDirector(Boolean(a.data.can_create_director))}else{setCanAdmin(false);setAdminUsers([])}
 }
 useEffect(()=>{void load()},[]);
 async function saveProfile(e:FormEvent){e.preventDefault();if(!name.trim()){setNotice('El nombre es obligatorio.');return}setSaving(true);setNotice('');try{const p=await fetchProfileApi<ProfileResponse>('',{method:'PATCH',body:JSON.stringify({display_name:name.trim(),zone_code:zone.trim()||null})});if(p.status!==200||!p.data?.ok)throw new Error('profile');const{data:{session}}=await supabase.auth.getSession();const current=(session?.user?.user_metadata||{}) as Record<string,unknown>;const u=await supabase.auth.updateUser({data:{...current,full_name:name.trim(),phone:phone.trim(),bio:bio.trim(),avatar_url:avatar.trim(),social_links:socials}});if(u.error)throw u.error;setProfile(p.data.profile||null);setNotice('Perfil guardado correctamente.')}catch{setNotice('No se pudo guardar el perfil completo.')}finally{setSaving(false)}}
 async function changePassword(e:FormEvent){e.preventDefault();if(password!==password2){setNotice('Las contraseñas no coinciden.');return}if(!strongPassword(password)){setNotice('La contraseña debe tener al menos 12 caracteres, mayúscula, minúscula, número y símbolo.');return}setSaving(true);const r=await supabase.auth.updateUser({password});setSaving(false);if(r.error){setNotice('No se pudo cambiar la contraseña. Puede requerirse volver a iniciar sesión.');return}setPassword('');setPassword2('');setNotice('Contraseña actualizada.')}
 async function createUser(e:FormEvent){e.preventDefault();if(!canAdmin)return;if(!strongPassword(newPassword)){setNotice('La contraseña inicial no cumple la política de seguridad.');return}setSaving(true);const r=await fetchUserAdminApi<{ok?:boolean;error?:string}>('',{method:'POST',body:JSON.stringify({action:'create_user',email:newEmail.trim(),display_name:newName.trim(),role:newRole,password:newPassword})});setSaving(false);if(r.status!==201||!r.data?.ok){setNotice(r.data?.error==='email_exists'?'Ese email ya existe.':'No se pudo crear el usuario.');return}setNewEmail('');setNewName('');setNewPassword('');setNotice('Usuario creado y vinculado a su rol.');await load()}
 async function resetUserPassword(e:FormEvent){e.preventDefault();if(!resetActor||!strongPassword(resetPassword)){setNotice('Selecciona usuario y usa una contraseña segura.');return}setSaving(true);const r=await fetchUserAdminApi<{ok?:boolean;error?:string}>('',{method:'POST',body:JSON.stringify({action:'reset_password',actor_code:resetActor,password:resetPassword})});setSaving(false);if(r.status!==200||!r.data?.ok){setNotice('No se pudo restablecer la contraseña de ese usuario.');return}setResetPassword('');setNotice('Contraseña del usuario actualizada.')}
 const setSocial=(k:keyof Socials,v:string)=>setSocials(s=>({...s,[k]:v}));
 return <section className="profile-account-controls" aria-label="Editar perfil y seguridad">
  <header><div><UserCog size={20}/><span><strong>Cuenta y administración</strong><small>Edita tu perfil, redes, contraseña y usuarios autorizados.</small></span></div>{profile&&<span className="profile-account-role"><ShieldCheck size={14}/>{profile.role}</span>}</header>
  {notice&&<div className="profile-account-notice" role="status">{notice}</div>}
  <form className="profile-edit-grid" onSubmit={saveProfile}>
   <label>Nombre completo<input value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label><label>Zona<input value={zone} onChange={e=>setZone(e.target.value)} maxLength={80}/></label><label>Teléfono<input value={phone} onChange={e=>setPhone(e.target.value)} maxLength={40}/></label><label>Avatar / foto (URL)<input value={avatar} onChange={e=>setAvatar(e.target.value)} placeholder="https://…"/></label><label className="profile-wide">Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={1000}/></label>
   <fieldset className="profile-wide"><legend><Link2 size={15}/> Redes sociales y enlaces</legend><div className="profile-social-grid"><input value={socials.linkedin} onChange={e=>setSocial('linkedin',e.target.value)} placeholder="LinkedIn"/><input value={socials.instagram} onChange={e=>setSocial('instagram',e.target.value)} placeholder="Instagram"/><input value={socials.facebook} onChange={e=>setSocial('facebook',e.target.value)} placeholder="Facebook"/><input value={socials.x} onChange={e=>setSocial('x',e.target.value)} placeholder="X / Twitter"/><input value={socials.tiktok} onChange={e=>setSocial('tiktok',e.target.value)} placeholder="TikTok"/><input value={socials.youtube} onChange={e=>setSocial('youtube',e.target.value)} placeholder="YouTube"/><input value={socials.website} onChange={e=>setSocial('website',e.target.value)} placeholder="Web"/><input value={socials.other} onChange={e=>setSocial('other',e.target.value)} placeholder="Otro enlace"/></div></fieldset>
   <button className="profile-save" disabled={saving}><Save size={16}/>{saving?'Guardando…':'Guardar perfil'}</button>
  </form>
  <form className="profile-password" onSubmit={changePassword}><div><KeyRound size={18}/><span><strong>Cambiar mi contraseña</strong><small>Puedes cambiarla siempre que quieras.</small></span></div><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nueva contraseña"/><input type="password" autoComplete="new-password" value={password2} onChange={e=>setPassword2(e.target.value)} placeholder="Repetir contraseña"/><button disabled={saving||!password}>Actualizar contraseña</button></form>
  {canAdmin&&<section className="profile-admin"><header><Plus size={18}/><div><strong>Gestión de usuarios</strong><small>Crear usuarios por rol y restablecer sus contraseñas.</small></div></header><form onSubmit={createUser}><input type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="Email" required/><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nombre" required/><select value={newRole} onChange={e=>setNewRole(e.target.value)}><option>Financiero</option><option>Visitador</option>{canDirector&&<option>Direccion</option>}</select><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Contraseña inicial" required/><button disabled={saving}>Crear usuario</button></form><form onSubmit={resetUserPassword}><select value={resetActor} onChange={e=>setResetActor(e.target.value)}><option value="">Seleccionar usuario</option>{adminUsers.map(u=><option key={u.actor_code} value={u.actor_code}>{u.display_name||u.email||u.actor_code} · {u.role}</option>)}</select><input type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} placeholder="Nueva contraseña segura"/><button disabled={saving||!resetActor}>Cambiar contraseña</button></form></section>}
 </section>
}
