import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {FileText,Landmark,Search,Users} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import {anaVertical} from './assets/visualAssets';
import './operational.css';
import './search-shell.css';
import './inmobiliarias-polish.css';

type Theme='light'|'dark';type Row=Record<string,unknown>;type Ctx={role?:string};
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function rowsFrom(data:unknown):Row[]{if(!data||typeof data!=='object')return[];const d=data as Record<string,unknown>;for(const k of ['items','results','resultados'])if(Array.isArray(d[k]))return d[k] as Row[];return[];}
function first(r:Row,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number')return String(v);}return'';}
function groupOf(r:Row){const raw=first(r,['tipo','type','categoria','category','resource','entidad']).toLowerCase();if(raw.includes('exped'))return'Expedientes';if(raw.includes('contact')||raw.includes('client'))return'Contactos';if(raw.includes('inmobil'))return'Inmobiliarias';if(raw.includes('banco'))return'Bancos';if(raw.includes('tasac'))return'Tasaciones';if(raw.includes('firma'))return'Firmas';if(raw.includes('document'))return'Documentación';if(raw.includes('tarea'))return'Agenda';return'Otros';}
function titleOf(r:Row){return first(r,['titulo','title','label','nombre','name','cliente_alias','cliente','inmobiliaria','banco'])||'Resultado';}function metaOf(r:Row){return first(r,['meta','estado','stage','fase','localidad','email','descripcion','description'])||groupOf(r);}function iconFor(group:string){if(group==='Bancos')return<Landmark size={18}/>;if(group==='Contactos'||group==='Inmobiliarias')return<Users size={18}/>;return<FileText size={18}/>;}
export default function SearchShell(){
 const location=useLocation(),navigate=useNavigate();const active=location.pathname==='/buscar';const initial=new URLSearchParams(location.search).get('q')||'';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[query,setQuery]=useState(initial),[rows,setRows]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[area,setArea]=useState('Todos'),[refine,setRefine]=useState(''),[metaFilter,setMetaFilter]=useState(''),[sort,setSort]=useState('relevancia'),[exact,setExact]=useState(false);
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(alive){setLogged(Boolean(s));setReady(true)}});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;let alive=true;(async()=>{try{const[c,n]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]);if(!alive)return;setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);}catch{if(!alive)return;setCtx(null);setNav([]);}})();return()=>{alive=false};},[active,logged]);
 useEffect(()=>{if(!active||!logged)return;const q=new URLSearchParams(location.search).get('q')?.trim()||'';setQuery(q);setArea('Todos');setRows([]);setStatus(null);setMessage('');if(q.length<2){setStatus(200);return;}let alive=true;(async()=>{setLoading(true);try{const r=await fetchAppApi<unknown>(`/search?q=${encodeURIComponent(q)}`);if(!alive)return;setStatus(r.status);setRows(r.status===200?rowsFrom(r.data):[]);if(r.status===403)setMessage('Tu perfil no tiene acceso a esta búsqueda.');else if(r.status!==200)setMessage(r.status===0?'No se pudo conectar con la búsqueda autorizada.':'No se pudo completar la búsqueda.');}catch{if(!alive)return;setRows([]);setStatus(0);setMessage('No se pudo conectar con la búsqueda autorizada.');}finally{if(alive)setLoading(false);}})();return()=>{alive=false};},[active,logged,location.search]);
 const groups=useMemo(()=>['Todos',...Array.from(new Set(rows.map(groupOf)))],[rows]);
 const visible=useMemo(()=>{const q=refine.trim().toLocaleLowerCase('es');const m=metaFilter.trim().toLocaleLowerCase('es');let out=rows.filter(r=>area==='Todos'||groupOf(r)===area).filter(r=>!q||`${titleOf(r)} ${first(r,['id','code','codigo'])} ${groupOf(r)}`.toLocaleLowerCase('es').includes(q)).filter(r=>!m||metaOf(r).toLocaleLowerCase('es').includes(m));if(exact&&query.trim())out=out.filter(r=>titleOf(r).toLocaleLowerCase('es')===query.trim().toLocaleLowerCase('es'));if(sort==='titulo')out=[...out].sort((a,b)=>titleOf(a).localeCompare(titleOf(b),'es',{sensitivity:'base'}));if(sort==='tipo')out=[...out].sort((a,b)=>groupOf(a).localeCompare(groupOf(b),'es')||titleOf(a).localeCompare(titleOf(b),'es'));return out;},[rows,area,refine,metaFilter,sort,exact,query]);
 if(!active||!ready||!logged)return null;const searched=new URLSearchParams(location.search).get('q')?.trim()||'';const effectiveNav=nav.length?nav:fallbackNav;
 function submit(e?:FormEvent){e?.preventDefault();const q=query.trim();const next=q?`/buscar?q=${encodeURIComponent(q)}`:'/buscar';if(`${location.pathname}${location.search}`===next){window.dispatchEvent(new PopStateEvent('popstate'));return;}navigate(next);}function open(r:Row){const route=first(r,['destino','route','ruta']);if(route.startsWith('/'))navigate(route);}async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}const role=ctx?.role||'Usuario';
 return <OperationalShellFrame className="search-root inmo-root" theme={theme} navigation={effectiveNav} activeRoute="/buscar" anaSubtitle="Busca solo dentro de tu ámbito autorizado." anaRoute="/ana" query={query} onQueryChange={setQuery} searchPlaceholder="Buscar expediente, cliente, banco, inmobiliaria..." searchActionLabel="Buscar" onSearchAction={()=>submit()} name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="search-content inmo-content">
  <section className="inmo-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · BUSCADOR AVANZADO</span><h2>Busca una vez y cruza todas las áreas</h2><p>Combino la búsqueda transversal con filtros encadenados. Puedes empezar por una persona, expediente, banco, documento o localidad y después afinar sin perder los resultados autorizados.</p><div className="inmo-next"><button onClick={()=>setArea('Expedientes')}><b>1</b><strong>Expedientes</strong><small>Clientes, códigos y localidades →</small></button><button onClick={()=>setArea('Documentación')}><b>2</b><strong>Documentos</strong><small>Títulos y tipos →</small></button><button onClick={()=>setArea('Todos')}><b>3</b><strong>Cruzar todo</strong><small>Todas las áreas autorizadas →</small></button></div></div><article className="inmo-correct"><span>BÚSQUEDA GUIADA</span><h3>Cómo afinar</h3><p>Primero escribe una pista general. Después usa área, texto secundario, estado/localidad y orden. Los filtros trabajan sobre el mismo conjunto de resultados.</p><textarea readOnly rows={3} value="Ejemplo: Cristina → Documentación → nómina → Pendiente"/><input readOnly value={`${rows.length} resultados base cargados`}/><button onClick={()=>navigate('/ana?mode=help&resource=buscar')}>Preguntar a Ana</button></article></section>
  <div className="search-heading"><small>BÚSQUEDA TRANSVERSAL</small><h1>Buscador avanzado</h1><p>Busca en expedientes, contactos, inmobiliarias, bancos, tasaciones, firmas, documentación y agenda según tus permisos.</p></div>
  <form className="search-form" onSubmit={submit}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, DNI si está indexado, expediente, banco, documento, localidad..." aria-label="Consulta avanzada"/><button>Buscar en todo</button></form>
  <section className="inmo-filter" data-testid="advanced-linked-filters"><div className="inmo-filter-head"><div><small>SUBBUSCADORES VINCULADOS</small><h2>Afina sin perder la búsqueda principal</h2></div><span>{visible.length} visibles</span></div><div className="inmo-filter-grid registry-cross-filter"><label>ÁREA<select value={area} onChange={e=>setArea(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>CONTIENTE EN NOMBRE / CÓDIGO<input value={refine} onChange={e=>setRefine(e.target.value)} placeholder="Ej. nómina, Cristina, EXP-..."/></label><label>ESTADO / LOCALIDAD / META<input value={metaFilter} onChange={e=>setMetaFilter(e.target.value)} placeholder="Ej. Pendiente, Córdoba..."/></label><label>ORDEN<select value={sort} onChange={e=>setSort(e.target.value)}><option value="relevancia">Relevancia backend</option><option value="titulo">Título A-Z</option><option value="tipo">Tipo y título</option></select></label><label className="search-exact"><input type="checkbox" checked={exact} onChange={e=>setExact(e.target.checked)}/> Coincidencia exacta de título</label><button type="button" onClick={()=>{setArea('Todos');setRefine('');setMetaFilter('');setSort('relevancia');setExact(false)}}>Limpiar filtros</button></div></section>
  {loading&&status===null&&<div className="ops-message" role="status" data-testid="search-loading">Buscando únicamente dentro de tu ámbito autorizado…</div>}{status===403&&message&&<div className="ops-message" data-testid="search-forbidden">{message}</div>}{status!==null&&status!==200&&status!==403&&message&&<div className="ops-message" data-testid="search-error">{message}</div>}{status===200&&<><section className="search-areas"><div><small>ÁREAS DETECTADAS</small><h2>Resultados por módulo</h2></div><div className="search-area-buttons">{groups.map(g=><button type="button" key={g} className={area===g?'active':''} onClick={()=>setArea(g)}>{g}<span>{g==='Todos'?rows.length:rows.filter(r=>groupOf(r)===g).length}</span></button>)}</div></section><section className="search-results"><div className="search-results-head"><div><small>RESULTADOS CRUZADOS</small><h2>Coincidencias autorizadas</h2></div><span>{visible.length} visibles</span></div>{searched.length===1&&<div className="ops-message">Escribe al menos 2 caracteres para buscar.</div>}{searched.length!==1&&visible.length===0&&<div className="ops-empty" data-testid="search-empty"><strong>Sin resultados visibles</strong><span>Prueba a limpiar uno de los subfiltros o cambiar de área.</span></div>}<div className="search-result-list">{visible.map((r,i)=>{const group=groupOf(r),title=titleOf(r),meta=metaOf(r),route=first(r,['destino','route','ruta']);return <button key={first(r,['id','code','codigo'])||`${title}-${i}`} disabled={!route.startsWith('/')} onClick={()=>open(r)}><span className="search-result-icon">{iconFor(group)}</span><span><strong>{title}</strong><small>{group} · {meta}</small></span><b>{route.startsWith('/')?'Abrir →':'Sin ruta disponible'}</b></button>})}</div></section></>}
 </OperationalShellFrame>;
}
