import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import {fetchSpecialCasesRuntime} from './specialCasesRuntime';
import {anaVertical} from './assets/visualAssets';
import './inmobiliarias-polish.css';
import './detail-expediente.css';

type Row=Record<string,unknown>;type Envelope={item?:Row};
const HER=['Entrada','Documentación','Análisis administrativo','Gestiones / interlocutores','Seguimiento','Preparación de firma','Firma en notaría','Cierre'];
const OBR=['Entrada','Recepción documental','Control administrativo','Faltantes / incidencias','Preparación / envío a interlocutor','Seguimiento','Preparación de firma','Firma en notaría','Cierre'];
function text(r:Row|null,k:string){const v=r?.[k];return typeof v==='string'?v.trim():''}
function has(s:string,terms:string[]){return terms.some(t=>s.includes(t))}
function herenciaPhaseIndex(raw:string){const s=raw.toLowerCase();if(has(s,['cierre','cerrada','finalizada']))return 7;if(has(s,['firma en notaría','firma notarial','firmada']))return 6;if(has(s,['preparación de firma','preparacion de firma','coordinar firma','fecha de firma']))return 5;if(has(s,['seguimiento','pendiente respuesta','en seguimiento']))return 4;if(has(s,['gestiones','interlocutor','registro','notaría','notaria','herederos','adjudicación','adjudicacion']))return 3;if(has(s,['análisis administrativo','analisis administrativo','análisis','analisis','revisión jurídica','revision juridica']))return 2;if(has(s,['document','certificado','testamento','declaración de herederos','declaracion de herederos']))return 1;return 0}
function obraPhaseIndex(raw:string){const s=raw.toLowerCase();if(has(s,['cierre','cerrada','finalizada']))return 8;if(has(s,['firma en notaría','firma notarial','firmada']))return 7;if(has(s,['preparación de firma','preparacion de firma','coordinar firma','fecha de firma']))return 6;if(has(s,['seguimiento','pendiente respuesta','en seguimiento']))return 5;if(has(s,['preparación / envío','preparacion / envio','envío a interlocutor','envio a interlocutor','enviado a','interlocutor']))return 4;if(has(s,['faltantes','incidencia','subsanación','subsanacion','pendiente documentación','pendiente documentacion']))return 3;if(has(s,['control administrativo','revisión administrativa','revision administrativa','validación administrativa','validacion administrativa']))return 2;if(has(s,['recepción documental','recepcion documental','documentación recibida','documentacion recibida','document']))return 1;return 0}
export default function SpecialCaseDetailExperience(){const location=useLocation(),navigate=useNavigate();const m=location.pathname.match(/^\/(herencias|obras-nuevas)\/([^/]+)$/);const active=Boolean(m)&&m?.[2]!=='nuevo';const kind=m?.[1]||'',id=m?.[2]?decodeURIComponent(m[2]):'';const[target,setTarget]=useState<Element|null>(null),[row,setRow]=useState<Row|null>(null);
 useEffect(()=>{if(!active)return;let alive=true;fetchSpecialCasesRuntime<Envelope>(`/${kind}/${encodeURIComponent(id)}`).then(r=>{if(alive&&r.status===200)setRow(r.data?.item??null)});return()=>{alive=false}},[active,kind,id]);
 useEffect(()=>{if(!active)return;const find=()=>{const root=document.querySelector('.ops-root .ops-content');if(!root)return;let host=root.querySelector(':scope > .special-detail-experience-host') as HTMLElement|null;if(!host){host=document.createElement('div');host.className='special-detail-experience-host';root.prepend(host)}setTarget(host)};find();const obs=new MutationObserver(find);obs.observe(document.body,{childList:true,subtree:true});return()=>{obs.disconnect();document.querySelector('.special-detail-experience-host')?.remove();setTarget(null)}},[active,location.pathname]);
 const isHer=kind==='herencias',phases=isHer?HER:OBR,current=text(row,'fase'),idx=isHer?herenciaPhaseIndex(current):obraPhaseIndex(current),next=text(row,'siguiente_accion'),block=text(row,'bloqueo')||text(row,'bloqueo_incidencia'),missing=text(row,'faltantes')||text(row,'documentacion_faltante');
 const currentLabel=phases[idx]||phases[0];const nextLabel=phases[Math.min(idx+1,phases.length-1)];
 const anaUrl=(mode:'help'|'do')=>`/ana?mode=${mode}&resource=${kind}&scope_code=${encodeURIComponent(id)}&phase=${encodeURIComponent(currentLabel)}&next_phase=${encodeURIComponent(nextLabel)}${next?`&next_action=${encodeURIComponent(next)}`:''}${block?`&block=${encodeURIComponent(block)}`:''}${missing?`&missing=${encodeURIComponent(missing)}`:''}`;
 const summary=useMemo(()=>{if(!row)return'Leyendo el caso antes de recomendar el siguiente paso.';if(block)return`Hay un bloqueo o incidencia que debe resolverse antes de avanzar: ${block}`;if(missing)return`Falta documentación antes de seguir: ${missing}`;return next?`El siguiente paso registrado es: ${next}`:`Estamos en ${currentLabel}. Antes de avanzar a ${nextLabel}, Ana debe confirmar la siguiente acción real.`},[row,block,missing,next,currentLabel,nextLabel]);
 if(!active||!target)return null;return createPortal(<><section className="inmo-ana-hero special-detail-ana-hero" data-testid="special-detail-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · {isHer?'HERENCIA':'OBRA NUEVA'}</span><h2>Te guío por este caso paso a paso</h2><p>{summary}</p><div className="inmo-next"><button onClick={()=>document.getElementById('special-case-current')?.scrollIntoView({behavior:'smooth'})}><b>1</b><strong>Fase actual</strong><small>{currentLabel} →</small></button><button onClick={()=>navigate(anaUrl('help'))}><b>2</b><strong>Qué toca ahora</strong><small>{next||`Preparar ${nextLabel}`} →</small></button><button onClick={()=>navigate(anaUrl('do'))}><b>3</b><strong>Que lo haga Ana</strong><small>Solo dentro de permisos →</small></button></div></div><article className="inmo-correct"><span>CONTROL DEL CASO</span><h3>Qué necesita atención</h3><p>Ana usa la fase real, la siguiente acción, la documentación y los bloqueos de este tipo de caso para asesorar ahora y poder automatizarlo después sin mezclar la lógica de Hipotecas, Herencias y Obras Nuevas.</p><textarea readOnly rows={3} value={block||missing||`Fase actual: ${currentLabel}`}/><input readOnly value={next||`Siguiente fase prevista: ${nextLabel}`}/><button onClick={()=>navigate(anaUrl('help'))}>Revisar con Ana</button></article></section><section className="detail-journey special-detail-journey" id="special-case-current"><div className="detail-section-label">{isHer?'RECORRIDO DE LA HERENCIA':'RECORRIDO DE LA OBRA NUEVA'} · ACTUAL: {currentLabel}</div><div className="detail-phase-track">{phases.map((phase,i)=><div key={phase} className={i<idx?'done':i===idx?'current':''} aria-current={i===idx?'step':undefined}><span>{i<idx?'✓':i+1}</span><small>{phase}</small></div>)}</div></section></>,target)}
