import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import {fetchSpecialCasesRuntime} from './specialCasesRuntime';
import {anaVertical} from './assets/visualAssets';
import './inmobiliarias-polish.css';
import './detail-expediente.css';

type Row=Record<string,unknown>;type Envelope={item?:Row};
const HER=['Entrada','Documentación','Análisis administrativo','Gestiones / interlocutores','Seguimiento','Preparación de firma','Firma en notaría','Cierre'];
const OBR=['Entrada','Recepción documental','Control administrativo','Faltantes / incidencias','Preparación / envío a interlocutor','Seguimiento','Preparación de firma','Firma en notaría','Cierre'];
function text(r:Row|null,k:string){const v=r?.[k];return typeof v==='string'?v.trim():''}
function phaseIndex(raw:string,phases:string[]){const s=raw.toLowerCase();const aliases:Record<string,string[]>={'Entrada':['entrada','nueva'],'Documentación':['document','recepción documental'],'Análisis administrativo':['análisis','analisis','control administrativo'],'Gestiones / interlocutores':['gestiones','interlocutor','preparación / envío'],'Seguimiento':['seguimiento'],'Preparación de firma':['preparación de firma'],'Firma en notaría':['firma en notaría','firma'],'Cierre':['cierre','cerrada']};const i=phases.findIndex(p=>(aliases[p]||[p.toLowerCase()]).some(x=>s.includes(x)));return i<0?0:i}
export default function SpecialCaseDetailExperience(){const location=useLocation(),navigate=useNavigate();const m=location.pathname.match(/^\/(herencias|obras-nuevas)\/([^/]+)$/);const active=Boolean(m)&&m?.[2]!=='nuevo';const kind=m?.[1]||'',id=m?.[2]?decodeURIComponent(m[2]):'';const[target,setTarget]=useState<Element|null>(null),[row,setRow]=useState<Row|null>(null);
 useEffect(()=>{if(!active)return;let alive=true;fetchSpecialCasesRuntime<Envelope>(`/${kind}/${encodeURIComponent(id)}`).then(r=>{if(alive&&r.status===200)setRow(r.data?.item??null)});return()=>{alive=false}},[active,kind,id]);
 useEffect(()=>{if(!active)return;const find=()=>{const root=document.querySelector(`.ops-root .ops-content`);if(!root)return;let host=root.querySelector(':scope > .special-detail-experience-host') as HTMLElement|null;if(!host){host=document.createElement('div');host.className='special-detail-experience-host';root.prepend(host)}setTarget(host)};find();const obs=new MutationObserver(find);obs.observe(document.body,{childList:true,subtree:true});return()=>{obs.disconnect();const host=document.querySelector('.special-detail-experience-host');host?.remove();setTarget(null)}},[active,location.pathname]);
 const isHer=kind==='herencias',phases=isHer?HER:OBR,current=text(row,'fase'),idx=phaseIndex(current,phases),next=text(row,'siguiente_accion'),block=text(row,'bloqueo')||text(row,'bloqueo_incidencia'),missing=text(row,'faltantes')||text(row,'documentacion_faltante');const summary=useMemo(()=>{if(!row)return'Leyendo el caso antes de recomendar el siguiente paso.';if(block)return`Hay un bloqueo o incidencia que debe resolverse antes de avanzar: ${block}`;if(missing)return`Falta documentación antes de seguir: ${missing}`;return next?`El siguiente paso registrado es: ${next}`:'No hay una siguiente acción segura registrada; primero hay que completar ese dato.'},[row,block,missing,next]);
 if(!active||!target)return null;return createPortal(<><section className="inmo-ana-hero special-detail-ana-hero" data-testid="special-detail-ana-hero"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · {isHer?'HERENCIA':'OBRA NUEVA'}</span><h2>Te guío por este caso paso a paso</h2><p>{summary}</p><div className="inmo-next"><button onClick={()=>document.getElementById('special-case-current')?.scrollIntoView({behavior:'smooth'})}><b>1</b><strong>Qué toca ahora</strong><small>{next||'Confirmar siguiente acción'} →</small></button><button onClick={()=>navigate(`/ana?mode=help&resource=${kind}&scope_code=${encodeURIComponent(id)}`)}><b>2</b><strong>Ayúdame</strong><small>Ver motivo y pasos →</small></button><button onClick={()=>navigate(`/ana?mode=do&resource=${kind}&scope_code=${encodeURIComponent(id)}`)}><b>3</b><strong>Que lo haga Ana</strong><small>Solo dentro de permisos →</small></button></div></div><article className="inmo-correct"><span>CONTROL DEL CASO</span><h3>Qué necesita atención</h3><p>La guía usa la fase, siguiente acción, documentación y bloqueos registrados; no completa criterios sensibles por intuición.</p><textarea readOnly rows={3} value={block||missing||'No hay bloqueo explícito registrado.'}/><input readOnly value={next||'Siguiente acción pendiente de definir'}/><button onClick={()=>navigate(`/ana?mode=help&resource=${kind}&scope_code=${encodeURIComponent(id)}`)}>Revisar con Ana</button></article></section><section className="detail-journey special-detail-journey" id="special-case-current"><div className="detail-section-label">RECORRIDO DEL CASO</div><div className="detail-phase-track">{phases.map((phase,i)=><div key={phase} className={i<idx?'done':i===idx?'current':''}><span>{i<idx?'✓':i+1}</span><small>{phase}</small></div>)}</div></section></>,target)}
