import {useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,FolderOpen,ShieldAlert} from 'lucide-react';
import {fetchAppApi,supabase} from './supabase';
import {fetchSpecialCasesRuntime} from './specialCasesRuntime';
import {anaVertical} from './assets/visualAssets';
import {directionSidebarNavigation,isDirectionNavigation,normalizeNavigation,orderAuthorizedNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './expedientes-polish.css';
import './inmobiliarias-polish.css';
import './sortable-table.css';

type Theme='light'|'dark';
type Row=Record<string,unknown>;
type Ctx={role?:string};
type Envelope={items?:Row[];item?:Row;intervinientes?:Row[]};
type ModuleDef={route:'/herencias'|'/obras-nuevas';label:string;singular:string;search:string;description:string;ana:string};
const defs:ModuleDef[]=[
 {route:'/herencias',label:'Herencias',singular:'Herencia',search:'Buscar herencia, estado, fase, responsable o acción...',description:'Casos de herencia gestionados por fases, igual que un expediente.',ana:'Te indico qué herencia necesita documentación, validación o siguiente acción antes de avanzar.'},
 {route:'/obras-nuevas',label:'Obras Nuevas',singular:'Obra nueva',search:'Buscar obra nueva, estado, fase, interlocutor o acción...',description:'Operaciones de obra nueva gestionadas por fases, igual que un expediente.',ana:'Te indico qué promoción necesita documentación, validación técnica, envío o preparación de firma.'}
];
const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function s(r:Row|null,k:string){const v=r?.[k];return typeof v==='string'?v.trim():''}
function b(r:Row|null,k:string){return r?.[k]===true}
function arr(r:Row|null,k:string){const v=r?.[k];return Array.isArray(v)?v.filter(x=>typeof x==='string') as string[]:[]}
function nice(v:string){return v||'—'}
function defFor(path:string){return defs.find(d=>path===d.route||path.startsWith(`${d.route}/`))??null}
function haystack(r:Row){return Object.values(r).flat().filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase()}

export default function SpecialCasesShell(){
 const location=useLocation(),navigate=useNavigate(),def=defFor(location.pathname),active=Boolean(def),detailId=def&&location.pathname.startsWith(`${def.route}/`)?decodeURIComponent(location.pathname.slice(def.route.length+1)):'';
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light'),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[authorized,setAuthorized]=useState<boolean|null>(null),[rows,setRows]=useState<Row[]>([]),[row,setRow]=useState<Row|null>(null),[people,setPeople]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[state,setState]=useState(''),[phase,setPhase]=useState(''),[validation,setValidation]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,x)=>{setLogged(Boolean(x));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(active){document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme)}},[active,theme]);
 useEffect(()=>{if(!active||!logged||!def)return;let alive=true;(async()=>{setLoading(true);setStatus(null);setRows([]);setRow(null);setPeople([]);const path=detailId?`${def.route}/${encodeURIComponent(detailId)}`:def.route;try{const[c,n,r]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation'),fetchSpecialCasesRuntime<Envelope>(path)]);if(!alive)return;setCtx(c.status===200?c.data:null);const normalized=n.status===200?normalizeNavigation(n.data):[];setNav(isDirectionNavigation(normalized)?directionSidebarNavigation(normalized):orderAuthorizedNavigation(normalized));const canUse=normalized.some(i=>i.route===def.route);setAuthorized(canUse);if(!canUse&&r.status===200){navigate('/inicio',{replace:true});return}setStatus(r.status);if(r.status===200){if(detailId){setRow(r.data?.item??null);setPeople(Array.isArray(r.data?.intervinientes)?r.data!.intervinientes!:[])}else setRows(Array.isArray(r.data?.items)?r.data!.items!:[])}}catch{if(alive)setStatus(0)}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[active,logged,def?.route,detailId,navigate]);
 const states=useMemo(()=>Array.from(new Set(rows.map(r=>s(r,'estado')).filter(Boolean))).sort((a,c)=>a.localeCompare(c,'es')),[rows]);
 const phases=useMemo(()=>Array.from(new Set(rows.map(r=>s(r,'fase')).filter(Boolean))).sort((a,c)=>a.localeCompare(c,'es')),[rows]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(r=>(!state||s(r,'estado')===state)&&(!phase||s(r,'fase')===phase)&&(!validation||(validation==='pendiente'?b(r,'requiere_validacion'):!b(r,'requiere_validacion')))&&(!q||haystack(r).includes(q)))},[rows,query,state,phase,validation]);
 const activeCount=useMemo(()=>rows.filter(r=>r.activo===true||/curso|activ|tramit|gesti/i.test(`${s(r,'estado')} ${s(r,'fase')}`)).length,[rows]);
 const reviewCount=useMemo(()=>rows.filter(r=>b(r,'requiere_validacion')||Boolean(s(r,'bloqueo')||s(r,'bloqueo_incidencia'))).length,[rows]);
 const signingCount=useMemo(()=>rows.filter(r=>/firma/i.test(`${s(r,'fase')} ${s(r,'estado')}`)||b(r,'firma_realizada')).length,[rows]);
 const phaseRank=useMemo(()=>{const m=new Map<string,number>();rows.forEach(r=>{const x=s(r,'fase')||'Sin fase';m.set(x,(m.get(x)||0)+1)});return[...m.entries()].sort((a,c)=>c[1]-a[1]).slice(0,6)},[rows]);
 const maxPhase=useMemo(()=>Math.max(1,...phaseRank.map(([,n])=>n)),[phaseRank]);
 if(!active||!def||!ready||!logged||authorized===false&&status===200)return null;
 const effectiveNav=nav.length?nav:fallbackNav,role=ctx?.role||'Usuario';async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL}
 const anaSummary=loading?'Estoy leyendo los casos autorizados antes de priorizar.':status!==200?'No tengo datos suficientes para recomendar una prioridad fiable.':rows.length===0?`No hay ${def.label.toLowerCase()} visibles todavía.`:reviewCount?`Hay ${reviewCount} ${def.label.toLowerCase()} con bloqueo, incidencia o validación pendiente. Empezaría por esos casos.`:`Veo ${rows.length} ${def.label.toLowerCase()}. Priorizaría por fase, siguiente acción y fecha comprometida.`;
 return <OperationalShellFrame className={!detailId?'inmo-root':undefined} theme={theme} navigation={effectiveNav} activeRoute={def.route} query={query} onQueryChange={setQuery} searchPlaceholder={def.search} name={role} role={role} initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName={!detailId?'inmo-content':undefined}>
  {detailId?<Detail def={def} row={row} people={people} status={status} loading={loading} onBack={()=>navigate(def.route)}/>:<List def={def} rows={rows} visible={visible} status={status} loading={loading} states={states} phases={phases} state={state} phase={phase} validation={validation} setState={setState} setPhase={setPhase} setValidation={setValidation} setQuery={setQuery} navigate={navigate} activeCount={activeCount} reviewCount={reviewCount} signingCount={signingCount} phaseRank={phaseRank} maxPhase={maxPhase} anaSummary={anaSummary}/>} 
 </OperationalShellFrame>
}

function List({def,rows,visible,status,loading,states,phases,state,phase,validation,setState,setPhase,setValidation,setQuery,navigate,activeCount,reviewCount,signingCount,phaseRank,maxPhase,anaSummary}:any){return <>
 <section className="inmo-ana-hero" data-testid={`${def.route.slice(1)}-ana-hero`}><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · {def.label.toUpperCase()}</span><h2>Esto es lo que toca ahora</h2><p>{anaSummary}</p><div className="inmo-next"><button onClick={()=>navigate(`/ana?mode=do&resource=${encodeURIComponent(def.route.slice(1))}`)}><b>1</b><strong>Que lo haga Ana</strong><small>Preparar siguiente acción →</small></button><button onClick={()=>navigate(`/ana?mode=help&resource=${encodeURIComponent(def.route.slice(1))}`)}><b>2</b><strong>Ayúdame</strong><small>Revisar prioridades →</small></button><button onClick={()=>navigate(`/ana?mode=manual&resource=${encodeURIComponent(def.route.slice(1))}`)}><b>3</b><strong>Lo hago yo</strong><small>Ver instrucciones →</small></button></div></div><article className="inmo-correct"><span>CONTROL DEL CASO</span><h3>Qué necesita atención</h3><p>{def.ana}</p><textarea readOnly rows={3} value={reviewCount?`${reviewCount} casos requieren revisión prioritaria.`:'No hay bloqueos o validaciones explícitas pendientes.'}/><input readOnly value={`${signingCount} casos en preparación o estado de firma`}/><button onClick={()=>navigate(`/ana?mode=help&resource=${encodeURIComponent(def.route.slice(1))}`)}>Revisar con Ana</button></article></section>
 <div className="ops-title"><div><span className="ops-icon"><FolderOpen size={20}/></span><div><h1>{def.label}</h1><p>{def.description}</p></div></div><span className={status===200&&!loading?'ops-live ok':'ops-live'}>{loading?'Cargando…':status===200?'Datos actualizados':status===403?'Sin acceso':'Sin conexión'}</span></div>
 {loading&&<div className="ops-message" data-testid="ops-loading">Cargando {def.label.toLowerCase()}…</div>}
 {!loading&&status===403&&<div className="ops-message" data-testid="ops-forbidden">Tu perfil no tiene acceso a este módulo.</div>}
 {!loading&&status!==null&&status!==200&&status!==403&&<div className="ops-message" data-testid="ops-error">No se pudo cargar el módulo.</div>}
 {!loading&&status===200&&<><section className="inmo-kpis" data-testid={`${def.route.slice(1)}-live`}><article><small>CASOS</small><strong>{rows.length}</strong><span>Visibles</span></article><article><small>EN CURSO</small><strong>{activeCount}</strong><span>Con actividad o fase abierta</span></article><article><small>REVISAR</small><strong>{reviewCount}</strong><span>Bloqueo o validación</span></article><article><small>FIRMA</small><strong>{signingCount}</strong><span>En preparación o realizada</span></article></section><section className="inmo-insights inmo-live-charts"><article><span>DISTRIBUCIÓN POR FASE</span><h2>Situación de {def.label.toLowerCase()}</h2><div className="inmo-bars">{phaseRank.map(([x,n]:[string,number])=><button key={x} className="inmo-bar-row inmo-bar-button" onClick={()=>setPhase(x==='Sin fase'?'':x)}><div className="inmo-bar-label"><strong>{x}</strong><span>{n}</span></div><div className="inmo-bar-track"><i style={{width:`${Math.max(8,n/maxPhase*100)}%`}}/></div></button>)}</div></article><article><span>LECTURA OPERATIVA</span><h2>Prioridad inmediata</h2><strong className="inmo-priority">{reviewCount}</strong><p>Casos con bloqueo, incidencia o validación pendiente. La distribución por fase permite entrar directamente en la parte de la cartera que quieras revisar.</p></article></section></>}
 <div className="exp-filter-card"><input value={queryPlaceholderHack()} onChange={()=>{}} style={{display:'none'}}/><select value={state} onChange={(e:any)=>setState(e.target.value)} aria-label="Estado"><option value="">Todos los estados</option>{states.map((x:string)=><option key={x}>{x}</option>)}</select><select value={phase} onChange={(e:any)=>setPhase(e.target.value)} aria-label="Fase"><option value="">Todas las fases</option>{phases.map((x:string)=><option key={x}>{x}</option>)}</select><select value={validation} onChange={(e:any)=>setValidation(e.target.value)} aria-label="Validación"><option value="">Toda validación</option><option value="pendiente">Pendiente de validación</option><option value="ok">Sin validación pendiente</option></select><button onClick={()=>{setQuery('');setState('');setPhase('');setValidation('')}}>Limpiar filtros</button></div>
 {!loading&&status===200&&visible.length===0&&<div className="ops-message" data-testid="ops-empty">No hay casos con estos filtros.</div>}
 {!loading&&status===200&&visible.length>0&&<div className="ops-table-card exp-table"><div className="ops-table-head"><strong>Cartera · {def.label}</strong><span>{visible.length} registros</span></div><div className="ops-table-wrap"><table className="ops-sortable-table"><thead><tr><th>CASO</th><th>ESTADO</th><th>FASE</th><th>SIGUIENTE ACCIÓN</th><th>VALIDACIÓN</th><th>ÚLTIMA ACTIVIDAD</th></tr></thead><tbody>{visible.map((r:Row)=><tr key={s(r,'id')} onClick={()=>s(r,'id')&&navigate(`${def.route}/${encodeURIComponent(s(r,'id'))}`)}><td><strong>{nice(s(r,'nombre'))}</strong></td><td>{nice(s(r,'estado'))}</td><td>{nice(s(r,'fase'))}</td><td>{nice(s(r,'siguiente_accion'))}</td><td>{b(r,'requiere_validacion')?'Pendiente':'No'}</td><td>{nice(s(r,'ultima_actividad'))}</td></tr>)}</tbody></table></div></div>}
 </>}

function queryPlaceholderHack(){return''}

function Detail({def,row,people,status,loading,onBack}:{def:ModuleDef;row:Row|null;people:Row[];status:number|null;loading:boolean;onBack:()=>void}){if(loading)return <div className="ops-message">Cargando ficha…</div>;if(status===403)return <><button onClick={onBack}><ArrowLeft size={15}/> Volver</button><div className="ops-message">Tu perfil no tiene acceso a este caso.</div></>;if(status!==200||!row)return <><button onClick={onBack}><ArrowLeft size={15}/> Volver</button><div className="ops-message">No se pudo cargar la ficha.</div></>;const isHer=def.route==='/herencias';const refs=arr(row,isHer?'cliente':'cliente_promotor');return <>
 <button className="secondary-action" onClick={onBack}><ArrowLeft size={15}/> Volver a {def.label}</button>
 <div className="ops-title"><div><span className="ops-icon"><FolderOpen size={20}/></span><div><h1>{nice(s(row,'nombre'))}</h1><p>{nice(s(row,'fase'))} · {nice(s(row,'estado'))}</p></div></div><span className="ops-live ok">Datos actualizados</span></div>
 <section className="exp-case-summary" style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12,marginBottom:16}}><article className="ops-table-card" style={{padding:16}}><small>ESTADO</small><strong style={{display:'block',fontSize:22}}>{nice(s(row,'estado'))}</strong></article><article className="ops-table-card" style={{padding:16}}><small>FASE</small><strong style={{display:'block',fontSize:22}}>{nice(s(row,'fase'))}</strong></article><article className="ops-table-card" style={{padding:16}}><small>VALIDACIÓN</small><strong style={{display:'block',fontSize:22}}>{b(row,'requiere_validacion')?'Pendiente':'No'}</strong></article><article className="ops-table-card" style={{padding:16}}><small>FIRMA</small><strong style={{display:'block',fontSize:22}}>{b(row,'firma_realizada')?'Realizada':'Pendiente'}</strong></article></section>
 <div className="ops-table-card" style={{padding:20,marginBottom:16}}><small>SIGUIENTE ACCIÓN</small><h2>{nice(s(row,'siguiente_accion'))}</h2><p><ShieldAlert size={16}/> <b>Bloqueo / incidencia:</b> {nice(s(row,'bloqueo')||s(row,'bloqueo_incidencia'))}</p><p><b>Documentación pendiente:</b> {nice(s(row,'faltantes')||s(row,'documentacion_faltante'))}</p>{!isHer&&<p><b>Estado de envío:</b> {nice(s(row,'estado_envio'))}</p>}<p><b>{isHer?'Cliente':'Cliente / promotor'}:</b> {refs.length?refs.join(', '):'—'}</p></div>
 <div className="ops-table-card" data-testid={`${def.route.slice(1)}-intervinientes`}><div className="ops-table-head"><strong>Intervinientes</strong><span>{people.length} vinculados</span></div>{people.length===0?<div className="ops-message">No hay intervinientes visibles todavía.</div>:<div className="ops-table-wrap"><table className="ops-sortable-table"><thead><tr><th>PERSONA / ENTIDAD</th><th>ROL</th><th>EMPRESA / ORGANISMO</th><th>TELÉFONO</th><th>EMAIL</th></tr></thead><tbody>{people.map((p,i)=><tr key={s(p,'id')||String(i)}><td>{nice(s(p,'persona')||s(p,'persona_entidad'))}</td><td>{nice(s(p,'rol'))}</td><td>{nice(s(p,'empresa_organismo'))}</td><td>{nice(s(p,'telefono'))}</td><td>{nice(s(p,'email'))}</td></tr>)}</tbody></table></div>}</div>
 </>}
