import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import {CheckCircle2,FileClock,FileText} from 'lucide-react';
import {fetchAppApi,IS_PRODUCTION} from './supabase';

type Ctx={role?:string};
type HistoryItem=Record<string,unknown>;
type HistoryEnvelope={ok?:boolean;status?:number;items?:HistoryItem[];history?:HistoryItem[];error?:string};
type ReportEnvelope={ok?:boolean;status?:number;document_code?:string;informe_document_code?:string;error?:string};
type ScopeEnvelope={ok?:boolean;status?:number;tasacion?:Record<string,unknown>;item?:Record<string,unknown>;error?:string};
function val(v:unknown){if(v===null||v===undefined||v==='')return'—';if(typeof v==='object')return JSON.stringify(v);return String(v)}

export default function TasacionLifecycleGuard(){
 const location=useLocation(),navigate=useNavigate();const match=location.pathname.match(/^\/tasaciones\/([^/]+)$/);const id=match?.[1]?decodeURIComponent(match[1]):'';const active=Boolean(IS_PRODUCTION&&match&&id&&id!=='nuevo'&&id!=='nueva');
 const[host,setHost]=useState<HTMLElement|null>(null),[ctx,setCtx]=useState<Ctx|null>(null),[history,setHistory]=useState<HistoryItem[]>([]),[historyStatus,setHistoryStatus]=useState<number|null>(null),[scope,setScope]=useState<Record<string,unknown>|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const[decision,setDecision]=useState(''),[reason,setReason]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[actionMsg,setActionMsg]=useState('');
 useEffect(()=>{if(!active){setHost(null);return}const place=()=>{const roots=[...document.querySelectorAll('.ops-root')].filter(el=>{const r=(el as HTMLElement).getBoundingClientRect();return r.width>0&&r.height>0});const root=roots.at(-1) as HTMLElement|undefined;const content=root?.querySelector('.ops-content') as HTMLElement|null;if(!content)return;let h=content.querySelector(':scope > .tasacion-lifecycle-host') as HTMLElement|null;if(!h){h=document.createElement('div');h.className='tasacion-lifecycle-host';content.appendChild(h)}setHost(h)};place();const observer=new MutationObserver(place);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();document.querySelectorAll('.tasacion-lifecycle-host').forEach(el=>el.remove());setHost(null)}},[active,location.pathname]);
 async function load(){if(!active)return;setLoading(true);setMessage('');const[c,h,s]=await Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<HistoryEnvelope>(`/tasaciones/${encodeURIComponent(id)}/history`),fetchAppApi<ScopeEnvelope>(`/tasaciones/${encodeURIComponent(id)}`)]);setCtx(c.status===200?c.data:null);setHistoryStatus(h.status);setHistory(h.status===200?(h.data?.items??h.data?.history??[]):[]);setScope(s.status===200?(s.data?.tasacion??s.data?.item??null):null);if(h.status!==200&&h.status!==404)setMessage('No se pudo cargar el histórico de la tasación.');setLoading(false)}
 useEffect(()=>{void load()},[active,id]);
 const version=Number(scope?.version??0)||null;const validation=String(scope?.validacion_belen??'').trim();
 const ordered=useMemo(()=>[...history].sort((a,b)=>String(b.created_at??b.happened_at??'').localeCompare(String(a.created_at??a.happened_at??''))),[history]);
 if(!active||!host)return null;
 async function openReport(){setActionMsg('');const r=await fetchAppApi<ReportEnvelope>(`/tasaciones/${encodeURIComponent(id)}/report`);if(r.status===200&&r.data?.ok){const code=r.data.document_code||r.data.informe_document_code;if(code){navigate(`/documentacion/${encodeURIComponent(code)}`);return}setActionMsg('El informe existe, pero no devuelve un documento navegable.');return}if(r.status===404)setActionMsg('Todavía no hay informe de tasación disponible.');else if(r.status===403)setActionMsg('Tu perfil no puede abrir este informe.');else setActionMsg('No se pudo abrir el informe de tasación.');}
 async function validate(){if(ctx?.role!=='Direccion'||!decision||!version)return;if(!preview){setPreview(true);setActionMsg('');return}setBusy(true);const r=await fetchAppApi<any>(`/tasaciones/${encodeURIComponent(id)}/validacion-belen`,{method:'POST',body:JSON.stringify({expected_version:version,decision,reason:reason.trim()||null})});setBusy(false);if(r.status===200){setActionMsg(`Validación ${decision.toLowerCase()} guardada y auditada.`);setPreview(false);setDecision('');setReason('');await load()}else if(r.status===409){setActionMsg('La tasación cambió mientras la revisabas. He recargado para evitar sobrescribir datos.');setPreview(false);await load()}else if(r.status===403)setActionMsg('Solo Dirección puede validar o rechazar esta tasación.');else setActionMsg(`No se pudo guardar la validación (${r.data?.error||r.status}).`)}
 return createPortal(<section className="ops-table-card" data-testid="tasacion-lifecycle" style={{marginTop:16}}><div className="ops-table-head"><strong>Control de tasación</strong><span>Histórico, informe y validación Dirección · PROD</span></div><div className="ops-message" style={{display:'grid',gap:12}}>
  <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" onClick={()=>void openReport()}><FileText size={16}/> Abrir informe</button><button type="button" onClick={()=>void load()} disabled={loading}><FileClock size={16}/> {loading?'Actualizando…':'Actualizar histórico'}</button></div>
  {actionMsg&&<div className="ops-message">{actionMsg}</div>}{message&&<div className="ops-message">{message}</div>}
  <div><small>VALIDACIÓN BELÉN / DIRECCIÓN</small><div><strong>{validation||'Pendiente'}</strong></div></div>
  {ctx?.role==='Direccion'&&<><label>Decisión<select value={decision} onChange={e=>{setDecision(e.target.value);setPreview(false);setActionMsg('')}}><option value="">Selecciona</option><option value="Validada">Validada</option><option value="Rechazada">Rechazada</option></select></label><label>Motivo / criterio<textarea rows={2} value={reason} onChange={e=>{setReason(e.target.value);setPreview(false)}} placeholder="Motivo útil para trazabilidad"/></label>{preview&&<div className="ops-message" data-testid="tasacion-validation-preview"><strong>Vista previa</strong><div>Decisión: {decision}</div><div>Motivo: {reason.trim()||'Sin motivo adicional'}</div><small>Nada se guarda hasta confirmar.</small></div>}<button type="button" className="primary" disabled={!decision||!version||busy} onClick={()=>void validate()}><CheckCircle2 size={16}/>{busy?'Guardando…':preview?'Confirmar validación':'Revisar validación'}</button></>}
  <div><small>HISTÓRICO</small>{loading?<p>Cargando histórico…</p>:historyStatus===200&&ordered.length===0?<p>No hay eventos de histórico para esta tasación.</p>:historyStatus===200?<div style={{display:'grid',gap:8}}>{ordered.map((e,i)=><div key={String(e.id??e.event_id??i)} className="ops-message"><strong>{val(e.action??e.event_type??e.estado??'Evento')}</strong><div>{val(e.created_at??e.happened_at??e.updated_at)}</div><small>{val(e.actor_code??e.created_by??'')}</small></div>)}</div>:historyStatus===404?<p>No se ha encontrado la tasación.</p>:<p>Histórico no disponible.</p>}</div>
 </div></section>,host);
}
