import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import {anaVertical} from './assets/visualAssets';
import AgendaRowOpenGuard from './AgendaRowOpenGuard';
import TaskRouteCompatibilityGuard from './TaskRouteCompatibilityGuard';
import TaskDetailShell from './TaskDetailShell';
import './task-detail-polish.css';

export default function TaskDetailExperienceGuard(){
 const location=useLocation(),navigate=useNavigate();
 const active=/^\/tareas\/[^/]+$/.test(location.pathname)&&!location.pathname.endsWith('/nueva');
 const[host,setHost]=useState<HTMLElement|null>(null);
 useEffect(()=>{if(!active){setHost(null);return}const place=()=>{const roots=[...document.querySelectorAll('.ops-root')].filter(el=>{const r=(el as HTMLElement).getBoundingClientRect();return r.width>0&&r.height>0});const root=roots.at(-1) as HTMLElement|undefined;if(!root)return;root.classList.add('task-detail-polished');const content=root.querySelector('.ops-content') as HTMLElement|null;if(!content)return;const title=content.querySelector(':scope > .ops-title') as HTMLElement|null;const legacy=content.querySelector(':scope > .ops-ana-card') as HTMLElement|null;if(legacy){legacy.classList.add('task-detail-legacy-ana');legacy.hidden=true;legacy.style.setProperty('display','none','important')}let h=content.querySelector(':scope > .task-detail-ana-host') as HTMLElement|null;if(!h){h=document.createElement('div');h.className='task-detail-ana-host';if(title?.nextSibling)content.insertBefore(h,title.nextSibling);else content.prepend(h)}setHost(current=>current===h?current:h)};place();const observer=new MutationObserver(place);observer.observe(document.body,{childList:true,subtree:true});return()=>{observer.disconnect();document.querySelectorAll('.task-detail-polished').forEach(el=>el.classList.remove('task-detail-polished'));document.querySelectorAll('.task-detail-legacy-ana').forEach(el=>{el.classList.remove('task-detail-legacy-ana');const h=el as HTMLElement;h.hidden=false;h.style.removeProperty('display')});document.querySelectorAll('.task-detail-ana-host').forEach(el=>el.remove());setHost(null)}},[active,location.pathname]);
 const helpers=<><AgendaRowOpenGuard/><TaskRouteCompatibilityGuard/><TaskDetailShell/></>;
 if(!active||!host)return helpers;
 return <>{helpers}{createPortal(<section className="inmo-ana-hero task-detail-ana" data-testid="task-detail-ana"><div className="inmo-ana-photo"><img src={anaVertical} alt="Ana"/></div><div className="inmo-ana-body"><span>ANA · TAREA</span><h2>Vamos a resolver esta tarea sin perder contexto</h2><p>Reviso el estado, la criticidad, la fecha límite y el responsable. Te indico qué toca ahora y nada se guarda sin que revises y confirmes la acción.</p><div className="inmo-next"><button onClick={()=>document.querySelector('.task-detail-polished .ops-message')?.scrollIntoView({behavior:'smooth'})}><b>1</b><strong>Revisar contexto</strong><small>Ver datos de la tarea →</small></button><button onClick={()=>document.querySelector('.task-detail-polished .ops-table-card')?.scrollIntoView({behavior:'smooth'})}><b>2</b><strong>Actualizar tarea</strong><small>Preparar cambios →</small></button><button onClick={()=>navigate(`/ana?mode=help&scope_type=tarea&scope_code=${encodeURIComponent(location.pathname.split('/').pop()||'')}`)}><b>3</b><strong>Ayúdame con Ana</strong><small>Ver siguiente paso →</small></button></div></div><article className="inmo-correct"><span>CONTROL DE LA TAREA</span><h3>¿En qué me equivoco?</h3><p>Si falta contexto o mi recomendación no encaja, corrígeme. La corrección mantiene esta tarea como contexto y pasa por el flujo de revisión antes de convertirse en conocimiento.</p><button onClick={()=>navigate(`/ana?mode=help&scope_type=tarea&scope_code=${encodeURIComponent(location.pathname.split('/').pop()||'')}`)}>Corregir o ampliar contexto</button></article></section>,host)}</>;
}
