import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {fetchAppApi,supabase} from './supabase';
import {normalizeNavigation,type NavItem} from './masterNavigation';
import OperationalShellFrame from './OperationalShellFrame';
import './operational.css';
import './contactos-polish.css';

type Theme='light'|'dark';type Ctx={actor_code?:string;role?:string};type Row=Record<string,any>;const fallbackNav:NavItem[]=[{label:'Inicio',route:'/inicio'}];
function fmt(v?:string){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('es-ES');}
export default function WebLeadDetailShell(){
 const location=useLocation(),navigate=useNavigate();const m=location.pathname.match(/^\/web-leads\/([^/]+)$/);const code=m?.[1]?decodeURIComponent(m[1]):'';const active=Boolean(code);
 const[ready,setReady]=useState(false),[logged,setLogged]=useState(false),[ctx,setCtx]=useState<Ctx|null>(null),[nav,setNav]=useState<NavItem[]>([]),[theme,setTheme]=useState<Theme>(()=>(sessionStorage.getItem('fenix-theme') as Theme)||'light');
 const[lead,setLead]=useState<Row|null>(null),[timeline,setTimeline]=useState<Row[]>([]),[status,setStatus]=useState<number|null>(null),[saving,setSaving]=useState(false),[saveMessage,setSaveMessage]=useState('');
 const[actionKind,setActionKind]=useState('contacto'),[happened,setHappened]=useState(''),[planned,setPlanned]=useState(''),[comment,setComment]=useState(''),[nextAt,setNextAt]=useState('');
 useEffect(()=>{if(!active)return;let alive=true;supabase.auth.getSession().then(({data})=>{if(alive){setLogged(Boolean(data.session));setReady(true)}});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setLogged(Boolean(s));setReady(true)});return()=>{alive=false;subscription.unsubscribe()};},[active]);
 useEffect(()=>{if(!active)return;document.documentElement.dataset.theme=theme;sessionStorage.setItem('fenix-theme',theme);},[active,theme]);
 useEffect(()=>{if(!active||!logged)return;Promise.all([fetchAppApi<Ctx>('/session/context'),fetchAppApi<unknown>('/navigation')]).then(([c,n])=>{setCtx(c.status===200?c.data:null);setNav(n.status===200?normalizeNavigation(n.data):[]);});},[active,logged]);
 async function load(){const r=await fetchAppApi<any>('/web-leads/'+encodeURIComponent(code)+'/timeline');setStatus(r.status);if(r.status===200){setLead(r.data?.lead||null);setTimeline(Array.isArray(r.data?.timeline)?r.data.timeline:[]);}}
 useEffect(()=>{if(active&&logged&&ctx)void load();},[active,logged,ctx,code]);
 async function save(e:FormEvent){e.preventDefault();setSaveMessage('');setSaving(true);const r=await fetchAppApi<any>('/web-leads/'+encodeURIComponent(code)+'/actions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action_kind:actionKind,happened,planned_action:planned,comment,next_at:nextAt?new Date(nextAt).toISOString():null})});setSaving(false);if(r.status===200){setSaveMessage('Acción registrada con fecha y hora.');setHappened('');setPlanned('');setComment('');setNextAt('');await load();}else setSaveMessage('No se pudo registrar la acción.');}
 const payload=lead?.source_payload||{};const summary=useMemo(()=>[payload.city||payload.source_city,payload.funnel||payload.intent,payload.source].filter(Boolean).join(' · '),[payload]);
 if(!active||!ready||!logged)return null;
 async function logout(){await supabase.auth.signOut();window.location.href=import.meta.env.BASE_URL;}
 const role=ctx?.role||'Usuario';
 return <OperationalShellFrame className="contactos-root" theme={theme} navigation={nav.length?nav:fallbackNav} activeRoute="/contactos" anaSubtitle="Histórico cronológico del lead." query="" onQueryChange={()=>{}} searchPlaceholder="Buscar" searchActionLabel="Buscar" onSearchAction={()=>{}} name={role} role="" initials={role.slice(0,2).toUpperCase()} onToggleTheme={()=>setTheme(theme==='light'?'dark':'light')} onLogout={logout} contentClassName="contactos-content">
   <div className="contactos-title inmo-title"><div><small>LEAD WEB · {summary||'CEREBRO'}</small><h1>{lead?.nombre||'Lead web'}</h1><p>{lead?.email||'—'} · {lead?.telefono||'—'} · entrada {fmt(lead?.created_at)}</p></div><button onClick={()=>navigate('/web-leads')}>← Leads web</button></div>
   {status===403?<div className="ops-message">Sin permiso para abrir este lead.</div>:status===404?<div className="ops-message">Lead no encontrado.</div>:null}
   {status===200&&lead&&<><section className="inmo-kpis contactos-kpis"><article><small>ESTADO</small><strong>{lead.estado||'Nuevo'}</strong><span>CRM</span></article><article><small>ORIGEN</small><strong>{payload.city||payload.source_city||'Web'}</strong><span>{payload.funnel||payload.intent||payload.source||'captación'}</span></article><article><small>CONSENTIMIENTO</small><strong>{lead.consentimiento_comercial?'Sí':'No'}</strong><span>Marketing</span></article><article><small>EVENTOS</small><strong>{timeline.length}</strong><span>Trazados</span></article></section>
   <section className="inmo-insights"><article><span>REGISTRAR TRABAJO</span><h2>Acción realizada y siguiente paso</h2><form onSubmit={save} style={{display:'grid',gap:10}}><label>Tipo de acción<select value={actionKind} onChange={e=>setActionKind(e.target.value)}><option value="contacto">Contacto</option><option value="llamada">Llamada</option><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="documentacion">Documentación</option><option value="seguimiento">Seguimiento</option><option value="nota">Nota</option></select></label><label>Qué se hizo<input value={happened} onChange={e=>setHappened(e.target.value)} placeholder="Ej. Llamada realizada, cliente interesado"/></label><label>Resultado / observación<textarea value={comment} onChange={e=>setComment(e.target.value)} rows={3}/></label><label>Siguiente acción<input value={planned} onChange={e=>setPlanned(e.target.value)} placeholder="Ej. Revisar documentación"/></label><label>Fecha y hora siguiente<input type="datetime-local" value={nextAt} onChange={e=>setNextAt(e.target.value)}/></label><button className="primary" disabled={saving}>{saving?'Guardando…':'Registrar acción'}</button>{saveMessage&&<small>{saveMessage}</small>}</form></article>
   <article><span>TRAZABILIDAD</span><h2>Origen y recurso</h2><p><b>Landing:</b> {payload.landing_url||'—'}</p><p><b>Recurso:</b> {payload.asset_label||payload.asset_url||'—'}</p><p><b>Fuente:</b> {payload.source||'web'}</p></article></section>
   <div className="ops-table-card contactos-table"><div className="ops-table-head"><strong>Histórico</strong><span>Fecha/hora exacta</span></div><div className="ops-table-wrap"><table className="ops-sortable-table"><thead><tr><th>Fecha y hora</th><th>Tipo</th><th>Acción / estado</th><th>Actor</th><th>Detalle</th></tr></thead><tbody>{timeline.map((x,i)=><tr key={i}><td>{fmt(x.occurred_at)}</td><td>{x.kind||'evento'}</td><td>{x.action||'—'}</td><td>{x.actor_code||'CEREBRO'}</td><td>{x.meta?.comment||x.meta?.asunto||x.meta?.source_ref||x.meta?.provider_message_id||'—'}</td></tr>)}</tbody></table></div></div></>}
 </OperationalShellFrame>;
}
