import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")??"",A=Deno.env.get("SUPABASE_ANON_KEY")??"",S=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",TARGET=`${U}/functions/v1/fenix-app-api-test`,BUCKET="fenix-preprod-documents-test";
const origins=new Set(["https://carlosjmunoz78.github.io","https://fenix-capital-preprod.vercel.app","http://localhost:3000","http://localhost:4173","http://127.0.0.1:4173"]);
function ch(req:Request){const o=req.headers.get("origin")??"",ao=origins.has(o)?o:"https://carlosjmunoz78.github.io";return{"access-control-allow-origin":ao,"access-control-allow-methods":"GET,POST,PATCH,OPTIONS","access-control-allow-headers":"authorization,apikey,content-type,x-client-info","access-control-max-age":"86400","vary":"Origin","cache-control":"no-store"}}
function J(req:Request,d:any,s=200){return new Response(JSON.stringify(d),{status:s,headers:{...ch(req),"content-type":"application/json; charset=utf-8","x-fenix-env":"PREPROD_TEST"}})}
Deno.serve(async(req:Request)=>{try{
 const cors=ch(req);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(!U||!A||!S)return J(req,{ok:false,error:"gateway_config_missing"},500);
 const auth=req.headers.get("authorization")??"";if(!auth.toLowerCase().startsWith("bearer "))return J(req,{ok:false,error:"unauthorized"},401);const token=auth.slice(7).trim(),ac=createClient(U,A,{auth:{persistSession:false}}),au=await ac.auth.getUser(token);if(au.error||!au.data.user)return J(req,{ok:false,error:"unauthorized"},401);
 const incoming=new URL(req.url),mark="/fenix-app-gateway-test",i=incoming.pathname.indexOf(mark),p=i>=0?incoming.pathname.slice(i+mark.length):"/",svc=createClient(U,S,{auth:{persistSession:false}});const ar=await svc.rpc("preprod_test_actor_context_by_auth_server",{p_auth_user_id:au.data.user.id});if(ar.error)return J(req,{ok:false,error:"actor_context_failed"},500);const me:any=ar.data;if(!me?.ok)return J(req,{ok:false,error:"test_identity_not_linked"},403);const actor=me.actor_code;
 const rpc=async(name:string,args:any,err:string)=>{const r=await svc.rpc(name,args);return r.error?J(req,{ok:false,error:err,detail:r.error.message},500):J(req,r.data??{ok:false,error:"empty_response"},Number(r.data?.status??500))};
 if(req.method==="GET"&&p==="/health")return J(req,{ok:true,env:"PREPROD_TEST",actor,role:me.role});
 if(req.method==="GET"&&p==="/session/context"){const r=await svc.rpc("preprod_test_session_context_server",{p_actor_code:actor});return r.error?J(req,{ok:false,error:"session_context_failed"},500):J(req,{ok:true,context:r.data??{}})}
 if(req.method==="GET"&&p==="/navigation"){const r=await svc.rpc("preprod_test_navigation_server",{p_actor_code:actor});return r.error?J(req,{ok:false,error:"navigation_failed"},500):J(req,{ok:true,items:r.data??[]})}
 const ew=p.match(/^\/expedientes\/([^/]+)\/workspace$/);if(req.method==="GET"&&ew)return rpc("preprod_test_expediente_workspace_server",{p_actor_code:actor,p_exp_code:decodeURIComponent(ew[1])},"expediente_workspace_failed");
 const ed=p.match(/^\/expedientes\/([^/]+)$/);if(req.method==="GET"&&ed){const r=await svc.rpc("preprod_test_get_expediente_server",{p_actor_code:actor,p_code:decodeURIComponent(ed[1])});if(r.error)return J(req,{ok:false,error:"expediente_read_failed"},500);return r.data&&Object.keys(r.data).length?J(req,{ok:true,expediente:r.data}):J(req,{ok:false,error:"not_found"},404)}
 if(req.method==="GET"&&p==="/tareas"){const r=await svc.rpc("preprod_test_get_tareas_server",{p_actor_code:actor});return r.error?J(req,{ok:false,error:"tasks_read_failed"},500):J(req,{ok:true,tareas:r.data??[]})}
 if(req.method==="GET"&&p==="/search"){const q=(incoming.searchParams.get("q")??"").trim();if(q.length<2)return J(req,{ok:false,error:"query_too_short"},400);const r=await svc.rpc("preprod_test_search_server",{p_actor_code:actor,p_q:q});return r.error?J(req,{ok:false,error:"search_failed"},500):J(req,{ok:true,results:r.data??[]})}
 const tr=p.match(/^\/tareas\/([^/]+)\/reassign$/);if(req.method==="POST"&&tr){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}const target=String(b?.new_actor_code??"").trim(),v=Number(b?.expectedVersion);if(!target||!Number.isInteger(v))return J(req,{ok:false,error:"invalid_payload"},400);return rpc("preprod_test_reassign_task_server",{p_actor_code:actor,p_task_code:decodeURIComponent(tr[1]),p_new_actor_code:target,p_expected_version:v},"reassign_failed")}
 if(req.method==="GET"&&p==="/documentos"){const r=await svc.rpc("preprod_test_document_list_server",{p_actor_code:actor});return r.error?J(req,{ok:false,error:"document_list_failed"},500):J(req,{ok:true,documentos:r.data??[]})}
 const dv=p.match(/^\/documentos\/([^/]+)\/versions$/);if(req.method==="GET"&&dv)return rpc("preprod_test_document_versions_server",{p_actor_code:actor,p_document_code:decodeURIComponent(dv[1])},"versions_failed");
 const dview=p.match(/^\/documentos\/([^/]+)\/view$/);if(req.method==="GET"&&dview){const code=decodeURIComponent(dview[1]),r=await svc.rpc("preprod_test_document_view_path_server",{p_actor_code:actor,p_document_code:code});if(r.error)return J(req,{ok:false,error:"view_path_failed"},500);if(!r.data?.ok)return J(req,r.data,Number(r.data?.status??500));const sg=await svc.storage.from(BUCKET).createSignedUrl(r.data.storage_path,60);return sg.error?J(req,{ok:false,error:"signed_view_failed"},500):J(req,{ok:true,document_code:code,version:r.data.version_no,version_kind:r.data.version_kind,mime_type:r.data.mime_type,bytes:r.data.bytes,url:sg.data.signedUrl,expires_in:60})}
 const dd=p.match(/^\/documentos\/([^/]+)$/);if(req.method==="GET"&&dd){const r=await svc.rpc("preprod_test_document_access_server",{p_actor_code:actor,p_document_code:decodeURIComponent(dd[1])});if(r.error)return J(req,{ok:false,error:"document_access_failed"},500);if(!r.data?.exists)return J(req,{ok:false,error:"not_found"},404);return r.data.allowed?J(req,{ok:true,documento:r.data.document}):J(req,{ok:false,error:"forbidden"},403)}
 if(req.method==="GET"&&p==="/personal"){if(me.role!=="Direccion")return J(req,{ok:false,error:"forbidden"},403);return rpc("preprod_test_personal_server",{p_actor_code:actor},"personal_list_failed")}
 const cd=p.match(/^\/contactos\/([^/]+)$/);if(req.method==="GET"&&cd)return rpc("preprod_test_contact_get_server",{p_actor_code:actor,p_id:decodeURIComponent(cd[1])},"contact_get_failed");
 const im=p.match(/^\/inmobiliarias\/([^/]+)$/);if(req.method==="GET"&&im)return rpc("preprod_test_inmo_get_server",{p_actor_code:actor,p_code:decodeURIComponent(im[1])},"inmobiliaria_get_failed");
 if(req.method==="POST"&&p==="/inmobiliarias"){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}return rpc("preprod_test_inmo_create_server",{p_actor_code:actor,p_inmobiliaria_code:String(b?.inmobiliaria_code??"").trim(),p_nombre_alias:String(b?.nombre_alias??"").trim(),p_zone_code:String(b?.zone_code??"").trim()},"inmobiliaria_create_failed")}
 const iu=p.match(/^\/inmobiliarias\/([^/]+)$/);if(req.method==="PATCH"&&iu){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}const v=Number(b?.expectedVersion??b?.expected_version);if(!Number.isInteger(v))return J(req,{ok:false,error:"invalid_payload"},400);return rpc("preprod_test_inmo_update_server",{p_actor_code:actor,p_inmobiliaria_code:decodeURIComponent(iu[1]),p_expected_version:v,p_nombre_alias:b?.nombre_alias===undefined?null:String(b.nombre_alias),p_zone_code:b?.zone_code===undefined?null:String(b.zone_code)},"inmobiliaria_update_failed")}
 if(req.method==="GET"&&p==="/tasaciones")return rpc("preprod_test_appraisal_list_server",{p_actor_code:actor},"appraisal_list_failed");
 const ah=p.match(/^\/tasaciones\/([^/]+)\/history$/);if(req.method==="GET"&&ah)return rpc("preprod_test_appraisal_history_server",{p_actor_code:actor,p_appraisal_code:decodeURIComponent(ah[1])},"appraisal_history_failed");
 const arp=p.match(/^\/tasaciones\/([^/]+)\/report$/);if(req.method==="GET"&&arp)return rpc("preprod_test_appraisal_report_server",{p_actor_code:actor,p_appraisal_code:decodeURIComponent(arp[1])},"appraisal_report_failed");
 const ast=p.match(/^\/tasaciones\/([^/]+)\/status$/);if(req.method==="POST"&&ast){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}const v=Number(b?.expectedVersion),s=String(b?.status??"");if(!Number.isInteger(v)||!s)return J(req,{ok:false,error:"invalid_payload"},400);return rpc("preprod_test_appraisal_status_server",{p_actor_code:actor,p_appraisal_code:decodeURIComponent(ast[1]),p_expected_version:v,p_new_status:s},"appraisal_status_failed")}
 const av=p.match(/^\/tasaciones\/([^/]+)\/validacion-belen$/);if(req.method==="POST"&&av){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}const v=Number(b?.expectedVersion),d=String(b?.decision??""),reason=String(b?.reason??"");if(!Number.isInteger(v)||!d)return J(req,{ok:false,error:"invalid_payload"},400);return rpc("preprod_test_appraisal_validate_server",{p_actor_code:actor,p_appraisal_code:decodeURIComponent(av[1]),p_expected_version:v,p_decision:d,p_reason:reason},"appraisal_validation_failed")}
 const ad=p.match(/^\/tasaciones\/([^/]+)$/);if(req.method==="GET"&&ad)return rpc("preprod_test_appraisal_scope_server",{p_actor_code:actor,p_appraisal_code:decodeURIComponent(ad[1])},"appraisal_get_failed");
 if(req.method==="GET"&&p==="/firmas")return rpc("preprod_test_sign_list_server",{p_actor_code:actor},"sign_list_failed");
 const fbe=p.match(/^\/expedientes\/([^/]+)\/fein-firma$/);if(req.method==="GET"&&fbe)return rpc("preprod_test_sign_by_exp_server",{p_actor_code:actor,p_exp_code:decodeURIComponent(fbe[1])},"sign_by_exp_failed");
 const fh=p.match(/^\/firmas\/([^/]+)\/history$/);if(req.method==="GET"&&fh)return rpc("preprod_test_sign_history_server",{p_actor_code:actor,p_firma_code:decodeURIComponent(fh[1])},"sign_history_failed");
 const fs=p.match(/^\/firmas\/([^/]+)\/schedule$/);if(req.method==="POST"&&fs){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}const v=Number(b?.expectedVersion),dt=String(b?.fecha_firma??"");if(!Number.isInteger(v)||!dt)return J(req,{ok:false,error:"invalid_payload"},400);return rpc("preprod_test_sign_schedule_server",{p_actor_code:actor,p_firma_code:decodeURIComponent(fs[1]),p_expected_version:v,p_fecha_firma:dt,p_notaria:String(b?.notaria??""),p_oficial:String(b?.oficial??"")},"sign_schedule_failed")}
 const fc=p.match(/^\/firmas\/([^/]+)\/confirm$/);if(req.method==="POST"&&fc){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}const v=Number(b?.expectedVersion);if(!Number.isInteger(v))return J(req,{ok:false,error:"invalid_payload"},400);return rpc("preprod_test_sign_confirm_server",{p_actor_code:actor,p_firma_code:decodeURIComponent(fc[1]),p_expected_version:v},"sign_confirm_failed")}
 const fcl=p.match(/^\/firmas\/([^/]+)\/close$/);if(req.method==="POST"&&fcl){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}const v=Number(b?.expectedVersion);if(!Number.isInteger(v))return J(req,{ok:false,error:"invalid_payload"},400);return rpc("preprod_test_sign_close_server",{p_actor_code:actor,p_firma_code:decodeURIComponent(fcl[1]),p_expected_version:v},"sign_close_failed")}
 const fd=p.match(/^\/firmas\/([^/]+)$/);if(req.method==="GET"&&fd)return rpc("preprod_test_sign_scope_server",{p_actor_code:actor,p_firma_code:decodeURIComponent(fd[1])},"sign_get_failed");
 const rg=async(name:string,err:string)=>rpc(name,{p_actor_code:actor},err);if(req.method==="GET"&&p==="/expedientes")return rg("preprod_test_exp_list_server","expedientes_list_failed");if(req.method==="GET"&&p==="/inmobiliarias")return rg("preprod_test_inmo_list_server","inmobiliarias_list_failed");if(req.method==="GET"&&p==="/contactos")return rg("preprod_test_contacts_server","contacts_list_failed");
 const wl=p.match(/^\\/web-leads\\/([^/]+)\\/timeline$/);if(req.method==="GET"&&wl)return rpc("preprod_test_web_lead_timeline_server",{p_actor_code:actor,p_lead_id:decodeURIComponent(wl[1])},"web_lead_timeline_failed");
 const wa=p.match(/^\\/web-leads\\/([^/]+)\\/actions$/);if(req.method==="POST"&&wa){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}return rpc("preprod_test_web_lead_action_server",{p_actor_code:actor,p_lead_id:decodeURIComponent(wa[1]),p_action_kind:String(b?.action_kind??""),p_comment:b?.comment?String(b.comment):null,p_happened:b?.happened?String(b.happened):null,p_planned_action:b?.planned_action?String(b.planned_action):null,p_next_at:b?.next_at?String(b.next_at):null},"web_lead_action_failed")}
 if(req.method==="GET"&&p==="/web-leads")return rg("preprod_test_web_leads_list_server","web_leads_list_failed");
 if(req.method==="GET"&&p==="/visitadores")return rg("preprod_test_visitadores_server","visitadores_list_failed");if(req.method==="GET"&&p==="/ana/correcciones")return rg("preprod_test_ana_corrections_list_server","ana_corrections_list_failed");
 if(req.method==="POST"&&p==="/ana/correcciones"){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}return rpc("preprod_test_ana_correction_create_server",{p_actor_code:actor,p_scope_type:String(b?.scope_type??"general"),p_scope_code:b?.scope_code?String(b.scope_code):"",p_ana_suggestion:String(b?.ana_suggestion??""),p_user_reason:String(b?.user_reason??""),p_proposed_rule:String(b?.proposed_rule??"")},"ana_correction_create_failed")}
 const dec=p.match(/^\/ana\/correcciones\/([^/]+)\/decision$/);if(req.method==="POST"&&dec){let b:any;try{b=await req.json()}catch{return J(req,{ok:false,error:"invalid_json"},400)}return rpc("preprod_test_ana_correction_decide_server",{p_actor_code:actor,p_correction_code:decodeURIComponent(dec[1]),p_expected_version:Number(b?.expected_version),p_decision:String(b?.decision??""),p_review_reason:String(b?.review_reason??""),p_approved_rule:String(b?.approved_rule??"")},"ana_correction_decision_failed")}
 const h=new Headers();h.set("authorization",auth);h.set("apikey",A);const ct=req.headers.get("content-type");if(ct)h.set("content-type",ct);const init:RequestInit={method:req.method,headers:h};if(!["GET","HEAD"].includes(req.method))init.body=await req.arrayBuffer();const up=await fetch(`${TARGET}${p}${incoming.search}`,init),buf=await up.arrayBuffer(),rh=new Headers(cors);rh.set("content-type",up.headers.get("content-type")??"application/json; charset=utf-8");rh.set("x-fenix-env","PREPROD_TEST");return new Response(buf,{status:up.status,headers:rh});
}catch(e){console.error("gateway",e);return J(req,{ok:false,error:"gateway_exception"},500)}});