import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const ALLOWED=new Set(['https://app.fenixcapital.es']);
function key(raw:string){try{const x=JSON.parse(raw||'{}');return String((x as any)?.default??Object.values(x??{})[0]??'')}catch{return ''}}
function cfg(){return{url:Deno.env.get('SUPABASE_URL')??'',anon:Deno.env.get('SUPABASE_ANON_KEY')||key(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')??''),service:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||key(Deno.env.get('SUPABASE_SECRET_KEYS')??'')}}
function cors(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ALLOWED.has(o)?o:'https://app.fenixcapital.es','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'GET,PATCH,OPTIONS','Vary':'Origin','x-fenix-env':'PROD'}}
function out(req:Request,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function me(req:Request){const c=cfg(),h=req.headers.get('authorization')||'';if(!c.url||!c.anon||!c.service||!h.startsWith('Bearer '))return null;const auth=createClient(c.url,c.anon,{auth:{persistSession:false,autoRefreshToken:false}}),svc=createClient(c.url,c.service,{auth:{persistSession:false,autoRefreshToken:false}});const {data:u,error}=await auth.auth.getUser(h.slice(7));if(error||!u.user)return null;const {data:ctx,error:ce}=await svc.rpc('fenix_prod_actor_context_by_auth_server',{p_auth_user_id:u.user.id});if(ce||!ctx?.ok)return null;return{svc,actor:ctx.actor_code}}
function code(req:Request){const p=new URL(req.url).pathname.replace(/^\/(?:functions\/v1\/)?fenix-document-actions/,'')||'/';return p==='/'?'':decodeURIComponent(p.slice(1))}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const id=await me(req);if(!id)return out(req,{ok:false,status:401,error:'unauthorized'},401);const c=code(req);if(!c)return out(req,{ok:false,status:404,error:'not_found'},404);try{if(req.method==='GET'){const {data,error}=await id.svc.rpc('fenix_prod_document_get_server',{p_actor_code:id.actor,p_document_code:c});if(error)throw error;return out(req,data,Number(data?.status)||200)}if(req.method==='PATCH'){let b:any={};try{b=await req.json()}catch{}const {data,error}=await id.svc.rpc('fenix_prod_document_update_server',{p_actor_code:id.actor,p_document_code:c,p_estado:b.estado??null,p_calidad:b.calidad??b.calidad_archivo??null});if(error)throw error;return out(req,data,Number(data?.status)||200)}return out(req,{ok:false,status:405,error:'method_not_allowed'},405)}catch(e){console.error(e);return out(req,{ok:false,status:500,error:'document_backend_error'},500)}});
